Repository Azure/azure-sdk-for-js, pull requests merged in 2018-11, with the labels that each got.

#371 [AutoPR cosmos-db/resource-manager] Adding property to VirtualNetworkRule for Cosmos DB
  packages/@azure/arm-cosmosdb/LICENSE.txt
  packages/@azure/arm-cosmosdb/README.md
  packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
  packages/@azure/arm-cosmosdb/lib/models/index.ts
  packages/@azure/arm-cosmosdb/lib/models/mappers.ts
  packages/@azure/arm-cosmosdb/package.json
Labels: RestPRMerged, in progress

#378 [AutoPR] network/resource-manager
  packages/@azure/arm-network/lib/models/parameters.ts
  packages/@azure/arm-network/lib/operations/virtualNetworks.ts
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#363 [AutoPR web/resource-manager] Fix network trace API bugs (Retake)
  packages/@azure/arm-appservice/LICENSE.txt
  packages/@azure/arm-appservice/README.md
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/operations/webApps.ts
Labels: RestPRMerged, in progress

#379 [AutoPR] cosmos-db/resource-manager
  packages/@azure/arm-cosmosdb/.npmignore
  packages/@azure/arm-cosmosdb/LICENSE.txt
  packages/@azure/arm-cosmosdb/README.md
  packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
  packages/@azure/arm-cosmosdb/lib/models/index.ts
  packages/@azure/arm-cosmosdb/lib/models/mappers.ts
  packages/@azure/arm-cosmosdb/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#374 [AutoPR containerinstance/resource-manager] Update Microsoft.Containerinstance swagger with DNSConfig and GPU
  packages/@azure/arm-containerinstance/LICENSE.txt
  packages/@azure/arm-containerinstance/README.md
  packages/@azure/arm-containerinstance/lib/containerInstanceManagementClientContext.ts
  packages/@azure/arm-containerinstance/lib/models/containerGroupsMappers.ts
  packages/@azure/arm-containerinstance/lib/models/index.ts
  packages/@azure/arm-containerinstance/lib/models/mappers.ts
  packages/@azure/arm-containerinstance/package.json
Labels: RestPRMerged, in progress

#383 [AutoPR apimanagement/resource-manager] Move version 2018-01-01 to stable folder
  packages/@azure/arm-apimanagement/lib/apiManagementClientContext.ts
Labels: RestPRMerged, in progress

#369 [AutoPR reservations/resource-manager] Reservations RP 2018-06-01 Preview: Add new reserved resource type RedHat
  packages/@azure/arm-reservations/README.md
  packages/@azure/arm-reservations/lib/azureReservationAPIContext.ts
  packages/@azure/arm-reservations/lib/models/index.ts
  packages/@azure/arm-reservations/lib/operations/reservation.ts
  packages/@azure/arm-reservations/lib/operations/reservationOrder.ts
  packages/@azure/arm-reservations/package.json
Labels: RestPRMerged, in progress

#380 [AutoPR] web/resource-manager
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/operations/webApps.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
  packages/@azure/arm-appservice/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#385 [AutoPR] containerinstance/resource-manager
  packages/@azure/arm-containerinstance/.npmignore
  packages/@azure/arm-containerinstance/LICENSE.txt
  packages/@azure/arm-containerinstance/README.md
  packages/@azure/arm-containerinstance/lib/containerInstanceManagementClientContext.ts
  packages/@azure/arm-containerinstance/lib/models/containerGroupsMappers.ts
  packages/@azure/arm-containerinstance/lib/models/index.ts
  packages/@azure/arm-containerinstance/lib/models/mappers.ts
  packages/@azure/arm-containerinstance/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#386 [AutoPR] apimanagement/resource-manager
  packages/@azure/arm-apimanagement/lib/apiManagementClientContext.ts
  packages/@azure/arm-apimanagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#388 [AutoPR] reservations/resource-manager
  packages/@azure/arm-reservations/.npmignore
  packages/@azure/arm-reservations/README.md
  packages/@azure/arm-reservations/lib/azureReservationAPIContext.ts
  packages/@azure/arm-reservations/lib/models/index.ts
  packages/@azure/arm-reservations/lib/operations/reservation.ts
  packages/@azure/arm-reservations/lib/operations/reservationOrder.ts
  packages/@azure/arm-reservations/package.json
Labels: ServicePR, in progress

#372 [AutoPR visualstudio/resource-manager] Added patch API to swagger doc in Visual studio RP[Draft]
  packages/@azure/arm-visualstudio/LICENSE.txt
  packages/@azure/arm-visualstudio/README.md
  packages/@azure/arm-visualstudio/lib/models/accountsMappers.ts
  packages/@azure/arm-visualstudio/lib/models/index.ts
  packages/@azure/arm-visualstudio/lib/models/mappers.ts
  packages/@azure/arm-visualstudio/lib/operations/accounts.ts
  packages/@azure/arm-visualstudio/lib/visualStudioResourceProviderClientContext.ts
  packages/@azure/arm-visualstudio/package.json
Labels: RestPRMerged, in progress

#389 [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step
  packages/@azure/arm-containerregistry/README.md
  packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/package.json
Labels: RestPRMerged, in progress

#390 [AutoPR] visualstudio/resource-manager
  packages/@azure/arm-visualstudio/LICENSE.txt
  packages/@azure/arm-visualstudio/README.md
  packages/@azure/arm-visualstudio/lib/models/accountsMappers.ts
  packages/@azure/arm-visualstudio/lib/models/index.ts
  packages/@azure/arm-visualstudio/lib/models/mappers.ts
  packages/@azure/arm-visualstudio/lib/operations/accounts.ts
  packages/@azure/arm-visualstudio/lib/visualStudioResourceProviderClientContext.ts
  packages/@azure/arm-visualstudio/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#391 [AutoPR] containerregistry/resource-manager
  packages/@azure/arm-containerregistry/.npmignore
  packages/@azure/arm-containerregistry/README.md
  packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#392 [AutoPR] domainservices/resource-manager
  packages/@azure/arm-domainservices/.npmignore
  packages/@azure/arm-domainservices/LICENSE.txt
  packages/@azure/arm-domainservices/README.md
  packages/@azure/arm-domainservices/lib/domainservicesManagementClientContext.ts
  packages/@azure/arm-domainservices/lib/models/domainServicesMappers.ts
  packages/@azure/arm-domainservices/lib/models/index.ts
  packages/@azure/arm-domainservices/lib/models/mappers.ts
  packages/@azure/arm-domainservices/lib/operations/domainServices.ts
  packages/@azure/arm-domainservices/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#381 [AutoPR cognitiveservices/data-plane/VisualSearch] [Visual Search API] Update encoding format documentation per PM request
  packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts
Labels: RestPRMerged, in progress

#398 [AutoPR cognitiveservices/data-plane/VisualSearch] enable swagger-to-sdk in visual search for Go SDK
  packages/@azure/cognitiveservices-visualsearch/lib/operations/images.ts
  packages/@azure/cognitiveservices-visualsearch/lib/visualSearchAPIClientContext.ts
  packages/@azure/cognitiveservices-visualsearch/package.json
Labels: RestPRMerged, in progress

#397 [AutoPR] cognitiveservices/data-plane/VisualSearch
  packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#402 [AutoPR datamigration/resource-manager] Fix Version value to fix Ruby SDK Generation
  packages/@azure/arm-datamigration/lib/dataMigrationServiceClientContext.ts
  packages/@azure/arm-datamigration/lib/models/index.ts
  packages/@azure/arm-datamigration/lib/models/parameters.ts
  packages/@azure/arm-datamigration/lib/operations/files.ts
  packages/@azure/arm-datamigration/lib/operations/operations.ts
  packages/@azure/arm-datamigration/lib/operations/projects.ts
  packages/@azure/arm-datamigration/lib/operations/resourceSkus.ts
  packages/@azure/arm-datamigration/lib/operations/services.ts
  packages/@azure/arm-datamigration/lib/operations/tasks.ts
  packages/@azure/arm-datamigration/lib/operations/usages.ts
  packages/@azure/arm-datamigration/package.json
Labels: RestPRMerged, in progress

#404 CI update
  azure-pipelines.yml
  gulpfile.ts
Labels: in progress

#401 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  packages/@azure/arm-authorization/LICENSE.txt
  packages/@azure/arm-authorization/README.md
  packages/@azure/arm-authorization/lib/authorizationManagementClient.ts
  packages/@azure/arm-authorization/lib/models/index.ts
  packages/@azure/arm-authorization/lib/models/mappers.ts
  packages/@azure/arm-authorization/lib/models/parameters.ts
  packages/@azure/arm-authorization/lib/operations/denyAssignments.ts
  packages/@azure/arm-authorization/lib/operations/index.ts
  packages/@azure/arm-authorization/lib/operations/roleAssignments.ts
Labels: RestPRMerged, in progress

#384 [AutoPR datafactory/resource-manager] Enable delete activity
  packages/@azure/arm-datafactory/LICENSE.txt
  packages/@azure/arm-datafactory/README.md
  packages/@azure/arm-datafactory/lib/dataFactoryManagementClientContext.ts
  packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
  packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
  packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
  packages/@azure/arm-datafactory/lib/models/triggersMappers.ts
  packages/@azure/arm-datafactory/package.json
Labels: RestPRMerged, in progress

#376 [AutoPR datafactory/resource-manager] [DataFactory]Add sensitive fields extracted from connection string in swagger for AKV reference
  packages/@azure/arm-datafactory/.npmignore
  packages/@azure/arm-datafactory/README.md
  packages/@azure/arm-datafactory/lib/dataFactoryManagementClientContext.ts
  packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
  packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
  packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
  packages/@azure/arm-datafactory/lib/models/triggersMappers.ts
  packages/@azure/arm-datafactory/lib/operations/activityRuns.ts
  packages/@azure/arm-datafactory/lib/operations/datasets.ts
  packages/@azure/arm-datafactory/lib/operations/factories.ts
  packages/@azure/arm-datafactory/lib/operations/integrationRuntimeNodes.ts
  packages/@azure/arm-datafactory/lib/operations/integrationRuntimes.ts
  packages/@azure/arm-datafactory/lib/operations/linkedServices.ts
  packages/@azure/arm-datafactory/lib/operations/operations.ts
  packages/@azure/arm-datafactory/lib/operations/pipelineRuns.ts
  packages/@azure/arm-datafactory/lib/operations/pipelines.ts
  packages/@azure/arm-datafactory/lib/operations/rerunTriggers.ts
  packages/@azure/arm-datafactory/lib/operations/triggerRuns.ts
  packages/@azure/arm-datafactory/lib/operations/triggers.ts
  packages/@azure/arm-datafactory/package.json
Labels: RestPRMerged, in progress

#403 [AutoPR] datamigration/resource-manager
  packages/@azure/arm-datamigration/lib/dataMigrationServiceClientContext.ts
  packages/@azure/arm-datamigration/lib/models/index.ts
  packages/@azure/arm-datamigration/lib/models/parameters.ts
  packages/@azure/arm-datamigration/lib/operations/files.ts
  packages/@azure/arm-datamigration/lib/operations/operations.ts
  packages/@azure/arm-datamigration/lib/operations/projects.ts
  packages/@azure/arm-datamigration/lib/operations/resourceSkus.ts
  packages/@azure/arm-datamigration/lib/operations/services.ts
  packages/@azure/arm-datamigration/lib/operations/tasks.ts
  packages/@azure/arm-datamigration/lib/operations/usages.ts
  packages/@azure/arm-datamigration/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#410 [AutoPR] authorization/resource-manager
  packages/@azure/arm-authorization/.npmignore
  packages/@azure/arm-authorization/lib/authorizationManagementClient.ts
  packages/@azure/arm-authorization/lib/authorizationManagementClientContext.ts
  packages/@azure/arm-authorization/lib/models/index.ts
  packages/@azure/arm-authorization/lib/models/mappers.ts
  packages/@azure/arm-authorization/lib/models/parameters.ts
  packages/@azure/arm-authorization/lib/operations/classicAdministrators.ts
  packages/@azure/arm-authorization/lib/operations/denyAssignments.ts
  packages/@azure/arm-authorization/lib/operations/index.ts
  packages/@azure/arm-authorization/lib/operations/permissions.ts
  packages/@azure/arm-authorization/lib/operations/providerOperationsMetadataOperations.ts
  packages/@azure/arm-authorization/lib/operations/roleAssignments.ts
  packages/@azure/arm-authorization/lib/operations/roleDefinitions.ts
  packages/@azure/arm-authorization/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#411 [AutoPR] datafactory/resource-manager
  packages/@azure/arm-datafactory/LICENSE.txt
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#412 [AutoPR sql/resource-manager] Fix blob auditing documentation
  packages/@azure/arm-sql/README.md
  packages/@azure/arm-sql/lib/models/databaseVulnerabilityAssessmentsMappers.ts
  packages/@azure/arm-sql/lib/models/index.ts
  packages/@azure/arm-sql/lib/models/managedDatabaseVulnerabilityAssessmentsMappers.ts
  packages/@azure/arm-sql/lib/models/mappers.ts
  packages/@azure/arm-sql/lib/models/parameters.ts
  packages/@azure/arm-sql/lib/operations/databaseVulnerabilityAssessments.ts
  packages/@azure/arm-sql/lib/operations/managedDatabaseVulnerabilityAssessments.ts
  packages/@azure/arm-sql/lib/sqlManagementClientContext.ts
Labels: RestPRMerged, in progress

#425 [AutoPR] storagesync/resource-manager
  packages/@azure/arm-storagesync/.npmignore
  packages/@azure/arm-storagesync/lib/models/index.ts
  packages/@azure/arm-storagesync/lib/operations/cloudEndpoints.ts
  packages/@azure/arm-storagesync/lib/operations/operations.ts
  packages/@azure/arm-storagesync/lib/operations/registeredServers.ts
  packages/@azure/arm-storagesync/lib/operations/serverEndpoints.ts
  packages/@azure/arm-storagesync/lib/operations/storageSyncServices.ts
  packages/@azure/arm-storagesync/lib/operations/syncGroups.ts
  packages/@azure/arm-storagesync/lib/operations/workflows.ts
  packages/@azure/arm-storagesync/lib/storageSyncManagementClientContext.ts
  packages/@azure/arm-storagesync/package.json
Labels: ServicePR, in progress

#433 Update README.md authentication section
  README.md
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#441 [AutoPR cognitiveservices/resource-manager] fixing sample names in cognitive services
  packages/@azure/arm-cognitiveservices/LICENSE.txt
  packages/@azure/arm-cognitiveservices/README.md
  packages/@azure/arm-cognitiveservices/lib/cognitiveServicesManagementClientContext.ts
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/operations/accounts.ts
  packages/@azure/arm-cognitiveservices/lib/operations/checkSkuAvailability.ts
  packages/@azure/arm-cognitiveservices/lib/operations/operations.ts
  packages/@azure/arm-cognitiveservices/lib/operations/resourceSkus.ts
  packages/@azure/arm-cognitiveservices/package.json
Labels: RestPRMerged, in progress

#422 [AutoPR authorization/resource-manager] remove duplicate entry for Go SDK build
  packages/@azure/arm-authorization/LICENSE.txt
  packages/@azure/arm-authorization/README.md
  packages/@azure/arm-authorization/package.json
Labels: RestPRMerged, in progress

#460 [AutoPR cognitiveservices/data-plane/Face] FaceAPI Split Python conf in it's own file
  packages/@azure/cognitiveservices-face/README.md
  packages/@azure/cognitiveservices-face/lib/faceClientContext.ts
  packages/@azure/cognitiveservices-face/lib/models/index.ts
  packages/@azure/cognitiveservices-face/lib/operations/face.ts
  packages/@azure/cognitiveservices-face/lib/operations/faceListOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largeFaceListOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupPerson.ts
  packages/@azure/cognitiveservices-face/lib/operations/personGroupOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/personGroupPerson.ts
  packages/@azure/cognitiveservices-face/package.json
Labels: RestPRMerged, in progress

#459 Add MergeOptions to regenerate scenario
  .scripts/git.ts
  .scripts/gulp.ts
Labels: Unplanned-Sprint-126, in progress

#448 [AutoPR] cognitiveservices/resource-manager
  README.md
  packages/@azure/arm-cognitiveservices/LICENSE.txt
  packages/@azure/arm-cognitiveservices/README.md
  packages/@azure/arm-cognitiveservices/lib/cognitiveServicesManagementClientContext.ts
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/operations/accounts.ts
  packages/@azure/arm-cognitiveservices/lib/operations/checkSkuAvailability.ts
  packages/@azure/arm-cognitiveservices/lib/operations/operations.ts
  packages/@azure/arm-cognitiveservices/lib/operations/resourceSkus.ts
  packages/@azure/arm-cognitiveservices/package.json
  packages/@azure/graph/README.md
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#455 [AutoPR web/resource-manager] Add initial set for changes for ANT79
  packages/@azure/arm-appservice/LICENSE.txt
  packages/@azure/arm-appservice/README.md
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/models/mappers.ts
  packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
  packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
  packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
  packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/certificates.ts
  packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
  packages/@azure/arm-appservice/lib/operations/diagnostics.ts
  packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/domains.ts
  packages/@azure/arm-appservice/lib/operations/provider.ts
  packages/@azure/arm-appservice/lib/operations/recommendations.ts
  packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
  packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
  packages/@azure/arm-appservice/lib/operations/webApps.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
  packages/@azure/arm-appservice/package.json
Labels: RestPRMerged, in progress

#466 [AutoPR network/resource-manager] Make NIC VM ref readonly
  packages/@azure/arm-network/lib/models/index.ts
  packages/@azure/arm-network/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#467 [AutoPR network/resource-manager] Make NIC VM readOnly
  packages/@azure/arm-network/lib/models/index.ts
  packages/@azure/arm-network/lib/models/mappers.ts
  packages/@azure/arm-network/lib/models/networkWatchersMappers.ts
  packages/@azure/arm-network/lib/models/parameters.ts
  packages/@azure/arm-network/lib/networkManagementClient.ts
  packages/@azure/arm-network/lib/operations/index.ts
  packages/@azure/arm-network/lib/operations/virtualNetworks.ts
  packages/@azure/arm-network/package.json
Labels: RestPRMerged, in progress

#470 [AutoPR security/resource-manager] Add Allowed Connections REST API
  packages/@azure/arm-security/lib/models/allowedConnectionsMappers.ts
  packages/@azure/arm-security/lib/models/index.ts
  packages/@azure/arm-security/lib/models/mappers.ts
  packages/@azure/arm-security/lib/models/parameters.ts
  packages/@azure/arm-security/lib/operations/advancedThreatProtection.ts
  packages/@azure/arm-security/lib/operations/alerts.ts
  packages/@azure/arm-security/lib/operations/allowedConnections.ts
  packages/@azure/arm-security/lib/operations/autoProvisioningSettings.ts
  packages/@azure/arm-security/lib/operations/compliances.ts
  packages/@azure/arm-security/lib/operations/discoveredSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/externalSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/index.ts
  packages/@azure/arm-security/lib/operations/informationProtectionPolicies.ts
  packages/@azure/arm-security/lib/operations/jitNetworkAccessPolicies.ts
  packages/@azure/arm-security/lib/operations/locations.ts
  packages/@azure/arm-security/lib/operations/operations.ts
  packages/@azure/arm-security/lib/operations/pricings.ts
  packages/@azure/arm-security/lib/operations/securityContacts.ts
  packages/@azure/arm-security/lib/operations/settings.ts
  packages/@azure/arm-security/lib/operations/tasks.ts
  packages/@azure/arm-security/lib/operations/topology.ts
  packages/@azure/arm-security/lib/operations/workspaceSettings.ts
  packages/@azure/arm-security/lib/securityCenter.ts
  packages/@azure/arm-security/lib/securityCenterContext.ts
  packages/@azure/arm-security/package.json
Labels: RestPRMerged

#469 [AutoPR] network/resource-manager
  packages/@azure/arm-network/lib/models/index.ts
  packages/@azure/arm-network/lib/models/mappers.ts
  packages/@azure/arm-network/lib/models/networkWatchersMappers.ts
  packages/@azure/arm-network/lib/models/parameters.ts
  packages/@azure/arm-network/lib/networkManagementClient.ts
  packages/@azure/arm-network/lib/operations/index.ts
  packages/@azure/arm-network/lib/operations/virtualNetworks.ts
  packages/@azure/arm-network/package.json
  packages/@azure/arm-network/tsconfig.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#461 [AutoPR] cognitiveservices/data-plane/Face
  README.md
  packages/@azure/arm-cognitiveservices/LICENSE.txt
  packages/@azure/arm-cognitiveservices/README.md
  packages/@azure/cognitiveservices-face/README.md
  packages/@azure/cognitiveservices-face/lib/faceClientContext.ts
  packages/@azure/cognitiveservices-face/lib/models/index.ts
  packages/@azure/cognitiveservices-face/lib/operations/face.ts
  packages/@azure/cognitiveservices-face/lib/operations/faceListOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largeFaceListOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largePersonGroupPerson.ts
  packages/@azure/cognitiveservices-face/lib/operations/personGroupOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/personGroupPerson.ts
  packages/@azure/cognitiveservices-face/package.json
  packages/@azure/graph/README.md
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#442 [AutoPR containerinstance/resource-manager] Azure Container Instance: Add start container group API
  packages/@azure/arm-containerinstance/lib/containerInstanceManagementClientContext.ts
  packages/@azure/arm-containerinstance/lib/models/index.ts
  packages/@azure/arm-containerinstance/lib/operations/containerGroupUsage.ts
  packages/@azure/arm-containerinstance/lib/operations/containerGroups.ts
  packages/@azure/arm-containerinstance/lib/operations/containerOperations.ts
  packages/@azure/arm-containerinstance/lib/operations/operations.ts
  packages/@azure/arm-containerinstance/lib/operations/serviceAssociationLink.ts
  packages/@azure/arm-containerinstance/package.json
Labels: RestPRMerged, in progress

#474 [AutoPR web/resource-manager] Add GeoRegion property to DeletedSite model
  packages/@azure/arm-appservice/LICENSE.txt
  packages/@azure/arm-appservice/README.md
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/models/mappers.ts
  packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
  packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
  packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
  packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/certificates.ts
  packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
  packages/@azure/arm-appservice/lib/operations/diagnostics.ts
  packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/domains.ts
  packages/@azure/arm-appservice/lib/operations/provider.ts
  packages/@azure/arm-appservice/lib/operations/recommendations.ts
  packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
  packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
  packages/@azure/arm-appservice/lib/operations/webApps.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
  packages/@azure/arm-appservice/package.json
Labels: RestPRMerged, in progress

#479 [AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#482 [AutoPR storage/resource-manager] Adds storage account Quick Failover API
  packages/@azure/arm-storage/LICENSE.txt
  packages/@azure/arm-storage/README.md
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/models/mappers.ts
  packages/@azure/arm-storage/lib/operations/blobContainers.ts
  packages/@azure/arm-storage/lib/operations/blobServices.ts
  packages/@azure/arm-storage/lib/operations/managementPolicies.ts
  packages/@azure/arm-storage/lib/operations/operations.ts
  packages/@azure/arm-storage/lib/operations/skus.ts
  packages/@azure/arm-storage/lib/operations/storageAccounts.ts
  packages/@azure/arm-storage/lib/operations/usages.ts
  packages/@azure/arm-storage/lib/storageManagementClientContext.ts
  packages/@azure/arm-storage/package.json
Labels: RestPRMerged, in progress

#490 [AutoPR apimanagement/resource-manager] Added missing PATCH operation to Api Issue resource
  packages/@azure/arm-apimanagement/lib/models/apiIssueMappers.ts
  packages/@azure/arm-apimanagement/lib/models/index.ts
  packages/@azure/arm-apimanagement/lib/models/mappers.ts
  packages/@azure/arm-apimanagement/lib/operations/apiIssue.ts
Labels: RestPRMerged

#476 [AutoPR] web/resource-manager
  packages/@azure/arm-appservice/LICENSE.txt
Labels: ServicePR, in progress

#487 [AutoPR] datafactory/resource-manager
  packages/@azure/arm-datafactory/README.md
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
Labels: ServicePR, in progress

#489 [AutoPR] storage/resource-manager
  packages/@azure/arm-storage/LICENSE.txt
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/models/mappers.ts
  packages/@azure/arm-storage/lib/operations/storageAccounts.ts
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#491 [AutoPR] apimanagement/resource-manager
  packages/@azure/arm-apimanagement/lib/models/apiIssueMappers.ts
  packages/@azure/arm-apimanagement/lib/models/index.ts
  packages/@azure/arm-apimanagement/lib/models/mappers.ts
  packages/@azure/arm-apimanagement/lib/models/userMappers.ts
  packages/@azure/arm-apimanagement/lib/operations/apiIssue.ts
  packages/@azure/arm-apimanagement/lib/operations/user.ts
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#496 [AutoPR authorization/resource-manager] Add latest authorization tag to java config
  packages/@azure/arm-authorization/LICENSE.txt
  packages/@azure/arm-authorization/README.md
  packages/@azure/arm-authorization/lib/authorizationManagementClient.ts
  packages/@azure/arm-authorization/lib/authorizationManagementClientContext.ts
  packages/@azure/arm-authorization/lib/models/index.ts
  packages/@azure/arm-authorization/lib/models/mappers.ts
  packages/@azure/arm-authorization/lib/models/parameters.ts
  packages/@azure/arm-authorization/lib/operations/classicAdministrators.ts
  packages/@azure/arm-authorization/lib/operations/denyAssignments.ts
  packages/@azure/arm-authorization/lib/operations/permissions.ts
  packages/@azure/arm-authorization/lib/operations/providerOperationsMetadataOperations.ts
  packages/@azure/arm-authorization/lib/operations/roleAssignments.ts
  packages/@azure/arm-authorization/lib/operations/roleDefinitions.ts
  packages/@azure/arm-authorization/package.json
  packages/@azure/arm-authorization/rollup.config.js
  packages/@azure/arm-authorization/tsconfig.json
Labels: RestPRMerged

#503 Update @azure/arm-storage version to 0.1.1
  packages/@azure/arm-storage/README.md
  packages/@azure/arm-storage/lib/storageManagementClientContext.ts
  packages/@azure/arm-storage/package.json
Labels: Unplanned-Sprint-127, in progress

#513 [AutoPR logic/resource-manager] Microsoft.Logic - Don't make ResourceReference id readonly
  packages/@azure/arm-logic/lib/models/index.ts
  packages/@azure/arm-logic/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#475 [AutoPR hdinsight/resource-manager] [HDInsight] - Support KV URL
  packages/@azure/arm-hdinsight/lib/hDInsightManagementClientContext.ts
  packages/@azure/arm-hdinsight/lib/models/applicationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/clustersMappers.ts
  packages/@azure/arm-hdinsight/lib/models/index.ts
  packages/@azure/arm-hdinsight/lib/models/mappers.ts
  packages/@azure/arm-hdinsight/lib/operations/applications.ts
  packages/@azure/arm-hdinsight/lib/operations/clusters.ts
  packages/@azure/arm-hdinsight/lib/operations/configurations.ts
  packages/@azure/arm-hdinsight/lib/operations/extensions.ts
  packages/@azure/arm-hdinsight/lib/operations/locations.ts
  packages/@azure/arm-hdinsight/lib/operations/operations.ts
  packages/@azure/arm-hdinsight/lib/operations/scriptActions.ts
  packages/@azure/arm-hdinsight/lib/operations/scriptExecutionHistory.ts
  packages/@azure/arm-hdinsight/package.json
Labels: RestPRMerged, in progress

#512 [AutoPR cognitiveservices/data-plane/AutoSuggest] Description of Autosuggest usage needs improvement.
  packages/@azure/cognitiveservices-autosuggest/README.md
  packages/@azure/cognitiveservices-autosuggest/lib/autoSuggestClient.ts
  packages/@azure/cognitiveservices-autosuggest/lib/autoSuggestClientContext.ts
  packages/@azure/cognitiveservices-autosuggest/lib/models/index.ts
  packages/@azure/cognitiveservices-autosuggest/lib/models/mappers.ts
  packages/@azure/cognitiveservices-autosuggest/lib/models/parameters.ts
  packages/@azure/cognitiveservices-autosuggest/package.json
  packages/@azure/cognitiveservices-autosuggest/rollup.config.js
  packages/@azure/cognitiveservices-autosuggest/tsconfig.json
Labels: RestPRMerged, in progress

#511 [AutoPR cognitiveservices/data-plane/QnAMaker] Adding API For QnAMaker v4.0
  packages/@azure/cognitiveservices-qnamaker/LICENSE.txt
  packages/@azure/cognitiveservices-qnamaker/README.md
  packages/@azure/cognitiveservices-qnamaker/lib/models/alterationsMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/endpointMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/index.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/knowledgebaseMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/mappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/operationsMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/parameters.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/alterations.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/endpoint.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/index.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/knowledgebase.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/operations.ts
  packages/@azure/cognitiveservices-qnamaker/lib/qnAMakerClient.ts
  packages/@azure/cognitiveservices-qnamaker/lib/qnAMakerClientContext.ts
  packages/@azure/cognitiveservices-qnamaker/package.json
  packages/@azure/cognitiveservices-qnamaker/rollup.config.js
  packages/@azure/cognitiveservices-qnamaker/tsconfig.json
Labels: RestPRMerged, in progress

#521 [AutoPR network/resource-manager] Fixes the missing array for the header actions
  packages/@azure/arm-network/lib/models/index.ts
  packages/@azure/arm-network/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#534 [AutoPR cdn/resource-manager] typo: cdn/resource-manager/Microsoft.Cdn/cdn.json
  packages/@azure/arm-cdn/LICENSE.txt
  packages/@azure/arm-cdn/README.md
  packages/@azure/arm-cdn/lib/cdnManagementClient.ts
  packages/@azure/arm-cdn/lib/cdnManagementClientContext.ts
  packages/@azure/arm-cdn/lib/models/index.ts
  packages/@azure/arm-cdn/lib/models/mappers.ts
  packages/@azure/arm-cdn/lib/models/parameters.ts
  packages/@azure/arm-cdn/lib/operations/customDomains.ts
  packages/@azure/arm-cdn/lib/operations/edgeNodes.ts
  packages/@azure/arm-cdn/lib/operations/endpoints.ts
  packages/@azure/arm-cdn/lib/operations/operations.ts
  packages/@azure/arm-cdn/lib/operations/origins.ts
  packages/@azure/arm-cdn/lib/operations/profiles.ts
  packages/@azure/arm-cdn/lib/operations/resourceUsageOperations.ts
  packages/@azure/arm-cdn/package.json
  packages/@azure/arm-cdn/rollup.config.js
  packages/@azure/arm-cdn/tsconfig.json
Labels: RestPRMerged, in progress

#525 Read packages from file system instead of spec repo.
  azure-pipelines.yml
  gulpfile.ts
  package.json
Labels: in progress

#533 [AutoPR cosmos-db/resource-manager] typo: cosmos-db/resource-manager/Microsoft.DocumentDB/cosmos-db.json
  packages/@azure/arm-cosmosdb/README.md
  packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClient.ts
  packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
  packages/@azure/arm-cosmosdb/lib/models/index.ts
  packages/@azure/arm-cosmosdb/lib/models/mappers.ts
  packages/@azure/arm-cosmosdb/lib/models/parameters.ts
  packages/@azure/arm-cosmosdb/lib/operations/collection.ts
  packages/@azure/arm-cosmosdb/lib/operations/collectionPartition.ts
  packages/@azure/arm-cosmosdb/lib/operations/collectionPartitionRegion.ts
  packages/@azure/arm-cosmosdb/lib/operations/collectionRegion.ts
  packages/@azure/arm-cosmosdb/lib/operations/database.ts
  packages/@azure/arm-cosmosdb/lib/operations/databaseAccountRegion.ts
  packages/@azure/arm-cosmosdb/lib/operations/databaseAccounts.ts
  packages/@azure/arm-cosmosdb/lib/operations/operations.ts
  packages/@azure/arm-cosmosdb/lib/operations/partitionKeyRangeId.ts
  packages/@azure/arm-cosmosdb/lib/operations/partitionKeyRangeIdRegion.ts
  packages/@azure/arm-cosmosdb/lib/operations/percentile.ts
  packages/@azure/arm-cosmosdb/lib/operations/percentileSourceTarget.ts
  packages/@azure/arm-cosmosdb/lib/operations/percentileTarget.ts
  packages/@azure/arm-cosmosdb/package.json
  packages/@azure/arm-cosmosdb/rollup.config.js
  packages/@azure/arm-cosmosdb/tsconfig.json
Labels: RestPRMerged, in progress

#540 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  packages/@azure/arm-authorization/LICENSE.txt
  packages/@azure/arm-authorization/README.md
  packages/@azure/arm-authorization/lib/authorizationManagementClient.ts
  packages/@azure/arm-authorization/lib/authorizationManagementClientContext.ts
  packages/@azure/arm-authorization/lib/models/index.ts
  packages/@azure/arm-authorization/lib/models/mappers.ts
  packages/@azure/arm-authorization/lib/models/parameters.ts
  packages/@azure/arm-authorization/lib/operations/classicAdministrators.ts
  packages/@azure/arm-authorization/lib/operations/denyAssignments.ts
  packages/@azure/arm-authorization/lib/operations/permissions.ts
  packages/@azure/arm-authorization/lib/operations/providerOperationsMetadataOperations.ts
  packages/@azure/arm-authorization/lib/operations/roleAssignments.ts
  packages/@azure/arm-authorization/lib/operations/roleDefinitions.ts
  packages/@azure/arm-authorization/package.json
  packages/@azure/arm-authorization/rollup.config.js
  packages/@azure/arm-authorization/tsconfig.json
Labels: RestPRMerged, in progress

#526 [AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json
  packages/@azure/arm-appservice/README.md
  packages/@azure/arm-appservice/lib/models/index.ts
  packages/@azure/arm-appservice/lib/models/mappers.ts
  packages/@azure/arm-appservice/lib/models/parameters.ts
  packages/@azure/arm-appservice/lib/operations/appServiceCertificateOrders.ts
  packages/@azure/arm-appservice/lib/operations/appServiceEnvironments.ts
  packages/@azure/arm-appservice/lib/operations/appServicePlans.ts
  packages/@azure/arm-appservice/lib/operations/certificateRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/certificates.ts
  packages/@azure/arm-appservice/lib/operations/deletedWebApps.ts
  packages/@azure/arm-appservice/lib/operations/diagnostics.ts
  packages/@azure/arm-appservice/lib/operations/domainRegistrationProvider.ts
  packages/@azure/arm-appservice/lib/operations/domains.ts
  packages/@azure/arm-appservice/lib/operations/provider.ts
  packages/@azure/arm-appservice/lib/operations/recommendations.ts
  packages/@azure/arm-appservice/lib/operations/resourceHealthMetadataOperations.ts
  packages/@azure/arm-appservice/lib/operations/topLevelDomains.ts
  packages/@azure/arm-appservice/lib/operations/webApps.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClient.ts
  packages/@azure/arm-appservice/lib/webSiteManagementClientContext.ts
  packages/@azure/arm-appservice/package.json
  packages/@azure/arm-appservice/rollup.config.js
  packages/@azure/arm-appservice/tsconfig.json
Labels: RestPRMerged, in progress

#532 [AutoPR iothub/resource-manager] typo: iothub/resource-manager/Microsoft.Devices/iothub.json
  packages/@azure/arm-iothub/.npmignore
  packages/@azure/arm-iothub/LICENSE.txt
  packages/@azure/arm-iothub/README.md
  packages/@azure/arm-iothub/package.json
Labels: RestPRMerged, in progress

#394 [AutoPR databox/resource-manager] DataBox : Swagger and example changes for next version of client DLL
  packages/@azure/arm-databox/LICENSE.txt
  packages/@azure/arm-databox/README.md
  packages/@azure/arm-databox/lib/dataBoxManagementClientContext.ts
  packages/@azure/arm-databox/lib/models/index.ts
  packages/@azure/arm-databox/lib/models/jobsMappers.ts
  packages/@azure/arm-databox/lib/models/mappers.ts
  packages/@azure/arm-databox/package.json
Labels: RestPRMerged, in progress

#552 [AutoPR storage/resource-manager] Adds canFailover boolean flag under storage account's GeoReplicationS…
  packages/@azure/arm-storage/README.md
  packages/@azure/arm-storage/lib/models/blobContainersMappers.ts
  packages/@azure/arm-storage/lib/models/blobServicesMappers.ts
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/models/managementPoliciesMappers.ts
  packages/@azure/arm-storage/lib/models/mappers.ts
  packages/@azure/arm-storage/lib/models/parameters.ts
  packages/@azure/arm-storage/lib/models/storageAccountsMappers.ts
  packages/@azure/arm-storage/lib/operations/blobContainers.ts
  packages/@azure/arm-storage/lib/operations/blobServices.ts
  packages/@azure/arm-storage/lib/operations/managementPolicies.ts
  packages/@azure/arm-storage/lib/operations/operations.ts
  packages/@azure/arm-storage/lib/operations/skus.ts
  packages/@azure/arm-storage/lib/operations/storageAccounts.ts
  packages/@azure/arm-storage/lib/operations/usages.ts
  packages/@azure/arm-storage/lib/storageManagementClient.ts
  packages/@azure/arm-storage/lib/storageManagementClientContext.ts
  packages/@azure/arm-storage/package.json
  packages/@azure/arm-storage/rollup.config.js
  packages/@azure/arm-storage/tsconfig.json
Labels: RestPRMerged, in progress

#518 [AutoPR billing/resource-manager] [Microsoft.Billing]: Updating swagger with rename changes required.
  packages/@azure/arm-billing/.npmignore
  packages/@azure/arm-billing/LICENSE.txt
  packages/@azure/arm-billing/README.md
  packages/@azure/arm-billing/lib/models/index.ts
  packages/@azure/arm-billing/lib/models/mappers.ts
  packages/@azure/arm-billing/package.json
  packages/@azure/arm-billing/tsconfig.esm.json
  packages/@azure/arm-billing/tsconfig.json
  packages/@azure/arm-billing/webpack.config.js
Labels: RestPRMerged, in progress

#549 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments
  packages/@azure/arm-appservice/lib/models/index.ts
Labels: RestPRMerged, in progress

#535 [AutoPR customer-insights/resource-manager] typo: Fix customer-insights/resource-manager/Microsoft.CustomerInsights/customer-insights
  packages/@azure/arm-customerinsights/LICENSE.txt
  packages/@azure/arm-customerinsights/README.md
  packages/@azure/arm-customerinsights/lib/customerInsightsManagementClient.ts
  packages/@azure/arm-customerinsights/lib/customerInsightsManagementClientContext.ts
  packages/@azure/arm-customerinsights/lib/models/index.ts
  packages/@azure/arm-customerinsights/lib/models/mappers.ts
  packages/@azure/arm-customerinsights/lib/models/parameters.ts
  packages/@azure/arm-customerinsights/lib/operations/authorizationPolicies.ts
  packages/@azure/arm-customerinsights/lib/operations/connectorMappings.ts
  packages/@azure/arm-customerinsights/lib/operations/connectors.ts
  packages/@azure/arm-customerinsights/lib/operations/hubs.ts
  packages/@azure/arm-customerinsights/lib/operations/images.ts
  packages/@azure/arm-customerinsights/lib/operations/interactions.ts
  packages/@azure/arm-customerinsights/lib/operations/kpi.ts
  packages/@azure/arm-customerinsights/lib/operations/links.ts
  packages/@azure/arm-customerinsights/lib/operations/operations.ts
  packages/@azure/arm-customerinsights/lib/operations/predictions.ts
  packages/@azure/arm-customerinsights/lib/operations/profiles.ts
  packages/@azure/arm-customerinsights/lib/operations/relationshipLinks.ts
  packages/@azure/arm-customerinsights/lib/operations/relationships.ts
  packages/@azure/arm-customerinsights/lib/operations/roleAssignments.ts
  packages/@azure/arm-customerinsights/lib/operations/roles.ts
  packages/@azure/arm-customerinsights/lib/operations/views.ts
  packages/@azure/arm-customerinsights/lib/operations/widgetTypes.ts
  packages/@azure/arm-customerinsights/package.json
  packages/@azure/arm-customerinsights/rollup.config.js
  packages/@azure/arm-customerinsights/tsconfig.json
Labels: RestPRMerged, in progress

#554 [AutoPR cognitiveservices/data-plane/TextAnalytics] Change default generation to TextAnalytics 2.1
  packages/@azure/cognitiveservices-textanalytics/lib/models/index.ts
  packages/@azure/cognitiveservices-textanalytics/lib/models/mappers.ts
  packages/@azure/cognitiveservices-textanalytics/lib/textAnalyticsClient.ts
  packages/@azure/cognitiveservices-textanalytics/package.json
Labels: RestPRMerged, in progress

#558 [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights/policyEvents
  packages/@azure/arm-policyinsights/LICENSE.txt
  packages/@azure/arm-policyinsights/README.md
  packages/@azure/arm-policyinsights/lib/models/index.ts
  packages/@azure/arm-policyinsights/lib/models/mappers.ts
  packages/@azure/arm-policyinsights/lib/models/parameters.ts
  packages/@azure/arm-policyinsights/lib/operations/operations.ts
  packages/@azure/arm-policyinsights/lib/operations/policyEvents.ts
  packages/@azure/arm-policyinsights/lib/operations/policyStates.ts
  packages/@azure/arm-policyinsights/lib/operations/policyTrackedResources.ts
  packages/@azure/arm-policyinsights/lib/operations/remediations.ts
  packages/@azure/arm-policyinsights/lib/policyInsightsClient.ts
  packages/@azure/arm-policyinsights/lib/policyInsightsClientContext.ts
  packages/@azure/arm-policyinsights/package.json
  packages/@azure/arm-policyinsights/rollup.config.js
  packages/@azure/arm-policyinsights/tsconfig.json
Labels: RestPRMerged, in progress

#564 [AutoPR batchai/resource-manager] typo: batchai/resource-manager/Microsoft.BatchAI/BatchAI
  packages/@azure/arm-batchai/LICENSE.txt
  packages/@azure/arm-batchai/README.md
  packages/@azure/arm-batchai/lib/batchAIManagementClient.ts
  packages/@azure/arm-batchai/lib/batchAIManagementClientContext.ts
  packages/@azure/arm-batchai/lib/models/index.ts
  packages/@azure/arm-batchai/lib/models/mappers.ts
  packages/@azure/arm-batchai/lib/models/parameters.ts
  packages/@azure/arm-batchai/lib/operations/clusters.ts
  packages/@azure/arm-batchai/lib/operations/experiments.ts
  packages/@azure/arm-batchai/lib/operations/fileServers.ts
  packages/@azure/arm-batchai/lib/operations/jobs.ts
  packages/@azure/arm-batchai/lib/operations/operations.ts
  packages/@azure/arm-batchai/lib/operations/usages.ts
  packages/@azure/arm-batchai/lib/operations/workspaces.ts
  packages/@azure/arm-batchai/package.json
  packages/@azure/arm-batchai/rollup.config.js
  packages/@azure/arm-batchai/tsconfig.json
Labels: RestPRMerged, in progress

#550 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric
  packages/@azure/servicefabric/.npmignore
  packages/@azure/servicefabric/LICENSE.txt
  packages/@azure/servicefabric/README.md
  packages/@azure/servicefabric/lib/models/index.ts
  packages/@azure/servicefabric/lib/models/mappers.ts
  packages/@azure/servicefabric/lib/serviceFabricClient.ts
  packages/@azure/servicefabric/package.json
Labels: RestPRMerged, in progress

#571 [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API
  packages/@azure/arm-appinsights/LICENSE.txt
  packages/@azure/arm-appinsights/README.md
  packages/@azure/arm-appinsights/lib/applicationInsightsManagementClient.ts
  packages/@azure/arm-appinsights/lib/applicationInsightsManagementClientContext.ts
  packages/@azure/arm-appinsights/lib/models/index.ts
  packages/@azure/arm-appinsights/lib/models/mappers.ts
  packages/@azure/arm-appinsights/lib/models/parameters.ts
  packages/@azure/arm-appinsights/lib/operations/aPIKeys.ts
  packages/@azure/arm-appinsights/lib/operations/analyticsItems.ts
  packages/@azure/arm-appinsights/lib/operations/annotations.ts
  packages/@azure/arm-appinsights/lib/operations/componentAvailableFeatures.ts
  packages/@azure/arm-appinsights/lib/operations/componentCurrentBillingFeatures.ts
  packages/@azure/arm-appinsights/lib/operations/componentFeatureCapabilities.ts
  packages/@azure/arm-appinsights/lib/operations/componentQuotaStatus.ts
  packages/@azure/arm-appinsights/lib/operations/components.ts
  packages/@azure/arm-appinsights/lib/operations/exportConfigurations.ts
  packages/@azure/arm-appinsights/lib/operations/favorites.ts
  packages/@azure/arm-appinsights/lib/operations/operations.ts
  packages/@azure/arm-appinsights/lib/operations/proactiveDetectionConfigurations.ts
  packages/@azure/arm-appinsights/lib/operations/webTestLocations.ts
  packages/@azure/arm-appinsights/lib/operations/webTests.ts
  packages/@azure/arm-appinsights/lib/operations/workItemConfigurations.ts
  packages/@azure/arm-appinsights/lib/operations/workbooks.ts
  packages/@azure/arm-appinsights/package.json
  packages/@azure/arm-appinsights/rollup.config.js
  packages/@azure/arm-appinsights/tsconfig.json
Labels: RestPRMerged, in progress

#567 [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/operations/storageAccounts.ts
Labels: RestPRMerged, in progress

#562 [AutoPR mediaservices/resource-manager] typo: mediaservices/resource-manager/Microsoft.Media/Encoding
  packages/@azure/arm-mediaservices/LICENSE.txt
  packages/@azure/arm-mediaservices/README.md
  packages/@azure/arm-mediaservices/lib/azureMediaServices.ts
  packages/@azure/arm-mediaservices/lib/azureMediaServicesContext.ts
  packages/@azure/arm-mediaservices/lib/models/index.ts
  packages/@azure/arm-mediaservices/lib/models/mappers.ts
  packages/@azure/arm-mediaservices/lib/models/parameters.ts
  packages/@azure/arm-mediaservices/lib/operations/accountFilters.ts
  packages/@azure/arm-mediaservices/lib/operations/assetFilters.ts
  packages/@azure/arm-mediaservices/lib/operations/assets.ts
  packages/@azure/arm-mediaservices/lib/operations/contentKeyPolicies.ts
  packages/@azure/arm-mediaservices/lib/operations/jobs.ts
  packages/@azure/arm-mediaservices/lib/operations/liveEvents.ts
  packages/@azure/arm-mediaservices/lib/operations/liveOutputs.ts
  packages/@azure/arm-mediaservices/lib/operations/locations.ts
  packages/@azure/arm-mediaservices/lib/operations/mediaservices.ts
  packages/@azure/arm-mediaservices/lib/operations/operations.ts
  packages/@azure/arm-mediaservices/lib/operations/streamingEndpoints.ts
  packages/@azure/arm-mediaservices/lib/operations/streamingLocators.ts
  packages/@azure/arm-mediaservices/lib/operations/streamingPolicies.ts
  packages/@azure/arm-mediaservices/lib/operations/transforms.ts
  packages/@azure/arm-mediaservices/package.json
  packages/@azure/arm-mediaservices/rollup.config.js
  packages/@azure/arm-mediaservices/tsconfig.json
Labels: RestPRMerged, in progress

#560 [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory/entityTypes/LinkedService
  packages/@azure/arm-datafactory/README.md
  packages/@azure/arm-datafactory/lib/dataFactoryManagementClient.ts
  packages/@azure/arm-datafactory/lib/dataFactoryManagementClientContext.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/parameters.ts
  packages/@azure/arm-datafactory/lib/operations/activityRuns.ts
  packages/@azure/arm-datafactory/lib/operations/datasets.ts
  packages/@azure/arm-datafactory/lib/operations/factories.ts
  packages/@azure/arm-datafactory/lib/operations/integrationRuntimeNodes.ts
  packages/@azure/arm-datafactory/lib/operations/integrationRuntimes.ts
  packages/@azure/arm-datafactory/lib/operations/linkedServices.ts
  packages/@azure/arm-datafactory/lib/operations/operations.ts
  packages/@azure/arm-datafactory/lib/operations/pipelineRuns.ts
  packages/@azure/arm-datafactory/lib/operations/pipelines.ts
  packages/@azure/arm-datafactory/lib/operations/rerunTriggers.ts
  packages/@azure/arm-datafactory/lib/operations/triggerRuns.ts
  packages/@azure/arm-datafactory/lib/operations/triggers.ts
  packages/@azure/arm-datafactory/package.json
  packages/@azure/arm-datafactory/rollup.config.js
  packages/@azure/arm-datafactory/tsconfig.json
Labels: RestPRMerged, in progress

#572 [AutoPR eventhub/resource-manager] typo: eventhub/resource-manager/Microsoft.EventHub/EventHub
  packages/@azure/arm-eventhub/LICENSE.txt
  packages/@azure/arm-eventhub/README.md
  packages/@azure/arm-eventhub/lib/eventHubManagementClient.ts
  packages/@azure/arm-eventhub/lib/eventHubManagementClientContext.ts
  packages/@azure/arm-eventhub/lib/models/index.ts
  packages/@azure/arm-eventhub/lib/models/mappers.ts
  packages/@azure/arm-eventhub/lib/models/parameters.ts
  packages/@azure/arm-eventhub/lib/operations/consumerGroups.ts
  packages/@azure/arm-eventhub/lib/operations/disasterRecoveryConfigs.ts
  packages/@azure/arm-eventhub/lib/operations/eventHubs.ts
  packages/@azure/arm-eventhub/lib/operations/namespaces.ts
  packages/@azure/arm-eventhub/lib/operations/operations.ts
  packages/@azure/arm-eventhub/lib/operations/regions.ts
  packages/@azure/arm-eventhub/package.json
  packages/@azure/arm-eventhub/rollup.config.js
  packages/@azure/arm-eventhub/tsconfig.json
Labels: RestPRMerged, in progress

#523 [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup
  packages/@azure/arm-resources/lib/models/index.ts
  packages/@azure/arm-resources/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#575 [AutoPR security/resource-manager] rename folder paths for autorest code generation
  packages/@azure/arm-security/README.md
  packages/@azure/arm-security/lib/models/index.ts
  packages/@azure/arm-security/lib/models/mappers.ts
  packages/@azure/arm-security/lib/models/parameters.ts
  packages/@azure/arm-security/lib/operations/advancedThreatProtection.ts
  packages/@azure/arm-security/lib/operations/alerts.ts
  packages/@azure/arm-security/lib/operations/allowedConnections.ts
  packages/@azure/arm-security/lib/operations/autoProvisioningSettings.ts
  packages/@azure/arm-security/lib/operations/compliances.ts
  packages/@azure/arm-security/lib/operations/discoveredSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/externalSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/informationProtectionPolicies.ts
  packages/@azure/arm-security/lib/operations/jitNetworkAccessPolicies.ts
  packages/@azure/arm-security/lib/operations/locations.ts
  packages/@azure/arm-security/lib/operations/operations.ts
  packages/@azure/arm-security/lib/operations/pricings.ts
  packages/@azure/arm-security/lib/operations/securityContacts.ts
  packages/@azure/arm-security/lib/operations/settings.ts
  packages/@azure/arm-security/lib/operations/tasks.ts
  packages/@azure/arm-security/lib/operations/topology.ts
  packages/@azure/arm-security/lib/operations/workspaceSettings.ts
  packages/@azure/arm-security/lib/securityCenter.ts
  packages/@azure/arm-security/lib/securityCenterContext.ts
  packages/@azure/arm-security/package.json
  packages/@azure/arm-security/rollup.config.js
  packages/@azure/arm-security/tsconfig.json
Labels: RestPRMerged, in progress

#585 [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/operations/integrationRuntimes.ts
Labels: RestPRMerged, in progress

#530 [AutoPR graphrbac/data-plane] add customKeyIdentifier to password credential
  packages/@azure/graph/LICENSE.txt
  packages/@azure/graph/README.md
  packages/@azure/graph/lib/graphRbacManagementClient.ts
  packages/@azure/graph/lib/graphRbacManagementClientContext.ts
  packages/@azure/graph/lib/models/deletedApplicationsMappers.ts
  packages/@azure/graph/lib/models/groupsMappers.ts
  packages/@azure/graph/lib/models/index.ts
  packages/@azure/graph/lib/models/mappers.ts
  packages/@azure/graph/lib/models/objectsMappers.ts
  packages/@azure/graph/lib/models/parameters.ts
  packages/@azure/graph/lib/models/signedInUserMappers.ts
  packages/@azure/graph/lib/models/usersMappers.ts
  packages/@azure/graph/lib/operations/applications.ts
  packages/@azure/graph/lib/operations/deletedApplications.ts
  packages/@azure/graph/lib/operations/domains.ts
  packages/@azure/graph/lib/operations/groups.ts
  packages/@azure/graph/lib/operations/oAuth2.ts
  packages/@azure/graph/lib/operations/objects.ts
  packages/@azure/graph/lib/operations/servicePrincipals.ts
  packages/@azure/graph/lib/operations/signedInUser.ts
  packages/@azure/graph/lib/operations/users.ts
  packages/@azure/graph/package.json
  packages/@azure/graph/rollup.config.js
  packages/@azure/graph/tsconfig.json
Labels: RestPRMerged, in progress

#583 [AutoPR storagesync/resource-manager] Microsoft.StorageSync - Fix Issue 4559 and other known problems with preview version
  packages/@azure/arm-storagesync/package.json
Labels: RestPRMerged, in progress

#586 [AutoPR analysisservices/resource-manager] typo: analysisservices/resource-manager/Microsoft.AnalysisServices
  packages/@azure/arm-analysisservices/LICENSE.txt
  packages/@azure/arm-analysisservices/README.md
  packages/@azure/arm-analysisservices/lib/analysisServicesManagementClient.ts
  packages/@azure/arm-analysisservices/lib/analysisServicesManagementClientContext.ts
  packages/@azure/arm-analysisservices/lib/models/index.ts
  packages/@azure/arm-analysisservices/lib/models/mappers.ts
  packages/@azure/arm-analysisservices/lib/models/parameters.ts
  packages/@azure/arm-analysisservices/lib/operations/operations.ts
  packages/@azure/arm-analysisservices/lib/operations/servers.ts
  packages/@azure/arm-analysisservices/package.json
  packages/@azure/arm-analysisservices/rollup.config.js
  packages/@azure/arm-analysisservices/tsconfig.json
Labels: RestPRMerged, in progress

#561 [AutoPR devtestlabs/resource-manager] typo: devtestlabs/resource-manager/Microsoft.DevTestLab/DTL
  packages/@azure/arm-devtestlabs/README.md
  packages/@azure/arm-devtestlabs/lib/devTestLabsClient.ts
  packages/@azure/arm-devtestlabs/lib/devTestLabsClientContext.ts
  packages/@azure/arm-devtestlabs/lib/models/index.ts
  packages/@azure/arm-devtestlabs/lib/models/mappers.ts
  packages/@azure/arm-devtestlabs/lib/models/parameters.ts
  packages/@azure/arm-devtestlabs/lib/operations/armTemplates.ts
  packages/@azure/arm-devtestlabs/lib/operations/artifactSources.ts
  packages/@azure/arm-devtestlabs/lib/operations/artifacts.ts
  packages/@azure/arm-devtestlabs/lib/operations/costs.ts
  packages/@azure/arm-devtestlabs/lib/operations/customImages.ts
  packages/@azure/arm-devtestlabs/lib/operations/disks.ts
  packages/@azure/arm-devtestlabs/lib/operations/environments.ts
  packages/@azure/arm-devtestlabs/lib/operations/formulas.ts
  packages/@azure/arm-devtestlabs/lib/operations/galleryImages.ts
  packages/@azure/arm-devtestlabs/lib/operations/globalSchedules.ts
  packages/@azure/arm-devtestlabs/lib/operations/labs.ts
  packages/@azure/arm-devtestlabs/lib/operations/notificationChannels.ts
  packages/@azure/arm-devtestlabs/lib/operations/operations.ts
  packages/@azure/arm-devtestlabs/lib/operations/policies.ts
  packages/@azure/arm-devtestlabs/lib/operations/policySets.ts
  packages/@azure/arm-devtestlabs/lib/operations/providerOperations.ts
  packages/@azure/arm-devtestlabs/lib/operations/schedules.ts
  packages/@azure/arm-devtestlabs/lib/operations/secrets.ts
  packages/@azure/arm-devtestlabs/lib/operations/serviceFabricSchedules.ts
  packages/@azure/arm-devtestlabs/lib/operations/serviceFabrics.ts
  packages/@azure/arm-devtestlabs/lib/operations/serviceRunners.ts
  packages/@azure/arm-devtestlabs/lib/operations/users.ts
  packages/@azure/arm-devtestlabs/lib/operations/virtualMachineSchedules.ts
  packages/@azure/arm-devtestlabs/lib/operations/virtualMachines.ts
  packages/@azure/arm-devtestlabs/lib/operations/virtualNetworks.ts
  packages/@azure/arm-devtestlabs/package.json
  packages/@azure/arm-devtestlabs/rollup.config.js
  packages/@azure/arm-devtestlabs/tsconfig.json
Labels: RestPRMerged, in progress

#514 [AutoPR msi/resource-manager] Update manage service identity api version
  packages/@azure/arm-msi/LICENSE.txt
  packages/@azure/arm-msi/README.md
  packages/@azure/arm-msi/lib/managedServiceIdentityClient.ts
  packages/@azure/arm-msi/lib/managedServiceIdentityClientContext.ts
  packages/@azure/arm-msi/lib/models/index.ts
  packages/@azure/arm-msi/lib/models/mappers.ts
  packages/@azure/arm-msi/lib/models/parameters.ts
  packages/@azure/arm-msi/lib/operations/operations.ts
  packages/@azure/arm-msi/lib/operations/userAssignedIdentities.ts
  packages/@azure/arm-msi/package.json
  packages/@azure/arm-msi/rollup.config.js
  packages/@azure/arm-msi/tsconfig.json
Labels: RestPRMerged, in progress

#598 Update dependencies
  .scripts/logger.ts
  azure-pipelines.yml
  gulpfile.ts
  package.json
  packages/@azure/arm-datamigration/LICENSE.txt
  packages/@azure/arm-datamigration/README.md
  packages/@azure/arm-datamigration/lib/dataMigrationServiceClient.ts
  packages/@azure/arm-datamigration/lib/dataMigrationServiceClientContext.ts
  packages/@azure/arm-datamigration/lib/models/filesMappers.ts
  packages/@azure/arm-datamigration/lib/models/index.ts
  packages/@azure/arm-datamigration/lib/models/mappers.ts
  packages/@azure/arm-datamigration/lib/models/operationsMappers.ts
  packages/@azure/arm-datamigration/lib/models/parameters.ts
  packages/@azure/arm-datamigration/lib/models/projectsMappers.ts
  packages/@azure/arm-datamigration/lib/models/resourceSkusMappers.ts
  packages/@azure/arm-datamigration/lib/models/servicesMappers.ts
  packages/@azure/arm-datamigration/lib/models/tasksMappers.ts
  packages/@azure/arm-datamigration/lib/models/usagesMappers.ts
  packages/@azure/arm-datamigration/lib/operations/files.ts
  packages/@azure/arm-datamigration/lib/operations/index.ts
  packages/@azure/arm-datamigration/lib/operations/operations.ts
  packages/@azure/arm-datamigration/lib/operations/projects.ts
  packages/@azure/arm-datamigration/lib/operations/resourceSkus.ts
  packages/@azure/arm-datamigration/lib/operations/services.ts
  packages/@azure/arm-datamigration/lib/operations/tasks.ts
  packages/@azure/arm-datamigration/lib/operations/usages.ts
  packages/@azure/arm-datamigration/package.json
  packages/@azure/arm-datamigration/rollup.config.js
  packages/@azure/arm-datamigration/tsconfig.json
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress

#600 [AutoPR resources/resource-manager] Fix the ARM R2062 error for Microsoft.Resources
  packages/@azure/arm-resources/lib/models/deploymentsMappers.ts
  packages/@azure/arm-resources/lib/models/index.ts
  packages/@azure/arm-resources/lib/models/resourceGroupsMappers.ts
  packages/@azure/arm-resources/lib/models/resourcesMappers.ts
Labels: RestPRMerged, in progress

#602 Generate @azure/arm-kusto
  packages/@azure/arm-kusto/LICENSE.txt
  packages/@azure/arm-kusto/README.md
  packages/@azure/arm-kusto/lib/kustoManagementClient.ts
  packages/@azure/arm-kusto/lib/kustoManagementClientContext.ts
  packages/@azure/arm-kusto/lib/models/clustersMappers.ts
  packages/@azure/arm-kusto/lib/models/databasesMappers.ts
  packages/@azure/arm-kusto/lib/models/eventHubConnectionsMappers.ts
  packages/@azure/arm-kusto/lib/models/index.ts
  packages/@azure/arm-kusto/lib/models/mappers.ts
  packages/@azure/arm-kusto/lib/models/operationsMappers.ts
  packages/@azure/arm-kusto/lib/models/parameters.ts
  packages/@azure/arm-kusto/lib/operations/clusters.ts
  packages/@azure/arm-kusto/lib/operations/databases.ts
  packages/@azure/arm-kusto/lib/operations/eventHubConnections.ts
  packages/@azure/arm-kusto/lib/operations/index.ts
  packages/@azure/arm-kusto/lib/operations/operations.ts
  packages/@azure/arm-kusto/package.json
  packages/@azure/arm-kusto/rollup.config.js
  packages/@azure/arm-kusto/tsconfig.json
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#599 [AutoPR timeseriesinsights/resource-manager] Add a new preview api-version for Time Series Insights
  packages/@azure/arm-timeseriesinsights/LICENSE.txt
  packages/@azure/arm-timeseriesinsights/README.md
  packages/@azure/arm-timeseriesinsights/lib/models/index.ts
  packages/@azure/arm-timeseriesinsights/lib/models/mappers.ts
  packages/@azure/arm-timeseriesinsights/lib/models/parameters.ts
  packages/@azure/arm-timeseriesinsights/lib/operations/accessPolicies.ts
  packages/@azure/arm-timeseriesinsights/lib/operations/environments.ts
  packages/@azure/arm-timeseriesinsights/lib/operations/eventSources.ts
  packages/@azure/arm-timeseriesinsights/lib/operations/operations.ts
  packages/@azure/arm-timeseriesinsights/lib/operations/referenceDataSets.ts
  packages/@azure/arm-timeseriesinsights/lib/timeSeriesInsightsClient.ts
  packages/@azure/arm-timeseriesinsights/lib/timeSeriesInsightsClientContext.ts
  packages/@azure/arm-timeseriesinsights/package.json
  packages/@azure/arm-timeseriesinsights/rollup.config.js
  packages/@azure/arm-timeseriesinsights/tsconfig.json
Labels: RestPRMerged, in progress

#609 [AutoPR resources/resource-manager] Revert "Fix the ARM R2062 error for Microsoft.Resources"
  packages/@azure/arm-resources/lib/models/deploymentsMappers.ts
  packages/@azure/arm-resources/lib/models/index.ts
  packages/@azure/arm-resources/lib/models/resourceGroupsMappers.ts
  packages/@azure/arm-resources/lib/models/resourcesMappers.ts
Labels: RestPRMerged

#615 Regenerate @azure/arm-network, bump version to 0.2.1, add README.md
  packages/@azure/arm-network/README.md
  packages/@azure/arm-network/lib/networkManagementClientContext.ts
  packages/@azure/arm-network/package.json
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#621 [AutoPR cdn/resource-manager] typo: Microsoft.Cdn
  packages/@azure/arm-cdn/lib/cdnManagementClientContext.ts
  packages/@azure/arm-cdn/lib/models/index.ts
Labels: RestPRMerged, in progress

#529 [AutoPR containerregistry/resource-manager] [ACR] Add empty resource group name validation, minor cleanup
  packages/@azure/arm-containerregistry/README.md
  packages/@azure/arm-containerregistry/lib/containerRegistryManagementClient.ts
  packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/lib/models/parameters.ts
  packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
  packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
  packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
  packages/@azure/arm-containerregistry/lib/operations/operations.ts
  packages/@azure/arm-containerregistry/lib/operations/registries.ts
  packages/@azure/arm-containerregistry/lib/operations/replications.ts
  packages/@azure/arm-containerregistry/lib/operations/runs.ts
  packages/@azure/arm-containerregistry/lib/operations/tasks.ts
  packages/@azure/arm-containerregistry/lib/operations/webhooks.ts
  packages/@azure/arm-containerregistry/package.json
  packages/@azure/arm-containerregistry/rollup.config.js
  packages/@azure/arm-containerregistry/tsconfig.json
Labels: RestPRMerged, in progress

#625 [AutoPR apimanagement/resource-manager] Added example for template params
  packages/@azure/arm-apimanagement/lib/models/index.ts
  packages/@azure/arm-apimanagement/lib/operations/apiDiagnosticLogger.ts
  packages/@azure/arm-apimanagement/lib/operations/apiIssue.ts
  packages/@azure/arm-apimanagement/lib/operations/apiIssueAttachment.ts
  packages/@azure/arm-apimanagement/lib/operations/apiIssueComment.ts
  packages/@azure/arm-apimanagement/lib/operations/diagnosticLogger.ts
  packages/@azure/arm-apimanagement/lib/operations/property.ts
  packages/@azure/arm-apimanagement/lib/operations/reports.ts
  packages/@azure/arm-apimanagement/lib/operations/subscription.ts
  packages/@azure/arm-apimanagement/lib/operations/tagDescription.ts
Labels: RestPRMerged

#606 [AutoPR automation/resource-manager] typo: Microsoft.Automation
  packages/@azure/arm-automation/LICENSE.txt
  packages/@azure/arm-automation/README.md
  packages/@azure/arm-automation/lib/automationClient.ts
  packages/@azure/arm-automation/lib/automationClientContext.ts
  packages/@azure/arm-automation/lib/models/index.ts
  packages/@azure/arm-automation/lib/models/mappers.ts
  packages/@azure/arm-automation/lib/models/parameters.ts
  packages/@azure/arm-automation/lib/operations/activityOperations.ts
  packages/@azure/arm-automation/lib/operations/agentRegistrationInformation.ts
  packages/@azure/arm-automation/lib/operations/automationAccountOperations.ts
  packages/@azure/arm-automation/lib/operations/certificateOperations.ts
  packages/@azure/arm-automation/lib/operations/connectionOperations.ts
  packages/@azure/arm-automation/lib/operations/connectionTypeOperations.ts
  packages/@azure/arm-automation/lib/operations/credentialOperations.ts
  packages/@azure/arm-automation/lib/operations/dscCompilationJobOperations.ts
  packages/@azure/arm-automation/lib/operations/dscCompilationJobStream.ts
  packages/@azure/arm-automation/lib/operations/dscConfigurationOperations.ts
  packages/@azure/arm-automation/lib/operations/dscNodeConfigurationOperations.ts
  packages/@azure/arm-automation/lib/operations/dscNodeOperations.ts
  packages/@azure/arm-automation/lib/operations/fields.ts
  packages/@azure/arm-automation/lib/operations/hybridRunbookWorkerGroupOperations.ts
  packages/@azure/arm-automation/lib/operations/jobOperations.ts
  packages/@azure/arm-automation/lib/operations/jobScheduleOperations.ts
  packages/@azure/arm-automation/lib/operations/jobStreamOperations.ts
  packages/@azure/arm-automation/lib/operations/keys.ts
  packages/@azure/arm-automation/lib/operations/linkedWorkspaceOperations.ts
  packages/@azure/arm-automation/lib/operations/moduleOperations.ts
  packages/@azure/arm-automation/lib/operations/nodeCountInformation.ts
  packages/@azure/arm-automation/lib/operations/nodeReports.ts
  packages/@azure/arm-automation/lib/operations/objectDataTypes.ts
  packages/@azure/arm-automation/lib/operations/operations.ts
  packages/@azure/arm-automation/lib/operations/python2Package.ts
  packages/@azure/arm-automation/lib/operations/runbookDraftOperations.ts
  packages/@azure/arm-automation/lib/operations/runbookOperations.ts
  packages/@azure/arm-automation/lib/operations/scheduleOperations.ts
  packages/@azure/arm-automation/lib/operations/softwareUpdateConfigurationMachineRuns.ts
  packages/@azure/arm-automation/lib/operations/softwareUpdateConfigurationRuns.ts
  packages/@azure/arm-automation/lib/operations/softwareUpdateConfigurations.ts
  packages/@azure/arm-automation/lib/operations/sourceControlOperations.ts
  packages/@azure/arm-automation/lib/operations/sourceControlSyncJobOperations.ts
  packages/@azure/arm-automation/lib/operations/sourceControlSyncJobStreams.ts
  packages/@azure/arm-automation/lib/operations/statisticsOperations.ts
  packages/@azure/arm-automation/lib/operations/testJobOperations.ts
  packages/@azure/arm-automation/lib/operations/testJobStreams.ts
  packages/@azure/arm-automation/lib/operations/usages.ts
  packages/@azure/arm-automation/lib/operations/variableOperations.ts
  packages/@azure/arm-automation/lib/operations/watcherOperations.ts
  packages/@azure/arm-automation/lib/operations/webhookOperations.ts
  packages/@azure/arm-automation/package.json
  packages/@azure/arm-automation/rollup.config.js
  packages/@azure/arm-automation/tsconfig.json
Labels: RestPRMerged, in progress
