Repository Azure/azure-sdk-for-js, pull requests merged in 2018-12, with the labels that each got.

#629 [AutoPR compute/resource-manager] updated Reimage API documentation in compute json for ephemeral os disks
  packages/@azure/arm-compute/LICENSE.txt
  packages/@azure/arm-compute/README.md
  packages/@azure/arm-compute/lib/computeManagementClient.ts
  packages/@azure/arm-compute/lib/computeManagementClientContext.ts
  packages/@azure/arm-compute/lib/models/index.ts
  packages/@azure/arm-compute/lib/models/mappers.ts
  packages/@azure/arm-compute/lib/models/parameters.ts
  packages/@azure/arm-compute/lib/operations/availabilitySets.ts
  packages/@azure/arm-compute/lib/operations/containerServices.ts
  packages/@azure/arm-compute/lib/operations/disks.ts
  packages/@azure/arm-compute/lib/operations/galleries.ts
  packages/@azure/arm-compute/lib/operations/galleryImageVersions.ts
  packages/@azure/arm-compute/lib/operations/galleryImages.ts
  packages/@azure/arm-compute/lib/operations/images.ts
  packages/@azure/arm-compute/lib/operations/logAnalytics.ts
  packages/@azure/arm-compute/lib/operations/operations.ts
  packages/@azure/arm-compute/lib/operations/resourceSkus.ts
  packages/@azure/arm-compute/lib/operations/snapshots.ts
  packages/@azure/arm-compute/lib/operations/usageOperations.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineExtensionImages.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineExtensions.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineImages.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineRunCommands.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineScaleSetExtensions.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineScaleSetRollingUpgrades.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineScaleSetVMs.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineScaleSets.ts
  packages/@azure/arm-compute/lib/operations/virtualMachineSizes.ts
  packages/@azure/arm-compute/lib/operations/virtualMachines.ts
  packages/@azure/arm-compute/package.json
  packages/@azure/arm-compute/rollup.config.js
  packages/@azure/arm-compute/tsconfig.json
Labels: RestPRMerged, in progress

#677 [AutoPR operationalinsights/resource-manager] typo: operationalinsights/resource-manager/Microsoft.OperationalInsights
  packages/@azure/arm-operationalinsights/LICENSE.txt
  packages/@azure/arm-operationalinsights/README.md
  packages/@azure/arm-operationalinsights/lib/models/index.ts
  packages/@azure/arm-operationalinsights/lib/operationalInsightsManagementClientContext.ts
  packages/@azure/arm-operationalinsights/lib/operations/dataSources.ts
  packages/@azure/arm-operationalinsights/lib/operations/linkedServices.ts
  packages/@azure/arm-operationalinsights/lib/operations/operations.ts
  packages/@azure/arm-operationalinsights/lib/operations/workspaces.ts
  packages/@azure/arm-operationalinsights/package.json
Labels: RestPRMerged, in progress

#666 [AutoPR marketplaceordering/resource-manager] typo: marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering
  packages/@azure/arm-marketplaceordering/LICENSE.txt
  packages/@azure/arm-marketplaceordering/README.md
  packages/@azure/arm-marketplaceordering/lib/marketplaceOrderingAgreements.ts
  packages/@azure/arm-marketplaceordering/lib/marketplaceOrderingAgreementsContext.ts
  packages/@azure/arm-marketplaceordering/lib/models/index.ts
  packages/@azure/arm-marketplaceordering/lib/models/mappers.ts
  packages/@azure/arm-marketplaceordering/lib/models/parameters.ts
  packages/@azure/arm-marketplaceordering/lib/operations/marketplaceAgreements.ts
  packages/@azure/arm-marketplaceordering/lib/operations/operations.ts
  packages/@azure/arm-marketplaceordering/package.json
  packages/@azure/arm-marketplaceordering/rollup.config.js
  packages/@azure/arm-marketplaceordering/tsconfig.json
Labels: RestPRMerged, in progress

#656 [AutoPR graphrbac/data-plane] typo: graphrbac
  packages/@azure/graph/lib/models/index.ts
Labels: RestPRMerged

#645 [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB
  packages/@azure/arm-cosmosdb/lib/cosmosDBManagementClientContext.ts
  packages/@azure/arm-cosmosdb/lib/operations/databaseAccounts.ts
Labels: RestPRMerged, in progress

#639 [AutoPR compute/resource-manager] typo: Microsoft.Compute
  packages/@azure/arm-compute/lib/models/index.ts
Labels: RestPRMerged, in progress

#649 [AutoPR deploymentmanager/resource-manager] typo: Microsoft.DeploymentManager
  packages/@azure/arm-deploymentmanager/LICENSE.txt
  packages/@azure/arm-deploymentmanager/README.md
  packages/@azure/arm-deploymentmanager/lib/azureDeploymentManager.ts
  packages/@azure/arm-deploymentmanager/lib/azureDeploymentManagerContext.ts
  packages/@azure/arm-deploymentmanager/lib/models/index.ts
  packages/@azure/arm-deploymentmanager/lib/models/mappers.ts
  packages/@azure/arm-deploymentmanager/lib/models/parameters.ts
  packages/@azure/arm-deploymentmanager/lib/operations/artifactSources.ts
  packages/@azure/arm-deploymentmanager/lib/operations/operations.ts
  packages/@azure/arm-deploymentmanager/lib/operations/rollouts.ts
  packages/@azure/arm-deploymentmanager/lib/operations/serviceTopologies.ts
  packages/@azure/arm-deploymentmanager/lib/operations/serviceUnits.ts
  packages/@azure/arm-deploymentmanager/lib/operations/services.ts
  packages/@azure/arm-deploymentmanager/lib/operations/steps.ts
  packages/@azure/arm-deploymentmanager/package.json
  packages/@azure/arm-deploymentmanager/rollup.config.js
  packages/@azure/arm-deploymentmanager/tsconfig.json
Labels: RestPRMerged, in progress

#651 [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab
  packages/@azure/arm-devtestlabs/lib/models/index.ts
  packages/@azure/arm-devtestlabs/lib/operations/notificationChannels.ts
Labels: RestPRMerged, in progress

#647 [AutoPR datacatalog/resource-manager] typo: Microsoft.DataCatalog
  packages/@azure/arm-datacatalog/LICENSE.txt
  packages/@azure/arm-datacatalog/README.md
  packages/@azure/arm-datacatalog/lib/dataCatalogRestClient.ts
  packages/@azure/arm-datacatalog/lib/dataCatalogRestClientContext.ts
  packages/@azure/arm-datacatalog/lib/models/index.ts
  packages/@azure/arm-datacatalog/lib/models/mappers.ts
  packages/@azure/arm-datacatalog/lib/models/parameters.ts
  packages/@azure/arm-datacatalog/lib/operations/aDCCatalogs.ts
  packages/@azure/arm-datacatalog/lib/operations/aDCOperations.ts
  packages/@azure/arm-datacatalog/package.json
  packages/@azure/arm-datacatalog/rollup.config.js
  packages/@azure/arm-datacatalog/tsconfig.json
Labels: RestPRMerged, in progress

#641 [AutoPR consumption/resource-manager] typo: Microsoft.Consumption
  packages/@azure/arm-consumption/README.md
  packages/@azure/arm-consumption/lib/consumptionManagementClient.ts
  packages/@azure/arm-consumption/lib/consumptionManagementClientContext.ts
  packages/@azure/arm-consumption/lib/models/index.ts
  packages/@azure/arm-consumption/lib/models/mappers.ts
  packages/@azure/arm-consumption/lib/models/parameters.ts
  packages/@azure/arm-consumption/lib/operations/aggregatedCost.ts
  packages/@azure/arm-consumption/lib/operations/balances.ts
  packages/@azure/arm-consumption/lib/operations/budgets.ts
  packages/@azure/arm-consumption/lib/operations/charges.ts
  packages/@azure/arm-consumption/lib/operations/forecasts.ts
  packages/@azure/arm-consumption/lib/operations/marketplaces.ts
  packages/@azure/arm-consumption/lib/operations/operations.ts
  packages/@azure/arm-consumption/lib/operations/priceSheet.ts
  packages/@azure/arm-consumption/lib/operations/reservationRecommendations.ts
  packages/@azure/arm-consumption/lib/operations/reservationsDetails.ts
  packages/@azure/arm-consumption/lib/operations/reservationsSummaries.ts
  packages/@azure/arm-consumption/lib/operations/tags.ts
  packages/@azure/arm-consumption/lib/operations/usageDetails.ts
  packages/@azure/arm-consumption/package.json
  packages/@azure/arm-consumption/rollup.config.js
  packages/@azure/arm-consumption/tsconfig.json
Labels: RestPRMerged, in progress

#633 [AutoPR cognitiveservices/data-plane/EntitySearch] typo: cognitiveservices/data-plane/EntitySearch
  packages/@azure/cognitiveservices-entitysearch/README.md
  packages/@azure/cognitiveservices-entitysearch/lib/entitySearchAPIClient.ts
  packages/@azure/cognitiveservices-entitysearch/lib/entitySearchAPIClientContext.ts
  packages/@azure/cognitiveservices-entitysearch/lib/models/index.ts
  packages/@azure/cognitiveservices-entitysearch/lib/models/mappers.ts
  packages/@azure/cognitiveservices-entitysearch/lib/models/parameters.ts
  packages/@azure/cognitiveservices-entitysearch/lib/operations/entitiesOperations.ts
  packages/@azure/cognitiveservices-entitysearch/package.json
  packages/@azure/cognitiveservices-entitysearch/rollup.config.js
  packages/@azure/cognitiveservices-entitysearch/tsconfig.json
Labels: RestPRMerged, in progress

#620 [AutoPR billing/resource-manager] typo: Microsoft.Billing
  packages/@azure/arm-billing/lib/models/index.ts
Labels: RestPRMerged, in progress

#607 [AutoPR azurestack/resource-manager] typo: Microsoft.AzureStack
  packages/@azure/arm-azurestack/LICENSE.txt
  packages/@azure/arm-azurestack/README.md
  packages/@azure/arm-azurestack/lib/azureStackManagementClient.ts
  packages/@azure/arm-azurestack/lib/azureStackManagementClientContext.ts
  packages/@azure/arm-azurestack/lib/models/index.ts
  packages/@azure/arm-azurestack/lib/models/mappers.ts
  packages/@azure/arm-azurestack/lib/models/parameters.ts
  packages/@azure/arm-azurestack/lib/operations/customerSubscriptions.ts
  packages/@azure/arm-azurestack/lib/operations/operations.ts
  packages/@azure/arm-azurestack/lib/operations/products.ts
  packages/@azure/arm-azurestack/lib/operations/registrations.ts
  packages/@azure/arm-azurestack/package.json
  packages/@azure/arm-azurestack/rollup.config.js
  packages/@azure/arm-azurestack/tsconfig.json
Labels: RestPRMerged, in progress

#634 [AutoPR cognitiveservices/data-plane/ImageSearch] typo: cognitiveservices/data-plane/ImageSearch
  packages/@azure/cognitiveservices-imagesearch/README.md
  packages/@azure/cognitiveservices-imagesearch/lib/imageSearchAPIClient.ts
  packages/@azure/cognitiveservices-imagesearch/lib/imageSearchAPIClientContext.ts
  packages/@azure/cognitiveservices-imagesearch/lib/models/index.ts
  packages/@azure/cognitiveservices-imagesearch/lib/models/mappers.ts
  packages/@azure/cognitiveservices-imagesearch/lib/models/parameters.ts
  packages/@azure/cognitiveservices-imagesearch/lib/operations/imagesOperations.ts
  packages/@azure/cognitiveservices-imagesearch/package.json
  packages/@azure/cognitiveservices-imagesearch/rollup.config.js
  packages/@azure/cognitiveservices-imagesearch/tsconfig.json
Labels: RestPRMerged, in progress

#658 [AutoPR iothub/resource-manager] typo: iothub/Microsoft.Devices
  packages/@azure/arm-iothub/lib/models/index.ts
Labels: RestPRMerged, in progress

#668 [AutoPR migrate/resource-manager] typo: migrate/resource-manager/Microsoft.Migrate
  packages/@azure/arm-migrate/LICENSE.txt
  packages/@azure/arm-migrate/README.md
  packages/@azure/arm-migrate/lib/azureMigrate.ts
  packages/@azure/arm-migrate/lib/azureMigrateContext.ts
  packages/@azure/arm-migrate/lib/models/index.ts
  packages/@azure/arm-migrate/lib/models/mappers.ts
  packages/@azure/arm-migrate/lib/models/parameters.ts
  packages/@azure/arm-migrate/lib/operations/assessedMachines.ts
  packages/@azure/arm-migrate/lib/operations/assessmentOptions.ts
  packages/@azure/arm-migrate/lib/operations/assessments.ts
  packages/@azure/arm-migrate/lib/operations/groups.ts
  packages/@azure/arm-migrate/lib/operations/location.ts
  packages/@azure/arm-migrate/lib/operations/machines.ts
  packages/@azure/arm-migrate/lib/operations/operations.ts
  packages/@azure/arm-migrate/lib/operations/projects.ts
  packages/@azure/arm-migrate/package.json
  packages/@azure/arm-migrate/rollup.config.js
  packages/@azure/arm-migrate/tsconfig.json
Labels: RestPRMerged, in progress

#684 [AutoPR recoveryservices/resource-manager] typo: recoveryservices/resource-manager/Microsoft.RecoveryServices
  packages/@azure/arm-recoveryservices/LICENSE.txt
  packages/@azure/arm-recoveryservices/README.md
  packages/@azure/arm-recoveryservices/lib/models/index.ts
  packages/@azure/arm-recoveryservices/lib/models/mappers.ts
  packages/@azure/arm-recoveryservices/lib/models/parameters.ts
  packages/@azure/arm-recoveryservices/lib/operations/operations.ts
  packages/@azure/arm-recoveryservices/lib/operations/registeredIdentities.ts
  packages/@azure/arm-recoveryservices/lib/operations/replicationUsages.ts
  packages/@azure/arm-recoveryservices/lib/operations/usages.ts
  packages/@azure/arm-recoveryservices/lib/operations/vaultCertificates.ts
  packages/@azure/arm-recoveryservices/lib/operations/vaultExtendedInfoOperations.ts
  packages/@azure/arm-recoveryservices/lib/operations/vaults.ts
  packages/@azure/arm-recoveryservices/lib/recoveryServicesClient.ts
  packages/@azure/arm-recoveryservices/lib/recoveryServicesClientContext.ts
  packages/@azure/arm-recoveryservices/package.json
  packages/@azure/arm-recoveryservices/rollup.config.js
  packages/@azure/arm-recoveryservices/tsconfig.json
Labels: RestPRMerged, in progress

#652 [AutoPR dns/resource-manager] typo: dns/Microsoft.Network
  packages/@azure/arm-dns/LICENSE.txt
  packages/@azure/arm-dns/README.md
  packages/@azure/arm-dns/lib/dnsManagementClient.ts
  packages/@azure/arm-dns/lib/dnsManagementClientContext.ts
  packages/@azure/arm-dns/lib/models/index.ts
  packages/@azure/arm-dns/lib/models/mappers.ts
  packages/@azure/arm-dns/lib/models/parameters.ts
  packages/@azure/arm-dns/lib/operations/dnsResourceReferenceOperations.ts
  packages/@azure/arm-dns/lib/operations/recordSets.ts
  packages/@azure/arm-dns/lib/operations/zones.ts
  packages/@azure/arm-dns/package.json
  packages/@azure/arm-dns/rollup.config.js
  packages/@azure/arm-dns/tsconfig.json
Labels: RestPRMerged, in progress

#685 [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices
  packages/@azure/arm-recoveryservicesbackup/LICENSE.txt
  packages/@azure/arm-recoveryservicesbackup/README.md
  packages/@azure/arm-recoveryservicesbackup/lib/models/index.ts
  packages/@azure/arm-recoveryservicesbackup/lib/models/mappers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/models/parameters.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupEngines.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupJobs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupPolicies.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectableItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectedItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectionContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectionIntent.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupResourceStorageConfigs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupResourceVaultConfigs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupStatus.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupUsageSummaries.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupWorkloadItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backups.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/exportJobsOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/featureSupport.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/itemLevelRecoveryConnections.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobCancellations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobDetails.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/operation.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/operations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectableContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItemOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItemOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainerOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainerRefreshOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionIntentOperations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicies.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicyOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicyOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/recoveryPoints.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/restores.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/securityPINs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/recoveryServicesBackupClient.ts
  packages/@azure/arm-recoveryservicesbackup/lib/recoveryServicesBackupClientContext.ts
  packages/@azure/arm-recoveryservicesbackup/package.json
  packages/@azure/arm-recoveryservicesbackup/rollup.config.js
  packages/@azure/arm-recoveryservicesbackup/tsconfig.json
Labels: RestPRMerged, in progress

#679 [AutoPR operationsmanagement/resource-manager] typo: operationsmanagement/resource-manager/Microsoft.OperationsManagement
  packages/@azure/arm-operations/LICENSE.txt
  packages/@azure/arm-operations/README.md
  packages/@azure/arm-operations/lib/models/index.ts
  packages/@azure/arm-operations/lib/models/mappers.ts
  packages/@azure/arm-operations/lib/models/parameters.ts
  packages/@azure/arm-operations/lib/operations/managementAssociations.ts
  packages/@azure/arm-operations/lib/operations/managementConfigurations.ts
  packages/@azure/arm-operations/lib/operations/operations.ts
  packages/@azure/arm-operations/lib/operations/solutions.ts
  packages/@azure/arm-operations/lib/operationsManagementClient.ts
  packages/@azure/arm-operations/lib/operationsManagementClientContext.ts
  packages/@azure/arm-operations/package.json
  packages/@azure/arm-operations/rollup.config.js
  packages/@azure/arm-operations/tsconfig.json
Labels: RestPRMerged, in progress

#703 [AutoPR applicationinsights/data-plane] fix: Rename applicationinsights/data-plane/Microsoft.Insights
  packages/@azure/applicationinsights-query/README.md
  packages/@azure/applicationinsights-query/lib/applicationInsightsDataClient.ts
  packages/@azure/applicationinsights-query/lib/applicationInsightsDataClientContext.ts
  packages/@azure/applicationinsights-query/lib/models/index.ts
  packages/@azure/applicationinsights-query/lib/models/mappers.ts
  packages/@azure/applicationinsights-query/lib/models/parameters.ts
  packages/@azure/applicationinsights-query/lib/operations/events.ts
  packages/@azure/applicationinsights-query/lib/operations/metrics.ts
  packages/@azure/applicationinsights-query/lib/operations/query.ts
  packages/@azure/applicationinsights-query/package.json
  packages/@azure/applicationinsights-query/rollup.config.js
  packages/@azure/applicationinsights-query/tsconfig.json
Labels: RestPRMerged, in progress

#612 [AutoPR labservices/resource-manager] Add first GA LabServices API
  packages/@azure/arm-LabServices/LICENSE.txt
  packages/@azure/arm-LabServices/README.md
  packages/@azure/arm-LabServices/lib/managedLabsClient.ts
  packages/@azure/arm-LabServices/lib/managedLabsClientContext.ts
  packages/@azure/arm-LabServices/lib/models/environmentSettingsMappers.ts
  packages/@azure/arm-LabServices/lib/models/environmentsMappers.ts
  packages/@azure/arm-LabServices/lib/models/galleryImagesMappers.ts
  packages/@azure/arm-LabServices/lib/models/globalUsersMappers.ts
  packages/@azure/arm-LabServices/lib/models/index.ts
  packages/@azure/arm-LabServices/lib/models/labAccountsMappers.ts
  packages/@azure/arm-LabServices/lib/models/labsMappers.ts
  packages/@azure/arm-LabServices/lib/models/mappers.ts
  packages/@azure/arm-LabServices/lib/models/operationsMappers.ts
  packages/@azure/arm-LabServices/lib/models/parameters.ts
  packages/@azure/arm-LabServices/lib/models/providerOperationsMappers.ts
  packages/@azure/arm-LabServices/lib/models/usersMappers.ts
  packages/@azure/arm-LabServices/lib/operations/environmentSettings.ts
  packages/@azure/arm-LabServices/lib/operations/environments.ts
  packages/@azure/arm-LabServices/lib/operations/galleryImages.ts
  packages/@azure/arm-LabServices/lib/operations/globalUsers.ts
  packages/@azure/arm-LabServices/lib/operations/index.ts
  packages/@azure/arm-LabServices/lib/operations/labAccounts.ts
  packages/@azure/arm-LabServices/lib/operations/labs.ts
  packages/@azure/arm-LabServices/lib/operations/operations.ts
  packages/@azure/arm-LabServices/lib/operations/providerOperations.ts
  packages/@azure/arm-LabServices/lib/operations/users.ts
  packages/@azure/arm-LabServices/package.json
  packages/@azure/arm-LabServices/rollup.config.js
  packages/@azure/arm-LabServices/tsconfig.json
  packages/@azure/arm-labservices/LICENSE.txt
  packages/@azure/arm-labservices/README.md
  packages/@azure/arm-labservices/lib/managedLabsClient.ts
  packages/@azure/arm-labservices/lib/managedLabsClientContext.ts
  packages/@azure/arm-labservices/lib/models/environmentSettingsMappers.ts
  packages/@azure/arm-labservices/lib/models/environmentsMappers.ts
  packages/@azure/arm-labservices/lib/models/galleryImagesMappers.ts
  packages/@azure/arm-labservices/lib/models/globalUsersMappers.ts
  packages/@azure/arm-labservices/lib/models/index.ts
  packages/@azure/arm-labservices/lib/models/labAccountsMappers.ts
  packages/@azure/arm-labservices/lib/models/labsMappers.ts
  packages/@azure/arm-labservices/lib/models/mappers.ts
  packages/@azure/arm-labservices/lib/models/operationsMappers.ts
  packages/@azure/arm-labservices/lib/models/parameters.ts
  packages/@azure/arm-labservices/lib/models/providerOperationsMappers.ts
  packages/@azure/arm-labservices/lib/models/usersMappers.ts
  packages/@azure/arm-labservices/lib/operations/environmentSettings.ts
  packages/@azure/arm-labservices/lib/operations/environments.ts
  packages/@azure/arm-labservices/lib/operations/galleryImages.ts
  packages/@azure/arm-labservices/lib/operations/globalUsers.ts
  packages/@azure/arm-labservices/lib/operations/index.ts
  packages/@azure/arm-labservices/lib/operations/labAccounts.ts
  packages/@azure/arm-labservices/lib/operations/labs.ts
  packages/@azure/arm-labservices/lib/operations/operations.ts
  packages/@azure/arm-labservices/lib/operations/providerOperations.ts
  packages/@azure/arm-labservices/lib/operations/users.ts
  packages/@azure/arm-labservices/package.json
  packages/@azure/arm-labservices/rollup.config.js
  packages/@azure/arm-labservices/tsconfig.json
Labels: RestPRMerged, in progress

#638 [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices
  packages/@azure/arm-cognitiveservices/LICENSE.txt
  packages/@azure/arm-cognitiveservices/README.md
  packages/@azure/arm-cognitiveservices/lib/cognitiveServicesManagementClient.ts
  packages/@azure/arm-cognitiveservices/lib/cognitiveServicesManagementClientContext.ts
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/models/mappers.ts
  packages/@azure/arm-cognitiveservices/lib/models/parameters.ts
  packages/@azure/arm-cognitiveservices/lib/operations/accounts.ts
  packages/@azure/arm-cognitiveservices/lib/operations/checkSkuAvailability.ts
  packages/@azure/arm-cognitiveservices/lib/operations/operations.ts
  packages/@azure/arm-cognitiveservices/lib/operations/resourceSkus.ts
  packages/@azure/arm-cognitiveservices/package.json
  packages/@azure/arm-cognitiveservices/rollup.config.js
  packages/@azure/arm-cognitiveservices/tsconfig.json
Labels: RestPRMerged, in progress

#676 [AutoPR notificationhubs/resource-manager] typo: notificationhubs/resource-manager/Microsoft.NotificationHubs
  packages/@azure/arm-notificationhubs/LICENSE.txt
  packages/@azure/arm-notificationhubs/README.md
  packages/@azure/arm-notificationhubs/lib/models/index.ts
  packages/@azure/arm-notificationhubs/lib/models/mappers.ts
  packages/@azure/arm-notificationhubs/lib/models/parameters.ts
  packages/@azure/arm-notificationhubs/lib/notificationHubsManagementClient.ts
  packages/@azure/arm-notificationhubs/lib/notificationHubsManagementClientContext.ts
  packages/@azure/arm-notificationhubs/lib/operations/namespaces.ts
  packages/@azure/arm-notificationhubs/lib/operations/notificationHubs.ts
  packages/@azure/arm-notificationhubs/lib/operations/operations.ts
  packages/@azure/arm-notificationhubs/package.json
  packages/@azure/arm-notificationhubs/rollup.config.js
  packages/@azure/arm-notificationhubs/tsconfig.json
Labels: RestPRMerged, in progress

#662 [AutoPR machinelearningservices/resource-manager] typo: machinelearningservices/resource-manager/Microsoft.MachineLearningServices
  packages/@azure/arm-machinelearningservices/.npmignore
  packages/@azure/arm-machinelearningservices/LICENSE.txt
  packages/@azure/arm-machinelearningservices/README.md
  packages/@azure/arm-machinelearningservices/lib/models/index.ts
  packages/@azure/arm-machinelearningservices/package.json
Labels: RestPRMerged, in progress

#636 [AutoPR cognitiveservices/data-plane/NewsSearch] typo: cognitiveservices/data-plane/NewsSearch
  packages/@azure/cognitiveservices-newssearch/README.md
  packages/@azure/cognitiveservices-newssearch/lib/models/index.ts
  packages/@azure/cognitiveservices-newssearch/lib/models/mappers.ts
  packages/@azure/cognitiveservices-newssearch/lib/models/parameters.ts
  packages/@azure/cognitiveservices-newssearch/lib/newsSearchAPIClient.ts
  packages/@azure/cognitiveservices-newssearch/lib/newsSearchAPIClientContext.ts
  packages/@azure/cognitiveservices-newssearch/lib/operations/newsOperations.ts
  packages/@azure/cognitiveservices-newssearch/package.json
  packages/@azure/cognitiveservices-newssearch/rollup.config.js
  packages/@azure/cognitiveservices-newssearch/tsconfig.json
Labels: RestPRMerged, in progress

#719 [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources
  packages/@azure/arm-links/lib/models/index.ts
  packages/@azure/arm-resources/lib/models/index.ts
Labels: RestPRMerged, in progress

#711 Add ignore-version to gulp pack
  gulpfile.ts
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#670 [AutoPR mysql/resource-manager] typo: mysql/resource-manager/Microsoft.DBforMySQL
  packages/@azure/arm-mysql/LICENSE.txt
  packages/@azure/arm-mysql/README.md
  packages/@azure/arm-mysql/lib/models/index.ts
  packages/@azure/arm-mysql/lib/models/mappers.ts
  packages/@azure/arm-mysql/lib/models/parameters.ts
  packages/@azure/arm-mysql/lib/mySQLManagementClient.ts
  packages/@azure/arm-mysql/lib/mySQLManagementClientContext.ts
  packages/@azure/arm-mysql/lib/operations/checkNameAvailability.ts
  packages/@azure/arm-mysql/lib/operations/configurations.ts
  packages/@azure/arm-mysql/lib/operations/databases.ts
  packages/@azure/arm-mysql/lib/operations/firewallRules.ts
  packages/@azure/arm-mysql/lib/operations/locationBasedPerformanceTier.ts
  packages/@azure/arm-mysql/lib/operations/logFiles.ts
  packages/@azure/arm-mysql/lib/operations/operations.ts
  packages/@azure/arm-mysql/lib/operations/replicas.ts
  packages/@azure/arm-mysql/lib/operations/serverSecurityAlertPolicies.ts
  packages/@azure/arm-mysql/lib/operations/servers.ts
  packages/@azure/arm-mysql/lib/operations/virtualNetworkRules.ts
  packages/@azure/arm-mysql/package.json
  packages/@azure/arm-mysql/rollup.config.js
  packages/@azure/arm-mysql/tsconfig.json
Labels: RestPRMerged

#681 [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL
  packages/@azure/arm-postgresql/LICENSE.txt
  packages/@azure/arm-postgresql/README.md
  packages/@azure/arm-postgresql/lib/models/index.ts
  packages/@azure/arm-postgresql/lib/models/mappers.ts
  packages/@azure/arm-postgresql/lib/models/parameters.ts
  packages/@azure/arm-postgresql/lib/operations/checkNameAvailability.ts
  packages/@azure/arm-postgresql/lib/operations/configurations.ts
  packages/@azure/arm-postgresql/lib/operations/databases.ts
  packages/@azure/arm-postgresql/lib/operations/firewallRules.ts
  packages/@azure/arm-postgresql/lib/operations/locationBasedPerformanceTier.ts
  packages/@azure/arm-postgresql/lib/operations/logFiles.ts
  packages/@azure/arm-postgresql/lib/operations/operations.ts
  packages/@azure/arm-postgresql/lib/operations/serverSecurityAlertPolicies.ts
  packages/@azure/arm-postgresql/lib/operations/servers.ts
  packages/@azure/arm-postgresql/lib/operations/virtualNetworkRules.ts
  packages/@azure/arm-postgresql/lib/postgreSQLManagementClient.ts
  packages/@azure/arm-postgresql/lib/postgreSQLManagementClientContext.ts
  packages/@azure/arm-postgresql/package.json
  packages/@azure/arm-postgresql/rollup.config.js
  packages/@azure/arm-postgresql/tsconfig.json
Labels: RestPRMerged, in progress

#664 [AutoPR managementgroups/resource-manager] typo: managementgroups/resource-manager/Microsoft.Management
  packages/@azure/arm-managementgroups/LICENSE.txt
  packages/@azure/arm-managementgroups/README.md
  packages/@azure/arm-managementgroups/lib/managementGroupsAPI.ts
  packages/@azure/arm-managementgroups/lib/managementGroupsAPIContext.ts
  packages/@azure/arm-managementgroups/lib/models/index.ts
  packages/@azure/arm-managementgroups/lib/models/mappers.ts
  packages/@azure/arm-managementgroups/lib/models/parameters.ts
  packages/@azure/arm-managementgroups/lib/operations/entities.ts
  packages/@azure/arm-managementgroups/lib/operations/managementGroupSubscriptions.ts
  packages/@azure/arm-managementgroups/lib/operations/managementGroups.ts
  packages/@azure/arm-managementgroups/lib/operations/operations.ts
  packages/@azure/arm-managementgroups/package.json
  packages/@azure/arm-managementgroups/rollup.config.js
  packages/@azure/arm-managementgroups/tsconfig.json
Labels: RestPRMerged, in progress

#657 [AutoPR hanaonazure/resource-manager] typo: Microsoft.HanaOnAzure
  packages/@azure/arm-hanaonazure/LICENSE.txt
  packages/@azure/arm-hanaonazure/README.md
  packages/@azure/arm-hanaonazure/lib/hanaManagementClient.ts
  packages/@azure/arm-hanaonazure/lib/hanaManagementClientContext.ts
  packages/@azure/arm-hanaonazure/lib/models/index.ts
  packages/@azure/arm-hanaonazure/lib/models/mappers.ts
  packages/@azure/arm-hanaonazure/lib/models/parameters.ts
  packages/@azure/arm-hanaonazure/lib/operations/hanaInstances.ts
  packages/@azure/arm-hanaonazure/lib/operations/operations.ts
  packages/@azure/arm-hanaonazure/package.json
  packages/@azure/arm-hanaonazure/rollup.config.js
  packages/@azure/arm-hanaonazure/tsconfig.json
Labels: RestPRMerged, in progress

#714 [AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices
  packages/@azure/arm-recoveryservices-siterecovery/lib/models/index.ts
  packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationJobs.ts
  packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationStorageClassificationMappings.ts
  packages/@azure/arm-recoveryservices-siterecovery/lib/operations/replicationvCenters.ts
Labels: RestPRMerged, in progress

#655 [AutoPR frontdoor/resource-manager] typo: frontdoor/Microsoft.Network
  packages/@azure/arm-frontdoor/LICENSE.txt
  packages/@azure/arm-frontdoor/README.md
  packages/@azure/arm-frontdoor/lib/frontDoorManagementClient.ts
  packages/@azure/arm-frontdoor/lib/frontDoorManagementClientContext.ts
  packages/@azure/arm-frontdoor/lib/models/index.ts
  packages/@azure/arm-frontdoor/lib/models/mappers.ts
  packages/@azure/arm-frontdoor/lib/models/parameters.ts
  packages/@azure/arm-frontdoor/lib/operations/backendPools.ts
  packages/@azure/arm-frontdoor/lib/operations/endpoints.ts
  packages/@azure/arm-frontdoor/lib/operations/frontDoors.ts
  packages/@azure/arm-frontdoor/lib/operations/frontendEndpoints.ts
  packages/@azure/arm-frontdoor/lib/operations/healthProbeSettings.ts
  packages/@azure/arm-frontdoor/lib/operations/loadBalancingSettings.ts
  packages/@azure/arm-frontdoor/lib/operations/policies.ts
  packages/@azure/arm-frontdoor/lib/operations/routingRules.ts
  packages/@azure/arm-frontdoor/package.json
  packages/@azure/arm-frontdoor/rollup.config.js
  packages/@azure/arm-frontdoor/tsconfig.json
Labels: RestPRMerged, in progress

#650 [AutoPR deviceprovisioningservices/resource-manager] typo: Microsoft.Devices
  packages/@azure/arm-deviceprovisioningservices/README.md
  packages/@azure/arm-deviceprovisioningservices/lib/iotDpsClient.ts
  packages/@azure/arm-deviceprovisioningservices/lib/iotDpsClientContext.ts
  packages/@azure/arm-deviceprovisioningservices/lib/models/index.ts
  packages/@azure/arm-deviceprovisioningservices/lib/models/mappers.ts
  packages/@azure/arm-deviceprovisioningservices/lib/models/parameters.ts
  packages/@azure/arm-deviceprovisioningservices/lib/operations/dpsCertificate.ts
  packages/@azure/arm-deviceprovisioningservices/lib/operations/iotDpsResource.ts
  packages/@azure/arm-deviceprovisioningservices/lib/operations/operations.ts
  packages/@azure/arm-deviceprovisioningservices/package.json
  packages/@azure/arm-deviceprovisioningservices/rollup.config.js
  packages/@azure/arm-deviceprovisioningservices/tsconfig.json
Labels: RestPRMerged, in progress

#730 Regenerate @azure/arm-network
  packages/@azure/arm-network/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#734 Generate @azure/arm-sqlvirtualmachine
  packages/@azure/arm-sqlvirtualmachine/LICENSE.txt
  packages/@azure/arm-sqlvirtualmachine/README.md
  packages/@azure/arm-sqlvirtualmachine/lib/models/availabilityGroupListenersMappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/index.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/mappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/operationsMappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/parameters.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/sqlVirtualMachineGroupsMappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/sqlVirtualMachinesMappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/operations/availabilityGroupListeners.ts
  packages/@azure/arm-sqlvirtualmachine/lib/operations/index.ts
  packages/@azure/arm-sqlvirtualmachine/lib/operations/operations.ts
  packages/@azure/arm-sqlvirtualmachine/lib/operations/sqlVirtualMachineGroups.ts
  packages/@azure/arm-sqlvirtualmachine/lib/operations/sqlVirtualMachines.ts
  packages/@azure/arm-sqlvirtualmachine/lib/sqlVirtualMachineManagementClient.ts
  packages/@azure/arm-sqlvirtualmachine/lib/sqlVirtualMachineManagementClientContext.ts
  packages/@azure/arm-sqlvirtualmachine/package.json
  packages/@azure/arm-sqlvirtualmachine/rollup.config.js
  packages/@azure/arm-sqlvirtualmachine/tsconfig.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#592 [AutoPR servicefabric/data-plane] Swagger specification for Service Fabric runtime version 6.4
  packages/@azure/servicefabric/lib/models/index.ts
  packages/@azure/servicefabric/lib/models/mappers.ts
  packages/@azure/servicefabric/lib/models/meshApplicationMappers.ts
  packages/@azure/servicefabric/lib/models/meshCodePackageMappers.ts
  packages/@azure/servicefabric/lib/models/meshGatewayMappers.ts
  packages/@azure/servicefabric/lib/models/meshNetworkMappers.ts
  packages/@azure/servicefabric/lib/models/meshSecretMappers.ts
  packages/@azure/servicefabric/lib/models/meshSecretValueMappers.ts
  packages/@azure/servicefabric/lib/models/meshServiceMappers.ts
  packages/@azure/servicefabric/lib/models/meshServiceReplicaMappers.ts
  packages/@azure/servicefabric/lib/models/meshVolumeMappers.ts
  packages/@azure/servicefabric/lib/models/parameters.ts
  packages/@azure/servicefabric/lib/operations/index.ts
  packages/@azure/servicefabric/lib/operations/meshApplication.ts
  packages/@azure/servicefabric/lib/operations/meshCodePackage.ts
  packages/@azure/servicefabric/lib/operations/meshGateway.ts
  packages/@azure/servicefabric/lib/operations/meshNetwork.ts
  packages/@azure/servicefabric/lib/operations/meshSecret.ts
  packages/@azure/servicefabric/lib/operations/meshSecretValue.ts
  packages/@azure/servicefabric/lib/operations/meshService.ts
  packages/@azure/servicefabric/lib/operations/meshServiceReplica.ts
  packages/@azure/servicefabric/lib/operations/meshVolume.ts
  packages/@azure/servicefabric/lib/serviceFabricClient.ts
Labels: RestPRMerged, in progress

#747 [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService
  packages/@azure/arm-signalr/LICENSE.txt
  packages/@azure/arm-signalr/README.md
  packages/@azure/arm-signalr/lib/models/index.ts
  packages/@azure/arm-signalr/lib/models/mappers.ts
  packages/@azure/arm-signalr/lib/models/parameters.ts
  packages/@azure/arm-signalr/lib/operations/operations.ts
  packages/@azure/arm-signalr/lib/operations/signalR.ts
  packages/@azure/arm-signalr/lib/operations/usages.ts
  packages/@azure/arm-signalr/lib/signalRManagementClient.ts
  packages/@azure/arm-signalr/lib/signalRManagementClientContext.ts
  packages/@azure/arm-signalr/package.json
  packages/@azure/arm-signalr/rollup.config.js
  packages/@azure/arm-signalr/tsconfig.json
Labels: RestPRMerged, in progress

#741 Regenerate @azure/cognitiveservices-customvision-prediction
  packages/@azure/cognitiveservices-customvision-prediction/README.md
  packages/@azure/cognitiveservices-customvision-prediction/package.json
  packages/@azure/cognitiveservices-customvision-prediction/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#740 Regenerate @azure/cognitiveservices-customvision-training
  packages/@azure/cognitiveservices-customvision-training/README.md
  packages/@azure/cognitiveservices-customvision-training/package.json
  packages/@azure/cognitiveservices-customvision-training/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#739 Update generator version to 2.1.1
  swagger_to_sdk_config.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#736 Regenerate @azure/arm-containerregistry
  packages/@azure/arm-containerregistry/README.md
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/lib/models/parameters.ts
  packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
  packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
  packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
  packages/@azure/arm-containerregistry/package.json
  packages/@azure/arm-containerregistry/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#737 Generate @azure/cognitiveservices-qnamaker
  packages/@azure/cognitiveservices-qnamaker/LICENSE.txt
  packages/@azure/cognitiveservices-qnamaker/README.md
  packages/@azure/cognitiveservices-qnamaker/lib/models/alterationsMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/endpointKeysMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/index.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/knowledgebaseMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/mappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/operationsMappers.ts
  packages/@azure/cognitiveservices-qnamaker/lib/models/parameters.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/alterations.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/endpointKeys.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/index.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/knowledgebase.ts
  packages/@azure/cognitiveservices-qnamaker/lib/operations/operations.ts
  packages/@azure/cognitiveservices-qnamaker/lib/qnAMakerClient.ts
  packages/@azure/cognitiveservices-qnamaker/lib/qnAMakerClientContext.ts
  packages/@azure/cognitiveservices-qnamaker/package.json
  packages/@azure/cognitiveservices-qnamaker/rollup.config.js
  packages/@azure/cognitiveservices-qnamaker/tsconfig.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#749 [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync
  packages/@azure/arm-storagesync/lib/operations/serverEndpoints.ts
Labels: RestPRMerged, in progress

#722 [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security
  packages/@azure/arm-security/lib/models/index.ts
  packages/@azure/arm-security/lib/operations/alerts.ts
Labels: RestPRMerged, in progress

#735 [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96
  packages/@azure/arm-hanaonazure/lib/models/index.ts
Labels: RestPRMerged, in progress

#723 [AutoPR service-map/resource-manager] typo: service-map/resource-manager/Microsoft.OperationalInsights
  packages/@azure/arm-servicemap/README.md
  packages/@azure/arm-servicemap/lib/models/index.ts
  packages/@azure/arm-servicemap/lib/models/mappers.ts
  packages/@azure/arm-servicemap/lib/models/parameters.ts
  packages/@azure/arm-servicemap/lib/operations/clientGroups.ts
  packages/@azure/arm-servicemap/lib/operations/machineGroups.ts
  packages/@azure/arm-servicemap/lib/operations/machines.ts
  packages/@azure/arm-servicemap/lib/operations/maps.ts
  packages/@azure/arm-servicemap/lib/operations/ports.ts
  packages/@azure/arm-servicemap/lib/operations/processes.ts
  packages/@azure/arm-servicemap/lib/operations/summaries.ts
  packages/@azure/arm-servicemap/lib/servicemapManagementClient.ts
  packages/@azure/arm-servicemap/lib/servicemapManagementClientContext.ts
  packages/@azure/arm-servicemap/package.json
  packages/@azure/arm-servicemap/rollup.config.js
  packages/@azure/arm-servicemap/tsconfig.json
Labels: RestPRMerged, in progress

#702 [AutoPR applicationinsights/resource-manager] chore: Rename microsoft.insights to Microsoft.Insights
  packages/@azure/arm-appinsights/lib/models/index.ts
  packages/@azure/arm-appinsights/lib/operations/webTests.ts
  packages/@azure/arm-appinsights/lib/operations/workItemConfigurations.ts
Labels: RestPRMerged, in progress

#744 [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh
  packages/@azure/arm-servicefabricmesh/lib/models/index.ts
  packages/@azure/arm-servicefabricmesh/lib/operations/secretValueOperations.ts
Labels: RestPRMerged, in progress

#616 [AutoPR servicebus/resource-manager] added new API for NetworkRuleSet
  packages/@azure/arm-servicebus/README.md
  packages/@azure/arm-servicebus/lib/models/index.ts
  packages/@azure/arm-servicebus/lib/models/mappers.ts
  packages/@azure/arm-servicebus/lib/models/parameters.ts
  packages/@azure/arm-servicebus/lib/operations/disasterRecoveryConfigs.ts
  packages/@azure/arm-servicebus/lib/operations/eventHubs.ts
  packages/@azure/arm-servicebus/lib/operations/migrationConfigs.ts
  packages/@azure/arm-servicebus/lib/operations/namespaces.ts
  packages/@azure/arm-servicebus/lib/operations/operations.ts
  packages/@azure/arm-servicebus/lib/operations/premiumMessagingRegionsOperations.ts
  packages/@azure/arm-servicebus/lib/operations/queues.ts
  packages/@azure/arm-servicebus/lib/operations/regions.ts
  packages/@azure/arm-servicebus/lib/operations/rules.ts
  packages/@azure/arm-servicebus/lib/operations/subscriptions.ts
  packages/@azure/arm-servicebus/lib/operations/topics.ts
  packages/@azure/arm-servicebus/lib/serviceBusManagementClient.ts
  packages/@azure/arm-servicebus/lib/serviceBusManagementClientContext.ts
  packages/@azure/arm-servicebus/package.json
  packages/@azure/arm-servicebus/rollup.config.js
  packages/@azure/arm-servicebus/tsconfig.json
Labels: RestPRMerged, in progress

#713 [AutoPR datafactory/resource-manager] Refactor delete activity payload
  packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
  packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
  packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
  packages/@azure/arm-datafactory/lib/models/triggersMappers.ts
Labels: RestPRMerged, in progress

#760 [AutoPR timeseriesinsights/resource-manager] typo: timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights
  packages/@azure/arm-timeseriesinsights/lib/models/index.ts
Labels: RestPRMerged, in progress

#762 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.CertificateRegistration
  packages/@azure/arm-appservice/lib/models/index.ts
Labels: RestPRMerged, in progress

#755 [AutoPR labservices/resource-manager] [LabServices] Fix typo, remove required from optional param
  packages/@azure/arm-labservices/lib/models/globalUsersMappers.ts
  packages/@azure/arm-labservices/lib/models/index.ts
  packages/@azure/arm-labservices/lib/models/mappers.ts
  packages/@azure/arm-labservices/lib/operations/globalUsers.ts
Labels: RestPRMerged, in progress

#768 Regenerate @azure/arm-logic
  packages/@azure/arm-logic/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#769 Regenerate @azure/cognitiveservices-autosuggest
  packages/@azure/cognitiveservices-autosuggest/README.md
  packages/@azure/cognitiveservices-autosuggest/lib/autoSuggestClient.ts
  packages/@azure/cognitiveservices-autosuggest/package.json
  packages/@azure/cognitiveservices-autosuggest/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#770 Regenerate @azure/cognitiveservices-customimagesearch
  packages/@azure/cognitiveservices-customimagesearch/README.md
  packages/@azure/cognitiveservices-customimagesearch/lib/customImageSearchClient.ts
  packages/@azure/cognitiveservices-customimagesearch/lib/customImageSearchClientContext.ts
  packages/@azure/cognitiveservices-customimagesearch/lib/models/index.ts
  packages/@azure/cognitiveservices-customimagesearch/lib/operations/customInstance.ts
  packages/@azure/cognitiveservices-customimagesearch/package.json
  packages/@azure/cognitiveservices-customimagesearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#774 Add NPM package check before packing back to 'gulp pack'
  gulpfile.ts
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#773 Regenerate @azure/cognitiveservices-imagesearch
  packages/@azure/cognitiveservices-imagesearch/README.md
  packages/@azure/cognitiveservices-imagesearch/lib/imageSearchClient.ts
  packages/@azure/cognitiveservices-imagesearch/lib/imageSearchClientContext.ts
  packages/@azure/cognitiveservices-imagesearch/lib/models/index.ts
  packages/@azure/cognitiveservices-imagesearch/lib/operations/imagesOperations.ts
  packages/@azure/cognitiveservices-imagesearch/package.json
  packages/@azure/cognitiveservices-imagesearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#772 Regenerate @azure/cognitiveservices-entitysearch
  packages/@azure/cognitiveservices-entitysearch/README.md
  packages/@azure/cognitiveservices-entitysearch/lib/entitySearchClient.ts
  packages/@azure/cognitiveservices-entitysearch/lib/entitySearchClientContext.ts
  packages/@azure/cognitiveservices-entitysearch/lib/models/index.ts
  packages/@azure/cognitiveservices-entitysearch/lib/operations/entitiesOperations.ts
  packages/@azure/cognitiveservices-entitysearch/package.json
  packages/@azure/cognitiveservices-entitysearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#771 Regenerate @azure/cognitiveservices-customsearch
  packages/@azure/cognitiveservices-customsearch/README.md
  packages/@azure/cognitiveservices-customsearch/lib/customSearchClient.ts
  packages/@azure/cognitiveservices-customsearch/lib/customSearchClientContext.ts
  packages/@azure/cognitiveservices-customsearch/lib/models/index.ts
  packages/@azure/cognitiveservices-customsearch/lib/operations/customInstance.ts
  packages/@azure/cognitiveservices-customsearch/package.json
  packages/@azure/cognitiveservices-customsearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#775 Regenerate @azure/cognitiveservices-newssearch
  packages/@azure/cognitiveservices-newssearch/README.md
  packages/@azure/cognitiveservices-newssearch/lib/models/index.ts
  packages/@azure/cognitiveservices-newssearch/lib/newsSearchClient.ts
  packages/@azure/cognitiveservices-newssearch/lib/newsSearchClientContext.ts
  packages/@azure/cognitiveservices-newssearch/lib/operations/newsOperations.ts
  packages/@azure/cognitiveservices-newssearch/package.json
  packages/@azure/cognitiveservices-newssearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#776 Regenerate @azure/cognitiveservices-spellcheck
  packages/@azure/cognitiveservices-spellcheck/README.md
  packages/@azure/cognitiveservices-spellcheck/lib/models/index.ts
  packages/@azure/cognitiveservices-spellcheck/lib/spellCheckClient.ts
  packages/@azure/cognitiveservices-spellcheck/lib/spellCheckClientContext.ts
  packages/@azure/cognitiveservices-spellcheck/package.json
  packages/@azure/cognitiveservices-spellcheck/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#777 Regenerate @azure/cognitiveservices-videosearch
  packages/@azure/cognitiveservices-videosearch/README.md
  packages/@azure/cognitiveservices-videosearch/lib/models/index.ts
  packages/@azure/cognitiveservices-videosearch/lib/operations/videosOperations.ts
  packages/@azure/cognitiveservices-videosearch/lib/videoSearchClient.ts
  packages/@azure/cognitiveservices-videosearch/lib/videoSearchClientContext.ts
  packages/@azure/cognitiveservices-videosearch/package.json
  packages/@azure/cognitiveservices-videosearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#778 Regenerate @azure/cognitiveservices-websearch
  packages/@azure/cognitiveservices-websearch/README.md
  packages/@azure/cognitiveservices-websearch/lib/models/index.ts
  packages/@azure/cognitiveservices-websearch/lib/operations/web.ts
  packages/@azure/cognitiveservices-websearch/lib/webSearchClient.ts
  packages/@azure/cognitiveservices-websearch/lib/webSearchClientContext.ts
  packages/@azure/cognitiveservices-websearch/package.json
  packages/@azure/cognitiveservices-websearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#780 Update @azure/cognitiveservices-autosuggest to 1.0.1
  packages/@azure/cognitiveservices-autosuggest/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#782 Update @azure/cognitiveservices-customsearch to 1.0.1
  packages/@azure/cognitiveservices-customsearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#781 Update @azure/cognitiveservices-customimagesearch to 1.0.1
  packages/@azure/cognitiveservices-customimagesearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#729 [AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API
  packages/@azure/arm-logic/lib/models/index.ts
  packages/@azure/arm-logic/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#783 Regenerate @azure/cognitiveservices-visualsearch
  packages/@azure/cognitiveservices-visualsearch/README.md
  packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts
  packages/@azure/cognitiveservices-visualsearch/lib/operations/images.ts
  packages/@azure/cognitiveservices-visualsearch/lib/visualSearchClient.ts
  packages/@azure/cognitiveservices-visualsearch/lib/visualSearchClientContext.ts
  packages/@azure/cognitiveservices-visualsearch/package.json
  packages/@azure/cognitiveservices-visualsearch/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#784 Update @azure/cognitiveservices-customsearch to 2.0.0
  packages/@azure/cognitiveservices-customsearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#785 Regenerate @azure/servicefabric
  packages/@azure/servicefabric/README.md
  packages/@azure/servicefabric/lib/models/index.ts
  packages/@azure/servicefabric/lib/models/mappers.ts
  packages/@azure/servicefabric/lib/models/meshApplicationMappers.ts
  packages/@azure/servicefabric/lib/models/meshCodePackageMappers.ts
  packages/@azure/servicefabric/lib/models/meshGatewayMappers.ts
  packages/@azure/servicefabric/lib/models/meshNetworkMappers.ts
  packages/@azure/servicefabric/lib/models/meshSecretMappers.ts
  packages/@azure/servicefabric/lib/models/meshSecretValueMappers.ts
  packages/@azure/servicefabric/lib/models/meshServiceMappers.ts
  packages/@azure/servicefabric/lib/models/meshServiceReplicaMappers.ts
  packages/@azure/servicefabric/lib/models/meshVolumeMappers.ts
  packages/@azure/servicefabric/lib/models/parameters.ts
  packages/@azure/servicefabric/lib/operations/index.ts
  packages/@azure/servicefabric/lib/operations/meshApplication.ts
  packages/@azure/servicefabric/lib/operations/meshCodePackage.ts
  packages/@azure/servicefabric/lib/operations/meshGateway.ts
  packages/@azure/servicefabric/lib/operations/meshNetwork.ts
  packages/@azure/servicefabric/lib/operations/meshSecret.ts
  packages/@azure/servicefabric/lib/operations/meshSecretValue.ts
  packages/@azure/servicefabric/lib/operations/meshService.ts
  packages/@azure/servicefabric/lib/operations/meshServiceReplica.ts
  packages/@azure/servicefabric/lib/operations/meshVolume.ts
  packages/@azure/servicefabric/lib/serviceFabricClient.ts
  packages/@azure/servicefabric/package.json
  packages/@azure/servicefabric/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#786 Regenerate @azure/arm-sqlvirtualmachine
  packages/@azure/arm-sqlvirtualmachine/lib/models/index.ts
  packages/@azure/arm-sqlvirtualmachine/lib/models/mappers.ts
  packages/@azure/arm-sqlvirtualmachine/lib/sqlVirtualMachineManagementClientContext.ts
  packages/@azure/arm-sqlvirtualmachine/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#758 [AutoPR storsimple8000series/resource-manager] typo: storsimple8000series/resource-manager/Microsoft.StorSimple
  packages/@azure/arm-storsimple8000series/LICENSE.txt
  packages/@azure/arm-storsimple8000series/README.md
  packages/@azure/arm-storsimple8000series/lib/models/index.ts
  packages/@azure/arm-storsimple8000series/lib/operations/operations.ts
  packages/@azure/arm-storsimple8000series/package.json
  packages/@azure/arm-storsimple8000series/rollup.config.js
Labels: RestPRMerged, in progress

#661 [AutoPR machinelearning/resource-manager] typo: machinelearning/resource-manager/Microsoft.MachineLearning
  packages/@azure/arm-commitmentplans/LICENSE.txt
  packages/@azure/arm-commitmentplans/README.md
  packages/@azure/arm-commitmentplans/lib/azureMLCommitmentPlansManagementClient.ts
  packages/@azure/arm-commitmentplans/lib/azureMLCommitmentPlansManagementClientContext.ts
  packages/@azure/arm-commitmentplans/lib/models/index.ts
  packages/@azure/arm-commitmentplans/lib/models/mappers.ts
  packages/@azure/arm-commitmentplans/lib/models/parameters.ts
  packages/@azure/arm-commitmentplans/lib/operations/commitmentAssociations.ts
  packages/@azure/arm-commitmentplans/lib/operations/commitmentPlans.ts
  packages/@azure/arm-commitmentplans/lib/operations/skus.ts
  packages/@azure/arm-commitmentplans/lib/operations/usageHistory.ts
  packages/@azure/arm-commitmentplans/package.json
  packages/@azure/arm-commitmentplans/rollup.config.js
  packages/@azure/arm-commitmentplans/tsconfig.json
  packages/@azure/arm-webservices/LICENSE.txt
  packages/@azure/arm-webservices/README.md
  packages/@azure/arm-webservices/lib/azureMLWebServicesManagementClient.ts
  packages/@azure/arm-webservices/lib/azureMLWebServicesManagementClientContext.ts
  packages/@azure/arm-webservices/lib/models/index.ts
  packages/@azure/arm-webservices/lib/models/mappers.ts
  packages/@azure/arm-webservices/lib/models/parameters.ts
  packages/@azure/arm-webservices/lib/operations/operations.ts
  packages/@azure/arm-webservices/lib/operations/webServices.ts
  packages/@azure/arm-webservices/package.json
  packages/@azure/arm-webservices/rollup.config.js
  packages/@azure/arm-webservices/tsconfig.json
  packages/@azure/arm-workspaces/LICENSE.txt
  packages/@azure/arm-workspaces/README.md
  packages/@azure/arm-workspaces/lib/machineLearningWorkspacesManagementClient.ts
  packages/@azure/arm-workspaces/lib/machineLearningWorkspacesManagementClientContext.ts
  packages/@azure/arm-workspaces/lib/models/index.ts
  packages/@azure/arm-workspaces/lib/models/mappers.ts
  packages/@azure/arm-workspaces/lib/models/parameters.ts
  packages/@azure/arm-workspaces/lib/operations/operations.ts
  packages/@azure/arm-workspaces/lib/operations/workspaces.ts
  packages/@azure/arm-workspaces/package.json
  packages/@azure/arm-workspaces/rollup.config.js
  packages/@azure/arm-workspaces/tsconfig.json
Labels: RestPRMerged, in progress

#792 [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face
  packages/@azure/cognitiveservices-face/README.md
  packages/@azure/cognitiveservices-face/lib/operations/faceListOperations.ts
  packages/@azure/cognitiveservices-face/lib/operations/largeFaceListOperations.ts
  packages/@azure/cognitiveservices-face/package.json
  packages/@azure/cognitiveservices-face/rollup.config.js
Labels: RestPRMerged, in progress

#798 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  packages/@azure/batch/README.md
  packages/@azure/batch/lib/models/index.ts
  packages/@azure/batch/lib/operations/computeNodeOperations.ts
  packages/@azure/batch/lib/operations/job.ts
  packages/@azure/batch/lib/operations/jobSchedule.ts
  packages/@azure/batch/lib/operations/pool.ts
  packages/@azure/batch/package.json
  packages/@azure/batch/rollup.config.js
Labels: RestPRMerged, in progress

#794 [AutoPR resourcehealth/resource-manager] typo: resourcehealth/resource-manager/Microsoft.ResourceHealth
  packages/@azure/arm-resourcehealth/README.md
  packages/@azure/arm-resourcehealth/lib/microsoftResourceHealth.ts
  packages/@azure/arm-resourcehealth/lib/microsoftResourceHealthContext.ts
  packages/@azure/arm-resourcehealth/lib/models/index.ts
  packages/@azure/arm-resourcehealth/lib/models/mappers.ts
  packages/@azure/arm-resourcehealth/lib/models/parameters.ts
  packages/@azure/arm-resourcehealth/lib/operations/availabilityStatuses.ts
  packages/@azure/arm-resourcehealth/lib/operations/operations.ts
  packages/@azure/arm-resourcehealth/package.json
  packages/@azure/arm-resourcehealth/rollup.config.js
  packages/@azure/arm-resourcehealth/tsconfig.json
Labels: RestPRMerged, in progress

#802 Generate @azure/cognitiveservices-localsearch
  packages/@azure/cognitiveservices-localsearch/LICENSE.txt
  packages/@azure/cognitiveservices-localsearch/README.md
  packages/@azure/cognitiveservices-localsearch/lib/localSearchClient.ts
  packages/@azure/cognitiveservices-localsearch/lib/localSearchClientContext.ts
  packages/@azure/cognitiveservices-localsearch/lib/models/index.ts
  packages/@azure/cognitiveservices-localsearch/lib/models/localMappers.ts
  packages/@azure/cognitiveservices-localsearch/lib/models/mappers.ts
  packages/@azure/cognitiveservices-localsearch/lib/models/parameters.ts
  packages/@azure/cognitiveservices-localsearch/lib/operations/index.ts
  packages/@azure/cognitiveservices-localsearch/lib/operations/local.ts
  packages/@azure/cognitiveservices-localsearch/package.json
  packages/@azure/cognitiveservices-localsearch/rollup.config.js
  packages/@azure/cognitiveservices-localsearch/tsconfig.json
Labels: Planned-Sprint-128, Started-Sprint-128

#763 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.DomainRegistration
  packages/@azure/arm-appservice/lib/models/index.ts
Labels: RestPRMerged, in progress

#797 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric
  packages/@azure/servicefabric/lib/models/index.ts
  packages/@azure/servicefabric/lib/operations/meshSecretValue.ts
Labels: RestPRMerged, in progress

#764 [AutoPR cognitiveservices/data-plane/CustomVision/Training] typo: CustomVision/Training
  packages/@azure/cognitiveservices-customvision-training/lib/models/index.ts
  packages/@azure/cognitiveservices-customvision-training/lib/trainingAPIClient.ts
  packages/@azure/cognitiveservices-customvision-training/lib/trainingAPIClientContext.ts
Labels: RestPRMerged, in progress

#682 [AutoPR powerbidedicated/resource-manager] typo: powerbidedicated/resource-manager/Microsoft.PowerBIdedicated
  packages/@azure/arm-powerbidedicated/LICENSE.txt
  packages/@azure/arm-powerbidedicated/README.md
  packages/@azure/arm-powerbidedicated/lib/models/index.ts
  packages/@azure/arm-powerbidedicated/lib/models/mappers.ts
  packages/@azure/arm-powerbidedicated/lib/models/parameters.ts
  packages/@azure/arm-powerbidedicated/lib/operations/capacities.ts
  packages/@azure/arm-powerbidedicated/lib/operations/operations.ts
  packages/@azure/arm-powerbidedicated/lib/powerBIDedicatedManagementClient.ts
  packages/@azure/arm-powerbidedicated/lib/powerBIDedicatedManagementClientContext.ts
  packages/@azure/arm-powerbidedicated/package.json
  packages/@azure/arm-powerbidedicated/rollup.config.js
  packages/@azure/arm-powerbidedicated/tsconfig.json
Labels: RestPRMerged, in progress

#793 [AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch
  packages/@azure/cognitiveservices-visualsearch/lib/models/index.ts
  packages/@azure/cognitiveservices-visualsearch/lib/visualSearchClientContext.ts
  packages/@azure/cognitiveservices-visualsearch/package.json
Labels: RestPRMerged, in progress

#731 [AutoPR cognitiveservices/data-plane/ComputerVision] Add areaOfInterest and detectObject to CV API
  packages/@azure/cognitiveservices-computervision/README.md
  packages/@azure/cognitiveservices-computervision/lib/computerVisionClient.ts
  packages/@azure/cognitiveservices-computervision/lib/computerVisionClientContext.ts
  packages/@azure/cognitiveservices-computervision/lib/models/index.ts
  packages/@azure/cognitiveservices-computervision/lib/models/mappers.ts
  packages/@azure/cognitiveservices-computervision/lib/models/parameters.ts
  packages/@azure/cognitiveservices-computervision/package.json
  packages/@azure/cognitiveservices-computervision/rollup.config.js
  packages/@azure/cognitiveservices-computervision/tsconfig.json
Labels: RestPRMerged, in progress

#811 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  packages/@azure/batch/lib/models/index.ts
Labels: RestPRMerged, in progress

#814 Regenerate @azure/arm-hdinsight
  packages/@azure/arm-hdinsight/README.md
  packages/@azure/arm-hdinsight/lib/models/applicationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/clustersMappers.ts
  packages/@azure/arm-hdinsight/lib/models/index.ts
  packages/@azure/arm-hdinsight/lib/models/mappers.ts
  packages/@azure/arm-hdinsight/lib/operations/clusters.ts
  packages/@azure/arm-hdinsight/package.json
  packages/@azure/arm-hdinsight/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#815 [AutoPR containerservices/resource-manager] ContainerServices - OpenShift - Add new routes and update
  packages/@azure/arm-containerservice/README.md
  packages/@azure/arm-containerservice/lib/containerServiceClient.ts
  packages/@azure/arm-containerservice/lib/containerServiceClientContext.ts
  packages/@azure/arm-containerservice/lib/models/index.ts
  packages/@azure/arm-containerservice/lib/models/mappers.ts
  packages/@azure/arm-containerservice/lib/models/openShiftManagedClustersMappers.ts
  packages/@azure/arm-containerservice/lib/models/parameters.ts
  packages/@azure/arm-containerservice/lib/operations/containerServices.ts
  packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
  packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts
  packages/@azure/arm-containerservice/lib/operations/operations.ts
  packages/@azure/arm-containerservice/package.json
  packages/@azure/arm-containerservice/rollup.config.js
  packages/@azure/arm-containerservice/tsconfig.json
Labels: RestPRMerged, in progress

#813 [AutoPR commerce/resource-manager] typo: commerce/resource-manager/Microsoft.Commerce
  packages/@azure/arm-commerce/LICENSE.txt
  packages/@azure/arm-commerce/README.md
  packages/@azure/arm-commerce/package.json
  packages/@azure/arm-commerce/rollup.config.js
Labels: RestPRMerged, in progress

#807 [AutoPR iothub/resource-manager] Add package-2018-12 to Go SDK build
  packages/@azure/arm-iothub/lib/iotHubClientContext.ts
  packages/@azure/arm-iothub/lib/models/certificatesMappers.ts
  packages/@azure/arm-iothub/lib/models/index.ts
  packages/@azure/arm-iothub/lib/models/iotHubResourceMappers.ts
  packages/@azure/arm-iothub/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#821 [AutoPR containerregistry/resource-manager] [ACR] Add IP rules
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
  packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
  packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
Labels: RestPRMerged, in progress

#671 [AutoPR batch/resource-manager] [Portal Generated] Review request for Microsoft.Batch to add version 2018-12-01
  packages/@azure/arm-batch/LICENSE.txt
  packages/@azure/arm-batch/README.md
  packages/@azure/arm-batch/lib/batchManagementClient.ts
  packages/@azure/arm-batch/lib/batchManagementClientContext.ts
  packages/@azure/arm-batch/lib/models/applicationOperationsMappers.ts
  packages/@azure/arm-batch/lib/models/applicationPackageOperationsMappers.ts
  packages/@azure/arm-batch/lib/models/batchAccountOperationsMappers.ts
  packages/@azure/arm-batch/lib/models/certificateOperationsMappers.ts
  packages/@azure/arm-batch/lib/models/index.ts
  packages/@azure/arm-batch/lib/models/mappers.ts
  packages/@azure/arm-batch/lib/models/parameters.ts
  packages/@azure/arm-batch/lib/models/poolOperationsMappers.ts
  packages/@azure/arm-batch/lib/operations/applicationOperations.ts
  packages/@azure/arm-batch/lib/operations/applicationPackageOperations.ts
  packages/@azure/arm-batch/lib/operations/batchAccountOperations.ts
  packages/@azure/arm-batch/lib/operations/certificateOperations.ts
  packages/@azure/arm-batch/lib/operations/location.ts
  packages/@azure/arm-batch/lib/operations/operations.ts
  packages/@azure/arm-batch/lib/operations/poolOperations.ts
  packages/@azure/arm-batch/package.json
  packages/@azure/arm-batch/rollup.config.js
  packages/@azure/arm-batch/tsconfig.json
Labels: RestPRMerged, in progress

#828 Update packageVersion in customSearchClientContext.ts
  packages/@azure/cognitiveservices-customsearch/lib/customSearchClientContext.ts
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#830 Regenerate @azure/arm-mediaservices
  packages/@azure/arm-mediaservices/README.md
  packages/@azure/arm-mediaservices/lib/models/index.ts
  packages/@azure/arm-mediaservices/lib/models/mappers.ts
  packages/@azure/arm-mediaservices/lib/models/parameters.ts
  packages/@azure/arm-mediaservices/lib/operations/jobs.ts
  packages/@azure/arm-mediaservices/lib/operations/transforms.ts
  packages/@azure/arm-mediaservices/package.json
  packages/@azure/arm-mediaservices/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#759 [AutoPR streamanalytics/resource-manager] typo: streamanalytics/resource-manager/Microsoft.StreamAnalytics
  packages/@azure/arm-streamanalytics/LICENSE.txt
  packages/@azure/arm-streamanalytics/README.md
  packages/@azure/arm-streamanalytics/lib/models/index.ts
  packages/@azure/arm-streamanalytics/package.json
  packages/@azure/arm-streamanalytics/rollup.config.js
Labels: RestPRMerged, in progress

#831 [AutoPR sql/resource-manager] Updating managed database swagger
  packages/@azure/arm-sql/lib/models/index.ts
  packages/@azure/arm-sql/lib/models/mappers.ts
  packages/@azure/arm-sql/lib/operations/managedDatabases.ts
Labels: RestPRMerged, in progress

#818 Implement BranchHasChanges for gulp pack
  .scripts/logger.ts
  azure-pipelines.yml
  gulpfile.ts
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#834 Regenerate @azure/arm-commerce
  packages/@azure/arm-commerce/README.md
  packages/@azure/arm-commerce/package.json
  packages/@azure/arm-commerce/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#761 [AutoPR trafficmanager/resource-manager] typo: trafficmanager/resource-manager/Microsoft.Network
  packages/@azure/arm-trafficmanager/LICENSE.txt
  packages/@azure/arm-trafficmanager/README.md
  packages/@azure/arm-trafficmanager/lib/models/index.ts
  packages/@azure/arm-trafficmanager/package.json
  packages/@azure/arm-trafficmanager/rollup.config.js
Labels: RestPRMerged, in progress

#757 [AutoPR storSimple1200Series/resource-manager] typo: storSimple1200Series/resource-manager/Microsoft.StorSimple
  packages/@azure/arm-storsimple1200series/LICENSE.txt
  packages/@azure/arm-storsimple1200series/README.md
  packages/@azure/arm-storsimple1200series/lib/models/index.ts
  packages/@azure/arm-storsimple1200series/lib/operations/devices.ts
  packages/@azure/arm-storsimple1200series/lib/operations/iscsiDisks.ts
  packages/@azure/arm-storsimple1200series/lib/operations/iscsiServers.ts
  packages/@azure/arm-storsimple1200series/package.json
  packages/@azure/arm-storsimple1200series/rollup.config.js
Labels: RestPRMerged, in progress

#832 Add template and pipeline
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
  gulpfile.ts
  packages/@azure/template/.gitignore
  packages/@azure/template/.npmignore
  packages/@azure/template/.prettierrc.json
  packages/@azure/template/.vscode/launch.json
  packages/@azure/template/.vscode/tasks.json
  packages/@azure/template/README.md
  packages/@azure/template/package.json
  packages/@azure/template/rollup.base.config.js
  packages/@azure/template/rollup.config.js
  packages/@azure/template/rollup.test.config.js
  packages/@azure/template/samples/.gitkeep
  packages/@azure/template/src/declarations/create-hmac.d.ts
  packages/@azure/template/src/index.ts
  packages/@azure/template/src/print.browser.ts
  packages/@azure/template/src/print.ts
  packages/@azure/template/test/index.spec.ts
  packages/@azure/template/tsconfig.json
Labels: in progress

#838 [AutoPR cognitiveservices/resource-manager] Change Kind and SKU name to string (from enum).
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/operations/checkSkuAvailability.ts
Labels: RestPRMerged, in progress

#839 Add client library status badge
  README.md
Labels: in progress

#843 [AutoPR containerservices/resource-manager] [DO NOT MERGE] [AKS] add C# config to readme.md
  packages/@azure/arm-containerservice/lib/models/index.ts
  packages/@azure/arm-containerservice/lib/operations/containerServices.ts
  packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
  packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts
Labels: RestPRMerged, in progress

#851 [AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices
  packages/@azure/arm-labservices/lib/models/index.ts
Labels: RestPRMerged, in progress

#852 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric
  packages/@azure/servicefabric/lib/models/index.ts
Labels: RestPRMerged, in progress

#847 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  packages/@azure/batch/lib/models/index.ts
Labels: RestPRMerged, in progress

#849 [AutoPR iothub/resource-manager] typo: iothub/resource-manager/Microsoft.Devices
  packages/@azure/arm-iothub/lib/models/index.ts
Labels: RestPRMerged, in progress

#825 [AutoPR eventgrid/resource-manager] Event Grid 2019-01-01 API Version: Swagger and related test examples
  packages/@azure/arm-eventgrid/README.md
  packages/@azure/arm-eventgrid/lib/eventGridManagementClient.ts
  packages/@azure/arm-eventgrid/lib/eventGridManagementClientContext.ts
  packages/@azure/arm-eventgrid/lib/models/eventSubscriptionsMappers.ts
  packages/@azure/arm-eventgrid/lib/models/index.ts
  packages/@azure/arm-eventgrid/lib/models/mappers.ts
  packages/@azure/arm-eventgrid/lib/models/parameters.ts
  packages/@azure/arm-eventgrid/lib/models/topicTypesMappers.ts
  packages/@azure/arm-eventgrid/lib/models/topicsMappers.ts
  packages/@azure/arm-eventgrid/lib/operations/eventSubscriptions.ts
  packages/@azure/arm-eventgrid/lib/operations/index.ts
Labels: RestPRMerged, in progress

#859 Regenerate @azure/arm-mediaservices
  packages/@azure/arm-mediaservices/lib/azureMediaServicesContext.ts
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#860 Regenerate @azure/arm-cognitiveservices and update version to 2.4.1
  packages/@azure/arm-cognitiveservices/README.md
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/operations/checkSkuAvailability.ts
  packages/@azure/arm-cognitiveservices/package.json
  packages/@azure/arm-cognitiveservices/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#861 Default to DifferentVersion if base and head references are equal
  azure-pipelines.yml
  gulpfile.ts
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#862 Don't show NPM view output
  gulpfile.ts
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#864 [AutoPR maps/resource-manager] [Hub Generated] Review request for Microsoft.Maps to add version 2018-05-01
  packages/@azure/arm-maps/LICENSE.txt
  packages/@azure/arm-maps/README.md
  packages/@azure/arm-maps/lib/models/accountsMappers.ts
  packages/@azure/arm-maps/lib/models/index.ts
  packages/@azure/arm-maps/lib/models/mappers.ts
  packages/@azure/arm-maps/package.json
  packages/@azure/arm-maps/rollup.config.js
Labels: RestPRMerged, in progress

#869 Reduce build time of audit job
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
Labels: in progress

#874 Fix gulpfile build errors
  .scripts/gulp.ts
  gulpfile.ts
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#876 Update @azure/arm-features to 1.0.1
  gulpfile.ts
  package.json
  packages/@azure/arm-features/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#877 Regenerate @azure/arm-policyinsights and update version to 2.0.0
  packages/@azure/arm-policyinsights/README.md
  packages/@azure/arm-policyinsights/lib/models/index.ts
  packages/@azure/arm-policyinsights/package.json
  packages/@azure/arm-policyinsights/rollup.config.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#870 [AutoPR network/resource-manager] Exposing PATCH for Application Security Group (ASG)
  packages/@azure/arm-network/lib/models/applicationSecurityGroupsMappers.ts
  packages/@azure/arm-network/lib/models/index.ts
  packages/@azure/arm-network/lib/operations/applicationSecurityGroups.ts
Labels: RestPRMerged, in progress

#856 [AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#868 [AutoPR hanaonazure/resource-manager] Add PATCH API example to hanaonazure
  packages/@azure/arm-hanaonazure/lib/models/hanaInstancesMappers.ts
  packages/@azure/arm-hanaonazure/lib/models/index.ts
  packages/@azure/arm-hanaonazure/lib/models/mappers.ts
  packages/@azure/arm-hanaonazure/lib/operations/hanaInstances.ts
Labels: RestPRMerged, in progress

#880 [AutoPR automation/resource-manager] Swagger change for Update configuration dynamic group Saved Search Query
  packages/@azure/arm-automation/lib/models/automationAccountOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/certificateOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/connectionOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/credentialOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/dscCompilationJobOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/dscConfigurationOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/dscNodeConfigurationOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/dscNodeOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/index.ts
  packages/@azure/arm-automation/lib/models/jobOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/mappers.ts
  packages/@azure/arm-automation/lib/models/moduleOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/python2PackageMappers.ts
  packages/@azure/arm-automation/lib/models/runbookOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/scheduleOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/softwareUpdateConfigurationsMappers.ts
  packages/@azure/arm-automation/lib/models/sourceControlOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/variableOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/watcherOperationsMappers.ts
  packages/@azure/arm-automation/lib/models/webhookOperationsMappers.ts
Labels: RestPRMerged, in progress
