Repository Azure/azure-sdk-for-js, pull requests merged in 2019-05, with the labels that each got.

#2563 receiveBatch()- Throw error when network connection goes down
  sdk/servicebus/service-bus/src/clientEntityContext.ts
  sdk/servicebus/service-bus/src/core/batchingReceiver.ts
Labels: Client, Service Bus, bug

#2627 [Service Bus] Fix NYC code coverage breaking changes in 14.0.0
  sdk/servicebus/service-bus/package.json
Labels: Client, Service Bus

#2606 Improve samples for Event Hubs
  sdk/eventhub/event-hubs/.vscode/launch.json
  sdk/eventhub/event-hubs/samples/README.md
  sdk/eventhub/event-hubs/samples/batchReceive.ts
  sdk/eventhub/event-hubs/samples/batchSendReceive.ts
  sdk/eventhub/event-hubs/samples/createEpochReceiver.ts
  sdk/eventhub/event-hubs/samples/getHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/interactiveLogin.ts
  sdk/eventhub/event-hubs/samples/iotGetHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/loginWithAzureAccount.ts
  sdk/eventhub/event-hubs/samples/receiveMessagesLoop.ts
  sdk/eventhub/event-hubs/samples/receiveMessagesStreaming.ts
  sdk/eventhub/event-hubs/samples/sendMessages.ts
  sdk/eventhub/event-hubs/samples/sendReceiveWithInteractiveAuth.ts
  sdk/eventhub/event-hubs/samples/sendReceiveWithSPAuth.ts
  sdk/eventhub/event-hubs/samples/sendUsingProxy.ts
  sdk/eventhub/event-hubs/samples/servicePrincipalLogin.ts
  sdk/eventhub/event-hubs/samples/simpleSendReceive.ts
  sdk/eventhub/event-hubs/samples/simpleSender.ts
  sdk/eventhub/event-hubs/samples/streamingReceive.ts
  sdk/eventhub/event-hubs/samples/useProxy.ts
Labels: Client, Event Hub

#2625 [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01
  sdk/apimanagement/arm-apimanagement/lib/models/apiDiagnosticMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiIssueAttachmentMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiIssueCommentMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiIssueMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiManagementServiceMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiOperationMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiOperationPolicyMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiPolicyMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiProductMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiReleaseMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiSchemaMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiTagDescriptionMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/apiVersionSetMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/authorizationServerMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/backendMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/cacheMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/certificateMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/delegationSettingsMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/diagnosticMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/emailTemplateMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/groupMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/groupUserMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/identityProviderMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/index.ts
  sdk/apimanagement/arm-apimanagement/lib/models/issueMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/loggerMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/mappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/notificationMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/notificationRecipientEmailMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/notificationRecipientUserMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/openIdConnectProviderMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/policyMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/productApiMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/productGroupMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/productMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/productPolicyMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/productSubscriptionsMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/propertyMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/signInSettingsMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/signUpSettingsMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/subscriptionMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/tagMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/userGroupMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/userMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/models/userSubscriptionMappers.ts
  sdk/apimanagement/arm-apimanagement/lib/operations/apiSchema.ts
Labels: RestPRMerged

#2644 [Event Hubs] Fix NYC code coverage breaking changes in 14.0.0
  sdk/eventhub/event-hubs/package.json
  sdk/eventhub/event-processor-host/package.json
Labels: Client, Event Hub

#2616 [Storage] Update live test command for storage packages
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-file/package.json
  sdk/storage/storage-queue/package.json
Labels: Storage

#2619 [AutoPR subscription/resource-manager] Add cancel and rename subscription API
  sdk/subscription/arm-subscriptions/LICENSE.txt
  sdk/subscription/arm-subscriptions/README.md
  sdk/subscription/arm-subscriptions/lib/models/index.ts
  sdk/subscription/arm-subscriptions/lib/models/mappers.ts
  sdk/subscription/arm-subscriptions/lib/models/operationsMappers.ts
  sdk/subscription/arm-subscriptions/lib/models/parameters.ts
  sdk/subscription/arm-subscriptions/lib/models/subscriptionFactoryMappers.ts
  sdk/subscription/arm-subscriptions/lib/models/subscriptionOperationOperationsMappers.ts
  sdk/subscription/arm-subscriptions/lib/models/subscriptionsMappers.ts
  sdk/subscription/arm-subscriptions/lib/models/tenantsMappers.ts
  sdk/subscription/arm-subscriptions/lib/operations/index.ts
  sdk/subscription/arm-subscriptions/lib/operations/operations.ts
  sdk/subscription/arm-subscriptions/lib/operations/subscriptionFactory.ts
  sdk/subscription/arm-subscriptions/lib/operations/subscriptionOperationOperations.ts
  sdk/subscription/arm-subscriptions/lib/operations/subscriptions.ts
  sdk/subscription/arm-subscriptions/lib/operations/tenants.ts
  sdk/subscription/arm-subscriptions/lib/subscriptionClient.ts
  sdk/subscription/arm-subscriptions/lib/subscriptionClientContext.ts
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/rollup.config.js
  sdk/subscription/arm-subscriptions/tsconfig.json
Labels: RestPRMerged

#2615 [AutoPR containerservice/resource-manager] Update list-orchestrator for api spec 2019-04-01
  sdk/containerservice/arm-containerservice/lib/models/index.ts
  sdk/containerservice/arm-containerservice/lib/models/mappers.ts
  sdk/containerservice/arm-containerservice/lib/models/parameters.ts
  sdk/containerservice/arm-containerservice/lib/operations/agentPools.ts
  sdk/containerservice/arm-containerservice/lib/operations/containerServices.ts
  sdk/containerservice/arm-containerservice/lib/operations/managedClusters.ts
  sdk/containerservice/arm-containerservice/lib/operations/operations.ts
Labels: RestPRMerged

#2666 [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version preview/2019-04-01-preview
  sdk/consumption/arm-consumption/LICENSE.txt
  sdk/consumption/arm-consumption/README.md
  sdk/consumption/arm-consumption/lib/consumptionManagementClient.ts
  sdk/consumption/arm-consumption/lib/consumptionManagementClientContext.ts
  sdk/consumption/arm-consumption/lib/models/aggregatedCostMappers.ts
  sdk/consumption/arm-consumption/lib/models/balancesMappers.ts
  sdk/consumption/arm-consumption/lib/models/budgetsMappers.ts
  sdk/consumption/arm-consumption/lib/models/chargesMappers.ts
  sdk/consumption/arm-consumption/lib/models/forecastsMappers.ts
  sdk/consumption/arm-consumption/lib/models/index.ts
  sdk/consumption/arm-consumption/lib/models/mappers.ts
  sdk/consumption/arm-consumption/lib/models/marketplacesMappers.ts
  sdk/consumption/arm-consumption/lib/models/operationsMappers.ts
  sdk/consumption/arm-consumption/lib/models/parameters.ts
  sdk/consumption/arm-consumption/lib/models/priceSheetMappers.ts
  sdk/consumption/arm-consumption/lib/models/reservationRecommendationsMappers.ts
  sdk/consumption/arm-consumption/lib/models/reservationsDetailsMappers.ts
  sdk/consumption/arm-consumption/lib/models/reservationsSummariesMappers.ts
  sdk/consumption/arm-consumption/lib/models/tagsMappers.ts
  sdk/consumption/arm-consumption/lib/models/usageDetailsMappers.ts
  sdk/consumption/arm-consumption/lib/operations/aggregatedCost.ts
  sdk/consumption/arm-consumption/lib/operations/balances.ts
  sdk/consumption/arm-consumption/lib/operations/budgets.ts
  sdk/consumption/arm-consumption/lib/operations/charges.ts
  sdk/consumption/arm-consumption/lib/operations/forecasts.ts
  sdk/consumption/arm-consumption/lib/operations/index.ts
  sdk/consumption/arm-consumption/lib/operations/marketplaces.ts
  sdk/consumption/arm-consumption/lib/operations/operations.ts
  sdk/consumption/arm-consumption/lib/operations/priceSheet.ts
  sdk/consumption/arm-consumption/lib/operations/reservationRecommendations.ts
  sdk/consumption/arm-consumption/lib/operations/reservationsDetails.ts
  sdk/consumption/arm-consumption/lib/operations/reservationsSummaries.ts
  sdk/consumption/arm-consumption/lib/operations/tags.ts
  sdk/consumption/arm-consumption/lib/operations/usageDetails.ts
  sdk/consumption/arm-consumption/package.json
  sdk/consumption/arm-consumption/rollup.config.js
  sdk/consumption/arm-consumption/tsconfig.json
Labels: RestPRMerged

#2665 [AutoPR containerservice/resource-manager] Revert node public ip support from 2019-04-01 model.
  sdk/containerservice/arm-containerservice/lib/models/index.ts
  sdk/containerservice/arm-containerservice/lib/models/mappers.ts
Labels: RestPRMerged

#2679 [Service Bus] Track rejected messages along with accepted ones
  sdk/servicebus/service-bus/test/perf/azure-sb-package/send.ts
  sdk/servicebus/service-bus/test/perf/rhea-promise/send.ts
Labels: Client, Service Bus

#2692 [AutoPR analysisservices/resource-manager] chore: jsonfmt analysisservices
  sdk/analysisservices/arm-analysisservices/LICENSE.txt
  sdk/analysisservices/arm-analysisservices/README.md
  sdk/analysisservices/arm-analysisservices/package.json
  sdk/analysisservices/arm-analysisservices/rollup.config.js
  sdk/analysisservices/arm-analysisservices/src/analysisServicesManagementClientContext.ts
  sdk/analysisservices/arm-analysisservices/src/models/index.ts
  sdk/analysisservices/arm-analysisservices/src/models/mappers.ts
  sdk/analysisservices/arm-analysisservices/src/models/operationsMappers.ts
  sdk/analysisservices/arm-analysisservices/src/models/serversMappers.ts
  sdk/analysisservices/arm-analysisservices/src/operations/servers.ts
Labels: RestPRMerged

#2713 [AutoPR keyvault/data-plane] Update Auto rest specs for KeyVault
  packages/@azure/keyvault/LICENSE.txt
  packages/@azure/keyvault/README.md
  packages/@azure/keyvault/lib/keyVaultClient.ts
  packages/@azure/keyvault/lib/keyVaultClientContext.ts
  packages/@azure/keyvault/lib/models/index.ts
  packages/@azure/keyvault/lib/models/mappers.ts
  packages/@azure/keyvault/lib/models/parameters.ts
  packages/@azure/keyvault/package.json
  packages/@azure/keyvault/rollup.config.js
  packages/@azure/keyvault/tsconfig.json
Labels: RestPRMerged

#2686 [AutoPR cdn/resource-manager] Add rulesEngine support to CDN
  sdk/cdn/arm-cdn/README.md
  sdk/cdn/arm-cdn/lib/cdnManagementClient.ts
  sdk/cdn/arm-cdn/lib/cdnManagementClientContext.ts
  sdk/cdn/arm-cdn/lib/models/customDomainsMappers.ts
  sdk/cdn/arm-cdn/lib/models/edgeNodesMappers.ts
  sdk/cdn/arm-cdn/lib/models/endpointsMappers.ts
  sdk/cdn/arm-cdn/lib/models/index.ts
  sdk/cdn/arm-cdn/lib/models/mappers.ts
  sdk/cdn/arm-cdn/lib/models/operationsMappers.ts
  sdk/cdn/arm-cdn/lib/models/originsMappers.ts
  sdk/cdn/arm-cdn/lib/models/parameters.ts
  sdk/cdn/arm-cdn/lib/models/profilesMappers.ts
  sdk/cdn/arm-cdn/lib/models/resourceUsageOperationsMappers.ts
  sdk/cdn/arm-cdn/lib/operations/customDomains.ts
  sdk/cdn/arm-cdn/lib/operations/edgeNodes.ts
  sdk/cdn/arm-cdn/lib/operations/endpoints.ts
  sdk/cdn/arm-cdn/lib/operations/index.ts
  sdk/cdn/arm-cdn/lib/operations/operations.ts
  sdk/cdn/arm-cdn/lib/operations/origins.ts
  sdk/cdn/arm-cdn/lib/operations/profiles.ts
  sdk/cdn/arm-cdn/lib/operations/resourceUsageOperations.ts
  sdk/cdn/arm-cdn/package.json
  sdk/cdn/arm-cdn/tsconfig.json
Labels: RestPRMerged

#2722 [AutoPR storage/resource-manager] Storage: Added Java ReadMe
  sdk/storage/arm-storage/lib/models/blobContainersMappers.ts
  sdk/storage/arm-storage/lib/models/blobServicesMappers.ts
  sdk/storage/arm-storage/lib/models/index.ts
  sdk/storage/arm-storage/lib/models/managementPoliciesMappers.ts
  sdk/storage/arm-storage/lib/models/mappers.ts
  sdk/storage/arm-storage/lib/models/operationsMappers.ts
  sdk/storage/arm-storage/lib/models/parameters.ts
  sdk/storage/arm-storage/lib/models/skusMappers.ts
  sdk/storage/arm-storage/lib/models/storageAccountsMappers.ts
  sdk/storage/arm-storage/lib/models/usagesMappers.ts
  sdk/storage/arm-storage/lib/operations/blobContainers.ts
  sdk/storage/arm-storage/lib/operations/blobServices.ts
  sdk/storage/arm-storage/lib/operations/index.ts
  sdk/storage/arm-storage/lib/operations/managementPolicies.ts
  sdk/storage/arm-storage/lib/operations/operations.ts
  sdk/storage/arm-storage/lib/operations/skus.ts
  sdk/storage/arm-storage/lib/operations/storageAccounts.ts
  sdk/storage/arm-storage/lib/operations/usages.ts
  sdk/storage/arm-storage/lib/storageManagementClient.ts
  sdk/storage/arm-storage/lib/storageManagementClientContext.ts
  sdk/storage/arm-storage/package.json
  sdk/storage/arm-storage/tsconfig.json
Labels: RestPRMerged

#2730 [AutoPR graphrbac/data-plane] graph: fix invalid types of accountEnabled
  sdk/graphrbac/graph/LICENSE.txt
  sdk/graphrbac/graph/README.md
  sdk/graphrbac/graph/lib/graphRbacManagementClient.ts
  sdk/graphrbac/graph/lib/graphRbacManagementClientContext.ts
  sdk/graphrbac/graph/lib/models/applicationsMappers.ts
  sdk/graphrbac/graph/lib/models/deletedApplicationsMappers.ts
  sdk/graphrbac/graph/lib/models/domainsMappers.ts
  sdk/graphrbac/graph/lib/models/groupsMappers.ts
  sdk/graphrbac/graph/lib/models/index.ts
  sdk/graphrbac/graph/lib/models/mappers.ts
  sdk/graphrbac/graph/lib/models/oAuth2PermissionGrantOperationsMappers.ts
  sdk/graphrbac/graph/lib/models/objectsMappers.ts
  sdk/graphrbac/graph/lib/models/parameters.ts
  sdk/graphrbac/graph/lib/models/servicePrincipalsMappers.ts
  sdk/graphrbac/graph/lib/models/signedInUserMappers.ts
  sdk/graphrbac/graph/lib/models/usersMappers.ts
  sdk/graphrbac/graph/lib/operations/applications.ts
  sdk/graphrbac/graph/lib/operations/deletedApplications.ts
  sdk/graphrbac/graph/lib/operations/domains.ts
  sdk/graphrbac/graph/lib/operations/groups.ts
  sdk/graphrbac/graph/lib/operations/index.ts
  sdk/graphrbac/graph/lib/operations/oAuth2PermissionGrantOperations.ts
  sdk/graphrbac/graph/lib/operations/objects.ts
  sdk/graphrbac/graph/lib/operations/servicePrincipals.ts
  sdk/graphrbac/graph/lib/operations/signedInUser.ts
  sdk/graphrbac/graph/lib/operations/users.ts
  sdk/graphrbac/graph/package.json
  sdk/graphrbac/graph/rollup.config.js
  sdk/graphrbac/graph/tsconfig.json
Labels: RestPRMerged

#2683 [AutoPR operationsmanagement/resource-manager] add patch for Solution, fix various tests, the ManagementAssociation …
  sdk/operationsmanagement/arm-operations/LICENSE.txt
  sdk/operationsmanagement/arm-operations/README.md
  sdk/operationsmanagement/arm-operations/lib/models/index.ts
  sdk/operationsmanagement/arm-operations/lib/models/managementAssociationsMappers.ts
  sdk/operationsmanagement/arm-operations/lib/models/managementConfigurationsMappers.ts
  sdk/operationsmanagement/arm-operations/lib/models/mappers.ts
  sdk/operationsmanagement/arm-operations/lib/models/operationsMappers.ts
  sdk/operationsmanagement/arm-operations/lib/models/parameters.ts
  sdk/operationsmanagement/arm-operations/lib/models/solutionsMappers.ts
  sdk/operationsmanagement/arm-operations/lib/operations/index.ts
  sdk/operationsmanagement/arm-operations/lib/operations/managementAssociations.ts
  sdk/operationsmanagement/arm-operations/lib/operations/managementConfigurations.ts
  sdk/operationsmanagement/arm-operations/lib/operations/operations.ts
  sdk/operationsmanagement/arm-operations/lib/operations/solutions.ts
  sdk/operationsmanagement/arm-operations/lib/operationsManagementClient.ts
  sdk/operationsmanagement/arm-operations/lib/operationsManagementClientContext.ts
  sdk/operationsmanagement/arm-operations/package.json
  sdk/operationsmanagement/arm-operations/rollup.config.js
  sdk/operationsmanagement/arm-operations/tsconfig.json
Labels: RestPRMerged

#2744 [AutoPR authorization/resource-manager] chore: jsonfmt authorization
  sdk/authorization/arm-authorization/LICENSE.txt
  sdk/authorization/arm-authorization/README.md
  sdk/authorization/arm-authorization/package.json
  sdk/authorization/arm-authorization/rollup.config.js
  sdk/authorization/arm-authorization/src/authorizationManagementClientContext.ts
  sdk/authorization/arm-authorization/src/models/classicAdministratorsMappers.ts
  sdk/authorization/arm-authorization/src/models/denyAssignmentsMappers.ts
  sdk/authorization/arm-authorization/src/models/index.ts
  sdk/authorization/arm-authorization/src/models/mappers.ts
  sdk/authorization/arm-authorization/src/models/permissionsMappers.ts
  sdk/authorization/arm-authorization/src/models/providerOperationsMetadataOperationsMappers.ts
  sdk/authorization/arm-authorization/src/models/roleAssignmentsMappers.ts
  sdk/authorization/arm-authorization/src/models/roleDefinitionsMappers.ts
Labels: RestPRMerged

#2720 [AutoPR security/resource-manager] Add complianceResults type to swagger
  sdk/security/arm-security/LICENSE.txt
  sdk/security/arm-security/README.md
  sdk/security/arm-security/lib/models/advancedThreatProtectionMappers.ts
  sdk/security/arm-security/lib/models/alertsMappers.ts
  sdk/security/arm-security/lib/models/allowedConnectionsMappers.ts
  sdk/security/arm-security/lib/models/autoProvisioningSettingsMappers.ts
  sdk/security/arm-security/lib/models/complianceResultsMappers.ts
  sdk/security/arm-security/lib/models/compliancesMappers.ts
  sdk/security/arm-security/lib/models/discoveredSecuritySolutionsMappers.ts
  sdk/security/arm-security/lib/models/externalSecuritySolutionsMappers.ts
  sdk/security/arm-security/lib/models/index.ts
  sdk/security/arm-security/lib/models/informationProtectionPoliciesMappers.ts
  sdk/security/arm-security/lib/models/jitNetworkAccessPoliciesMappers.ts
  sdk/security/arm-security/lib/models/locationsMappers.ts
  sdk/security/arm-security/lib/models/mappers.ts
  sdk/security/arm-security/lib/models/operationsMappers.ts
  sdk/security/arm-security/lib/models/parameters.ts
  sdk/security/arm-security/lib/models/pricingsMappers.ts
  sdk/security/arm-security/lib/models/regulatoryComplianceAssessmentsMappers.ts
  sdk/security/arm-security/lib/models/regulatoryComplianceControlsMappers.ts
  sdk/security/arm-security/lib/models/regulatoryComplianceStandardsMappers.ts
  sdk/security/arm-security/lib/models/securityContactsMappers.ts
  sdk/security/arm-security/lib/models/settingsMappers.ts
  sdk/security/arm-security/lib/models/tasksMappers.ts
  sdk/security/arm-security/lib/models/topologyMappers.ts
  sdk/security/arm-security/lib/models/workspaceSettingsMappers.ts
  sdk/security/arm-security/lib/operations/advancedThreatProtection.ts
  sdk/security/arm-security/lib/operations/alerts.ts
  sdk/security/arm-security/lib/operations/allowedConnections.ts
  sdk/security/arm-security/lib/operations/autoProvisioningSettings.ts
  sdk/security/arm-security/lib/operations/complianceResults.ts
  sdk/security/arm-security/lib/operations/compliances.ts
  sdk/security/arm-security/lib/operations/discoveredSecuritySolutions.ts
  sdk/security/arm-security/lib/operations/externalSecuritySolutions.ts
  sdk/security/arm-security/lib/operations/index.ts
  sdk/security/arm-security/lib/operations/informationProtectionPolicies.ts
  sdk/security/arm-security/lib/operations/jitNetworkAccessPolicies.ts
  sdk/security/arm-security/lib/operations/locations.ts
  sdk/security/arm-security/lib/operations/operations.ts
  sdk/security/arm-security/lib/operations/pricings.ts
  sdk/security/arm-security/lib/operations/regulatoryComplianceAssessments.ts
  sdk/security/arm-security/lib/operations/regulatoryComplianceControls.ts
  sdk/security/arm-security/lib/operations/regulatoryComplianceStandards.ts
  sdk/security/arm-security/lib/operations/securityContacts.ts
  sdk/security/arm-security/lib/operations/settings.ts
  sdk/security/arm-security/lib/operations/tasks.ts
  sdk/security/arm-security/lib/operations/topology.ts
  sdk/security/arm-security/lib/operations/workspaceSettings.ts
  sdk/security/arm-security/lib/securityCenter.ts
  sdk/security/arm-security/lib/securityCenterContext.ts
  sdk/security/arm-security/package.json
  sdk/security/arm-security/rollup.config.js
  sdk/security/arm-security/tsconfig.json
Labels: RestPRMerged

#2755 [AutoPR automation/resource-manager] chore: jsonfmt automation
  sdk/automation/arm-automation/LICENSE.txt
  sdk/automation/arm-automation/README.md
  sdk/automation/arm-automation/package.json
  sdk/automation/arm-automation/rollup.config.js
  sdk/automation/arm-automation/src/automationClientContext.ts
  sdk/automation/arm-automation/src/models/activityOperationsMappers.ts
  sdk/automation/arm-automation/src/models/agentRegistrationInformationMappers.ts
  sdk/automation/arm-automation/src/models/automationAccountOperationsMappers.ts
  sdk/automation/arm-automation/src/models/certificateOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionTypeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/credentialOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobStreamMappers.ts
  sdk/automation/arm-automation/src/models/dscConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/fieldsMappers.ts
  sdk/automation/arm-automation/src/models/hybridRunbookWorkerGroupOperationsMappers.ts
  sdk/automation/arm-automation/src/models/index.ts
  sdk/automation/arm-automation/src/models/jobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobScheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobStreamOperationsMappers.ts
  sdk/automation/arm-automation/src/models/keysMappers.ts
  sdk/automation/arm-automation/src/models/linkedWorkspaceOperationsMappers.ts
  sdk/automation/arm-automation/src/models/mappers.ts
  sdk/automation/arm-automation/src/models/moduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/nodeCountInformationMappers.ts
  sdk/automation/arm-automation/src/models/nodeReportsMappers.ts
  sdk/automation/arm-automation/src/models/objectDataTypesMappers.ts
  sdk/automation/arm-automation/src/models/operationsMappers.ts
  sdk/automation/arm-automation/src/models/python2PackageMappers.ts
  sdk/automation/arm-automation/src/models/runbookDraftOperationsMappers.ts
  sdk/automation/arm-automation/src/models/runbookOperationsMappers.ts
  sdk/automation/arm-automation/src/models/scheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationMachineRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/statisticsOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/usagesMappers.ts
  sdk/automation/arm-automation/src/models/variableOperationsMappers.ts
  sdk/automation/arm-automation/src/models/watcherOperationsMappers.ts
  sdk/automation/arm-automation/src/models/webhookOperationsMappers.ts
  sdk/automation/arm-automation/src/operations/connectionTypeOperations.ts
Labels: RestPRMerged

#2753 [Service Bus] Include Copyright text in all the samples
  sdk/servicebus/service-bus/samples/browserSample.html
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/deferral.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/movingMessagesToDLQ.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/processMessageFromDLQ.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/sessionState.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/topicFilters.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/browseMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/interactiveLogin.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/loginWithAzureAccount.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/receiveMessagesLoop.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/receiveMessagesStreaming.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/scheduledMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/sendMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/servicePrincipalLogin.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/session.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/useProxy.js
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/deferral.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/movingMessagesToDLQ.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/processMessageFromDLQ.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/sessionState.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/browseMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/interactiveLogin.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/loginWithAzureAccount.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesLoop.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/scheduledMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/sendMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/servicePrincipalLogin.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/session.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/useProxy.ts
Labels: Client, Service Bus

#2754 [Event Hubs] Include Copyright text in all the samples
  sdk/eventhub/event-hubs/samples/getHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/interactiveLogin.ts
  sdk/eventhub/event-hubs/samples/iotGetHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/loginWithAzureAccount.ts
  sdk/eventhub/event-hubs/samples/receiveMessagesLoop.ts
  sdk/eventhub/event-hubs/samples/receiveMessagesStreaming.ts
  sdk/eventhub/event-hubs/samples/sendMessages.ts
  sdk/eventhub/event-hubs/samples/servicePrincipalLogin.ts
  sdk/eventhub/event-hubs/samples/useProxy.ts
Labels: Client, Event Hubs

#2698 [Service Bus] Perf tests - testing azure-sb receive
  sdk/servicebus/service-bus/test/perf/azure-sb-package/receive.ts
Labels: Client, Service Bus

#2697 [Service Bus] Perf tests - testing rhea-promise receive
  sdk/servicebus/service-bus/test/perf/rhea-promise/receive.ts
Labels: Client, Service Bus

#2771 [AutoPR cdn/resource-manager] make "name" optional in DeliveryRule
  sdk/cdn/arm-cdn/lib/models/index.ts
  sdk/cdn/arm-cdn/lib/models/mappers.ts
Labels: RestPRMerged

#2738 [Event Hubs] Update README as per template
  sdk/eventhub/event-hubs/README.md
Labels: Client, Event Hubs

#2776 [Event Hubs] [EPH] Remove .npmignore file
  sdk/eventhub/event-hubs/.npmignore
  sdk/eventhub/event-hubs/package.json
  sdk/eventhub/event-processor-host/.npmignore
  sdk/eventhub/event-processor-host/package.json
Labels: Client, Event Hubs

#2777 [Service Bus] Add sendBatch example in README
  sdk/eventhub/event-hubs/README.md
  sdk/servicebus/service-bus/README.md
Labels: Client, Event Hubs, Service Bus

#2709 [Event Hubs (EPH)] Standardize samples
  sdk/eventhub/event-processor-host/.vscode/launch.json
  sdk/eventhub/event-processor-host/samples/README.md
  sdk/eventhub/event-processor-host/samples/iothubEph.ts
  sdk/eventhub/event-processor-host/samples/multiEph.ts
  sdk/eventhub/event-processor-host/samples/sendBatch.ts
  sdk/eventhub/event-processor-host/samples/singleEph.ts
Labels: Client, Event Hubs

#2784 [AutoPR cdn/resource-manager] add premium_chinaCdn to CDN sku
  sdk/cdn/arm-cdn/lib/models/index.ts
Labels: RestPRMerged

#2728 [AutoPR applicationinsights/resource-manager] Update Application Insights Schema to support WorkItemConfig operations
  sdk/applicationinsights/arm-appinsights/LICENSE.txt
  sdk/applicationinsights/arm-appinsights/README.md
  sdk/applicationinsights/arm-appinsights/lib/applicationInsightsManagementClient.ts
  sdk/applicationinsights/arm-appinsights/lib/applicationInsightsManagementClientContext.ts
  sdk/applicationinsights/arm-appinsights/lib/models/aPIKeysMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/analyticsItemsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/annotationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/componentAvailableFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/componentCurrentBillingFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/componentFeatureCapabilitiesMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/componentQuotaStatusMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/componentsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/exportConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/favoritesMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/index.ts
  sdk/applicationinsights/arm-appinsights/lib/models/mappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/operationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/parameters.ts
  sdk/applicationinsights/arm-appinsights/lib/models/proactiveDetectionConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/webTestLocationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/webTestsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/workItemConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/models/workbooksMappers.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/aPIKeys.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/analyticsItems.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/annotations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/componentAvailableFeatures.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/componentCurrentBillingFeatures.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/componentFeatureCapabilities.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/componentQuotaStatus.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/components.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/exportConfigurations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/favorites.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/index.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/operations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/proactiveDetectionConfigurations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/webTestLocations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/webTests.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/workItemConfigurations.ts
  sdk/applicationinsights/arm-appinsights/lib/operations/workbooks.ts
  sdk/applicationinsights/arm-appinsights/package.json
  sdk/applicationinsights/arm-appinsights/rollup.config.js
  sdk/applicationinsights/arm-appinsights/tsconfig.json
Labels: RestPRMerged

#2789 [Event Hubs] [EPH] Add missing Contributing.md and License files
  sdk/eventhub/event-hubs/CONTRIBUTING.md
  sdk/eventhub/event-hubs/License
  sdk/eventhub/event-processor-host/CONTRIBUTING.md
  sdk/eventhub/event-processor-host/License
Labels: Client, Event Hubs

#2795 [Event Hubs] Update samples to pass the default consumer group in the options parameter
  sdk/eventhub/event-hubs/samples/interactiveLogin.ts
  sdk/eventhub/event-hubs/samples/loginWithAzureAccount.ts
  sdk/eventhub/event-hubs/samples/receiveEventsLoop.ts
  sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
  sdk/eventhub/event-hubs/samples/sendEvents.ts
  sdk/eventhub/event-hubs/samples/servicePrincipalLogin.ts
  sdk/eventhub/event-hubs/samples/useProxy.ts
Labels: Client, Event Hubs

#2803 [AutoPR web/resource-manager] Add location based deleted Web Apps
  sdk/appservice/arm-appservice/LICENSE.txt
  sdk/appservice/arm-appservice/README.md
  sdk/appservice/arm-appservice/package.json
  sdk/appservice/arm-appservice/rollup.config.js
  sdk/appservice/arm-appservice/src/models/appServiceCertificateOrdersMappers.ts
  sdk/appservice/arm-appservice/src/models/appServiceEnvironmentsMappers.ts
  sdk/appservice/arm-appservice/src/models/appServicePlansMappers.ts
  sdk/appservice/arm-appservice/src/models/certificateRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/certificatesMappers.ts
  sdk/appservice/arm-appservice/src/models/deletedWebAppsMappers.ts
  sdk/appservice/arm-appservice/src/models/diagnosticsMappers.ts
  sdk/appservice/arm-appservice/src/models/domainRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/domainsMappers.ts
  sdk/appservice/arm-appservice/src/models/index.ts
  sdk/appservice/arm-appservice/src/models/mappers.ts
  sdk/appservice/arm-appservice/src/models/parameters.ts
  sdk/appservice/arm-appservice/src/models/providerMappers.ts
  sdk/appservice/arm-appservice/src/models/recommendationsMappers.ts
  sdk/appservice/arm-appservice/src/models/resourceHealthMetadataOperationsMappers.ts
  sdk/appservice/arm-appservice/src/models/topLevelDomainsMappers.ts
  sdk/appservice/arm-appservice/src/models/webAppsMappers.ts
  sdk/appservice/arm-appservice/src/operations/appServiceCertificateOrders.ts
  sdk/appservice/arm-appservice/src/operations/appServiceEnvironments.ts
  sdk/appservice/arm-appservice/src/operations/appServicePlans.ts
  sdk/appservice/arm-appservice/src/operations/certificateRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/certificates.ts
  sdk/appservice/arm-appservice/src/operations/deletedWebApps.ts
  sdk/appservice/arm-appservice/src/operations/diagnostics.ts
  sdk/appservice/arm-appservice/src/operations/domainRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/domains.ts
  sdk/appservice/arm-appservice/src/operations/provider.ts
  sdk/appservice/arm-appservice/src/operations/recommendations.ts
  sdk/appservice/arm-appservice/src/operations/resourceHealthMetadataOperations.ts
  sdk/appservice/arm-appservice/src/operations/topLevelDomains.ts
  sdk/appservice/arm-appservice/src/operations/webApps.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClient.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClientContext.ts
Labels: RestPRMerged

#2864 [AutoPR analysisservices/resource-manager] Fix incorrect type of enablePowerBIService property
  sdk/analysisservices/arm-analysisservices/LICENSE.txt
  sdk/analysisservices/arm-analysisservices/README.md
  sdk/analysisservices/arm-analysisservices/package.json
  sdk/analysisservices/arm-analysisservices/rollup.config.js
  sdk/analysisservices/arm-analysisservices/src/analysisServicesManagementClientContext.ts
  sdk/analysisservices/arm-analysisservices/src/models/index.ts
  sdk/analysisservices/arm-analysisservices/src/models/mappers.ts
  sdk/analysisservices/arm-analysisservices/src/models/operationsMappers.ts
  sdk/analysisservices/arm-analysisservices/src/models/serversMappers.ts
  sdk/analysisservices/arm-analysisservices/src/operations/servers.ts
Labels: RestPRMerged

#2868 [AutoPR web/resource-manager] Add Source Web App Location
  sdk/appservice/arm-appservice/LICENSE.txt
  sdk/appservice/arm-appservice/README.md
  sdk/appservice/arm-appservice/package.json
  sdk/appservice/arm-appservice/rollup.config.js
  sdk/appservice/arm-appservice/src/models/appServiceCertificateOrdersMappers.ts
  sdk/appservice/arm-appservice/src/models/appServiceEnvironmentsMappers.ts
  sdk/appservice/arm-appservice/src/models/appServicePlansMappers.ts
  sdk/appservice/arm-appservice/src/models/certificateRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/certificatesMappers.ts
  sdk/appservice/arm-appservice/src/models/deletedWebAppsMappers.ts
  sdk/appservice/arm-appservice/src/models/diagnosticsMappers.ts
  sdk/appservice/arm-appservice/src/models/domainRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/domainsMappers.ts
  sdk/appservice/arm-appservice/src/models/index.ts
  sdk/appservice/arm-appservice/src/models/mappers.ts
  sdk/appservice/arm-appservice/src/models/parameters.ts
  sdk/appservice/arm-appservice/src/models/providerMappers.ts
  sdk/appservice/arm-appservice/src/models/recommendationsMappers.ts
  sdk/appservice/arm-appservice/src/models/resourceHealthMetadataOperationsMappers.ts
  sdk/appservice/arm-appservice/src/models/topLevelDomainsMappers.ts
  sdk/appservice/arm-appservice/src/models/webAppsMappers.ts
  sdk/appservice/arm-appservice/src/operations/appServiceCertificateOrders.ts
  sdk/appservice/arm-appservice/src/operations/appServiceEnvironments.ts
  sdk/appservice/arm-appservice/src/operations/appServicePlans.ts
  sdk/appservice/arm-appservice/src/operations/certificateRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/certificates.ts
  sdk/appservice/arm-appservice/src/operations/deletedWebApps.ts
  sdk/appservice/arm-appservice/src/operations/diagnostics.ts
  sdk/appservice/arm-appservice/src/operations/domainRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/domains.ts
  sdk/appservice/arm-appservice/src/operations/provider.ts
  sdk/appservice/arm-appservice/src/operations/recommendations.ts
  sdk/appservice/arm-appservice/src/operations/resourceHealthMetadataOperations.ts
  sdk/appservice/arm-appservice/src/operations/topLevelDomains.ts
  sdk/appservice/arm-appservice/src/operations/webApps.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClient.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClientContext.ts
Labels: RestPRMerged

#2880 [AutoPR web/resource-manager] Add Api-version 2018-11-01 for WebApps Collection
  sdk/appservice/arm-appservice/src/operations/webApps.ts
Labels: RestPRMerged

#2904 [AutoPR consumption/resource-manager] scope description changed for usagedetails and marketplace microsoft.consumption 2019 01 01
  sdk/consumption/arm-consumption/LICENSE.txt
  sdk/consumption/arm-consumption/README.md
  sdk/consumption/arm-consumption/package.json
  sdk/consumption/arm-consumption/rollup.config.js
  sdk/consumption/arm-consumption/src/consumptionManagementClient.ts
  sdk/consumption/arm-consumption/src/consumptionManagementClientContext.ts
  sdk/consumption/arm-consumption/src/models/aggregatedCostMappers.ts
  sdk/consumption/arm-consumption/src/models/balancesMappers.ts
  sdk/consumption/arm-consumption/src/models/budgetsMappers.ts
  sdk/consumption/arm-consumption/src/models/chargesMappers.ts
  sdk/consumption/arm-consumption/src/models/forecastsMappers.ts
  sdk/consumption/arm-consumption/src/models/index.ts
  sdk/consumption/arm-consumption/src/models/mappers.ts
  sdk/consumption/arm-consumption/src/models/marketplacesMappers.ts
  sdk/consumption/arm-consumption/src/models/operationsMappers.ts
  sdk/consumption/arm-consumption/src/models/parameters.ts
  sdk/consumption/arm-consumption/src/models/priceSheetMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationRecommendationsMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationsDetailsMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationsSummariesMappers.ts
  sdk/consumption/arm-consumption/src/models/tagsMappers.ts
  sdk/consumption/arm-consumption/src/models/usageDetailsMappers.ts
  sdk/consumption/arm-consumption/src/operations/budgets.ts
  sdk/consumption/arm-consumption/src/operations/charges.ts
  sdk/consumption/arm-consumption/src/operations/index.ts
  sdk/consumption/arm-consumption/src/operations/marketplaces.ts
  sdk/consumption/arm-consumption/src/operations/reservationRecommendations.ts
  sdk/consumption/arm-consumption/src/operations/tags.ts
  sdk/consumption/arm-consumption/src/operations/usageDetails.ts
Labels: RestPRMerged

#2902 [Event Hubs] Check if link exists before using them
  sdk/eventhub/event-hubs/src/eventHubSender.ts
Labels: Client, Event Hubs

#2926 [AutoPR batchai/resource-manager] chore: jsonfmt batchai
  sdk/batchai/arm-batchai/LICENSE.txt
  sdk/batchai/arm-batchai/README.md
  sdk/batchai/arm-batchai/package.json
  sdk/batchai/arm-batchai/rollup.config.js
  sdk/batchai/arm-batchai/src/batchAIManagementClientContext.ts
  sdk/batchai/arm-batchai/src/models/clustersMappers.ts
  sdk/batchai/arm-batchai/src/models/experimentsMappers.ts
  sdk/batchai/arm-batchai/src/models/fileServersMappers.ts
  sdk/batchai/arm-batchai/src/models/index.ts
  sdk/batchai/arm-batchai/src/models/jobsMappers.ts
  sdk/batchai/arm-batchai/src/models/mappers.ts
  sdk/batchai/arm-batchai/src/models/operationsMappers.ts
  sdk/batchai/arm-batchai/src/models/usagesMappers.ts
  sdk/batchai/arm-batchai/src/models/workspacesMappers.ts
Labels: RestPRMerged

#2922 [AutoPR applicationinsights/resource-manager] AppInsights new folder
  sdk/applicationinsights/arm-appinsights/LICENSE.txt
  sdk/applicationinsights/arm-appinsights/README.md
  sdk/applicationinsights/arm-appinsights/package.json
  sdk/applicationinsights/arm-appinsights/rollup.config.js
  sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClient.ts
  sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClientContext.ts
  sdk/applicationinsights/arm-appinsights/src/models/aPIKeysMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/analyticsItemsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/annotationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentAvailableFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentCurrentBillingFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentFeatureCapabilitiesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentQuotaStatusMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/exportConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/favoritesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/index.ts
  sdk/applicationinsights/arm-appinsights/src/models/mappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/operationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/parameters.ts
  sdk/applicationinsights/arm-appinsights/src/models/proactiveDetectionConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/webTestLocationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/webTestsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/workItemConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/workbooksMappers.ts
  sdk/applicationinsights/arm-appinsights/src/operations/aPIKeys.ts
  sdk/applicationinsights/arm-appinsights/src/operations/analyticsItems.ts
  sdk/applicationinsights/arm-appinsights/src/operations/annotations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentAvailableFeatures.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentCurrentBillingFeatures.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentFeatureCapabilities.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentQuotaStatus.ts
  sdk/applicationinsights/arm-appinsights/src/operations/components.ts
  sdk/applicationinsights/arm-appinsights/src/operations/exportConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/favorites.ts
  sdk/applicationinsights/arm-appinsights/src/operations/proactiveDetectionConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/webTestLocations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/webTests.ts
  sdk/applicationinsights/arm-appinsights/src/operations/workItemConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/workbooks.ts
Labels: RestPRMerged

#2947 [AutoPR relay/resource-manager] Relay new SDK folder for Python
  sdk/relay/arm-relay/LICENSE.txt
  sdk/relay/arm-relay/README.md
  sdk/relay/arm-relay/lib/models/hybridConnectionsMappers.ts
  sdk/relay/arm-relay/lib/models/index.ts
  sdk/relay/arm-relay/lib/models/mappers.ts
  sdk/relay/arm-relay/lib/models/namespacesMappers.ts
  sdk/relay/arm-relay/lib/models/operationsMappers.ts
  sdk/relay/arm-relay/lib/models/parameters.ts
  sdk/relay/arm-relay/lib/models/wCFRelaysMappers.ts
  sdk/relay/arm-relay/lib/operations/hybridConnections.ts
  sdk/relay/arm-relay/lib/operations/index.ts
  sdk/relay/arm-relay/lib/operations/namespaces.ts
  sdk/relay/arm-relay/lib/operations/operations.ts
  sdk/relay/arm-relay/lib/operations/wCFRelays.ts
  sdk/relay/arm-relay/lib/relayManagementClient.ts
  sdk/relay/arm-relay/lib/relayManagementClientContext.ts
  sdk/relay/arm-relay/package.json
  sdk/relay/arm-relay/rollup.config.js
  sdk/relay/arm-relay/tsconfig.json
Labels: RestPRMerged

#2949 [AutoPR consumption/resource-manager] Consumption Python new folder
  sdk/consumption/arm-consumption/LICENSE.txt
  sdk/consumption/arm-consumption/README.md
  sdk/consumption/arm-consumption/package.json
  sdk/consumption/arm-consumption/rollup.config.js
  sdk/consumption/arm-consumption/src/consumptionManagementClient.ts
  sdk/consumption/arm-consumption/src/consumptionManagementClientContext.ts
  sdk/consumption/arm-consumption/src/models/aggregatedCostMappers.ts
  sdk/consumption/arm-consumption/src/models/balancesMappers.ts
  sdk/consumption/arm-consumption/src/models/budgetsMappers.ts
  sdk/consumption/arm-consumption/src/models/chargesMappers.ts
  sdk/consumption/arm-consumption/src/models/forecastsMappers.ts
  sdk/consumption/arm-consumption/src/models/index.ts
  sdk/consumption/arm-consumption/src/models/mappers.ts
  sdk/consumption/arm-consumption/src/models/marketplacesMappers.ts
  sdk/consumption/arm-consumption/src/models/operationsMappers.ts
  sdk/consumption/arm-consumption/src/models/parameters.ts
  sdk/consumption/arm-consumption/src/models/priceSheetMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationRecommendationsMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationsDetailsMappers.ts
  sdk/consumption/arm-consumption/src/models/reservationsSummariesMappers.ts
  sdk/consumption/arm-consumption/src/models/tagsMappers.ts
  sdk/consumption/arm-consumption/src/models/usageDetailsMappers.ts
  sdk/consumption/arm-consumption/src/operations/budgets.ts
  sdk/consumption/arm-consumption/src/operations/charges.ts
  sdk/consumption/arm-consumption/src/operations/index.ts
  sdk/consumption/arm-consumption/src/operations/marketplaces.ts
  sdk/consumption/arm-consumption/src/operations/reservationRecommendations.ts
  sdk/consumption/arm-consumption/src/operations/tags.ts
  sdk/consumption/arm-consumption/src/operations/usageDetails.ts
Labels: RestPRMerged

#2940 [AutoPR commerce/resource-manager] chore: jsonfmt commerce
  sdk/commerce/arm-commerce/LICENSE.txt
  sdk/commerce/arm-commerce/README.md
  sdk/commerce/arm-commerce/package.json
  sdk/commerce/arm-commerce/src/models/index.ts
  sdk/commerce/arm-commerce/src/models/mappers.ts
  sdk/commerce/arm-commerce/src/models/rateCardMappers.ts
  sdk/commerce/arm-commerce/src/models/usageAggregatesMappers.ts
Labels: RestPRMerged

#2953 [AutoPR msi/resource-manager] New folder and version for MSI and Python
  sdk/msi/arm-msi/LICENSE.txt
  sdk/msi/arm-msi/README.md
  sdk/msi/arm-msi/package.json
  sdk/msi/arm-msi/rollup.config.js
  sdk/msi/arm-msi/src/managedServiceIdentityClientContext.ts
  sdk/msi/arm-msi/src/models/index.ts
  sdk/msi/arm-msi/src/models/mappers.ts
  sdk/msi/arm-msi/src/models/operationsMappers.ts
  sdk/msi/arm-msi/src/models/userAssignedIdentitiesMappers.ts
Labels: RestPRMerged

#2894 [Event Hubs] Update constant package info to come from package.json
  sdk/eventhub/event-hubs/package.json
  sdk/eventhub/event-hubs/src/util/constants.ts
  sdk/eventhub/event-hubs/tsconfig.json
Labels: Client, Event Hubs

#2960 [AutoPR hanaonazure/resource-manager] Added new SKUs
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
Labels: RestPRMerged

#2967 [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Remove optional `mode` parameter from CognitiveService OCR preview API for GA preparation
  sdk/cognitiveservices/cognitiveservices-computervision/package.json
  sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClient.ts
  sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
  sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
Labels: RestPRMerged

#2951 [AutoPR devspaces/resource-manager] Update DevSpaces 2019-04-01 swagger specs
  sdk/devspaces/arm-devspaces/LICENSE.txt
  sdk/devspaces/arm-devspaces/README.md
  sdk/devspaces/arm-devspaces/package.json
  sdk/devspaces/arm-devspaces/rollup.config.js
  sdk/devspaces/arm-devspaces/src/devSpacesManagementClient.ts
  sdk/devspaces/arm-devspaces/src/devSpacesManagementClientContext.ts
  sdk/devspaces/arm-devspaces/src/models/containerHostMappingsMappers.ts
  sdk/devspaces/arm-devspaces/src/models/controllersMappers.ts
  sdk/devspaces/arm-devspaces/src/models/index.ts
  sdk/devspaces/arm-devspaces/src/models/mappers.ts
  sdk/devspaces/arm-devspaces/src/models/operationsMappers.ts
  sdk/devspaces/arm-devspaces/src/models/parameters.ts
  sdk/devspaces/arm-devspaces/src/operations/containerHostMappings.ts
  sdk/devspaces/arm-devspaces/src/operations/controllers.ts
  sdk/devspaces/arm-devspaces/src/operations/index.ts
Labels: RestPRMerged

#2923 {Event Hubs] Error from message handler should surface up
  sdk/eventhub/event-hubs/README.md
  sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
  sdk/eventhub/event-hubs/src/eventHubReceiver.ts
  sdk/eventhub/event-hubs/test/receiver.spec.ts
Labels: Client, Event Hubs

#2935 [Service Bus] Update variable name(ns -> sbClient) in all the samples
  sdk/servicebus/service-bus/samples/browserSample.html
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/deferral.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/movingMessagesToDLQ.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/processMessageFromDLQ.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/sessionState.js
  sdk/servicebus/service-bus/samples/javascript/advancedFeatures/topicFilters.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/browseMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/interactiveLogin.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/loginWithAzureAccount.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/receiveMessagesLoop.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/receiveMessagesStreaming.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/scheduledMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/sendMessages.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/servicePrincipalLogin.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/session.js
  sdk/servicebus/service-bus/samples/javascript/gettingStarted/useProxy.js
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/deferral.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/movingMessagesToDLQ.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/processMessageFromDLQ.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/sessionState.ts
  sdk/servicebus/service-bus/samples/typescript/advancedFeatures/topicFilters.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/browseMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/interactiveLogin.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/loginWithAzureAccount.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesLoop.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/receiveMessagesStreaming.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/scheduledMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/sendMessages.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/servicePrincipalLogin.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/session.ts
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/useProxy.ts
Labels: Client, Service Bus

#2975 [AutoPR containerservice/resource-manager] chore: jsonfmt containerservice
  sdk/containerservice/arm-containerservice/src/models/agentPoolsMappers.ts
  sdk/containerservice/arm-containerservice/src/models/containerServicesMappers.ts
  sdk/containerservice/arm-containerservice/src/models/index.ts
  sdk/containerservice/arm-containerservice/src/models/managedClustersMappers.ts
  sdk/containerservice/arm-containerservice/src/models/mappers.ts
  sdk/containerservice/arm-containerservice/src/models/openShiftManagedClustersMappers.ts
  sdk/containerservice/arm-containerservice/src/models/parameters.ts
  sdk/containerservice/arm-containerservice/src/operations/agentPools.ts
  sdk/containerservice/arm-containerservice/src/operations/containerServices.ts
  sdk/containerservice/arm-containerservice/src/operations/managedClusters.ts
  sdk/containerservice/arm-containerservice/src/operations/operations.ts
Labels: RestPRMerged

#2908 [Storage] Make Aborter parameter optional - storage-file
  sdk/storage/storage-file/samples/typescript/advanced.ts
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-file/src/Aborter.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileClient.ts
  sdk/storage/storage-file/src/FileDownloadResponse.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/ShareClient.ts
  sdk/storage/storage-file/src/highlevel.browser.ts
  sdk/storage/storage-file/src/highlevel.common.ts
  sdk/storage/storage-file/src/highlevel.node.ts
  sdk/storage/storage-file/src/utils/RetriableReadableStream.ts
  sdk/storage/storage-file/test/aborter.spec.ts
  sdk/storage/storage-file/test/directoryclient.spec.ts
  sdk/storage/storage-file/test/fileclient.spec.ts
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
  sdk/storage/storage-file/test/node/fileclient.spec.ts
  sdk/storage/storage-file/test/node/highlevel.node.spec.ts
  sdk/storage/storage-file/test/node/sas.spec.ts
  sdk/storage/storage-file/test/node/shareclient.spec.ts
  sdk/storage/storage-file/test/node/sharedkeycredentialpolicy.spec.ts
  sdk/storage/storage-file/test/retrypolicy.spec.ts
  sdk/storage/storage-file/test/shareclient.spec.ts
  sdk/storage/storage-file/test/specialnaming.spec.ts
Labels: Client, Storage

#2966 [AutoPR mixedreality/resource-manager] Update of Mixed Reality Azure Resource Management
  sdk/mixedreality/arm-mixedreality/README.md
  sdk/mixedreality/arm-mixedreality/package.json
Labels: RestPRMerged

#2939 [AutoPR cdn/resource-manager] chore: jsonfmt cdn
  sdk/cdn/arm-cdn/README.md
  sdk/cdn/arm-cdn/package.json
  sdk/cdn/arm-cdn/src/cdnManagementClientContext.ts
  sdk/cdn/arm-cdn/src/models/customDomainsMappers.ts
  sdk/cdn/arm-cdn/src/models/edgeNodesMappers.ts
  sdk/cdn/arm-cdn/src/models/endpointsMappers.ts
  sdk/cdn/arm-cdn/src/models/index.ts
  sdk/cdn/arm-cdn/src/models/mappers.ts
  sdk/cdn/arm-cdn/src/models/originsMappers.ts
  sdk/cdn/arm-cdn/src/models/profilesMappers.ts
Labels: RestPRMerged

#2993 [AutoPR compute/resource-manager] Add an example json for using toBeDetached flag for data disks
  sdk/compute/arm-compute/src/models/index.ts
Labels: RestPRMerged

#3000 [AutoPR databricks/resource-manager] chore: jsonfmt databricks
  sdk/databricks/arm-databricks/LICENSE.txt
  sdk/databricks/arm-databricks/README.md
  sdk/databricks/arm-databricks/package.json
  sdk/databricks/arm-databricks/rollup.config.js
  sdk/databricks/arm-databricks/src/databricksClientContext.ts
  sdk/databricks/arm-databricks/src/models/index.ts
  sdk/databricks/arm-databricks/src/models/mappers.ts
  sdk/databricks/arm-databricks/src/models/operationsMappers.ts
  sdk/databricks/arm-databricks/src/models/workspacesMappers.ts
Labels: RestPRMerged

#3010 [AutoPR cosmos-db/resource-manager] added service name field in CosmosDb and created a Java readme
  sdk/cosmosdb/arm-cosmosdb/LICENSE.txt
  sdk/cosmosdb/arm-cosmosdb/README.md
  sdk/cosmosdb/arm-cosmosdb/package.json
  sdk/cosmosdb/arm-cosmosdb/rollup.config.js
  sdk/cosmosdb/arm-cosmosdb/src/cosmosDBManagementClientContext.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/collectionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/collectionPartitionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/collectionPartitionRegionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/collectionRegionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/databaseAccountRegionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/databaseAccountsMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/databaseMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/operationsMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/parameters.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/partitionKeyRangeIdMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/partitionKeyRangeIdRegionMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/percentileMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/percentileSourceTargetMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/percentileTargetMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/operations/collection.ts
  sdk/cosmosdb/arm-cosmosdb/src/operations/database.ts
  sdk/cosmosdb/arm-cosmosdb/src/operations/databaseAccounts.ts
Labels: RestPRMerged

#2978 [AutoPR eventgrid/resource-manager] EventGrid: Swagger for API Version 2019-06-01
  sdk/eventgrid/arm-eventgrid/package.json
  sdk/eventgrid/arm-eventgrid/src/eventGridManagementClientContext.ts
  sdk/eventgrid/arm-eventgrid/src/models/domainTopicsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/domainsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/eventSubscriptionsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/index.ts
  sdk/eventgrid/arm-eventgrid/src/models/mappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/parameters.ts
  sdk/eventgrid/arm-eventgrid/src/models/topicTypesMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/topicsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/operations/domainTopics.ts
  sdk/eventgrid/arm-eventgrid/src/operations/domains.ts
  sdk/eventgrid/arm-eventgrid/src/operations/eventSubscriptions.ts
  sdk/eventgrid/arm-eventgrid/src/operations/operations.ts
  sdk/eventgrid/arm-eventgrid/src/operations/topicTypes.ts
  sdk/eventgrid/arm-eventgrid/src/operations/topics.ts
Labels: RestPRMerged

#3001 [AutoPR datacatalog/resource-manager] chore: jsonfmt datacatalog
  sdk/datacatalog/arm-datacatalog/LICENSE.txt
  sdk/datacatalog/arm-datacatalog/README.md
  sdk/datacatalog/arm-datacatalog/package.json
  sdk/datacatalog/arm-datacatalog/rollup.config.js
  sdk/datacatalog/arm-datacatalog/src/dataCatalogRestClient.ts
  sdk/datacatalog/arm-datacatalog/src/dataCatalogRestClientContext.ts
  sdk/datacatalog/arm-datacatalog/src/models/aDCCatalogsMappers.ts
  sdk/datacatalog/arm-datacatalog/src/models/aDCOperationsMappers.ts
  sdk/datacatalog/arm-datacatalog/src/models/index.ts
  sdk/datacatalog/arm-datacatalog/src/models/mappers.ts
Labels: RestPRMerged

#3018 [AutoPR monitor/resource-manager] [Hub Generated] Review request for Microsoft.Insights to add version stable/2018-09-01
  sdk/monitor/arm-monitor/package.json
  sdk/monitor/arm-monitor/src/models/actionGroupsMappers.ts
  sdk/monitor/arm-monitor/src/models/activityLogAlertsMappers.ts
  sdk/monitor/arm-monitor/src/models/alertRulesMappers.ts
  sdk/monitor/arm-monitor/src/models/autoscaleSettingsMappers.ts
  sdk/monitor/arm-monitor/src/models/baselinesMappers.ts
  sdk/monitor/arm-monitor/src/models/diagnosticSettingsCategoryOperationsMappers.ts
  sdk/monitor/arm-monitor/src/models/diagnosticSettingsOperationsMappers.ts
  sdk/monitor/arm-monitor/src/models/index.ts
  sdk/monitor/arm-monitor/src/models/logProfilesMappers.ts
  sdk/monitor/arm-monitor/src/models/mappers.ts
  sdk/monitor/arm-monitor/src/models/metricAlertsMappers.ts
  sdk/monitor/arm-monitor/src/models/scheduledQueryRulesMappers.ts
  sdk/monitor/arm-monitor/src/models/vMInsightsMappers.ts
  sdk/monitor/arm-monitor/src/monitorManagementClient.ts
  sdk/monitor/arm-monitor/src/operations/baselines.ts
  sdk/monitor/arm-monitor/src/operations/index.ts
Labels: RestPRMerged

#2997 [Event Hubs] Allow users to configure retry options in send requests
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/src/eventHubSender.ts
Labels: Client, Event Hubs

#2985 [AutoPR cognitiveservices/resource-manager] Add NetworkRuleSet Support.
  sdk/cognitiveservices/arm-cognitiveservices/src/models/accountsMappers.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/models/index.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/models/mappers.ts
Labels: RestPRMerged

#3038 [AutoPR eventgrid/data-plane] EventGrid dataplane SDK folder
  sdk/eventgrid/eventgrid/LICENSE.txt
  sdk/eventgrid/eventgrid/README.md
  sdk/eventgrid/eventgrid/package.json
  sdk/eventgrid/eventgrid/rollup.config.js
  sdk/eventgrid/eventgrid/src/eventGridClient.ts
  sdk/eventgrid/eventgrid/src/eventGridClientContext.ts
  sdk/eventgrid/eventgrid/src/models/index.ts
  sdk/eventgrid/eventgrid/src/models/mappers.ts
Labels: RestPRMerged

#3050 [AutoPR eventgrid/data-plane] Add new Event Grid event type for SignalR Service
  sdk/eventgrid/eventgrid/src/models/index.ts
  sdk/eventgrid/eventgrid/src/models/mappers.ts
Labels: RestPRMerged

#2930 [Storage] Update aborter.none changes in readme - storage-blob
  sdk/storage/storage-blob/README.md
Labels: Client, Storage

#3069 [AutoPR devtestlabs/resource-manager] chore: jsonfmt devtestlabls
  sdk/devtestlabs/arm-devtestlabs/README.md
  sdk/devtestlabs/arm-devtestlabs/package.json
  sdk/devtestlabs/arm-devtestlabs/src/devTestLabsClientContext.ts
Labels: RestPRMerged

#3065 [AutoPR mysql/resource-manager] MySQL intelligent performance APIs
  sdk/mysql/arm-mysql/LICENSE.txt
  sdk/mysql/arm-mysql/README.md
  sdk/mysql/arm-mysql/lib/models/checkNameAvailabilityMappers.ts
  sdk/mysql/arm-mysql/lib/models/configurationsMappers.ts
  sdk/mysql/arm-mysql/lib/models/databasesMappers.ts
  sdk/mysql/arm-mysql/lib/models/firewallRulesMappers.ts
  sdk/mysql/arm-mysql/lib/models/index.ts
  sdk/mysql/arm-mysql/lib/models/locationBasedPerformanceTierMappers.ts
  sdk/mysql/arm-mysql/lib/models/logFilesMappers.ts
  sdk/mysql/arm-mysql/lib/models/mappers.ts
  sdk/mysql/arm-mysql/lib/models/operationsMappers.ts
  sdk/mysql/arm-mysql/lib/models/parameters.ts
  sdk/mysql/arm-mysql/lib/models/replicasMappers.ts
  sdk/mysql/arm-mysql/lib/models/serverSecurityAlertPoliciesMappers.ts
  sdk/mysql/arm-mysql/lib/models/serversMappers.ts
  sdk/mysql/arm-mysql/lib/models/virtualNetworkRulesMappers.ts
  sdk/mysql/arm-mysql/lib/mySQLManagementClient.ts
  sdk/mysql/arm-mysql/lib/mySQLManagementClientContext.ts
  sdk/mysql/arm-mysql/lib/operations/checkNameAvailability.ts
  sdk/mysql/arm-mysql/lib/operations/configurations.ts
  sdk/mysql/arm-mysql/lib/operations/databases.ts
  sdk/mysql/arm-mysql/lib/operations/firewallRules.ts
  sdk/mysql/arm-mysql/lib/operations/index.ts
  sdk/mysql/arm-mysql/lib/operations/locationBasedPerformanceTier.ts
  sdk/mysql/arm-mysql/lib/operations/logFiles.ts
  sdk/mysql/arm-mysql/lib/operations/operations.ts
  sdk/mysql/arm-mysql/lib/operations/replicas.ts
  sdk/mysql/arm-mysql/lib/operations/serverSecurityAlertPolicies.ts
  sdk/mysql/arm-mysql/lib/operations/servers.ts
  sdk/mysql/arm-mysql/lib/operations/virtualNetworkRules.ts
  sdk/mysql/arm-mysql/package.json
  sdk/mysql/arm-mysql/rollup.config.js
  sdk/mysql/arm-mysql/tsconfig.json
Labels: RestPRMerged

#3071 [AutoPR recoveryservicesbackup/resource-manager] recoveryservicesbackup new Python path
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/LICENSE.txt
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/README.md
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/package.json
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/rollup.config.js
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupEnginesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupJobsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupOperationStatusesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupPoliciesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectableItemsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectedItemsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectionContainersMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupProtectionIntentMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupResourceStorageConfigsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupResourceVaultConfigsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupStatusMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupUsageSummariesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupWorkloadItemsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/backupsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/exportJobsOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/featureSupportMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/index.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/itemLevelRecoveryConnectionsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/jobCancellationsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/jobDetailsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/jobOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/jobsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/mappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/operationMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/operationsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectableContainersMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectedItemOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectedItemOperationStatusesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectedItemsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionContainerOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionContainerRefreshOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionContainersMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionIntentOperationsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionPoliciesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionPolicyOperationResultsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/protectionPolicyOperationStatusesMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/recoveryPointsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/restoresMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/models/securityPINsMappers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/operations/backupResourceStorageConfigs.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/operations/jobDetails.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/operations/protectableContainers.ts
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/src/recoveryServicesBackupClientContext.ts
Labels: RestPRMerged

#3078 [AutoPR signalr/resource-manager] Change SDK folder
  sdk/signalr/arm-signalr/LICENSE.txt
  sdk/signalr/arm-signalr/README.md
  sdk/signalr/arm-signalr/lib/models/index.ts
  sdk/signalr/arm-signalr/lib/models/mappers.ts
  sdk/signalr/arm-signalr/lib/models/operationsMappers.ts
  sdk/signalr/arm-signalr/lib/models/parameters.ts
  sdk/signalr/arm-signalr/lib/models/signalRMappers.ts
  sdk/signalr/arm-signalr/lib/models/usagesMappers.ts
  sdk/signalr/arm-signalr/lib/operations/index.ts
  sdk/signalr/arm-signalr/lib/operations/operations.ts
  sdk/signalr/arm-signalr/lib/operations/signalR.ts
  sdk/signalr/arm-signalr/lib/operations/usages.ts
  sdk/signalr/arm-signalr/lib/signalRManagementClient.ts
  sdk/signalr/arm-signalr/lib/signalRManagementClientContext.ts
  sdk/signalr/arm-signalr/package.json
  sdk/signalr/arm-signalr/rollup.config.js
  sdk/signalr/arm-signalr/tsconfig.json
Labels: RestPRMerged

#3093 [AutoPR containerservice/resource-manager] set hard limit on resourceName for AKS managed cluster.
  sdk/containerservice/arm-containerservice/src/models/agentPoolsMappers.ts
  sdk/containerservice/arm-containerservice/src/models/containerServicesMappers.ts
  sdk/containerservice/arm-containerservice/src/models/index.ts
  sdk/containerservice/arm-containerservice/src/models/managedClustersMappers.ts
  sdk/containerservice/arm-containerservice/src/models/mappers.ts
  sdk/containerservice/arm-containerservice/src/models/openShiftManagedClustersMappers.ts
  sdk/containerservice/arm-containerservice/src/models/parameters.ts
  sdk/containerservice/arm-containerservice/src/operations/agentPools.ts
  sdk/containerservice/arm-containerservice/src/operations/containerServices.ts
  sdk/containerservice/arm-containerservice/src/operations/managedClusters.ts
  sdk/containerservice/arm-containerservice/src/operations/openShiftManagedClusters.ts
  sdk/containerservice/arm-containerservice/src/operations/operations.ts
Labels: RestPRMerged

#3095 [AutoPR subscription/resource-manager] Subscription new Py path
  sdk/subscription/arm-subscriptions/LICENSE.txt
  sdk/subscription/arm-subscriptions/README.md
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/rollup.config.js
  sdk/subscription/arm-subscriptions/src/models/index.ts
  sdk/subscription/arm-subscriptions/src/models/mappers.ts
  sdk/subscription/arm-subscriptions/src/models/operationsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/parameters.ts
  sdk/subscription/arm-subscriptions/src/models/subscriptionsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/tenantsMappers.ts
  sdk/subscription/arm-subscriptions/src/operations/index.ts
  sdk/subscription/arm-subscriptions/src/operations/subscriptions.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClient.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClientContext.ts
Labels: RestPRMerged

#3044 [Event Hubs] Allow users to configure retry options in apis using the $management link
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/src/managementClient.ts
Labels: Client, Event Hubs

#3106 [AutoPR edgegateway/resource-manager] chore: jsonfmt edgegateway
  sdk/edgegateway/arm-edgegateway/package.json
Labels: RestPRMerged

#3122 [AutoPR machinelearningcompute/resource-manager] ML Compute Python path
  sdk/machinelearningcompute/arm-machinelearningcompute/LICENSE.txt
  sdk/machinelearningcompute/arm-machinelearningcompute/README.md
  sdk/machinelearningcompute/arm-machinelearningcompute/package.json
  sdk/machinelearningcompute/arm-machinelearningcompute/rollup.config.js
  sdk/machinelearningcompute/arm-machinelearningcompute/src/machineLearningComputeManagementClientContext.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/index.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/machineLearningComputeMappers.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/mappers.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/operationalizationClustersMappers.ts
Labels: RestPRMerged

#3124 [AutoPR containerinstance/resource-manager] chore: jsonfmt containerinstance
  containerinstance/arm-containerinstance/LICENSE.txt
  containerinstance/arm-containerinstance/README.md
  containerinstance/arm-containerinstance/package.json
  containerinstance/arm-containerinstance/rollup.config.js
  containerinstance/arm-containerinstance/src/containerInstanceManagementClient.ts
  containerinstance/arm-containerinstance/src/containerInstanceManagementClientContext.ts
  containerinstance/arm-containerinstance/src/models/containerGroupUsageMappers.ts
  containerinstance/arm-containerinstance/src/models/containerGroupsMappers.ts
  containerinstance/arm-containerinstance/src/models/containerOperationsMappers.ts
  containerinstance/arm-containerinstance/src/models/index.ts
  containerinstance/arm-containerinstance/src/models/mappers.ts
  containerinstance/arm-containerinstance/src/models/operationsMappers.ts
  containerinstance/arm-containerinstance/src/models/parameters.ts
  containerinstance/arm-containerinstance/src/models/serviceAssociationLinkMappers.ts
  containerinstance/arm-containerinstance/src/operations/containerGroupUsage.ts
  containerinstance/arm-containerinstance/src/operations/containerGroups.ts
  containerinstance/arm-containerinstance/src/operations/containerOperations.ts
  containerinstance/arm-containerinstance/src/operations/index.ts
  containerinstance/arm-containerinstance/src/operations/operations.ts
  containerinstance/arm-containerinstance/src/operations/serviceAssociationLink.ts
  containerinstance/arm-containerinstance/tsconfig.json
Labels: RestPRMerged

#3129 [AutoPR eventgrid/resource-manager] Move EventGrid to new Py folder
  sdk/eventgrid/arm-eventgrid/package.json
  sdk/eventgrid/arm-eventgrid/src/eventGridManagementClientContext.ts
  sdk/eventgrid/arm-eventgrid/src/models/domainTopicsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/domainsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/eventSubscriptionsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/index.ts
  sdk/eventgrid/arm-eventgrid/src/models/mappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/parameters.ts
  sdk/eventgrid/arm-eventgrid/src/models/topicTypesMappers.ts
  sdk/eventgrid/arm-eventgrid/src/models/topicsMappers.ts
  sdk/eventgrid/arm-eventgrid/src/operations/domainTopics.ts
  sdk/eventgrid/arm-eventgrid/src/operations/domains.ts
  sdk/eventgrid/arm-eventgrid/src/operations/eventSubscriptions.ts
  sdk/eventgrid/arm-eventgrid/src/operations/operations.ts
  sdk/eventgrid/arm-eventgrid/src/operations/topicTypes.ts
  sdk/eventgrid/arm-eventgrid/src/operations/topics.ts
Labels: RestPRMerged

#3144 [AutoPR hanaonazure/resource-manager] chore: jsonfmt hanaonazure
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
Labels: RestPRMerged

#3153 [AutoPR resources/resource-manager] ARM new Py Path
  sdk/features/arm-features/LICENSE.txt
  sdk/features/arm-features/README.md
  sdk/features/arm-features/package.json
  sdk/features/arm-features/src/models/featuresMappers.ts
  sdk/features/arm-features/src/models/index.ts
  sdk/features/arm-features/src/models/mappers.ts
  sdk/links/arm-links/LICENSE.txt
  sdk/links/arm-links/README.md
  sdk/links/arm-links/package.json
  sdk/links/arm-links/src/models/index.ts
  sdk/links/arm-links/src/models/mappers.ts
  sdk/links/arm-links/src/models/operationsMappers.ts
  sdk/links/arm-links/src/models/resourceLinksMappers.ts
  sdk/locks/arm-locks/LICENSE.txt
  sdk/locks/arm-locks/README.md
  sdk/locks/arm-locks/package.json
  sdk/locks/arm-locks/src/models/authorizationOperationsMappers.ts
  sdk/locks/arm-locks/src/models/index.ts
  sdk/locks/arm-locks/src/models/managementLocksMappers.ts
  sdk/locks/arm-locks/src/models/mappers.ts
  sdk/locks/arm-locks/src/operations/managementLocks.ts
  sdk/managedapplications/arm-managedapplications/LICENSE.txt
  sdk/managedapplications/arm-managedapplications/README.md
  sdk/managedapplications/arm-managedapplications/package.json
  sdk/managedapplications/arm-managedapplications/src/models/applianceDefinitionsMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/appliancesMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/index.ts
  sdk/managedapplications/arm-managedapplications/src/models/mappers.ts
  sdk/policy/arm-policy/LICENSE.txt
  sdk/policy/arm-policy/README.md
  sdk/policy/arm-policy/package.json
  sdk/policy/arm-policy/src/models/index.ts
  sdk/policy/arm-policy/src/models/mappers.ts
  sdk/policy/arm-policy/src/models/policyAssignmentsMappers.ts
  sdk/policy/arm-policy/src/models/policyDefinitionsMappers.ts
  sdk/policy/arm-policy/src/models/policySetDefinitionsMappers.ts
  sdk/resources/arm-resources/LICENSE.txt
  sdk/resources/arm-resources/README.md
  sdk/resources/arm-resources/package.json
  sdk/resources/arm-resources/src/models/deploymentOperationsMappers.ts
  sdk/resources/arm-resources/src/models/deploymentsMappers.ts
  sdk/resources/arm-resources/src/models/index.ts
  sdk/resources/arm-resources/src/models/mappers.ts
  sdk/resources/arm-resources/src/models/operationsMappers.ts
  sdk/resources/arm-resources/src/models/providersMappers.ts
  sdk/resources/arm-resources/src/models/resourceGroupsMappers.ts
  sdk/resources/arm-resources/src/models/resourcesMappers.ts
  sdk/resources/arm-resources/src/models/tagsMappers.ts
Labels: RestPRMerged

#3158 [AutoPR machinelearningservices/resource-manager] Adding usage id property to support usages by VM family, Workspace & Compute
  sdk/machinelearningservices/arm-machinelearningservices/LICENSE.txt
  sdk/machinelearningservices/arm-machinelearningservices/README.md
  sdk/machinelearningservices/arm-machinelearningservices/package.json
  sdk/machinelearningservices/arm-machinelearningservices/rollup.config.js
  sdk/machinelearningservices/arm-machinelearningservices/src/azureMachineLearningWorkspacesContext.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/index.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/machineLearningComputeMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/mappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/operationsMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/workspacesMappers.ts
Labels: RestPRMerged

#3166 [AutoPR hanaonazure/resource-manager] Add Create HanaInstance API
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
  sdk/hanaonazure/arm-hanaonazure/src/operations/hanaInstances.ts
Labels: RestPRMerged

#3182 [Event Hubs] Improve EventPosition class
  sdk/eventhub/event-hubs/src/eventHubReceiver.ts
  sdk/eventhub/event-hubs/src/eventPosition.ts
  sdk/eventhub/event-hubs/src/util/utils.ts
Labels: Client, Event Hubs

#3186 [AutoPR subscription/resource-manager] Make subscription a method parameter
  sdk/subscription/arm-subscriptions/LICENSE.txt
  sdk/subscription/arm-subscriptions/README.md
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/rollup.config.js
  sdk/subscription/arm-subscriptions/src/models/index.ts
  sdk/subscription/arm-subscriptions/src/models/mappers.ts
  sdk/subscription/arm-subscriptions/src/models/operationsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/parameters.ts
  sdk/subscription/arm-subscriptions/src/models/subscriptionsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/tenantsMappers.ts
  sdk/subscription/arm-subscriptions/src/operations/index.ts
  sdk/subscription/arm-subscriptions/src/operations/subscriptions.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClient.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClientContext.ts
Labels: RestPRMerged

#3193 [AutoPR search/resource-manager] Search new py path
  sdk/search/arm-search/LICENSE.txt
  sdk/search/arm-search/README.md
  sdk/search/arm-search/package.json
  sdk/search/arm-search/rollup.config.js
  sdk/search/arm-search/src/models/adminKeysMappers.ts
  sdk/search/arm-search/src/models/index.ts
  sdk/search/arm-search/src/models/mappers.ts
  sdk/search/arm-search/src/models/operationsMappers.ts
  sdk/search/arm-search/src/models/queryKeysMappers.ts
  sdk/search/arm-search/src/models/servicesMappers.ts
  sdk/search/arm-search/src/operations/services.ts
  sdk/search/arm-search/src/searchManagementClientContext.ts
Labels: RestPRMerged

#3198 [AutoPR mariadb/resource-manager] MariaDB intelligent performance
  sdk/mariadb/arm-mariadb/README.md
  sdk/mariadb/arm-mariadb/package.json
  sdk/mariadb/arm-mariadb/src/models/index.ts
  sdk/mariadb/arm-mariadb/src/models/mappers.ts
Labels: RestPRMerged

#3201 [AutoPR web/resource-manager] Web new path
  sdk/appservice/arm-appservice/LICENSE.txt
  sdk/appservice/arm-appservice/README.md
  sdk/appservice/arm-appservice/package.json
  sdk/appservice/arm-appservice/rollup.config.js
  sdk/appservice/arm-appservice/src/models/appServiceCertificateOrdersMappers.ts
  sdk/appservice/arm-appservice/src/models/appServiceEnvironmentsMappers.ts
  sdk/appservice/arm-appservice/src/models/appServicePlansMappers.ts
  sdk/appservice/arm-appservice/src/models/certificateRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/certificatesMappers.ts
  sdk/appservice/arm-appservice/src/models/deletedWebAppsMappers.ts
  sdk/appservice/arm-appservice/src/models/diagnosticsMappers.ts
  sdk/appservice/arm-appservice/src/models/domainRegistrationProviderMappers.ts
  sdk/appservice/arm-appservice/src/models/domainsMappers.ts
  sdk/appservice/arm-appservice/src/models/index.ts
  sdk/appservice/arm-appservice/src/models/mappers.ts
  sdk/appservice/arm-appservice/src/models/parameters.ts
  sdk/appservice/arm-appservice/src/models/providerMappers.ts
  sdk/appservice/arm-appservice/src/models/recommendationsMappers.ts
  sdk/appservice/arm-appservice/src/models/resourceHealthMetadataOperationsMappers.ts
  sdk/appservice/arm-appservice/src/models/topLevelDomainsMappers.ts
  sdk/appservice/arm-appservice/src/models/webAppsMappers.ts
  sdk/appservice/arm-appservice/src/operations/appServiceCertificateOrders.ts
  sdk/appservice/arm-appservice/src/operations/appServiceEnvironments.ts
  sdk/appservice/arm-appservice/src/operations/appServicePlans.ts
  sdk/appservice/arm-appservice/src/operations/certificateRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/certificates.ts
  sdk/appservice/arm-appservice/src/operations/deletedWebApps.ts
  sdk/appservice/arm-appservice/src/operations/diagnostics.ts
  sdk/appservice/arm-appservice/src/operations/domainRegistrationProvider.ts
  sdk/appservice/arm-appservice/src/operations/domains.ts
  sdk/appservice/arm-appservice/src/operations/provider.ts
  sdk/appservice/arm-appservice/src/operations/recommendations.ts
  sdk/appservice/arm-appservice/src/operations/resourceHealthMetadataOperations.ts
  sdk/appservice/arm-appservice/src/operations/topLevelDomains.ts
  sdk/appservice/arm-appservice/src/operations/webApps.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClient.ts
  sdk/appservice/arm-appservice/src/webSiteManagementClientContext.ts
Labels: RestPRMerged

#2812 [Storage] Update telemetry string - storage packages
  sdk/storage/storage-blob/src/TelemetryPolicyFactory.ts
  sdk/storage/storage-file/src/TelemetryPolicyFactory.ts
  sdk/storage/storage-queue/src/TelemetryPolicyFactory.ts
Labels: Client, Storage

#3211 [AutoPR iotspaces/resource-manager] chore: jsonfmt iotspaces
  sdk/iotspaces/arm-iotspaces/LICENSE.txt
  sdk/iotspaces/arm-iotspaces/README.md
  sdk/iotspaces/arm-iotspaces/package.json
  sdk/iotspaces/arm-iotspaces/rollup.config.js
  sdk/iotspaces/arm-iotspaces/src/ioTSpacesClientContext.ts
  sdk/iotspaces/arm-iotspaces/src/models/index.ts
  sdk/iotspaces/arm-iotspaces/src/models/ioTSpacesMappers.ts
  sdk/iotspaces/arm-iotspaces/src/models/mappers.ts
  sdk/iotspaces/arm-iotspaces/src/models/operationsMappers.ts
Labels: RestPRMerged

#3226 [AutoPR dns/resource-manager] chore: jsonfmt dns
  sdk/dns/arm-dns/LICENSE.txt
  sdk/dns/arm-dns/README.md
  sdk/dns/arm-dns/package.json
  sdk/dns/arm-dns/rollup.config.js
  sdk/dns/arm-dns/src/dnsManagementClientContext.ts
  sdk/dns/arm-dns/src/models/dnsResourceReferenceOperationsMappers.ts
  sdk/dns/arm-dns/src/models/index.ts
  sdk/dns/arm-dns/src/models/mappers.ts
  sdk/dns/arm-dns/src/models/recordSetsMappers.ts
  sdk/dns/arm-dns/src/models/zonesMappers.ts
Labels: RestPRMerged

#3209 [Event Hubs] Create one AMQP sender link per Sender
  sdk/eventhub/event-hubs/samples/sendEvents.ts
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/src/eventHubSender.ts
  sdk/eventhub/event-hubs/src/sender.ts
  sdk/eventhub/event-hubs/src/util/error.ts
  sdk/eventhub/event-hubs/test/sender.spec.ts
Labels: Client, Event Hubs

#3243 [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Fix bugs in OCR swagger file
  sdk/cognitiveservices/cognitiveservices-computervision/package.json
  sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClient.ts
  sdk/cognitiveservices/cognitiveservices-computervision/src/computerVisionClientContext.ts
  sdk/cognitiveservices/cognitiveservices-computervision/src/models/index.ts
  sdk/cognitiveservices/cognitiveservices-computervision/src/models/mappers.ts
Labels: RestPRMerged

#3250 [AutoPR mediaservices/resource-manager] [Hub Generated] Review request for Microsoft.Media to add version stable/2018-07-01
  sdk/mediaservices/arm-mediaservices/lib/azureMediaServices.ts
  sdk/mediaservices/arm-mediaservices/lib/azureMediaServicesContext.ts
  sdk/mediaservices/arm-mediaservices/lib/models/accountFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/assetFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/assetsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/contentKeyPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/index.ts
  sdk/mediaservices/arm-mediaservices/lib/models/jobsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/liveEventsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/liveOutputsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/locationsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/mappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/mediaservicesMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/operationsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/parameters.ts
  sdk/mediaservices/arm-mediaservices/lib/models/streamingEndpointsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/streamingLocatorsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/streamingPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/models/transformsMappers.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/accountFilters.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/assetFilters.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/assets.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/contentKeyPolicies.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/index.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/jobs.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/liveEvents.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/liveOutputs.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/locations.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/mediaservices.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/operations.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/streamingEndpoints.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/streamingLocators.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/streamingPolicies.ts
  sdk/mediaservices/arm-mediaservices/lib/operations/transforms.ts
  sdk/mediaservices/arm-mediaservices/package.json
  sdk/mediaservices/arm-mediaservices/tsconfig.json
Labels: RestPRMerged

#3234 [AutoPR batch/data-plane] Updated spec path
  sdk/batch/batch/src/batchServiceClient.ts
Labels: RestPRMerged

#3257 [AutoPR cosmos-db/resource-manager] CosmosDB add Availability Zone option for locations
  sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts
Labels: RestPRMerged

#3258 [AutoPR automation/resource-manager] Adding support for minute schedule
  sdk/automation/arm-automation/LICENSE.txt
  sdk/automation/arm-automation/README.md
  sdk/automation/arm-automation/package.json
  sdk/automation/arm-automation/rollup.config.js
  sdk/automation/arm-automation/src/automationClient.ts
  sdk/automation/arm-automation/src/automationClientContext.ts
  sdk/automation/arm-automation/src/models/activityOperationsMappers.ts
  sdk/automation/arm-automation/src/models/agentRegistrationInformationMappers.ts
  sdk/automation/arm-automation/src/models/automationAccountOperationsMappers.ts
  sdk/automation/arm-automation/src/models/certificateOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionTypeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/credentialOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobStreamMappers.ts
  sdk/automation/arm-automation/src/models/dscConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/fieldsMappers.ts
  sdk/automation/arm-automation/src/models/hybridRunbookWorkerGroupOperationsMappers.ts
  sdk/automation/arm-automation/src/models/index.ts
  sdk/automation/arm-automation/src/models/jobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobScheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobStreamOperationsMappers.ts
  sdk/automation/arm-automation/src/models/keysMappers.ts
  sdk/automation/arm-automation/src/models/linkedWorkspaceOperationsMappers.ts
  sdk/automation/arm-automation/src/models/mappers.ts
  sdk/automation/arm-automation/src/models/moduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/nodeCountInformationMappers.ts
  sdk/automation/arm-automation/src/models/nodeReportsMappers.ts
  sdk/automation/arm-automation/src/models/objectDataTypesMappers.ts
  sdk/automation/arm-automation/src/models/operationsMappers.ts
  sdk/automation/arm-automation/src/models/python2PackageMappers.ts
  sdk/automation/arm-automation/src/models/runbookDraftOperationsMappers.ts
  sdk/automation/arm-automation/src/models/runbookOperationsMappers.ts
  sdk/automation/arm-automation/src/models/scheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationMachineRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/statisticsOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/usagesMappers.ts
  sdk/automation/arm-automation/src/models/variableOperationsMappers.ts
  sdk/automation/arm-automation/src/models/watcherOperationsMappers.ts
  sdk/automation/arm-automation/src/models/webhookOperationsMappers.ts
  sdk/automation/arm-automation/src/operations/connectionTypeOperations.ts
  sdk/automation/arm-automation/src/operations/nodeCountInformation.ts
Labels: RestPRMerged

#3267 [AutoPR signalr/resource-manager] Add a new field to SignalR Resource property
  sdk/signalr/arm-signalr/LICENSE.txt
  sdk/signalr/arm-signalr/README.md
  sdk/signalr/arm-signalr/package.json
  sdk/signalr/arm-signalr/rollup.config.js
  sdk/signalr/arm-signalr/src/models/index.ts
  sdk/signalr/arm-signalr/src/models/mappers.ts
  sdk/signalr/arm-signalr/src/models/operationsMappers.ts
  sdk/signalr/arm-signalr/src/models/signalRMappers.ts
  sdk/signalr/arm-signalr/src/models/usagesMappers.ts
  sdk/signalr/arm-signalr/src/operations/signalR.ts
  sdk/signalr/arm-signalr/src/signalRManagementClientContext.ts
Labels: RestPRMerged

#3271 [AutoPR hanaonazure/resource-manager] Microsoft.HanaOnAzure: Add Delete HanaInstance API
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
  sdk/hanaonazure/arm-hanaonazure/src/operations/hanaInstances.ts
Labels: RestPRMerged

#3292 [AutoPR machinelearningexperimentation/resource-manager] chore: jsonfmt machinelearningexperimentation
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/LICENSE.txt
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/README.md
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/package.json
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/rollup.config.js
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/mLTeamAccountManagementClientContext.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/accountsMappers.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/index.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/mappers.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/operationsMappers.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/projectsMappers.ts
  sdk/machinelearningexperimentation/arm-machinelearningexperimentation/src/models/workspacesMappers.ts
Labels: RestPRMerged

#3281 [Storage] Fix storage-blob samples as per the api updates
  sdk/storage/storage-blob/samples/javascript/advanced.js
  sdk/storage/storage-blob/samples/javascript/basic.js
  sdk/storage/storage-blob/samples/typescript/advanced.ts
  sdk/storage/storage-blob/samples/typescript/basic.ts
Labels: Client, Storage

#3276 [Event Hubs] Add constructor that takes connection string
  sdk/eventhub/event-hubs/src/eventHubClient.ts
Labels: Client, Event Hubs

#3305 [AutoPR resources/resource-manager] Add deployment APIs for Microsoft.Resources
  sdk/features/arm-features/LICENSE.txt
  sdk/features/arm-features/README.md
  sdk/features/arm-features/package.json
  sdk/features/arm-features/src/models/featuresMappers.ts
  sdk/features/arm-features/src/models/index.ts
  sdk/features/arm-features/src/models/mappers.ts
  sdk/links/arm-links/LICENSE.txt
  sdk/links/arm-links/README.md
  sdk/links/arm-links/package.json
  sdk/links/arm-links/src/models/index.ts
  sdk/links/arm-links/src/models/mappers.ts
  sdk/links/arm-links/src/models/operationsMappers.ts
  sdk/links/arm-links/src/models/resourceLinksMappers.ts
  sdk/locks/arm-locks/LICENSE.txt
  sdk/locks/arm-locks/README.md
  sdk/locks/arm-locks/package.json
  sdk/locks/arm-locks/src/models/authorizationOperationsMappers.ts
  sdk/locks/arm-locks/src/models/index.ts
  sdk/locks/arm-locks/src/models/managementLocksMappers.ts
  sdk/locks/arm-locks/src/models/mappers.ts
  sdk/locks/arm-locks/src/operations/managementLocks.ts
  sdk/managedapplications/arm-managedapplications/LICENSE.txt
  sdk/managedapplications/arm-managedapplications/README.md
  sdk/managedapplications/arm-managedapplications/package.json
  sdk/managedapplications/arm-managedapplications/src/models/applianceDefinitionsMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/appliancesMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/index.ts
  sdk/managedapplications/arm-managedapplications/src/models/mappers.ts
  sdk/policy/arm-policy/LICENSE.txt
  sdk/policy/arm-policy/README.md
  sdk/policy/arm-policy/package.json
  sdk/policy/arm-policy/src/models/index.ts
  sdk/policy/arm-policy/src/models/mappers.ts
  sdk/policy/arm-policy/src/models/policyAssignmentsMappers.ts
  sdk/policy/arm-policy/src/models/policyDefinitionsMappers.ts
  sdk/policy/arm-policy/src/models/policySetDefinitionsMappers.ts
  sdk/resources/arm-resources/LICENSE.txt
  sdk/resources/arm-resources/README.md
  sdk/resources/arm-resources/package.json
  sdk/resources/arm-resources/src/models/deploymentOperationsMappers.ts
  sdk/resources/arm-resources/src/models/deploymentsMappers.ts
  sdk/resources/arm-resources/src/models/index.ts
  sdk/resources/arm-resources/src/models/mappers.ts
  sdk/resources/arm-resources/src/models/operationsMappers.ts
  sdk/resources/arm-resources/src/models/parameters.ts
  sdk/resources/arm-resources/src/models/providersMappers.ts
  sdk/resources/arm-resources/src/models/resourceGroupsMappers.ts
  sdk/resources/arm-resources/src/models/resourcesMappers.ts
  sdk/resources/arm-resources/src/models/tagsMappers.ts
  sdk/resources/arm-resources/src/operations/deploymentOperations.ts
  sdk/resources/arm-resources/src/operations/deployments.ts
  sdk/resources/arm-resources/src/resourceManagementClientContext.ts
Labels: RestPRMerged

#3337 [AutoPR hdinsight/resource-manager] [HDInsight] Fix specs not support subdomainsuffix parameter
  sdk/hdinsight/arm-hdinsight/package.json
  sdk/hdinsight/arm-hdinsight/src/models/index.ts
  sdk/hdinsight/arm-hdinsight/src/models/mappers.ts
Labels: RestPRMerged

#3333 [AutoPR machinelearningcompute/resource-manager] chore: jsonfmt machinelearningcompute
  sdk/machinelearningcompute/arm-machinelearningcompute/LICENSE.txt
  sdk/machinelearningcompute/arm-machinelearningcompute/README.md
  sdk/machinelearningcompute/arm-machinelearningcompute/package.json
  sdk/machinelearningcompute/arm-machinelearningcompute/rollup.config.js
  sdk/machinelearningcompute/arm-machinelearningcompute/src/machineLearningComputeManagementClientContext.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/index.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/machineLearningComputeMappers.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/mappers.ts
  sdk/machinelearningcompute/arm-machinelearningcompute/src/models/operationalizationClustersMappers.ts
Labels: RestPRMerged

#3343 [AutoPR deviceprovisioningservices/resource-manager] chore: jsonfmt deviceprovisioningservices
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/LICENSE.txt
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/README.md
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/package.json
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/rollup.config.js
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/iotDpsClientContext.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/models/dpsCertificateMappers.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/models/index.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/models/iotDpsResourceMappers.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/models/mappers.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/models/operationsMappers.ts
  sdk/deviceprovisioningservices/arm-deviceprovisioningservices/src/operations/dpsCertificate.ts
Labels: RestPRMerged

#3334 [AutoPR maps/resource-manager] chore: jsonfmt maps
  sdk/maps/arm-maps/LICENSE.txt
  sdk/maps/arm-maps/README.md
  sdk/maps/arm-maps/package.json
  sdk/maps/arm-maps/rollup.config.js
  sdk/maps/arm-maps/src/mapsManagementClientContext.ts
  sdk/maps/arm-maps/src/models/accountsMappers.ts
  sdk/maps/arm-maps/src/models/index.ts
  sdk/maps/arm-maps/src/models/mappers.ts
Labels: RestPRMerged

#3136 [Storage] Async iterator for listing blobs and containers - storage-blob
  sdk/storage/storage-blob/samples/typescript/iterators.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
Labels: Client, Storage

#3352 [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version preview/2018-11-01-preview
  sdk/billing/arm-billing/src/billingManagementClient.ts
  sdk/billing/arm-billing/src/models/addressesMappers.ts
  sdk/billing/arm-billing/src/models/index.ts
  sdk/billing/arm-billing/src/operations/addresses.ts
  sdk/billing/arm-billing/src/operations/index.ts
Labels: RestPRMerged

#3358 [AutoPR machinelearningservices/resource-manager] Revert "Adding usage id property to support usages by VM family, Workspace & Compute"
  sdk/machinelearningservices/arm-machinelearningservices/LICENSE.txt
  sdk/machinelearningservices/arm-machinelearningservices/README.md
  sdk/machinelearningservices/arm-machinelearningservices/package.json
  sdk/machinelearningservices/arm-machinelearningservices/rollup.config.js
  sdk/machinelearningservices/arm-machinelearningservices/src/azureMachineLearningWorkspacesContext.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/index.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/machineLearningComputeMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/mappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/operationsMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/workspacesMappers.ts
Labels: RestPRMerged

#3360 [AutoPR cosmos-db/resource-manager] Cosmos Python
  sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts
Labels: RestPRMerged

#3323 [Event Hubs] Add support for token cancellation in send requests
  sdk/eventhub/event-hubs/src/eventHubSender.ts
Labels: Client, Event Hubs

#3356 [Event Hubs] Ensure receiver is functional
  sdk/eventhub/event-hubs/samples/receiveEventsLoop.ts
  sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
  sdk/eventhub/event-hubs/samples/sendEvents.ts
  sdk/eventhub/event-hubs/src/index.ts
  sdk/eventhub/event-hubs/src/receiver.ts
  sdk/eventhub/event-hubs/src/sender.ts
  sdk/eventhub/event-hubs/test/receiver.spec.ts
Labels: Client, Event Hubs
