Repository Azure/azure-sdk-for-js, pull requests merged in 2019-06, with the labels that each got.

#3369 [Event Hubs] Add support for token cancellation in streaming and batching receiver
  sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
  sdk/eventhub/event-hubs/src/batchingReceiver.ts
  sdk/eventhub/event-hubs/src/eventHubReceiver.ts
  sdk/eventhub/event-hubs/src/receiver.ts
  sdk/eventhub/event-hubs/src/streamingReceiver.ts
Labels: Client, Event Hubs

#3380 [Event Hubs] Create one AMQP batching receiver link per Receiver
  sdk/eventhub/event-hubs/src/receiver.ts
Labels: Client, Event Hubs

#3217 [Storage] Async iterators for listing queues - storage-queue
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/test/queueserviceclient.spec.ts
Labels: Client, Storage

#3393 [AutoPR cognitiveservices/data-plane/QnAMaker] Adding missing docs for existing routes for QnA Maker APIM
  sdk/cognitiveservices/cognitiveservices-qnamaker/README.md
  sdk/cognitiveservices/cognitiveservices-qnamaker/package.json
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/endpointSettingsMappers.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/index.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/models/mappers.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/endpointSettings.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/operations/index.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/qnAMakerClient.ts
  sdk/cognitiveservices/cognitiveservices-qnamaker/src/qnAMakerClientContext.ts
Labels: RestPRMerged

#3384 [AutoPR msi/resource-manager] chore: jsonfmt msi
  sdk/msi/arm-msi/LICENSE.txt
  sdk/msi/arm-msi/README.md
  sdk/msi/arm-msi/package.json
  sdk/msi/arm-msi/rollup.config.js
  sdk/msi/arm-msi/src/managedServiceIdentityClientContext.ts
  sdk/msi/arm-msi/src/models/index.ts
  sdk/msi/arm-msi/src/models/mappers.ts
  sdk/msi/arm-msi/src/models/operationsMappers.ts
  sdk/msi/arm-msi/src/models/userAssignedIdentitiesMappers.ts
Labels: RestPRMerged

#3390 [AutoPR cdn/resource-manager] typo: Double word "use"
  sdk/cdn/arm-cdn/README.md
  sdk/cdn/arm-cdn/package.json
  sdk/cdn/arm-cdn/src/cdnManagementClientContext.ts
  sdk/cdn/arm-cdn/src/models/customDomainsMappers.ts
  sdk/cdn/arm-cdn/src/models/edgeNodesMappers.ts
  sdk/cdn/arm-cdn/src/models/endpointsMappers.ts
  sdk/cdn/arm-cdn/src/models/index.ts
  sdk/cdn/arm-cdn/src/models/mappers.ts
  sdk/cdn/arm-cdn/src/models/originsMappers.ts
  sdk/cdn/arm-cdn/src/models/profilesMappers.ts
Labels: RestPRMerged

#3399 [AutoPR postgresql/resource-manager] Enable PG 11
  sdk/postgresql/arm-postgresql/package.json
  sdk/postgresql/arm-postgresql/src/models/index.ts
  sdk/postgresql/arm-postgresql/src/models/mappers.ts
Labels: RestPRMerged

#3118 [JS] [Service Bus] package.json in the samples folder
  sdk/servicebus/service-bus/samples/README.md
  sdk/servicebus/service-bus/samples/package.json
  sdk/servicebus/service-bus/samples/typescript/gettingStarted/scheduledMessages.ts
Labels: Client, Service Bus

#3402 [AutoPR batch/data-plane] [Batch] Add new data plane verison 2019-06-01
  sdk/batch/batch/src/batchServiceClient.ts
  sdk/batch/batch/src/batchServiceClientContext.ts
  sdk/batch/batch/src/models/accountMappers.ts
  sdk/batch/batch/src/models/index.ts
  sdk/batch/batch/src/models/mappers.ts
  sdk/batch/batch/src/models/parameters.ts
  sdk/batch/batch/src/operations/account.ts
Labels: RestPRMerged

#2607 Rename files to follow yaml file naming conventions
  eng/pipelines/templates/jobs/archetype-sdk-tests-browser.yml
  eng/pipelines/templates/jobs/archetype-sdk-tests-node.yml
  eng/pipelines/templates/steps/tests-common.yml
  sdk/eventhub/event-hubs/tests.yml
  sdk/eventhub/event-processor-host/tests.yml
  sdk/servicebus/service-bus/tests.yml
  sdk/storage/archetype-sdk-tests-storage.yml
  sdk/storage/storage-blob/tests.yml
  sdk/storage/storage-file/tests.yml
  sdk/storage/storage-queue/tests.yml
Labels: EngSys

#3413 [AutoPR migrate/resource-manager] chore: jsonfmt migrate
  sdk/migrate/arm-migrate/LICENSE.txt
  sdk/migrate/arm-migrate/README.md
  sdk/migrate/arm-migrate/package.json
  sdk/migrate/arm-migrate/rollup.config.js
  sdk/migrate/arm-migrate/src/azureMigrateContext.ts
  sdk/migrate/arm-migrate/src/models/assessedMachinesMappers.ts
  sdk/migrate/arm-migrate/src/models/assessmentOptionsMappers.ts
  sdk/migrate/arm-migrate/src/models/assessmentsMappers.ts
  sdk/migrate/arm-migrate/src/models/groupsMappers.ts
  sdk/migrate/arm-migrate/src/models/index.ts
  sdk/migrate/arm-migrate/src/models/locationMappers.ts
  sdk/migrate/arm-migrate/src/models/machinesMappers.ts
  sdk/migrate/arm-migrate/src/models/mappers.ts
  sdk/migrate/arm-migrate/src/models/operationsMappers.ts
  sdk/migrate/arm-migrate/src/models/projectsMappers.ts
  sdk/migrate/arm-migrate/src/operations/assessedMachines.ts
  sdk/migrate/arm-migrate/src/operations/assessments.ts
Labels: RestPRMerged

#3415 [AutoPR resourcegraph/resource-manager] [Resource Graph] result format option added
  sdk/resourcegraph/arm-resourcegraph/package.json
  sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
  sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts
Labels: RestPRMerged

#3428 [AutoPR privatedns/resource-manager] chore: jsonfmt privatedns
  sdk/privatedns/arm-privatedns/README.md
  sdk/privatedns/arm-privatedns/package.json
Labels: RestPRMerged

#3438 [AutoPR managementgroups/resource-manager] chore: jsonfmt managementgroups
  sdk/managementgroups/arm-managementgroups/LICENSE.txt
  sdk/managementgroups/arm-managementgroups/README.md
  sdk/managementgroups/arm-managementgroups/package.json
  sdk/managementgroups/arm-managementgroups/rollup.config.js
  sdk/managementgroups/arm-managementgroups/src/managementGroupsAPIContext.ts
  sdk/managementgroups/arm-managementgroups/src/models/entitiesMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/index.ts
  sdk/managementgroups/arm-managementgroups/src/models/managementGroupSubscriptionsMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/managementGroupsMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/mappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/operationsMappers.ts
Labels: RestPRMerged

#3440 [AutoPR netapp/resource-manager] Essential corrections to R4 standard swagger for GA
  sdk/netapp/arm-netapp/src/models/index.ts
  sdk/netapp/arm-netapp/src/models/mappers.ts
  sdk/netapp/arm-netapp/src/models/parameters.ts
Labels: RestPRMerged

#3424 [AutoPR batch/data-plane] Make Batch Resources Proper Nouns
  sdk/batch/batch/src/models/index.ts
  sdk/batch/batch/src/operations/account.ts
  sdk/batch/batch/src/operations/application.ts
  sdk/batch/batch/src/operations/certificateOperations.ts
  sdk/batch/batch/src/operations/computeNodeOperations.ts
  sdk/batch/batch/src/operations/file.ts
  sdk/batch/batch/src/operations/job.ts
  sdk/batch/batch/src/operations/jobSchedule.ts
  sdk/batch/batch/src/operations/pool.ts
  sdk/batch/batch/src/operations/task.ts
Labels: RestPRMerged

#3442 [AutoPR eventgrid/resource-manager] EventgridL fixed package namespace, added java readme file
  sdk/eventgrid/arm-eventgrid/README.md
  sdk/eventgrid/arm-eventgrid/package.json
Labels: RestPRMerged

#3446 [AutoPR eventhub/resource-manager] EventHub-2018-01-01 Preview : update the API name
  sdk/eventhub/arm-eventhub/package.json
Labels: RestPRMerged

#3284 [JS] [KeyVault] @azure/keyvault-secrets
  common/config/rush/pnpm-lock.yaml
  rush.json
  sdk/keyvault/keyvault-secrets/LICENSE.md
  sdk/keyvault/keyvault-secrets/README.md
  sdk/keyvault/keyvault-secrets/ci.yml
  sdk/keyvault/keyvault-secrets/package.json
  sdk/keyvault/keyvault-secrets/rollup.config.js
  sdk/keyvault/keyvault-secrets/samples/secrets.pipeline.ts
  sdk/keyvault/keyvault-secrets/samples/singleSecret.ts
  sdk/keyvault/keyvault-secrets/src/core/clientOptions.ts
  sdk/keyvault/keyvault-secrets/src/core/index.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultBase.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultClient.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultClientContext.ts
  sdk/keyvault/keyvault-secrets/src/core/models/index.ts
  sdk/keyvault/keyvault-secrets/src/core/models/mappers.ts
  sdk/keyvault/keyvault-secrets/src/core/models/parameters.ts
  sdk/keyvault/keyvault-secrets/src/core/utils.ts
  sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts
  sdk/keyvault/keyvault-secrets/src/index.ts
  sdk/keyvault/keyvault-secrets/src/secretsModels.ts
  sdk/keyvault/keyvault-secrets/tsconfig.json
Labels: Client, KeyVault

#3408 [Event Hubs] Multiple receive operations on the same receiver
  sdk/eventhub/event-hubs/src/batchingReceiver.ts
  sdk/eventhub/event-hubs/src/eventData.ts
  sdk/eventhub/event-hubs/src/eventHubReceiver.ts
  sdk/eventhub/event-hubs/src/receiver.ts
Labels: Client, Event Hubs

#3280 [JS] [KeyVault] @azure/keyvault-keys
  common/config/rush/pnpm-lock.yaml
  rush.json
  sdk/keyvault/keyvault-keys/.prettierrc.json
  sdk/keyvault/keyvault-keys/LICENSE.md
  sdk/keyvault/keyvault-keys/README.md
  sdk/keyvault/keyvault-keys/ci.yml
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/rollup.config.js
  sdk/keyvault/keyvault-keys/samples/singleKey.ts
  sdk/keyvault/keyvault-keys/src/core/clientOptions.ts
  sdk/keyvault/keyvault-keys/src/core/index.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultBase.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultClient.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
  sdk/keyvault/keyvault-keys/src/core/models/index.ts
  sdk/keyvault/keyvault-keys/src/core/models/mappers.ts
  sdk/keyvault/keyvault-keys/src/core/models/parameters.ts
  sdk/keyvault/keyvault-keys/src/core/utils.ts
  sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
  sdk/keyvault/keyvault-keys/src/index.ts
  sdk/keyvault/keyvault-keys/src/keysModels.ts
  sdk/keyvault/keyvault-keys/tsconfig.json
Labels: Client, KeyVault

#2770 [Storage] Enable VS Code Debugging for storage packages
  sdk/storage/storage-blob/.vscode/extensions.json
  sdk/storage/storage-blob/.vscode/launch.json
  sdk/storage/storage-blob/.vscode/settings.json
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-blob/samples/javascript/iterator.js
  sdk/storage/storage-blob/samples/typescript/advanced.ts
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-file/.vscode/extensions.json
  sdk/storage/storage-file/.vscode/launch.json
  sdk/storage/storage-file/.vscode/settings.json
  sdk/storage/storage-file/package.json
  sdk/storage/storage-file/samples/typescript/advanced.ts
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-queue/.vscode/extensions.json
  sdk/storage/storage-queue/.vscode/launch.json
  sdk/storage/storage-queue/.vscode/settings.json
  sdk/storage/storage-queue/package.json
  sdk/storage/storage-queue/samples/typescript/basic.ts
Labels: Client, Storage

#3469 [AutoPR redis/resource-manager] chore: jsonfmt redis
  sdk/redis/arm-rediscache/README.md
  sdk/redis/arm-rediscache/package.json
Labels: RestPRMerged

#3493 [Event Hubs] Re-establish links on retryable errors for batching receiver
  sdk/eventhub/event-hubs/src/batchingReceiver.ts
Labels: Client, Event Hubs

#3328 [Storage] Workaround to avoid duplicated 'content-length' headers on HTTP requests - fix [storage-queue]
  sdk/storage/storage-queue/src/policies/SharedKeyCredentialPolicy.ts
Labels: Bug, Client, Storage

#3291 [Storage] Workaround to avoid duplicated 'content-length' headers on HTTP requests [storage-blob]
  sdk/storage/storage-blob/src/policies/SharedKeyCredentialPolicy.ts
Labels: Bug, Client, Storage

#3273 [Storage] Workaround to avoid duplicated 'content-length' headers on HTTP requests [storage-file]
  sdk/storage/storage-file/src/policies/SharedKeyCredentialPolicy.ts
Labels: Bug, Client, Storage

#3503 [AutoPR cognitiveservices/data-plane/Face] [FaceAPI] Add detection model argument on Detect and AddFace methods
  sdk/cognitiveservices/cognitiveservices-face/package.json
  sdk/cognitiveservices/cognitiveservices-face/src/models/index.ts
  sdk/cognitiveservices/cognitiveservices-face/src/models/parameters.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/face.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/faceListOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largeFaceListOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largePersonGroupOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largePersonGroupPerson.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/personGroupOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/personGroupPerson.ts
Labels: RestPRMerged

#3510 [AutoPR mixedreality/resource-manager] chore: jsonfmt mixedreality
  sdk/mixedreality/arm-mixedreality/README.md
  sdk/mixedreality/arm-mixedreality/package.json
Labels: RestPRMerged

#3509 [Event Hubs] Remove prefetch count support
  sdk/eventhub/event-hubs/src/receiver.ts
Labels: Event Hubs

#3514 [AutoPR storage/resource-manager] [SRP] Default value change for account property supportsHttpsTrafficOnly
  sdk/storage/arm-storage/src/models/index.ts
  sdk/storage/arm-storage/src/models/mappers.ts
  sdk/storage/arm-storage/src/models/parameters.ts
  sdk/storage/arm-storage/src/operations/blobContainers.ts
Labels: RestPRMerged

#3525 [AutoPR mediaservices/resource-manager] typo: mediaservices/resource-manager/Microsoft.Media
  sdk/mediaservices/arm-mediaservices/package.json
  sdk/mediaservices/arm-mediaservices/src/models/accountFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/assetFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/assetsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/contentKeyPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/index.ts
  sdk/mediaservices/arm-mediaservices/src/models/jobsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/liveEventsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/liveOutputsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/mappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/mediaservicesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingEndpointsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingLocatorsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/transformsMappers.ts
Labels: RestPRMerged

#3527 [AutoPR netapp/resource-manager] chore: jsonfmt netapp
  sdk/netapp/arm-netapp/src/models/index.ts
  sdk/netapp/arm-netapp/src/models/mappers.ts
  sdk/netapp/arm-netapp/src/models/parameters.ts
Labels: RestPRMerged

#3531 [AutoPR securityinsights/resource-manager] chore: jsonfmt securityinsights
  packages/@azure/arm-securityinsight/LICENSE.txt
  packages/@azure/arm-securityinsight/README.md
  packages/@azure/arm-securityinsight/lib/models/actionsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/alertRulesMappers.ts
  packages/@azure/arm-securityinsight/lib/models/bookmarksMappers.ts
  packages/@azure/arm-securityinsight/lib/models/casesAggregationsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/casesMappers.ts
  packages/@azure/arm-securityinsight/lib/models/dataConnectorsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/entitiesMappers.ts
  packages/@azure/arm-securityinsight/lib/models/index.ts
  packages/@azure/arm-securityinsight/lib/models/mappers.ts
  packages/@azure/arm-securityinsight/lib/models/officeConsentsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/operationsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/parameters.ts
  packages/@azure/arm-securityinsight/lib/models/productSettingsMappers.ts
  packages/@azure/arm-securityinsight/lib/operations/actions.ts
  packages/@azure/arm-securityinsight/lib/operations/alertRules.ts
  packages/@azure/arm-securityinsight/lib/operations/bookmarks.ts
  packages/@azure/arm-securityinsight/lib/operations/cases.ts
  packages/@azure/arm-securityinsight/lib/operations/casesAggregations.ts
  packages/@azure/arm-securityinsight/lib/operations/dataConnectors.ts
  packages/@azure/arm-securityinsight/lib/operations/entities.ts
  packages/@azure/arm-securityinsight/lib/operations/index.ts
  packages/@azure/arm-securityinsight/lib/operations/officeConsents.ts
  packages/@azure/arm-securityinsight/lib/operations/operations.ts
  packages/@azure/arm-securityinsight/lib/operations/productSettings.ts
  packages/@azure/arm-securityinsight/lib/securityInsights.ts
  packages/@azure/arm-securityinsight/lib/securityInsightsContext.ts
  packages/@azure/arm-securityinsight/package.json
  packages/@azure/arm-securityinsight/rollup.config.js
  packages/@azure/arm-securityinsight/tsconfig.json
Labels: RestPRMerged

#3478 Remove StorageClient from public API surface
  sdk/storage/README.md
  sdk/storage/storage-blob/README.md
  sdk/storage/storage-blob/samples/javascript/advanced.js
  sdk/storage/storage-blob/samples/javascript/basic.js
  sdk/storage/storage-blob/samples/javascript/iterator.js
  sdk/storage/storage-blob/samples/typescript/advanced.ts
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-blob/samples/typescript/iterators.ts
  sdk/storage/storage-blob/src/AppendBlobClient.ts
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/BlockBlobClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/PageBlobClient.ts
  sdk/storage/storage-blob/src/Pipeline.ts
  sdk/storage/storage-blob/src/StorageClient.ts
  sdk/storage/storage-blob/src/credentials/TokenCredential.ts
  sdk/storage/storage-blob/src/index.browser.ts
  sdk/storage/storage-blob/src/index.ts
  sdk/storage/storage-blob/test/node/sas.spec.ts
  sdk/storage/storage-blob/test/retrypolicy.spec.ts
  sdk/storage/storage-blob/test/utils/index.browser.ts
  sdk/storage/storage-blob/test/utils/index.ts
  sdk/storage/storage-file/README.md
  sdk/storage/storage-file/samples/javascript/advanced.js
  sdk/storage/storage-file/samples/javascript/basic.js
  sdk/storage/storage-file/samples/typescript/advanced.ts
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/Pipeline.ts
  sdk/storage/storage-file/src/ShareClient.ts
  sdk/storage/storage-file/src/StorageClient.ts
  sdk/storage/storage-file/src/index.browser.ts
  sdk/storage/storage-file/src/index.ts
  sdk/storage/storage-file/test/node/sas.spec.ts
  sdk/storage/storage-file/test/retrypolicy.spec.ts
  sdk/storage/storage-file/test/utils/index.browser.ts
  sdk/storage/storage-file/test/utils/index.ts
  sdk/storage/storage-queue/README.md
  sdk/storage/storage-queue/samples/javascript/basic.js
  sdk/storage/storage-queue/samples/typescript/basic.ts
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/src/MessageIdClient.ts
  sdk/storage/storage-queue/src/MessagesClient.ts
  sdk/storage/storage-queue/src/Pipeline.ts
  sdk/storage/storage-queue/src/QueueClient.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/src/StorageClient.ts
  sdk/storage/storage-queue/src/credentials/TokenCredential.ts
  sdk/storage/storage-queue/src/index.browser.ts
  sdk/storage/storage-queue/src/index.ts
  sdk/storage/storage-queue/test/node/sas.spec.ts
  sdk/storage/storage-queue/test/retrypolicy.spec.ts
  sdk/storage/storage-queue/test/utils/index.browser.ts
  sdk/storage/storage-queue/test/utils/index.ts
Labels: Client, Storage

#3552 [AutoPR cosmos-db/resource-manager] Add APIs for throughput read and update
  sdk/cosmosdb/arm-cosmosdb/README.md
  sdk/cosmosdb/arm-cosmosdb/package.json
  sdk/cosmosdb/arm-cosmosdb/src/models/databaseAccountsMappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/index.ts
  sdk/cosmosdb/arm-cosmosdb/src/models/mappers.ts
  sdk/cosmosdb/arm-cosmosdb/src/operations/databaseAccounts.ts
Labels: RestPRMerged

#3564 [AutoPR storageimportexport/resource-manager] chore: jsonfmt storageimportexport
  sdk/storageimportexport/arm-storageimportexport/LICENSE.txt
  sdk/storageimportexport/arm-storageimportexport/README.md
  sdk/storageimportexport/arm-storageimportexport/package.json
  sdk/storageimportexport/arm-storageimportexport/rollup.config.js
  sdk/storageimportexport/arm-storageimportexport/src/models/bitLockerKeysMappers.ts
  sdk/storageimportexport/arm-storageimportexport/src/models/index.ts
  sdk/storageimportexport/arm-storageimportexport/src/models/jobsMappers.ts
  sdk/storageimportexport/arm-storageimportexport/src/models/locationsMappers.ts
  sdk/storageimportexport/arm-storageimportexport/src/models/mappers.ts
  sdk/storageimportexport/arm-storageimportexport/src/models/operationsMappers.ts
  sdk/storageimportexport/arm-storageimportexport/src/storageImportExportManagementClientContext.ts
Labels: RestPRMerged

#3477 [JS] [KeyVault] rushx format on the keyvault packages
  sdk/keyvault/keyvault-keys/.prettierrc.json
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/rollup.config.js
  sdk/keyvault/keyvault-keys/src/core/clientOptions.ts
  sdk/keyvault/keyvault-keys/src/core/index.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultBase.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultClient.ts
  sdk/keyvault/keyvault-keys/src/core/keyVaultClientContext.ts
  sdk/keyvault/keyvault-keys/src/core/models/index.ts
  sdk/keyvault/keyvault-keys/src/core/models/mappers.ts
  sdk/keyvault/keyvault-keys/src/core/models/parameters.ts
  sdk/keyvault/keyvault-keys/src/core/utils.ts
  sdk/keyvault/keyvault-keys/src/core/utils/constants.ts
  sdk/keyvault/keyvault-keys/src/index.ts
  sdk/keyvault/keyvault-keys/src/keysModels.ts
  sdk/keyvault/keyvault-keys/tsconfig.json
  sdk/keyvault/keyvault-secrets/package.json
  sdk/keyvault/keyvault-secrets/rollup.config.js
  sdk/keyvault/keyvault-secrets/src/core/clientOptions.ts
  sdk/keyvault/keyvault-secrets/src/core/index.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultBase.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultClient.ts
  sdk/keyvault/keyvault-secrets/src/core/keyVaultClientContext.ts
  sdk/keyvault/keyvault-secrets/src/core/models/index.ts
  sdk/keyvault/keyvault-secrets/src/core/models/mappers.ts
  sdk/keyvault/keyvault-secrets/src/core/models/parameters.ts
  sdk/keyvault/keyvault-secrets/src/core/utils.ts
  sdk/keyvault/keyvault-secrets/src/core/utils/constants.ts
  sdk/keyvault/keyvault-secrets/src/index.ts
  sdk/keyvault/keyvault-secrets/src/secretsModels.ts
  sdk/keyvault/keyvault-secrets/tsconfig.json
Labels: Client, KeyVault

#3550 [AutoPR operationsmanagement/resource-manager] chore: jsonfmt operationsmanagement
  sdk/operationsmanagement/arm-operations/LICENSE.txt
  sdk/operationsmanagement/arm-operations/README.md
  sdk/operationsmanagement/arm-operations/package.json
  sdk/operationsmanagement/arm-operations/rollup.config.js
  sdk/operationsmanagement/arm-operations/src/models/index.ts
  sdk/operationsmanagement/arm-operations/src/models/managementAssociationsMappers.ts
  sdk/operationsmanagement/arm-operations/src/models/managementConfigurationsMappers.ts
  sdk/operationsmanagement/arm-operations/src/models/mappers.ts
  sdk/operationsmanagement/arm-operations/src/models/operationsMappers.ts
  sdk/operationsmanagement/arm-operations/src/models/solutionsMappers.ts
  sdk/operationsmanagement/arm-operations/src/operations/managementAssociations.ts
  sdk/operationsmanagement/arm-operations/src/operations/solutions.ts
  sdk/operationsmanagement/arm-operations/src/operationsManagementClientContext.ts
Labels: RestPRMerged

#3568 [AutoPR subscription/resource-manager] chore: jsonfmt subscription
  sdk/subscription/arm-subscriptions/LICENSE.txt
  sdk/subscription/arm-subscriptions/README.md
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/rollup.config.js
  sdk/subscription/arm-subscriptions/src/models/index.ts
  sdk/subscription/arm-subscriptions/src/models/mappers.ts
  sdk/subscription/arm-subscriptions/src/models/operationsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/parameters.ts
  sdk/subscription/arm-subscriptions/src/models/subscriptionsMappers.ts
  sdk/subscription/arm-subscriptions/src/models/tenantsMappers.ts
  sdk/subscription/arm-subscriptions/src/operations/index.ts
  sdk/subscription/arm-subscriptions/src/operations/subscriptions.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClient.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClientContext.ts
Labels: RestPRMerged

#3545 [Event Hubs] Add retry logic on receive batch
  sdk/eventhub/event-hubs/src/batchingReceiver.ts
  sdk/eventhub/event-hubs/src/receiver.ts
Labels: Client, Event Hubs

#3475 [JS] [KeyVault] Fixed the current keys tests
  common/config/rush/pnpm-lock.yaml
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/tests.yml
  sdk/keyvault/keyvault-keys/tests/keys.test.ts
  sdk/keyvault/keyvault-keys/tests/tsconfig.test.json
  sdk/keyvault/keyvault-keys/tests/utils/utils.common.ts
Labels: Client, KeyVault

#3590 [AutoPR streamanalytics/resource-manager] chore: jsonfmt streamanalytics
  sdk/streamanalytics/arm-streamanalytics/LICENSE.txt
  sdk/streamanalytics/arm-streamanalytics/README.md
  sdk/streamanalytics/arm-streamanalytics/package.json
  sdk/streamanalytics/arm-streamanalytics/rollup.config.js
  sdk/streamanalytics/arm-streamanalytics/src/models/functionsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/index.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/inputsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/mappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/operationsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/outputsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/streamingJobsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/subscriptionsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/models/transformationsMappers.ts
  sdk/streamanalytics/arm-streamanalytics/src/streamAnalyticsManagementClientContext.ts
Labels: RestPRMerged

#3592 [AutoPR signalr/resource-manager] chore: jsonfmt signalr
  sdk/signalr/arm-signalr/LICENSE.txt
  sdk/signalr/arm-signalr/README.md
  sdk/signalr/arm-signalr/package.json
  sdk/signalr/arm-signalr/rollup.config.js
  sdk/signalr/arm-signalr/src/models/index.ts
  sdk/signalr/arm-signalr/src/models/mappers.ts
  sdk/signalr/arm-signalr/src/models/operationsMappers.ts
  sdk/signalr/arm-signalr/src/models/signalRMappers.ts
  sdk/signalr/arm-signalr/src/models/usagesMappers.ts
  sdk/signalr/arm-signalr/src/operations/signalR.ts
  sdk/signalr/arm-signalr/src/signalRManagementClientContext.ts
Labels: RestPRMerged

#3594 [AutoPR apimanagement/resource-manager] Custom properties were updated to reflect all the possible values
  sdk/apimanagement/arm-apimanagement/src/models/index.ts
Labels: RestPRMerged

#3459 [JS] [KeyVault] Fixed the current secrets tests
  common/config/rush/pnpm-lock.yaml
  sdk/keyvault/keyvault-secrets/package.json
  sdk/keyvault/keyvault-secrets/tests.yml
  sdk/keyvault/keyvault-secrets/tests/secrets.test.ts
  sdk/keyvault/keyvault-secrets/tests/tsconfig.test.json
  sdk/keyvault/keyvault-secrets/tests/utils/utils.common.ts
Labels: Client, KeyVault

#3608 [AutoPR storage/resource-manager] [SRP] Remove azureFilesAadIntegration and add AzureFilesIdentityBased Authentication in storage account properties
  sdk/storage/arm-storage/src/models/blobContainersMappers.ts
  sdk/storage/arm-storage/src/models/blobServicesMappers.ts
  sdk/storage/arm-storage/src/models/index.ts
  sdk/storage/arm-storage/src/models/managementPoliciesMappers.ts
  sdk/storage/arm-storage/src/models/mappers.ts
  sdk/storage/arm-storage/src/models/parameters.ts
  sdk/storage/arm-storage/src/models/storageAccountsMappers.ts
  sdk/storage/arm-storage/src/operations/blobContainers.ts
Labels: RestPRMerged

#3611 [AutoPR visualstudio/resource-manager] chore: jsonfmt visualstudio
  sdk/visualstudio/arm-visualstudio/LICENSE.txt
  sdk/visualstudio/arm-visualstudio/README.md
  sdk/visualstudio/arm-visualstudio/package.json
  sdk/visualstudio/arm-visualstudio/rollup.config.js
  sdk/visualstudio/arm-visualstudio/src/models/accountsMappers.ts
  sdk/visualstudio/arm-visualstudio/src/models/extensionsMappers.ts
  sdk/visualstudio/arm-visualstudio/src/models/index.ts
  sdk/visualstudio/arm-visualstudio/src/models/mappers.ts
  sdk/visualstudio/arm-visualstudio/src/models/operationsMappers.ts
  sdk/visualstudio/arm-visualstudio/src/models/projectsMappers.ts
  sdk/visualstudio/arm-visualstudio/src/visualStudioResourceProviderClientContext.ts
Labels: RestPRMerged

#3614 [AutoPR resourcegraph/resource-manager] chore: jsonfmt resourcegraph
  sdk/resourcegraph/arm-resourcegraph/package.json
  sdk/resourcegraph/arm-resourcegraph/src/models/index.ts
  sdk/resourcegraph/arm-resourcegraph/src/models/mappers.ts
Labels: RestPRMerged

#3617 [AutoPR cognitiveservices/data-plane/Face] [FaceAPI] Update output folder of FaceAPI dotNet SDK
  sdk/cognitiveservices/cognitiveservices-face/package.json
  sdk/cognitiveservices/cognitiveservices-face/src/models/index.ts
  sdk/cognitiveservices/cognitiveservices-face/src/models/parameters.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/face.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/faceListOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largeFaceListOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largePersonGroupOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/largePersonGroupPerson.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/personGroupOperations.ts
  sdk/cognitiveservices/cognitiveservices-face/src/operations/personGroupPerson.ts
Labels: RestPRMerged

#3490 Make visibilityTimeout parameter optional with default value of zero
  sdk/storage/storage-queue/src/MessageIdClient.ts
  sdk/storage/storage-queue/test/messageidclient.spec.ts
  sdk/storage/storage-queue/test/node/messageidclient.spec.ts
Labels: Client, Storage

#3627 [AutoPR relay/resource-manager] chore: jsonfmt relay
  sdk/relay/arm-relay/LICENSE.txt
  sdk/relay/arm-relay/README.md
  sdk/relay/arm-relay/package.json
  sdk/relay/arm-relay/rollup.config.js
  sdk/relay/arm-relay/src/models/hybridConnectionsMappers.ts
  sdk/relay/arm-relay/src/models/index.ts
  sdk/relay/arm-relay/src/models/mappers.ts
  sdk/relay/arm-relay/src/models/namespacesMappers.ts
  sdk/relay/arm-relay/src/models/operationsMappers.ts
  sdk/relay/arm-relay/src/models/wCFRelaysMappers.ts
  sdk/relay/arm-relay/src/relayManagementClientContext.ts
Labels: RestPRMerged

#3635 Setting up for by-service pipelines.
  sdk/core/ci.yml
  sdk/cosmosdb/ci.yml
  sdk/eventhub/ci.yml
  sdk/keyvault/ci.yml
  sdk/servicebus/ci.yml
  sdk/storage/ci.yml
Labels: EngSys

#3648 [AutoPR resources/resource-manager] Add additional ExportTemplate options
  sdk/features/arm-features/LICENSE.txt
  sdk/features/arm-features/README.md
  sdk/features/arm-features/package.json
  sdk/features/arm-features/src/models/featuresMappers.ts
  sdk/features/arm-features/src/models/index.ts
  sdk/features/arm-features/src/models/mappers.ts
  sdk/links/arm-links/LICENSE.txt
  sdk/links/arm-links/README.md
  sdk/links/arm-links/package.json
  sdk/links/arm-links/src/models/index.ts
  sdk/links/arm-links/src/models/mappers.ts
  sdk/links/arm-links/src/models/operationsMappers.ts
  sdk/links/arm-links/src/models/resourceLinksMappers.ts
  sdk/locks/arm-locks/LICENSE.txt
  sdk/locks/arm-locks/README.md
  sdk/locks/arm-locks/package.json
  sdk/locks/arm-locks/src/models/authorizationOperationsMappers.ts
  sdk/locks/arm-locks/src/models/index.ts
  sdk/locks/arm-locks/src/models/managementLocksMappers.ts
  sdk/locks/arm-locks/src/models/mappers.ts
  sdk/locks/arm-locks/src/operations/managementLocks.ts
  sdk/managedapplications/arm-managedapplications/LICENSE.txt
  sdk/managedapplications/arm-managedapplications/README.md
  sdk/managedapplications/arm-managedapplications/package.json
  sdk/managedapplications/arm-managedapplications/src/models/applianceDefinitionsMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/appliancesMappers.ts
  sdk/managedapplications/arm-managedapplications/src/models/index.ts
  sdk/managedapplications/arm-managedapplications/src/models/mappers.ts
  sdk/policy/arm-policy/LICENSE.txt
  sdk/policy/arm-policy/README.md
  sdk/policy/arm-policy/package.json
  sdk/policy/arm-policy/src/models/index.ts
  sdk/policy/arm-policy/src/models/mappers.ts
  sdk/policy/arm-policy/src/models/policyAssignmentsMappers.ts
  sdk/policy/arm-policy/src/models/policyDefinitionsMappers.ts
  sdk/policy/arm-policy/src/models/policySetDefinitionsMappers.ts
  sdk/resources/arm-resources/LICENSE.txt
  sdk/resources/arm-resources/README.md
  sdk/resources/arm-resources/package.json
  sdk/resources/arm-resources/src/models/deploymentOperationsMappers.ts
  sdk/resources/arm-resources/src/models/deploymentsMappers.ts
  sdk/resources/arm-resources/src/models/index.ts
  sdk/resources/arm-resources/src/models/mappers.ts
  sdk/resources/arm-resources/src/models/operationsMappers.ts
  sdk/resources/arm-resources/src/models/parameters.ts
  sdk/resources/arm-resources/src/models/providersMappers.ts
  sdk/resources/arm-resources/src/models/resourceGroupsMappers.ts
  sdk/resources/arm-resources/src/models/resourcesMappers.ts
  sdk/resources/arm-resources/src/models/tagsMappers.ts
  sdk/resources/arm-resources/src/operations/deploymentOperations.ts
  sdk/resources/arm-resources/src/operations/deployments.ts
  sdk/resources/arm-resources/src/resourceManagementClientContext.ts
Labels: RestPRMerged

#3666 [AutoPR mariadb/resource-manager] MariaDb: updated readme and added java readme
  sdk/mariadb/arm-mariadb/README.md
  sdk/mariadb/arm-mariadb/package.json
  sdk/mariadb/arm-mariadb/src/models/index.ts
  sdk/mariadb/arm-mariadb/src/models/mappers.ts
Labels: RestPRMerged

#3677 [AutoPR labservices/resource-manager] chore: jsonfmt labservices
  sdk/labservices/arm-labservices/README.md
  sdk/labservices/arm-labservices/package.json
Labels: RestPRMerged

#3637 [AutoPR hanaonazure/resource-manager] Microsoft.HanaOnAzure: Remove readOnly attribute from customer-provided properties in CreateHanaInstance
  sdk/hanaonazure/arm-hanaonazure/README.md
  sdk/hanaonazure/arm-hanaonazure/package.json
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/mappers.ts
Labels: RestPRMerged

#3698 [AutoPR storage/resource-manager] Move Storage to Py v4.x
  sdk/storage/arm-storage/README.md
  sdk/storage/arm-storage/package.json
Labels: RestPRMerged

#3707 [AutoPR storage/resource-manager] Fix List containers
  sdk/storage/arm-storage/README.md
  sdk/storage/arm-storage/package.json
  sdk/storage/arm-storage/src/models/index.ts
  sdk/storage/arm-storage/src/models/mappers.ts
  sdk/storage/arm-storage/src/models/parameters.ts
  sdk/storage/arm-storage/src/operations/blobContainers.ts
Labels: RestPRMerged

#3723 [AutoPR containerregistry/resource-manager] ACR with Autorest for Python 4
  sdk/containerregistry/arm-containerregistry/README.md
  sdk/containerregistry/arm-containerregistry/package.json
Labels: RestPRMerged

#3741 [AutoPR applicationinsights/resource-manager] chore: jsonfmt applicationinsights
  sdk/applicationinsights/arm-appinsights/LICENSE.txt
  sdk/applicationinsights/arm-appinsights/README.md
  sdk/applicationinsights/arm-appinsights/package.json
  sdk/applicationinsights/arm-appinsights/rollup.config.js
  sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClient.ts
  sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClientContext.ts
  sdk/applicationinsights/arm-appinsights/src/models/aPIKeysMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/analyticsItemsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/annotationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentAvailableFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentCurrentBillingFeaturesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentFeatureCapabilitiesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentQuotaStatusMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/componentsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/exportConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/favoritesMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/index.ts
  sdk/applicationinsights/arm-appinsights/src/models/mappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/operationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/parameters.ts
  sdk/applicationinsights/arm-appinsights/src/models/proactiveDetectionConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/webTestLocationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/webTestsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/workItemConfigurationsMappers.ts
  sdk/applicationinsights/arm-appinsights/src/models/workbooksMappers.ts
  sdk/applicationinsights/arm-appinsights/src/operations/aPIKeys.ts
  sdk/applicationinsights/arm-appinsights/src/operations/analyticsItems.ts
  sdk/applicationinsights/arm-appinsights/src/operations/annotations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentAvailableFeatures.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentCurrentBillingFeatures.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentFeatureCapabilities.ts
  sdk/applicationinsights/arm-appinsights/src/operations/componentQuotaStatus.ts
  sdk/applicationinsights/arm-appinsights/src/operations/components.ts
  sdk/applicationinsights/arm-appinsights/src/operations/exportConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/favorites.ts
  sdk/applicationinsights/arm-appinsights/src/operations/proactiveDetectionConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/webTestLocations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/webTests.ts
  sdk/applicationinsights/arm-appinsights/src/operations/workItemConfigurations.ts
  sdk/applicationinsights/arm-appinsights/src/operations/workbooks.ts
Labels: RestPRMerged

#3748 [AutoPR batch/data-plane] Fixed SpecPath batch
  sdk/batch/batch/src/batchServiceClient.ts
  sdk/batch/batch/src/batchServiceClientContext.ts
  sdk/batch/batch/src/models/accountMappers.ts
  sdk/batch/batch/src/models/index.ts
  sdk/batch/batch/src/models/mappers.ts
  sdk/batch/batch/src/models/parameters.ts
  sdk/batch/batch/src/operations/account.ts
  sdk/batch/batch/src/operations/application.ts
  sdk/batch/batch/src/operations/certificateOperations.ts
  sdk/batch/batch/src/operations/computeNodeOperations.ts
  sdk/batch/batch/src/operations/file.ts
  sdk/batch/batch/src/operations/job.ts
  sdk/batch/batch/src/operations/jobSchedule.ts
  sdk/batch/batch/src/operations/pool.ts
  sdk/batch/batch/src/operations/task.ts
Labels: RestPRMerged

#3750 [AutoPR notificationhubs/resource-manager] chore: jsonfmt notificationhubs
  sdk/notificationhubs/arm-notificationhubs/LICENSE.txt
  sdk/notificationhubs/arm-notificationhubs/README.md
  sdk/notificationhubs/arm-notificationhubs/package.json
  sdk/notificationhubs/arm-notificationhubs/rollup.config.js
  sdk/notificationhubs/arm-notificationhubs/src/models/index.ts
  sdk/notificationhubs/arm-notificationhubs/src/models/mappers.ts
  sdk/notificationhubs/arm-notificationhubs/src/models/namespacesMappers.ts
  sdk/notificationhubs/arm-notificationhubs/src/models/notificationHubsMappers.ts
  sdk/notificationhubs/arm-notificationhubs/src/models/operationsMappers.ts
  sdk/notificationhubs/arm-notificationhubs/src/notificationHubsManagementClientContext.ts
  sdk/notificationhubs/arm-notificationhubs/src/operations/namespaces.ts
Labels: RestPRMerged

#3752 [AutoPR resources/resource-manager] chore: jsonfmt resources
  sdk/features/arm-features/README.md
  sdk/features/arm-features/package.json
  sdk/links/arm-links/README.md
  sdk/links/arm-links/package.json
  sdk/locks/arm-locks/README.md
  sdk/locks/arm-locks/package.json
  sdk/managedapplications/arm-managedapplications/README.md
  sdk/managedapplications/arm-managedapplications/package.json
  sdk/policy/arm-policy/README.md
  sdk/policy/arm-policy/package.json
  sdk/resources/arm-resources/README.md
  sdk/resources/arm-resources/package.json
Labels: RestPRMerged

#3754 [AutoPR servicebus/resource-manager] chore: jsonfmt servicebus
  sdk/servicebus/arm-servicebus/package.json
Labels: RestPRMerged

#3623 Log requests and response headers
  sdk/storage/storage-blob/samples/javascript/advanced.js
  sdk/storage/storage-blob/src/policies/LoggingPolicy.ts
  sdk/storage/storage-blob/src/utils/constants.ts
  sdk/storage/storage-blob/src/utils/utils.common.ts
  sdk/storage/storage-blob/test/utils.spec.ts
  sdk/storage/storage-file/samples/javascript/advanced.js
  sdk/storage/storage-file/src/policies/LoggingPolicy.ts
  sdk/storage/storage-file/src/utils/constants.ts
  sdk/storage/storage-file/src/utils/utils.common.ts
  sdk/storage/storage-file/test/utils.spec.ts
  sdk/storage/storage-queue/samples/javascript/basic.js
  sdk/storage/storage-queue/src/policies/LoggingPolicy.ts
  sdk/storage/storage-queue/src/utils/constants.ts
  sdk/storage/storage-queue/src/utils/utils.common.ts
  sdk/storage/storage-queue/test/utils.spec.ts
Labels: Client, Storage

#3397 Move lease operations into a separate LeaseClient
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/LeaseClient.ts
  sdk/storage/storage-blob/src/index.browser.ts
  sdk/storage/storage-blob/src/index.ts
  sdk/storage/storage-blob/test/blobclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
  sdk/storage/storage-blob/test/leaseclient.spec.ts
Labels: Client, Storage

#3759 Document @returns for most of public client APIs
  sdk/storage/storage-blob/src/AppendBlobClient.ts
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/BlockBlobClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/PageBlobClient.ts
  sdk/storage/storage-blob/src/Pipeline.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/IPRange.ts
  sdk/storage/storage-file/src/Pipeline.ts
  sdk/storage/storage-file/src/Range.ts
  sdk/storage/storage-file/src/ShareClient.ts
  sdk/storage/storage-queue/src/MessageIdClient.ts
  sdk/storage/storage-queue/src/MessagesClient.ts
  sdk/storage/storage-queue/src/Pipeline.ts
  sdk/storage/storage-queue/src/QueueClient.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/src/utils/utils.common.ts
Labels: Client, Storage

#3765 [AutoPR automation/resource-manager] chore: jsonfmt automation
  sdk/automation/arm-automation/LICENSE.txt
  sdk/automation/arm-automation/README.md
  sdk/automation/arm-automation/package.json
  sdk/automation/arm-automation/rollup.config.js
  sdk/automation/arm-automation/src/automationClient.ts
  sdk/automation/arm-automation/src/automationClientContext.ts
  sdk/automation/arm-automation/src/models/activityOperationsMappers.ts
  sdk/automation/arm-automation/src/models/agentRegistrationInformationMappers.ts
  sdk/automation/arm-automation/src/models/automationAccountOperationsMappers.ts
  sdk/automation/arm-automation/src/models/certificateOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionOperationsMappers.ts
  sdk/automation/arm-automation/src/models/connectionTypeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/credentialOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscCompilationJobStreamMappers.ts
  sdk/automation/arm-automation/src/models/dscConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeConfigurationOperationsMappers.ts
  sdk/automation/arm-automation/src/models/dscNodeOperationsMappers.ts
  sdk/automation/arm-automation/src/models/fieldsMappers.ts
  sdk/automation/arm-automation/src/models/hybridRunbookWorkerGroupOperationsMappers.ts
  sdk/automation/arm-automation/src/models/index.ts
  sdk/automation/arm-automation/src/models/jobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobScheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/jobStreamOperationsMappers.ts
  sdk/automation/arm-automation/src/models/keysMappers.ts
  sdk/automation/arm-automation/src/models/linkedWorkspaceOperationsMappers.ts
  sdk/automation/arm-automation/src/models/mappers.ts
  sdk/automation/arm-automation/src/models/moduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/nodeCountInformationMappers.ts
  sdk/automation/arm-automation/src/models/nodeReportsMappers.ts
  sdk/automation/arm-automation/src/models/objectDataTypesMappers.ts
  sdk/automation/arm-automation/src/models/operationsMappers.ts
  sdk/automation/arm-automation/src/models/python2PackageMappers.ts
  sdk/automation/arm-automation/src/models/runbookDraftOperationsMappers.ts
  sdk/automation/arm-automation/src/models/runbookOperationsMappers.ts
  sdk/automation/arm-automation/src/models/scheduleOperationsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationMachineRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationRunsMappers.ts
  sdk/automation/arm-automation/src/models/softwareUpdateConfigurationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/sourceControlSyncJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/statisticsOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobOperationsMappers.ts
  sdk/automation/arm-automation/src/models/testJobStreamsMappers.ts
  sdk/automation/arm-automation/src/models/usagesMappers.ts
  sdk/automation/arm-automation/src/models/variableOperationsMappers.ts
  sdk/automation/arm-automation/src/models/watcherOperationsMappers.ts
  sdk/automation/arm-automation/src/models/webhookOperationsMappers.ts
  sdk/automation/arm-automation/src/operations/connectionTypeOperations.ts
  sdk/automation/arm-automation/src/operations/nodeCountInformation.ts
Labels: RestPRMerged

#3255 [Storage] Add Blob constructor overloads
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-blob/src/AppendBlobClient.ts
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/BlockBlobClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/PageBlobClient.ts
  sdk/storage/storage-blob/src/utils/utils.common.ts
  sdk/storage/storage-blob/test/appendblobclient.spec.ts
  sdk/storage/storage-blob/test/blobclient.spec.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/blockblobclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
  sdk/storage/storage-blob/test/pageblobclient.spec.ts
  sdk/storage/storage-blob/test/utils.spec.ts
  sdk/storage/storage-blob/test/utils/index.browser.ts
  sdk/storage/storage-blob/test/utils/index.ts
Labels: Client, Storage

#3767 [AutoPR cosmos-db/resource-manager] chore: jsonfmt cosmos-db
  sdk/cosmosdb/arm-cosmosdb/README.md
  sdk/cosmosdb/arm-cosmosdb/package.json
Labels: RestPRMerged

#3675 [JS] [KeyVault] Full list of tests for keyvault-keys
  sdk/keyvault/keyvault-keys/.gitignore
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/tests/CRUD.test.ts
  sdk/keyvault/keyvault-keys/tests/keys.test.ts
  sdk/keyvault/keyvault-keys/tests/list.test.ts
  sdk/keyvault/keyvault-keys/tests/recoverBackupsRestore.test.ts
Labels: Client, KeyVault

#3674 [Storage-blob] Add creation/deletion functions to parent client
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/ShareClient.ts
  sdk/storage/storage-file/test/directoryclient.spec.ts
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
  sdk/storage/storage-file/test/shareclient.spec.ts
Labels: Client, Storage

#3760 [AutoPR servicefabric/data-plane] Swagger specification for Service Fabric runtime version 6.5
  sdk/servicefabric/servicefabric/LICENSE.txt
  sdk/servicefabric/servicefabric/README.md
  sdk/servicefabric/servicefabric/package.json
  sdk/servicefabric/servicefabric/src/models/index.ts
  sdk/servicefabric/servicefabric/src/models/mappers.ts
  sdk/servicefabric/servicefabric/src/models/meshApplicationMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshCodePackageMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshGatewayMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshNetworkMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshSecretMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshSecretValueMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshServiceMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshServiceReplicaMappers.ts
  sdk/servicefabric/servicefabric/src/models/meshVolumeMappers.ts
  sdk/servicefabric/servicefabric/src/models/parameters.ts
  sdk/servicefabric/servicefabric/src/operations/meshApplication.ts
  sdk/servicefabric/servicefabric/src/operations/meshCodePackage.ts
  sdk/servicefabric/servicefabric/src/operations/meshGateway.ts
  sdk/servicefabric/servicefabric/src/operations/meshNetwork.ts
  sdk/servicefabric/servicefabric/src/operations/meshSecret.ts
  sdk/servicefabric/servicefabric/src/operations/meshSecretValue.ts
  sdk/servicefabric/servicefabric/src/operations/meshService.ts
  sdk/servicefabric/servicefabric/src/operations/meshServiceReplica.ts
  sdk/servicefabric/servicefabric/src/operations/meshVolume.ts
  sdk/servicefabric/servicefabric/src/serviceFabricClient.ts
  sdk/servicefabric/servicefabric/src/serviceFabricClientContext.ts
Labels: RestPRMerged

#3315 [Storage-queue] Add constructor overloads
  sdk/storage/storage-blob/src/utils/utils.common.ts
  sdk/storage/storage-queue/src/MessageIdClient.ts
  sdk/storage/storage-queue/src/MessagesClient.ts
  sdk/storage/storage-queue/src/Pipeline.ts
  sdk/storage/storage-queue/src/QueueClient.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/src/utils/utils.common.ts
  sdk/storage/storage-queue/test/messageidclient.spec.ts
  sdk/storage/storage-queue/test/messagesclient.spec.ts
  sdk/storage/storage-queue/test/node/sas.spec.ts
  sdk/storage/storage-queue/test/queueclient.spec.ts
  sdk/storage/storage-queue/test/queueserviceclient.spec.ts
  sdk/storage/storage-queue/test/utils/index.browser.ts
  sdk/storage/storage-queue/test/utils/index.ts
Labels: Client, Storage

#3312 [Storage-file] Add constructor overloads
  sdk/storage/storage-blob/test/containerclient.spec.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/Pipeline.ts
  sdk/storage/storage-file/src/ShareClient.ts
  sdk/storage/storage-file/src/utils/utils.common.ts
  sdk/storage/storage-file/test/directoryclient.spec.ts
  sdk/storage/storage-file/test/fileclient.spec.ts
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
  sdk/storage/storage-file/test/node/sas.spec.ts
  sdk/storage/storage-file/test/shareclient.spec.ts
  sdk/storage/storage-file/test/utils.spec.ts
  sdk/storage/storage-file/test/utils/index.browser.ts
  sdk/storage/storage-file/test/utils/index.ts
Labels: Client, Storage

#3806 [AutoPR mediaservices/resource-manager] [Hub Generated] Review request for Microsoft.Media to add version preview/2019-05-01-preview and stable/2018-07-01
  sdk/mediaservices/arm-mediaservices/package.json
  sdk/mediaservices/arm-mediaservices/src/azureMediaServicesContext.ts
  sdk/mediaservices/arm-mediaservices/src/models/accountFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/assetFiltersMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/assetsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/contentKeyPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/index.ts
  sdk/mediaservices/arm-mediaservices/src/models/jobsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/liveEventsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/liveOutputsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/mappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/mediaservicesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/parameters.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingEndpointsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingLocatorsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/streamingPoliciesMappers.ts
  sdk/mediaservices/arm-mediaservices/src/models/transformsMappers.ts
  sdk/mediaservices/arm-mediaservices/src/operations/accountFilters.ts
  sdk/mediaservices/arm-mediaservices/src/operations/assetFilters.ts
  sdk/mediaservices/arm-mediaservices/src/operations/assets.ts
  sdk/mediaservices/arm-mediaservices/src/operations/contentKeyPolicies.ts
  sdk/mediaservices/arm-mediaservices/src/operations/jobs.ts
  sdk/mediaservices/arm-mediaservices/src/operations/liveEvents.ts
  sdk/mediaservices/arm-mediaservices/src/operations/liveOutputs.ts
  sdk/mediaservices/arm-mediaservices/src/operations/locations.ts
  sdk/mediaservices/arm-mediaservices/src/operations/mediaservices.ts
  sdk/mediaservices/arm-mediaservices/src/operations/operations.ts
  sdk/mediaservices/arm-mediaservices/src/operations/streamingEndpoints.ts
  sdk/mediaservices/arm-mediaservices/src/operations/streamingLocators.ts
  sdk/mediaservices/arm-mediaservices/src/operations/streamingPolicies.ts
  sdk/mediaservices/arm-mediaservices/src/operations/transforms.ts
Labels: RestPRMerged

#3801 Add missing return types
  sdk/storage/storage-blob/src/BlobClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/LeaseClient.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/src/ShareClient.ts
Labels: Client, Storage

#3812 [AutoPR eventhub/resource-manager] Add missing multi-api EventHub
  sdk/eventhub/arm-eventhub/package.json
Labels: RestPRMerged

#3822 [AutoPR devspaces/resource-manager] chore: jsonfmt devspaces
  sdk/devspaces/arm-devspaces/LICENSE.txt
  sdk/devspaces/arm-devspaces/README.md
  sdk/devspaces/arm-devspaces/package.json
  sdk/devspaces/arm-devspaces/rollup.config.js
  sdk/devspaces/arm-devspaces/src/devSpacesManagementClient.ts
  sdk/devspaces/arm-devspaces/src/devSpacesManagementClientContext.ts
  sdk/devspaces/arm-devspaces/src/models/containerHostMappingsMappers.ts
  sdk/devspaces/arm-devspaces/src/models/controllersMappers.ts
  sdk/devspaces/arm-devspaces/src/models/index.ts
  sdk/devspaces/arm-devspaces/src/models/mappers.ts
  sdk/devspaces/arm-devspaces/src/models/operationsMappers.ts
  sdk/devspaces/arm-devspaces/src/models/parameters.ts
  sdk/devspaces/arm-devspaces/src/operations/containerHostMappings.ts
  sdk/devspaces/arm-devspaces/src/operations/controllers.ts
  sdk/devspaces/arm-devspaces/src/operations/index.ts
Labels: RestPRMerged

#3824 [AutoPR mysql/resource-manager] chore: jsonfmt mysql
  sdk/mysql/arm-mysql/LICENSE.txt
  sdk/mysql/arm-mysql/README.md
  sdk/mysql/arm-mysql/package.json
  sdk/mysql/arm-mysql/rollup.config.js
  sdk/mysql/arm-mysql/src/models/checkNameAvailabilityMappers.ts
  sdk/mysql/arm-mysql/src/models/configurationsMappers.ts
  sdk/mysql/arm-mysql/src/models/databasesMappers.ts
  sdk/mysql/arm-mysql/src/models/firewallRulesMappers.ts
  sdk/mysql/arm-mysql/src/models/index.ts
  sdk/mysql/arm-mysql/src/models/locationBasedPerformanceTierMappers.ts
  sdk/mysql/arm-mysql/src/models/logFilesMappers.ts
  sdk/mysql/arm-mysql/src/models/mappers.ts
  sdk/mysql/arm-mysql/src/models/operationsMappers.ts
  sdk/mysql/arm-mysql/src/models/replicasMappers.ts
  sdk/mysql/arm-mysql/src/models/serverSecurityAlertPoliciesMappers.ts
  sdk/mysql/arm-mysql/src/models/serversMappers.ts
  sdk/mysql/arm-mysql/src/models/virtualNetworkRulesMappers.ts
  sdk/mysql/arm-mysql/src/mySQLManagementClientContext.ts
  sdk/mysql/arm-mysql/src/operations/servers.ts
Labels: RestPRMerged

#3832 [AutoPR hdinsight/resource-manager] [HDInsight] Fix syntax error in description of subDomainSuffix parameter
  sdk/hdinsight/arm-hdinsight/package.json
  sdk/hdinsight/arm-hdinsight/src/models/index.ts
  sdk/hdinsight/arm-hdinsight/src/models/mappers.ts
Labels: RestPRMerged

#3843 [AutoPR managementgroups/resource-manager] Add managementGroups/{id}/descendants route to allow pagination of descendants
  sdk/managementgroups/arm-managementgroups/LICENSE.txt
  sdk/managementgroups/arm-managementgroups/README.md
  sdk/managementgroups/arm-managementgroups/package.json
  sdk/managementgroups/arm-managementgroups/rollup.config.js
  sdk/managementgroups/arm-managementgroups/src/managementGroupsAPIContext.ts
  sdk/managementgroups/arm-managementgroups/src/models/entitiesMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/index.ts
  sdk/managementgroups/arm-managementgroups/src/models/managementGroupSubscriptionsMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/managementGroupsMappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/mappers.ts
  sdk/managementgroups/arm-managementgroups/src/models/operationsMappers.ts
  sdk/managementgroups/arm-managementgroups/src/operations/managementGroups.ts
Labels: RestPRMerged

#3770 [AutoPR netapp/resource-manager] chore: jsonfmt netapp
  sdk/netapp/arm-netapp/src/models/index.ts
  sdk/netapp/arm-netapp/src/models/mappers.ts
  sdk/netapp/arm-netapp/src/models/parameters.ts
Labels: RestPRMerged

#3805 [AutoPR cognitiveservices/resource-manager] Add CheckDomainAvailability resource type.
  sdk/cognitiveservices/arm-cognitiveservices/src/cognitiveServicesManagementClient.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/models/accountsMappers.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/models/index.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/models/mappers.ts
Labels: RestPRMerged

#3863 [AutoPR customer-insights/resource-manager] chore: jsonfmt customer-insights
  sdk/customer-insights/arm-customerinsights/LICENSE.txt
  sdk/customer-insights/arm-customerinsights/README.md
  sdk/customer-insights/arm-customerinsights/package.json
  sdk/customer-insights/arm-customerinsights/rollup.config.js
  sdk/customer-insights/arm-customerinsights/src/customerInsightsManagementClientContext.ts
  sdk/customer-insights/arm-customerinsights/src/models/authorizationPoliciesMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/connectorMappingsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/connectorsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/hubsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/imagesMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/index.ts
  sdk/customer-insights/arm-customerinsights/src/models/interactionsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/kpiMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/linksMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/mappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/operationsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/predictionsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/profilesMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/relationshipLinksMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/relationshipsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/roleAssignmentsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/rolesMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/viewsMappers.ts
  sdk/customer-insights/arm-customerinsights/src/models/widgetTypesMappers.ts
  sdk/customer-insights/arm-customerinsights/src/operations/views.ts
Labels: RestPRMerged

#3889 [Event Hubs] support for Azure Identity Creds when creating EventHubClient
  common/config/rush/pnpm-lock.yaml
  sdk/eventhub/event-hubs/package.json
  sdk/eventhub/event-hubs/review/event-hubs.api.md
  sdk/eventhub/event-hubs/samples/interactiveLogin.ts
  sdk/eventhub/event-hubs/samples/loginWithAzureAccount.ts
  sdk/eventhub/event-hubs/samples/usingAadAuth.ts
  sdk/eventhub/event-hubs/src/connectionContext.ts
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/src/index.ts
  sdk/eventhub/event-hubs/src/iothub/iothubClient.ts
  sdk/eventhub/event-hubs/src/linkEntity.ts
Labels: Client, Event Hubs

#3890 [AutoPR apimanagement/resource-manager] Remove restriction on groupId
  sdk/apimanagement/arm-apimanagement/src/models/index.ts
  sdk/apimanagement/arm-apimanagement/src/models/parameters.ts
Labels: RestPRMerged

#3847 [JS] [KeyVault] Added record and playback for keyvault-secrets
  sdk/keyvault/keyvault-secrets/package.json
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_before_all_hook.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_add_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_delete_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_delete_a_secret_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_get_a_deleted_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_get_a_deleted_secret_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_get_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_get_a_secret_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_list_deleted_secrets.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_list_secret_versions_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_list_secrets.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_retrieve_all_versions_of_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_retrieve_the_latest_version_of_a_secret_value.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_set_a_secret_with_attributes.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_set_a_secret_with_empty_value.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_update_a_disabled_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_can_update_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_cannot_create_a_secret_with_a_null_name.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_cannot_create_a_secret_with_an_empty_name.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__create_read_update_and_delete_operations/recording_cant_get_a_disabled_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__list_secrets_in_various_ways/recording_before_all_hook.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__list_secrets_in_various_ways/recording_can_list_deleted_secrets.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__list_secrets_in_various_ways/recording_can_list_secret_versions_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__list_secrets_in_various_ways/recording_can_list_secrets.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__list_secrets_in_various_ways/recording_can_retrieve_all_versions_of_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_before_all_hook.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_backup_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_backup_a_secret_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_recover_a_deleted_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_recover_a_deleted_secret_non_existing.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_restore_a_secret.js
  sdk/keyvault/keyvault-secrets/recordings/node/secret_client__restore_secrets_and_recover_backups/recording_can_restore_a_secret_malformed_backup_bytes.js
  sdk/keyvault/keyvault-secrets/rollup.config.js
  sdk/keyvault/keyvault-secrets/tests/CRUD.test.ts
  sdk/keyvault/keyvault-secrets/tests/list.test.ts
  sdk/keyvault/keyvault-secrets/tests/recoverBackupRestore.test.ts
  sdk/keyvault/keyvault-secrets/tests/utils/recorder.ts
  sdk/keyvault/keyvault-secrets/tests/utils/utils.common.ts
  sdk/keyvault/keyvault-secrets/tsconfig.json
Labels: Client, KeyVault

#3914 [AutoPR cosmos-db/resource-manager] Regex validation for Cosmos DB Accounts
  sdk/cosmosdb/arm-cosmosdb/README.md
  sdk/cosmosdb/arm-cosmosdb/package.json
  sdk/cosmosdb/arm-cosmosdb/src/models/parameters.ts
Labels: RestPRMerged

#3917 [AutoPR azurestack/resource-manager] chore: jsonfmt azurestack
  sdk/azurestack/arm-azurestack/LICENSE.txt
  sdk/azurestack/arm-azurestack/README.md
  sdk/azurestack/arm-azurestack/package.json
  sdk/azurestack/arm-azurestack/rollup.config.js
  sdk/azurestack/arm-azurestack/src/azureStackManagementClientContext.ts
  sdk/azurestack/arm-azurestack/src/models/customerSubscriptionsMappers.ts
  sdk/azurestack/arm-azurestack/src/models/index.ts
  sdk/azurestack/arm-azurestack/src/models/mappers.ts
  sdk/azurestack/arm-azurestack/src/models/operationsMappers.ts
  sdk/azurestack/arm-azurestack/src/models/productsMappers.ts
  sdk/azurestack/arm-azurestack/src/models/registrationsMappers.ts
Labels: RestPRMerged

#3919 [AutoPR databox/resource-manager] chore: jsonfmt databox
  sdk/databox/arm-databox/LICENSE.txt
  sdk/databox/arm-databox/README.md
  sdk/databox/arm-databox/lib/dataBoxManagementClient.ts
  sdk/databox/arm-databox/lib/dataBoxManagementClientContext.ts
  sdk/databox/arm-databox/lib/models/index.ts
  sdk/databox/arm-databox/lib/models/jobsMappers.ts
  sdk/databox/arm-databox/lib/models/mappers.ts
  sdk/databox/arm-databox/lib/models/operationsMappers.ts
  sdk/databox/arm-databox/lib/models/parameters.ts
  sdk/databox/arm-databox/lib/models/serviceMappers.ts
  sdk/databox/arm-databox/lib/operations/index.ts
  sdk/databox/arm-databox/lib/operations/jobs.ts
  sdk/databox/arm-databox/lib/operations/operations.ts
  sdk/databox/arm-databox/lib/operations/service.ts
  sdk/databox/arm-databox/package.json
  sdk/databox/arm-databox/rollup.config.js
  sdk/databox/arm-databox/tsconfig.json
Labels: RestPRMerged

#3906 [AutoPR deploymentmanager/resource-manager] chore: jsonfmt deploymentmanager
  sdk/deploymentmanager/arm-deploymentmanager/LICENSE.txt
  sdk/deploymentmanager/arm-deploymentmanager/README.md
  sdk/deploymentmanager/arm-deploymentmanager/package.json
  sdk/deploymentmanager/arm-deploymentmanager/rollup.config.js
  sdk/deploymentmanager/arm-deploymentmanager/src/azureDeploymentManagerContext.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/artifactSourcesMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/index.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/mappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/operationsMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/rolloutsMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/serviceTopologiesMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/serviceUnitsMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/servicesMappers.ts
  sdk/deploymentmanager/arm-deploymentmanager/src/models/stepsMappers.ts
Labels: RestPRMerged

#3907 [AutoPR machinelearningservices/resource-manager] chore: jsonfmt machinelearningservices
  sdk/machinelearningservices/arm-machinelearningservices/LICENSE.txt
  sdk/machinelearningservices/arm-machinelearningservices/README.md
  sdk/machinelearningservices/arm-machinelearningservices/package.json
  sdk/machinelearningservices/arm-machinelearningservices/rollup.config.js
  sdk/machinelearningservices/arm-machinelearningservices/src/azureMachineLearningWorkspacesContext.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/index.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/machineLearningComputeMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/mappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/operationsMappers.ts
  sdk/machinelearningservices/arm-machinelearningservices/src/models/workspacesMappers.ts
Labels: RestPRMerged

#3925 [AutoPR mariadb/resource-manager] chore: jsonfmt mariadb
  sdk/mariadb/arm-mariadb/README.md
  sdk/mariadb/arm-mariadb/package.json
Labels: RestPRMerged

#3893 [Storage] updates to PagedAsyncIterableIterator interface
  sdk/core/core-paging/types/corePaging.d.ts
  sdk/keyvault/keyvault-keys/review/keyvault-keys.api.md
  sdk/keyvault/keyvault-keys/src/index.ts
  sdk/keyvault/keyvault-secrets/review/keyvault-secrets.api.md
  sdk/keyvault/keyvault-secrets/src/index.ts
Labels: Storage

#2928 [Storage] Proxy support for storage-blob
  sdk/storage/storage-blob/samples/typescript/proxyAuth.ts
  sdk/storage/storage-blob/src/Pipeline.ts
Labels: Client, Storage

#3931 [Event Hubs] Naming changes: feedback from the service team
  sdk/eventhub/event-hubs/review/event-hubs.api.md
  sdk/eventhub/event-hubs/src/batchingReceiver.ts
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/src/eventHubReceiver.ts
  sdk/eventhub/event-hubs/src/eventHubSender.ts
  sdk/eventhub/event-hubs/src/index.ts
  sdk/eventhub/event-hubs/src/receiver.ts
  sdk/eventhub/event-hubs/src/sender.ts
  sdk/eventhub/event-hubs/src/streamingReceiver.ts
  sdk/eventhub/event-hubs/test/client.spec.ts
  sdk/eventhub/event-hubs/test/iothub.spec.ts
  sdk/eventhub/event-hubs/test/misc.spec.ts
  sdk/eventhub/event-hubs/test/receiver.spec.ts
  sdk/eventhub/event-hubs/test/sender.spec.ts
Labels: Client, Event Hubs

#3926 [Event Hubs] Close batching receiver link when returning the events to the user is less than maxMessageCount
  sdk/eventhub/event-hubs/src/receiver.ts
  sdk/eventhub/event-hubs/test/receiver.spec.ts
Labels: Client, Event Hub

#3941 [Storage] Fix browser tests in storage-blob - feature/storage
  sdk/storage/storage-blob/src/Pipeline.ts
Labels: Client, Storage

#3957 [Event Hubs] Add constructor overload that takes connection string and event hubs path
  sdk/core/core-amqp/src/index.ts
  sdk/core/core-http/lib/credentials/tokenCredential.ts
  sdk/eventhub/event-hubs/review/event-hubs.api.md
  sdk/eventhub/event-hubs/samples/getHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/iotGetHubRuntimeInfo.ts
  sdk/eventhub/event-hubs/samples/receiveEventsLoop.ts
  sdk/eventhub/event-hubs/samples/receiveEventsStreaming.ts
  sdk/eventhub/event-hubs/samples/sendEvents.ts
  sdk/eventhub/event-hubs/samples/usingAadAuth.ts
  sdk/eventhub/event-hubs/samples/websockets.ts
  sdk/eventhub/event-hubs/src/eventHubClient.ts
  sdk/eventhub/event-hubs/test/client.spec.ts
  sdk/eventhub/event-hubs/test/hubruntime.spec.ts
  sdk/eventhub/event-hubs/test/misc.spec.ts
  sdk/eventhub/event-hubs/test/receiver.spec.ts
  sdk/eventhub/event-hubs/test/sender.spec.ts
Labels: Client, Event Hubs

#3959 [Storage] Async iterators for listing blobs and containers - storage-blob
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-blob/samples/typescript/iterators-blobs.ts
  sdk/storage/storage-blob/samples/typescript/iterators-containers.ts
  sdk/storage/storage-blob/samples/typescript/iterators.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
Labels: Client, Storage

#3523 [Storage] Async iterator - Paging prototype for storage-queue
  sdk/storage/storage-queue/package.json
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/test/queueserviceclient.spec.ts
Labels: Client, Storage

#3216 [Storage] Async iterators for listing directories, files - storage-file
  sdk/storage/storage-file/package.json
  sdk/storage/storage-file/samples/typescript/iterators-files-and-directories.ts
  sdk/storage/storage-file/samples/typescript/iterators-shares.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/test/directoryclient.spec.ts
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
Labels: Client, Storage

#3911 [JS] [KeyVault] Copyright headers
  sdk/keyvault/keyvault-keys/src/index.ts
  sdk/keyvault/keyvault-keys/src/keysModels.ts
  sdk/keyvault/keyvault-keys/tests/CRUD.test.ts
  sdk/keyvault/keyvault-keys/tests/list.test.ts
  sdk/keyvault/keyvault-keys/tests/recoverBackupRestore.test.ts
  sdk/keyvault/keyvault-keys/tests/utils/index.browser.ts
  sdk/keyvault/keyvault-keys/tests/utils/recorder.ts
  sdk/keyvault/keyvault-keys/tests/utils/utils.common.ts
  sdk/keyvault/keyvault-secrets/src/index.ts
  sdk/keyvault/keyvault-secrets/src/secretsModels.ts
  sdk/keyvault/keyvault-secrets/tests/CRUD.test.ts
  sdk/keyvault/keyvault-secrets/tests/list.test.ts
  sdk/keyvault/keyvault-secrets/tests/recoverBackupRestore.test.ts
  sdk/keyvault/keyvault-secrets/tests/utils/recorder.ts
  sdk/keyvault/keyvault-secrets/tests/utils/utils.common.ts
Labels: Client, KeyVault

#3977 [Storage] Simplify samples for async iterators
  sdk/storage/storage-blob/samples/typescript/iterators-blobs.ts
  sdk/storage/storage-blob/samples/typescript/iterators-containers.ts
  sdk/storage/storage-queue/samples/typescript/iterators.ts
Labels: Client, Storage

#3982 [Storage] update scripts - to run tests in playback mode
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-file/package.json
  sdk/storage/storage-queue/package.json
Labels: Client, Storage

#3983 [Event Hubs] Track 2: Update README
  sdk/eventhub/event-hubs/README.md
Labels: Client

#4017 [Event Hubs] improve consumer tests
  sdk/eventhub/event-hubs/test/receiver.spec.ts
Labels: Event Hubs

#3991 [Storage] Hide segment methods and update tests, samples - storage-blob
  sdk/storage/storage-blob/samples/javascript/basic.js
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/test/blobclient.spec.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/containerclient.spec.ts
  sdk/storage/storage-blob/test/node/blobclient.spec.ts
  sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
  sdk/storage/storage-blob/test/node/sas.spec.ts
  sdk/storage/storage-blob/test/specialnaming.spec.ts
Labels: Client, Storage

#3995 [Storage] Hide segment methods and update tests, samples - storage-file
  sdk/storage/storage-file/samples/javascript/basic.js
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-file/src/DirectoryClient.ts
  sdk/storage/storage-file/src/FileServiceClient.ts
  sdk/storage/storage-file/test/directoryclient.spec.ts
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
  sdk/storage/storage-file/test/node/sas.spec.ts
  sdk/storage/storage-file/test/specialnaming.spec.ts
Labels: Client, Storage

#4003 [Storage] Hide segment methods and update tests, samples - storage-queue
  sdk/storage/storage-queue/samples/javascript/basic.js
  sdk/storage/storage-queue/samples/typescript/basic.ts
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/src/QueueServiceClient.ts
  sdk/storage/storage-queue/test/queueserviceclient.spec.ts
Labels: Client, Storage

#4004 [Storage] Proxy support for storage-file
  sdk/storage/storage-file/samples/typescript/proxyAuth.ts
  sdk/storage/storage-file/src/Pipeline.ts
Labels: Client, Storage

#4020 [Storage] Updating test scripts to run `npm run clean`
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-file/package.json
  sdk/storage/storage-queue/package.json
Labels: Client, Storage

#4031 [Event Hubs] Add test for Azure Identity
  sdk/eventhub/event-hubs/package.json
  sdk/eventhub/event-hubs/test/client.spec.ts
  sdk/eventhub/event-hubs/test/tsconfig.test.json
Labels: Client, Event Hubs

#4007 [Storage] Proxy support for storage-queue
  sdk/storage/storage-queue/samples/typescript/proxyAuth.ts
  sdk/storage/storage-queue/src/Pipeline.ts
Labels: Client, Storage

#4041 [Storage] Proxy support - maintain consistency across storage-packages
  sdk/storage/storage-blob/src/Pipeline.ts
  sdk/storage/storage-file/src/Pipeline.ts
Labels: Client, Storage

#4056 [Storage] Fix build failures and disable playback in PR validations
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-blob/test/blobclient.spec.ts
  sdk/storage/storage-blob/test/blobserviceclient.spec.ts
  sdk/storage/storage-blob/test/leaseclient.spec.ts
  sdk/storage/storage-blob/test/node/blobclient.spec.ts
  sdk/storage/storage-blob/test/node/pageblobclient.spec.ts
  sdk/storage/storage-blob/test/utils/recorder.ts
  sdk/storage/storage-file/package.json
  sdk/storage/storage-file/test/fileserviceclient.spec.ts
  sdk/storage/storage-file/test/utils/recorder.ts
  sdk/storage/storage-queue/package.json
  sdk/storage/storage-queue/test/queueserviceclient.spec.ts
  sdk/storage/storage-queue/test/utils/recorder.ts
Labels: Client, Storage

#4066 [Storage] provide dummy values for conn.string during playback
  sdk/storage/storage-blob/test/utils/recorder.ts
  sdk/storage/storage-file/test/utils/recorder.ts
  sdk/storage/storage-queue/test/utils/recorder.ts
Labels: Client, Storage

#4068 Revert "[Storage] Update versions to preview.1.0 (#4049)"
  sdk/storage/storage-blob/src/utils/constants.ts
  sdk/storage/storage-file/package.json
  sdk/storage/storage-file/src/utils/constants.ts
  sdk/storage/storage-queue/BreakingChanges.md
  sdk/storage/storage-queue/package.json
  sdk/storage/storage-queue/src/utils/constants.ts
Labels: Client, Storage

#3504 [Storage] Guidelines for record and playback
  sdk/storage/CONTRIBUTING.md
  sdk/storage/RecordAndPlayback.md
Labels: Client, Storage

#4112 [Storage] Cleaning duplicated dev dependency
  sdk/storage/storage-file/package.json
  sdk/storage/storage-queue/package.json
Labels: Client, Storage

#4113 [Storage] Add ignore tags for internal attributes
  sdk/storage/storage-blob/src/StorageClient.ts
  sdk/storage/storage-file/src/StorageClient.ts
  sdk/storage/storage-queue/src/StorageClient.ts
Labels: Client, Storage

#3744 Update Storage README
  sdk/storage/CONTRIBUTING.md
  sdk/storage/README.md
  sdk/storage/storage-blob/README.md
  sdk/storage/storage-blob/samples/javascript/basic.js
  sdk/storage/storage-blob/samples/javascript/iterator.js
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-blob/samples/typescript/iterators-blobs.ts
  sdk/storage/storage-blob/samples/typescript/iterators-containers.ts
  sdk/storage/storage-blob/samples/typescript/proxyAuth.ts
  sdk/storage/storage-blob/src/PageBlobClient.ts
  sdk/storage/storage-blob/src/Pipeline.ts
  sdk/storage/storage-blob/src/utils/utils.common.ts
  sdk/storage/storage-file/README.md
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-file/samples/typescript/iterators-files-and-directories.ts
  sdk/storage/storage-file/samples/typescript/proxyAuth.ts
  sdk/storage/storage-file/src/Pipeline.ts
  sdk/storage/storage-file/src/StorageClient.ts
  sdk/storage/storage-file/src/TelemetryPolicyFactory.ts
  sdk/storage/storage-file/src/utils/utils.common.ts
  sdk/storage/storage-file/test/specialnaming.spec.ts
  sdk/storage/storage-queue/README.md
  sdk/storage/storage-queue/samples/javascript/azureAdAuth.js
  sdk/storage/storage-queue/samples/javascript/basic.js
  sdk/storage/storage-queue/samples/typescript/azureAdAuth.ts
  sdk/storage/storage-queue/samples/typescript/basic.ts
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/samples/typescript/proxyAuth.ts
  sdk/storage/storage-queue/src/Pipeline.ts
  sdk/storage/storage-queue/src/TelemetryPolicyFactory.ts
  sdk/storage/storage-queue/test/queueclient.spec.ts
Labels: Client, Storage

#4058 [Storage] Add samples to create clients without pipelines
  sdk/storage/storage-blob/samples/typescript/advanced.ts
  sdk/storage/storage-blob/samples/typescript/anonymousCred.ts
  sdk/storage/storage-blob/samples/typescript/azureAdAuth.ts
  sdk/storage/storage-blob/samples/typescript/basic.ts
  sdk/storage/storage-blob/samples/typescript/customPipeline.ts
  sdk/storage/storage-blob/samples/typescript/iterators-blobs-hierarchy.ts
  sdk/storage/storage-blob/samples/typescript/iterators-blobs.ts
  sdk/storage/storage-blob/samples/typescript/iterators-containers.ts
  sdk/storage/storage-blob/samples/typescript/sharedKeyCred.ts
  sdk/storage/storage-blob/samples/typescript/withConnString.ts
  sdk/storage/storage-file/samples/typescript/advanced.ts
  sdk/storage/storage-file/samples/typescript/anonymousCred.ts
  sdk/storage/storage-file/samples/typescript/basic.ts
  sdk/storage/storage-file/samples/typescript/customPipeline.ts
  sdk/storage/storage-file/samples/typescript/iterators-files-and-directories.ts
  sdk/storage/storage-file/samples/typescript/iterators-shares.ts
  sdk/storage/storage-file/samples/typescript/sharedKeyCred.ts
  sdk/storage/storage-file/samples/typescript/withConnString.ts
  sdk/storage/storage-queue/samples/typescript/anonymousCred.ts
  sdk/storage/storage-queue/samples/typescript/azureAdAuth.ts
  sdk/storage/storage-queue/samples/typescript/customPipeline.ts
  sdk/storage/storage-queue/samples/typescript/iterators.ts
  sdk/storage/storage-queue/samples/typescript/sharedKeyCred.ts
  sdk/storage/storage-queue/samples/typescript/withConnString.ts
Labels: Client, Storage

#4094 [Storage] Update changelog
  sdk/storage/storage-blob/BreakingChanges.md
  sdk/storage/storage-blob/ChangeLog.md
  sdk/storage/storage-file/BreakingChanges.md
  sdk/storage/storage-file/ChangeLog.md
  sdk/storage/storage-queue/BreakingChanges.md
  sdk/storage/storage-queue/ChangeLog.md
Labels: Client, Storage

#4123 [Storage] release notes and more information
  sdk/storage/storage-blob/ChangeLog.md
  sdk/storage/storage-file/ChangeLog.md
  sdk/storage/storage-queue/ChangeLog.md
Labels: Client, Storage

#4130 [Storage] Version update 11.0.0 -> 12.0.0
  sdk/storage/storage-blob/BreakingChanges.md
  sdk/storage/storage-blob/ChangeLog.md
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-blob/src/utils/constants.ts
  sdk/storage/storage-file/BreakingChanges.md
  sdk/storage/storage-file/ChangeLog.md
  sdk/storage/storage-file/package.json
  sdk/storage/storage-file/src/utils/constants.ts
  sdk/storage/storage-queue/BreakingChanges.md
  sdk/storage/storage-queue/ChangeLog.md
  sdk/storage/storage-queue/package.json
  sdk/storage/storage-queue/src/utils/constants.ts
Labels: Client, Storage
