Repository Azure/azure-sdk-for-js, pull requests merged in 2019-01, with the labels that each got.

#882 [AutoPR security/resource-manager] Settings API - changed the kind to work with .net nuget
  packages/@azure/arm-security/LICENSE.txt
  packages/@azure/arm-security/lib/models/advancedThreatProtectionMappers.ts
  packages/@azure/arm-security/lib/models/alertsMappers.ts
  packages/@azure/arm-security/lib/models/autoProvisioningSettingsMappers.ts
  packages/@azure/arm-security/lib/models/compliancesMappers.ts
  packages/@azure/arm-security/lib/models/index.ts
  packages/@azure/arm-security/lib/models/informationProtectionPoliciesMappers.ts
  packages/@azure/arm-security/lib/models/locationsMappers.ts
  packages/@azure/arm-security/lib/models/mappers.ts
  packages/@azure/arm-security/lib/models/pricingsMappers.ts
  packages/@azure/arm-security/lib/models/securityContactsMappers.ts
  packages/@azure/arm-security/lib/models/settingsMappers.ts
  packages/@azure/arm-security/lib/models/tasksMappers.ts
  packages/@azure/arm-security/lib/models/workspaceSettingsMappers.ts
  packages/@azure/arm-security/lib/operations/settings.ts
Labels: RestPRMerged, in progress

#888 Fix missing typings for command line options
  .scripts/commandLine.ts
  gulpfile.ts
Labels: in progress

#890 Remove SDK type parameter demanding
  .scripts/commandLine.ts
Labels: in progress

#553 [AutoPR] storage/resource-manager
  packages/@azure/arm-storage/LICENSE.txt
  packages/@azure/arm-storage/README.md
  packages/@azure/arm-storage/lib/models/blobContainersMappers.ts
  packages/@azure/arm-storage/lib/models/blobServicesMappers.ts
  packages/@azure/arm-storage/lib/models/index.ts
  packages/@azure/arm-storage/lib/models/managementPoliciesMappers.ts
  packages/@azure/arm-storage/lib/models/mappers.ts
  packages/@azure/arm-storage/lib/models/operationsMappers.ts
  packages/@azure/arm-storage/lib/models/parameters.ts
  packages/@azure/arm-storage/lib/models/skusMappers.ts
  packages/@azure/arm-storage/lib/models/storageAccountsMappers.ts
  packages/@azure/arm-storage/lib/models/usagesMappers.ts
  packages/@azure/arm-storage/lib/operations/storageAccounts.ts
  packages/@azure/arm-storage/lib/storageManagementClientContext.ts
  packages/@azure/arm-storage/package.json
  packages/@azure/arm-storage/rollup.config.js
Labels: ServicePR, in progress

#895 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Change from preview to stable for 2018-10-01 ApiVersion
  packages/@azure/arm-storagesync/LICENSE.txt
  packages/@azure/arm-storagesync/lib/models/cloudEndpointsMappers.ts
  packages/@azure/arm-storagesync/lib/models/index.ts
  packages/@azure/arm-storagesync/lib/models/mappers.ts
  packages/@azure/arm-storagesync/lib/models/registeredServersMappers.ts
  packages/@azure/arm-storagesync/lib/models/serverEndpointsMappers.ts
  packages/@azure/arm-storagesync/lib/models/storageSyncServicesMappers.ts
  packages/@azure/arm-storagesync/lib/models/syncGroupsMappers.ts
  packages/@azure/arm-storagesync/lib/models/workflowsMappers.ts
  packages/@azure/arm-storagesync/lib/storageSyncManagementClientContext.ts
Labels: RestPRMerged, in progress

#878 [AutoPR datafactory/resource-manager] [Azure Data Factory] Change Ssis activity property type to support expression
  packages/@azure/arm-datafactory/LICENSE.txt
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#871 Move mocha reporter into pipeline
  .azure-pipelines/client.test.yml
  package.json
Labels: in progress

#891 [AutoPR containerservices/resource-manager] [AKS] add empty resource group validation
  packages/@azure/arm-containerservice/LICENSE.txt
  packages/@azure/arm-containerservice/lib/models/parameters.ts
  packages/@azure/arm-containerservice/lib/operations/containerServices.ts
  packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
  packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts
Labels: RestPRMerged, in progress

#623 [AutoPR] containerregistry/resource-manager
  packages/@azure/arm-containerregistry/LICENSE.txt
  packages/@azure/arm-containerregistry/lib/containerRegistryManagementClientContext.ts
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/lib/models/operationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
  packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
  packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
  packages/@azure/arm-containerregistry/package.json
Labels: ServicePR, in progress

#885 [AutoPR edgegateway/resource-manager] Swagger and examples for Microsoft.DataBoxEdge RP
  packages/@azure/arm-edgedateway/LICENSE.txt
  packages/@azure/arm-edgedateway/README.md
  packages/@azure/arm-edgedateway/lib/dataBoxEdgeManagementClient.ts
  packages/@azure/arm-edgedateway/lib/dataBoxEdgeManagementClientContext.ts
  packages/@azure/arm-edgedateway/lib/models/alertsMappers.ts
  packages/@azure/arm-edgedateway/lib/models/bandwidthSchedulesMappers.ts
  packages/@azure/arm-edgedateway/lib/models/devicesMappers.ts
  packages/@azure/arm-edgedateway/lib/models/index.ts
  packages/@azure/arm-edgedateway/lib/models/mappers.ts
  packages/@azure/arm-edgedateway/lib/models/operationsMappers.ts
  packages/@azure/arm-edgedateway/lib/models/operationsStatusMappers.ts
  packages/@azure/arm-edgedateway/lib/models/ordersMappers.ts
  packages/@azure/arm-edgedateway/lib/models/parameters.ts
  packages/@azure/arm-edgedateway/lib/models/rolesMappers.ts
  packages/@azure/arm-edgedateway/lib/models/sharesMappers.ts
  packages/@azure/arm-edgedateway/lib/models/storageAccountCredentialsMappers.ts
  packages/@azure/arm-edgedateway/lib/models/triggersMappers.ts
  packages/@azure/arm-edgedateway/lib/models/usersMappers.ts
  packages/@azure/arm-edgedateway/lib/operations/alerts.ts
  packages/@azure/arm-edgedateway/lib/operations/bandwidthSchedules.ts
  packages/@azure/arm-edgedateway/lib/operations/devices.ts
  packages/@azure/arm-edgedateway/lib/operations/index.ts
  packages/@azure/arm-edgedateway/lib/operations/operations.ts
  packages/@azure/arm-edgedateway/lib/operations/operationsStatus.ts
  packages/@azure/arm-edgedateway/lib/operations/orders.ts
  packages/@azure/arm-edgedateway/lib/operations/roles.ts
  packages/@azure/arm-edgedateway/lib/operations/shares.ts
  packages/@azure/arm-edgedateway/lib/operations/storageAccountCredentials.ts
  packages/@azure/arm-edgedateway/lib/operations/triggers.ts
  packages/@azure/arm-edgedateway/lib/operations/users.ts
  packages/@azure/arm-edgedateway/package.json
  packages/@azure/arm-edgedateway/rollup.config.js
  packages/@azure/arm-edgedateway/tsconfig.json
Labels: RestPRMerged, in progress

#901 [AutoPR frontdoor/resource-manager] fixing invalid paths in frontdoor
  packages/@azure/arm-frontdoor/LICENSE.txt
  packages/@azure/arm-frontdoor/README.md
  packages/@azure/arm-frontdoor/lib/models/index.ts
  packages/@azure/arm-frontdoor/lib/operations/frontendEndpoints.ts
  packages/@azure/arm-frontdoor/lib/operations/policies.ts
  packages/@azure/arm-frontdoor/package.json
  packages/@azure/arm-frontdoor/rollup.config.js
Labels: RestPRMerged, in progress

#908 [AutoPR apimanagement/resource-manager] OpenAPIv3 support documented
  packages/@azure/arm-apimanagement/LICENSE.txt
Labels: RestPRMerged

#674 [AutoPR] eventgrid/resource-manager
  packages/@azure/arm-eventgrid/LICENSE.txt
  packages/@azure/arm-eventgrid/README.md
  packages/@azure/arm-eventgrid/lib/eventGridManagementClient.ts
  packages/@azure/arm-eventgrid/lib/eventGridManagementClientContext.ts
  packages/@azure/arm-eventgrid/lib/models/domainTopicsMappers.ts
  packages/@azure/arm-eventgrid/lib/models/domainsMappers.ts
  packages/@azure/arm-eventgrid/lib/models/eventSubscriptionsMappers.ts
  packages/@azure/arm-eventgrid/lib/models/index.ts
  packages/@azure/arm-eventgrid/lib/models/mappers.ts
  packages/@azure/arm-eventgrid/lib/models/operationsMappers.ts
  packages/@azure/arm-eventgrid/lib/models/parameters.ts
  packages/@azure/arm-eventgrid/lib/models/topicTypesMappers.ts
  packages/@azure/arm-eventgrid/lib/models/topicsMappers.ts
  packages/@azure/arm-eventgrid/lib/operations/domainTopics.ts
  packages/@azure/arm-eventgrid/lib/operations/domains.ts
  packages/@azure/arm-eventgrid/lib/operations/eventSubscriptions.ts
  packages/@azure/arm-eventgrid/lib/operations/index.ts
  packages/@azure/arm-eventgrid/package.json
  packages/@azure/arm-eventgrid/rollup.config.js
Labels: ServicePR, in progress

#507 [AutoPR] logic/resource-manager
  packages/@azure/arm-logic/LICENSE.txt
  packages/@azure/arm-logic/README.md
  packages/@azure/arm-logic/lib/logicManagementClientContext.ts
  packages/@azure/arm-logic/lib/models/index.ts
  packages/@azure/arm-logic/lib/models/integrationAccountAgreementsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountAssembliesMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountBatchConfigurationsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountCertificatesMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountMapsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountPartnersMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountSchemasMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountSessionsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountsMappers.ts
  packages/@azure/arm-logic/lib/models/mappers.ts
  packages/@azure/arm-logic/lib/models/operationsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRepetitionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRepetitionsRequestHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRequestHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionScopeRepetitionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunOperationsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowTriggerHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowTriggersMappers.ts
  packages/@azure/arm-logic/lib/models/workflowVersionTriggersMappers.ts
  packages/@azure/arm-logic/lib/models/workflowVersionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowsMappers.ts
  packages/@azure/arm-logic/package.json
Labels: ServicePR, in progress

#899 [AutoPR servicebus/resource-manager] Updated as per review comments from ARM Team for Eventhub swagger
  packages/@azure/arm-servicebus/LICENSE.txt
Labels: RestPRMerged, in progress

#912 [AutoPR datafactory/resource-manager] [Datafactory] Add Webhook Activity to Azure Data Factory
  packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
  packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
  packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
  packages/@azure/arm-datafactory/lib/models/triggersMappers.ts
Labels: RestPRMerged, in progress

#918 [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API
  packages/@azure/arm-logic/lib/models/index.ts
  packages/@azure/arm-logic/lib/models/integrationAccountAgreementsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountAssembliesMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountBatchConfigurationsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountCertificatesMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountMapsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountPartnersMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountSchemasMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountSessionsMappers.ts
  packages/@azure/arm-logic/lib/models/integrationAccountsMappers.ts
  packages/@azure/arm-logic/lib/models/mappers.ts
  packages/@azure/arm-logic/lib/models/operationsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRepetitionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRepetitionsRequestHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionRequestHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionScopeRepetitionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunActionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunOperationsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowRunsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowTriggerHistoriesMappers.ts
  packages/@azure/arm-logic/lib/models/workflowTriggersMappers.ts
  packages/@azure/arm-logic/lib/models/workflowVersionTriggersMappers.ts
  packages/@azure/arm-logic/lib/models/workflowVersionsMappers.ts
  packages/@azure/arm-logic/lib/models/workflowsMappers.ts
  packages/@azure/arm-logic/package.json
Labels: RestPRMerged, in progress

#921 [AutoPR] logic/resource-manager
  packages/@azure/arm-logic/lib/logicManagementClientContext.ts
  packages/@azure/arm-logic/lib/models/index.ts
  packages/@azure/arm-logic/lib/models/mappers.ts
  packages/@azure/arm-logic/package.json
Labels: ServicePR, in progress

#922 [AutoPR sql/resource-manager] Fix set LTR policy example
  packages/@azure/arm-sql/LICENSE.txt
  packages/@azure/arm-sql/lib/operations/longTermRetentionBackups.ts
Labels: RestPRMerged, in progress

#926 Regenerate @azure/arm-rediscache package
  packages/@azure/arm-rediscache/LICENSE.txt
  packages/@azure/arm-rediscache/README.md
  packages/@azure/arm-rediscache/lib/models/firewallRulesMappers.ts
  packages/@azure/arm-rediscache/lib/models/index.ts
  packages/@azure/arm-rediscache/lib/models/linkedServerMappers.ts
  packages/@azure/arm-rediscache/lib/models/mappers.ts
  packages/@azure/arm-rediscache/lib/models/operationsMappers.ts
  packages/@azure/arm-rediscache/lib/models/patchSchedulesMappers.ts
  packages/@azure/arm-rediscache/lib/models/redisMappers.ts
  packages/@azure/arm-rediscache/lib/redisManagementClientContext.ts
  packages/@azure/arm-rediscache/package.json
  packages/@azure/arm-rediscache/rollup.config.js
Labels: in progress

#923 [AutoPR eventgrid/data-plane] Add MediaJobOutputProgressEventData in Media Services EventGrid swagger
  packages/@azure/eventgrid/LICENSE.txt
  packages/@azure/eventgrid/lib/models/index.ts
  packages/@azure/eventgrid/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#925 [AutoPR devspaces/resource-manager] Adding API version 2019-01-01-preview for Microsoft.DevSpaces
  packages/@azure/arm-devspaces/LICENSE.txt
  packages/@azure/arm-devspaces/README.md
  packages/@azure/arm-devspaces/lib/devSpacesManagementClient.ts
  packages/@azure/arm-devspaces/lib/devSpacesManagementClientContext.ts
  packages/@azure/arm-devspaces/lib/models/index.ts
  packages/@azure/arm-devspaces/lib/models/mappers.ts
  packages/@azure/arm-devspaces/lib/operations/containerHostMappings.ts
  packages/@azure/arm-devspaces/lib/operations/index.ts
  packages/@azure/arm-devspaces/package.json
  packages/@azure/arm-devspaces/rollup.config.js
Labels: RestPRMerged, in progress

#939 [AutoPR containerregistry/resource-manager] Add target and credentials flag to the requests.
  packages/@azure/arm-containerregistry/lib/models/index.ts
  packages/@azure/arm-containerregistry/lib/models/mappers.ts
  packages/@azure/arm-containerregistry/lib/models/operationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/registriesMappers.ts
  packages/@azure/arm-containerregistry/lib/models/replicationsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/runsMappers.ts
  packages/@azure/arm-containerregistry/lib/models/tasksMappers.ts
  packages/@azure/arm-containerregistry/lib/models/webhooksMappers.ts
  packages/@azure/arm-containerregistry/package.json
Labels: RestPRMerged, in progress

#946 [AutoPR datafactory/resource-manager] Remove webhook activity
  packages/@azure/arm-datafactory/lib/models/datasetsMappers.ts
  packages/@azure/arm-datafactory/lib/models/factoriesMappers.ts
  packages/@azure/arm-datafactory/lib/models/index.ts
  packages/@azure/arm-datafactory/lib/models/integrationRuntimesMappers.ts
  packages/@azure/arm-datafactory/lib/models/linkedServicesMappers.ts
  packages/@azure/arm-datafactory/lib/models/mappers.ts
  packages/@azure/arm-datafactory/lib/models/pipelinesMappers.ts
  packages/@azure/arm-datafactory/lib/models/rerunTriggersMappers.ts
  packages/@azure/arm-datafactory/lib/models/triggersMappers.ts
Labels: RestPRMerged, in progress

#942 [AutoPR edgegateway/resource-manager] typo: edgedateway -> edgegateway
  packages/@azure/arm-edgegateway/LICENSE.txt
  packages/@azure/arm-edgegateway/README.md
  packages/@azure/arm-edgegateway/lib/dataBoxEdgeManagementClient.ts
  packages/@azure/arm-edgegateway/lib/dataBoxEdgeManagementClientContext.ts
  packages/@azure/arm-edgegateway/lib/models/alertsMappers.ts
  packages/@azure/arm-edgegateway/lib/models/bandwidthSchedulesMappers.ts
  packages/@azure/arm-edgegateway/lib/models/devicesMappers.ts
  packages/@azure/arm-edgegateway/lib/models/index.ts
  packages/@azure/arm-edgegateway/lib/models/mappers.ts
  packages/@azure/arm-edgegateway/lib/models/operationsMappers.ts
  packages/@azure/arm-edgegateway/lib/models/operationsStatusMappers.ts
  packages/@azure/arm-edgegateway/lib/models/ordersMappers.ts
  packages/@azure/arm-edgegateway/lib/models/parameters.ts
  packages/@azure/arm-edgegateway/lib/models/rolesMappers.ts
  packages/@azure/arm-edgegateway/lib/models/sharesMappers.ts
  packages/@azure/arm-edgegateway/lib/models/storageAccountCredentialsMappers.ts
  packages/@azure/arm-edgegateway/lib/models/triggersMappers.ts
  packages/@azure/arm-edgegateway/lib/models/usersMappers.ts
  packages/@azure/arm-edgegateway/lib/operations/alerts.ts
  packages/@azure/arm-edgegateway/lib/operations/bandwidthSchedules.ts
  packages/@azure/arm-edgegateway/lib/operations/devices.ts
  packages/@azure/arm-edgegateway/lib/operations/index.ts
  packages/@azure/arm-edgegateway/lib/operations/operations.ts
  packages/@azure/arm-edgegateway/lib/operations/operationsStatus.ts
  packages/@azure/arm-edgegateway/lib/operations/orders.ts
  packages/@azure/arm-edgegateway/lib/operations/roles.ts
  packages/@azure/arm-edgegateway/lib/operations/shares.ts
  packages/@azure/arm-edgegateway/lib/operations/storageAccountCredentials.ts
  packages/@azure/arm-edgegateway/lib/operations/triggers.ts
  packages/@azure/arm-edgegateway/lib/operations/users.ts
  packages/@azure/arm-edgegateway/package.json
  packages/@azure/arm-edgegateway/rollup.config.js
  packages/@azure/arm-edgegateway/tsconfig.json
Labels: RestPRMerged, in progress

#955 [AutoPR iothub/resource-manager] Adding JSON encoding type to storage endpoint
  packages/@azure/arm-iothub/LICENSE.txt
  packages/@azure/arm-iothub/lib/models/index.ts
Labels: RestPRMerged, in progress

#958 [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get
  packages/@azure/arm-security/README.md
  packages/@azure/arm-security/lib/models/index.ts
  packages/@azure/arm-security/lib/models/mappers.ts
  packages/@azure/arm-security/lib/models/parameters.ts
  packages/@azure/arm-security/lib/operations/advancedThreatProtection.ts
  packages/@azure/arm-security/lib/operations/alerts.ts
  packages/@azure/arm-security/lib/operations/allowedConnections.ts
  packages/@azure/arm-security/lib/operations/autoProvisioningSettings.ts
  packages/@azure/arm-security/lib/operations/compliances.ts
  packages/@azure/arm-security/lib/operations/discoveredSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/externalSecuritySolutions.ts
  packages/@azure/arm-security/lib/operations/informationProtectionPolicies.ts
  packages/@azure/arm-security/lib/operations/jitNetworkAccessPolicies.ts
  packages/@azure/arm-security/lib/operations/locations.ts
  packages/@azure/arm-security/lib/operations/operations.ts
  packages/@azure/arm-security/lib/operations/pricings.ts
  packages/@azure/arm-security/lib/operations/securityContacts.ts
  packages/@azure/arm-security/lib/operations/settings.ts
  packages/@azure/arm-security/lib/operations/tasks.ts
  packages/@azure/arm-security/lib/operations/topology.ts
  packages/@azure/arm-security/lib/operations/workspaceSettings.ts
  packages/@azure/arm-security/lib/securityCenter.ts
  packages/@azure/arm-security/lib/securityCenterContext.ts
  packages/@azure/arm-security/package.json
  packages/@azure/arm-security/rollup.config.js
  packages/@azure/arm-security/tsconfig.json
Labels: RestPRMerged, in progress

#966 Enable building Service Bus in the new engineering system
  package.json
Labels: in progress

#962 [AutoPR hdinsight/resource-manager] [HDInsight] - Support MSI for ADLS gen2
  packages/@azure/arm-hdinsight/LICENSE.txt
  packages/@azure/arm-hdinsight/lib/models/index.ts
  packages/@azure/arm-hdinsight/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#951 [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices
  packages/@azure/arm-recoveryservicesbackup/README.md
  packages/@azure/arm-recoveryservicesbackup/lib/models/index.ts
  packages/@azure/arm-recoveryservicesbackup/lib/models/mappers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/models/parameters.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupEngines.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupJobs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupPolicies.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectableItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectedItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectionContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupProtectionIntent.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupResourceStorageConfigs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupResourceVaultConfigs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupStatus.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupUsageSummaries.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backupWorkloadItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/backups.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/exportJobsOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/featureSupport.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/itemLevelRecoveryConnections.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobCancellations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobDetails.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/jobs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/operation.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/operations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectableContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItemOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItemOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectedItems.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainerOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainerRefreshOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionContainers.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionIntentOperations.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicies.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicyOperationResults.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/protectionPolicyOperationStatuses.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/recoveryPoints.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/restores.ts
  packages/@azure/arm-recoveryservicesbackup/lib/operations/securityPINs.ts
  packages/@azure/arm-recoveryservicesbackup/lib/recoveryServicesBackupClient.ts
  packages/@azure/arm-recoveryservicesbackup/lib/recoveryServicesBackupClientContext.ts
  packages/@azure/arm-recoveryservicesbackup/package.json
  packages/@azure/arm-recoveryservicesbackup/rollup.config.js
  packages/@azure/arm-recoveryservicesbackup/tsconfig.json
Labels: RestPRMerged, in progress

#929 [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.
  packages/@azure/arm-cognitiveservices/LICENSE.txt
  packages/@azure/arm-cognitiveservices/lib/models/index.ts
  packages/@azure/arm-cognitiveservices/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#971 Move the remaining changes from the old service bus repo
  packages/@azure/servicebus/data-plane/.vscode/launch.json
  packages/@azure/servicebus/data-plane/examples/README.md
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts
Labels: in progress

#967 Make sure all the files have the copyright header applied.
  packages/@azure/servicebus/data-plane/lib/client.ts
  packages/@azure/servicebus/data-plane/lib/clientEntityContext.ts
  packages/@azure/servicebus/data-plane/lib/connectionContext.ts
  packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/linkEntity.ts
  packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
  packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/messageSender.ts
  packages/@azure/servicebus/data-plane/lib/core/streamingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/index.ts
  packages/@azure/servicebus/data-plane/lib/log.ts
  packages/@azure/servicebus/data-plane/lib/namespace.ts
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/serviceBusMessage.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
  packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
  packages/@azure/servicebus/data-plane/lib/topicClient.ts
  packages/@azure/servicebus/data-plane/lib/util/concurrentExpiringMap.ts
  packages/@azure/servicebus/data-plane/lib/util/constants.ts
  packages/@azure/servicebus/data-plane/lib/util/semaphore.ts
  packages/@azure/servicebus/data-plane/lib/util/utils.ts
  packages/@azure/servicebus/data-plane/rollup.base.config.js
  packages/@azure/servicebus/data-plane/rollup.config.js
  packages/@azure/servicebus/data-plane/rollup.test.config.js
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/maxDeliveryCount.spec.ts
  packages/@azure/servicebus/data-plane/test/namespace.spec.ts
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
  packages/@azure/servicebus/data-plane/test/renewLock.spec.ts
  packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/testUtils.ts
  packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts
Labels: Client, in progress

#974 Use defaults for queue/topic/subscription names in tests
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/maxDeliveryCount.spec.ts
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
  packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
  packages/@azure/servicebus/data-plane/test/testUtils.ts
  packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts
Labels: in progress

#969 Refactor samples for Service Bus
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/movingMessagesToDLQ.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/topicFilters.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesLoop.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/scheduledMessages.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/session.ts
Labels: Client, Service Bus, in progress

#973 Service Bus Streaming Receiver Tests: Partitioned/Unpartitioned - with sessions
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
Labels: Client, Service Bus, in progress

#972 Resolved - Error when settling a deferred msg in a session enabled queue in Service Bus
  packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
  packages/@azure/servicebus/data-plane/lib/serviceBusMessage.ts
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
Labels: Service Bus, in progress

#976 ReceiveBatch Session Error.
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
Labels: Client, Service Bus, bug, in progress

#979 [ServiceBus] - Minor errors in comments corresponding to the Docs
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
Labels: Client, Service Bus, in progress

#884 [AutoPR resources/resource-manager] Adding ResourceGroup example
  packages/@azure/arm-features/LICENSE.txt
  packages/@azure/arm-links/LICENSE.txt
  packages/@azure/arm-locks/LICENSE.txt
  packages/@azure/arm-managedapplications/LICENSE.txt
  packages/@azure/arm-policy/LICENSE.txt
  packages/@azure/arm-resources/LICENSE.txt
Labels: RestPRMerged, in progress

#977 [Service Bus] Refactor tests to create minimal assets for each tests
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
Labels: Service Bus, in progress

#968 [AutoPR containerservice/resource-manager] Renaming containerservice directory for downstream consistency
  packages/@azure/arm-containerservice/LICENSE.txt
  packages/@azure/arm-containerservice/README.md
  packages/@azure/arm-containerservice/lib/models/index.ts
  packages/@azure/arm-containerservice/lib/models/mappers.ts
  packages/@azure/arm-containerservice/lib/models/openShiftManagedClustersMappers.ts
  packages/@azure/arm-containerservice/lib/models/parameters.ts
  packages/@azure/arm-containerservice/lib/operations/containerServices.ts
  packages/@azure/arm-containerservice/lib/operations/managedClusters.ts
  packages/@azure/arm-containerservice/lib/operations/openShiftManagedClusters.ts
  packages/@azure/arm-containerservice/package.json
  packages/@azure/arm-containerservice/rollup.config.js
Labels: RestPRMerged, in progress

#978 [ServiceBus] - Sessions integrated tests
  packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts
  packages/@azure/servicebus/data-plane/test/testUtils.ts
Labels: Client, Service Bus, in progress

#984 [Service Bus] Enable AutoLockRenewal for subscription client
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
Labels: in progress

#985 [Service Bus] - Refactor tests - Streaming Receiver With Sessions
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
Labels: Client, Service Bus, in progress

#982 [Service Bus] - Refactoring Streaming Receiver
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
Labels: Client, Service Bus, in progress

#990 [Service Bus] Enable receiveDeferredMsgs on unpartitioned entities
  packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
Labels: in progress

#997 [Service Bus] - Migrating TestMultipleAbandon from maxDeliveryCount.spec.ts
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/maxDeliveryCount.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
Labels: Client, Service Bus, in progress

#970 [Service Bus] Add tests for Lock Renewal of messages
  packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
  packages/@azure/servicebus/data-plane/test/renewLock.spec.ts
Labels: Client, Service Bus, in progress

#992 [Service Bus] Changes as per preliminary API review
  packages/@azure/servicebus/data-plane/lib/clientEntityContext.ts
  packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/messageSender.ts
  packages/@azure/servicebus/data-plane/lib/core/streamingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/index.ts
  packages/@azure/servicebus/data-plane/lib/namespace.ts
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
  packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
  packages/@azure/servicebus/data-plane/lib/topicClient.ts
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
  packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
Labels: in progress

#999 ReceiveAndDelete Mode : Refactor tests and added new tests.
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
Labels: Client, Service Bus, in progress

#1000 [Service Bus] - Test for defer() in Streaming Receiver in Service Bus pass but with warnings
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
Labels: Client, Service Bus, in progress

#994 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features.
  packages/@azure/cognitiveservices-face/lib/models/index.ts
  packages/@azure/cognitiveservices-face/lib/operations/snapshotOperations.ts
Labels: RestPRMerged, in progress

#1003 [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property
  packages/@azure/arm-containerservice/lib/models/index.ts
  packages/@azure/arm-containerservice/lib/models/mappers.ts
Labels: RestPRMerged, in progress

#1009 [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance
  packages/@azure/arm-hanaonazure/README.md
  packages/@azure/arm-hanaonazure/lib/hanaManagementClient.ts
  packages/@azure/arm-hanaonazure/lib/hanaManagementClientContext.ts
  packages/@azure/arm-hanaonazure/lib/models/index.ts
  packages/@azure/arm-hanaonazure/lib/models/mappers.ts
  packages/@azure/arm-hanaonazure/lib/models/parameters.ts
  packages/@azure/arm-hanaonazure/lib/operations/hanaInstances.ts
  packages/@azure/arm-hanaonazure/lib/operations/operations.ts
  packages/@azure/arm-hanaonazure/package.json
  packages/@azure/arm-hanaonazure/rollup.config.js
  packages/@azure/arm-hanaonazure/tsconfig.json
Labels: RestPRMerged, in progress

#1006 Updated client.yaml for vm parallelization
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
Labels: in progress

#1002 [Service Bus] API updates as per review for Preview 1
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/movingMessagesToDLQ.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/processMessageFromDLQ.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/sessionState.ts
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/topicFilters.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/browseMessages.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesLoop.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/receiveMessagesStreaming.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/scheduledMessages.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/sendMessages.ts
  packages/@azure/servicebus/data-plane/examples/gettingStarted/session.ts
  packages/@azure/servicebus/data-plane/lib/clientEntityContext.ts
  packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/managementClient.ts
  packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/messageSender.ts
  packages/@azure/servicebus/data-plane/lib/core/streamingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/index.ts
  packages/@azure/servicebus/data-plane/lib/namespace.ts
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/receiver.ts
  packages/@azure/servicebus/data-plane/lib/sender.ts
  packages/@azure/servicebus/data-plane/lib/serviceBusMessage.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
  packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
  packages/@azure/servicebus/data-plane/lib/topicClient.ts
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/namespace.spec.ts
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
  packages/@azure/servicebus/data-plane/test/renewLock.spec.ts
  packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
  packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
  packages/@azure/servicebus/data-plane/test/testUtils.ts
  packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts
Labels: in progress

#1014 [Service Bus] Purge queue/subscription before each test
  packages/@azure/servicebus/data-plane/package.json
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/receiveAndDeleteMode.spec.ts
  packages/@azure/servicebus/data-plane/test/renewLock.spec.ts
  packages/@azure/servicebus/data-plane/test/sendSchedule.spec.ts
  packages/@azure/servicebus/data-plane/test/sessionsTests.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
  packages/@azure/servicebus/data-plane/test/testUtils.ts
  packages/@azure/servicebus/data-plane/test/topicFilters.spec.ts
Labels: in progress

#1001 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response
  packages/@azure/cognitiveservices-luis-runtime/LICENSE.txt
  packages/@azure/cognitiveservices-luis-runtime/README.md
  packages/@azure/cognitiveservices-luis-runtime/lib/models/index.ts
  packages/@azure/cognitiveservices-luis-runtime/lib/models/mappers.ts
  packages/@azure/cognitiveservices-luis-runtime/package.json
  packages/@azure/cognitiveservices-luis-runtime/rollup.config.js
Labels: RestPRMerged, in progress

#1016 [Service Bus] Doc updates as per feedback
  packages/@azure/servicebus/data-plane/examples/advancedFeatures/deferral.ts
  packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/messageReceiver.ts
  packages/@azure/servicebus/data-plane/lib/core/streamingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/receiver.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
  packages/@azure/servicebus/data-plane/lib/session/sessionManager.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
Labels: in progress

#1020 [Service Bus] Update readme for tests to include details on expected entities and names
  packages/@azure/servicebus/data-plane/test/README.md
Labels: in progress

#1025 Handling error for receiveBatch() method.
  packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
Labels: Client, Service Bus, in progress

#1027 Update the package-lock.json file after the package version change.
  packages/@azure/servicebus/data-plane/package-lock.json
Labels: in progress

#1028 Fix tests to set purge option to false for DLQs
  packages/@azure/servicebus/data-plane/test/batchReceiver.spec.ts
  packages/@azure/servicebus/data-plane/test/deferredMessage.spec.ts
  packages/@azure/servicebus/data-plane/test/streamingReceiverSessions.spec.ts
Labels: in progress

#515 [AutoPR] hdinsight/resource-manager
  packages/@azure/arm-hdinsight/LICENSE.txt
  packages/@azure/arm-hdinsight/lib/hDInsightManagementClientContext.ts
  packages/@azure/arm-hdinsight/lib/models/applicationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/clustersMappers.ts
  packages/@azure/arm-hdinsight/lib/models/configurationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/extensionsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/index.ts
  packages/@azure/arm-hdinsight/lib/models/locationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/mappers.ts
  packages/@azure/arm-hdinsight/lib/models/operationsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/scriptActionsMappers.ts
  packages/@azure/arm-hdinsight/lib/models/scriptExecutionHistoryMappers.ts
  packages/@azure/arm-hdinsight/package.json
Labels: ServicePR, in progress

#710 [AutoPR] labservices/resource-manager
  packages/@azure/arm-labservices/LICENSE.txt
  packages/@azure/arm-labservices/README.md
  packages/@azure/arm-labservices/lib/managedLabsClient.ts
  packages/@azure/arm-labservices/lib/managedLabsClientContext.ts
  packages/@azure/arm-labservices/lib/models/environmentSettingsMappers.ts
  packages/@azure/arm-labservices/lib/models/environmentsMappers.ts
  packages/@azure/arm-labservices/lib/models/galleryImagesMappers.ts
  packages/@azure/arm-labservices/lib/models/globalUsersMappers.ts
  packages/@azure/arm-labservices/lib/models/index.ts
  packages/@azure/arm-labservices/lib/models/labAccountsMappers.ts
  packages/@azure/arm-labservices/lib/models/labsMappers.ts
  packages/@azure/arm-labservices/lib/models/mappers.ts
  packages/@azure/arm-labservices/lib/models/operationsMappers.ts
  packages/@azure/arm-labservices/lib/models/parameters.ts
  packages/@azure/arm-labservices/lib/models/providerOperationsMappers.ts
  packages/@azure/arm-labservices/lib/models/usersMappers.ts
  packages/@azure/arm-labservices/lib/operations/environmentSettings.ts
  packages/@azure/arm-labservices/lib/operations/environments.ts
  packages/@azure/arm-labservices/lib/operations/galleryImages.ts
  packages/@azure/arm-labservices/lib/operations/globalUsers.ts
  packages/@azure/arm-labservices/lib/operations/index.ts
  packages/@azure/arm-labservices/lib/operations/labAccounts.ts
  packages/@azure/arm-labservices/lib/operations/labs.ts
  packages/@azure/arm-labservices/lib/operations/operations.ts
  packages/@azure/arm-labservices/lib/operations/providerOperations.ts
  packages/@azure/arm-labservices/lib/operations/users.ts
  packages/@azure/arm-labservices/package.json
  packages/@azure/arm-labservices/rollup.config.js
  packages/@azure/arm-labservices/tsconfig.json
Labels: ServicePR, in progress

#981 [AutoPR securityinsights/resource-manager] Creates the "real" API for Scheduled Alert Rules
  packages/@azure/arm-securityinsight/LICENSE.txt
  packages/@azure/arm-securityinsight/README.md
  packages/@azure/arm-securityinsight/lib/models/alertRulesMappers.ts
  packages/@azure/arm-securityinsight/lib/models/index.ts
  packages/@azure/arm-securityinsight/lib/models/mappers.ts
  packages/@azure/arm-securityinsight/lib/models/operationsMappers.ts
  packages/@azure/arm-securityinsight/lib/models/parameters.ts
  packages/@azure/arm-securityinsight/lib/models/scheduledAlertRulesMappers.ts
  packages/@azure/arm-securityinsight/lib/operations/alertRules.ts
  packages/@azure/arm-securityinsight/lib/operations/index.ts
  packages/@azure/arm-securityinsight/lib/operations/operations.ts
  packages/@azure/arm-securityinsight/lib/operations/scheduledAlertRules.ts
  packages/@azure/arm-securityinsight/lib/securityInsights.ts
  packages/@azure/arm-securityinsight/lib/securityInsightsContext.ts
  packages/@azure/arm-securityinsight/package.json
  packages/@azure/arm-securityinsight/rollup.config.js
  packages/@azure/arm-securityinsight/tsconfig.json
Labels: RestPRMerged, in progress

#594 [AutoPR] devtestlabs/resource-manager
  packages/@azure/arm-devtestlabs/LICENSE.txt
  packages/@azure/arm-devtestlabs/README.md
  packages/@azure/arm-devtestlabs/lib/devTestLabsClientContext.ts
  packages/@azure/arm-devtestlabs/lib/models/armTemplatesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/artifactSourcesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/artifactsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/costsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/customImagesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/disksMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/environmentsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/formulasMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/galleryImagesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/globalSchedulesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/index.ts
  packages/@azure/arm-devtestlabs/lib/models/labsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/mappers.ts
  packages/@azure/arm-devtestlabs/lib/models/notificationChannelsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/operationsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/policiesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/policySetsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/providerOperationsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/schedulesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/secretsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/serviceFabricSchedulesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/serviceFabricsMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/serviceRunnersMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/usersMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/virtualMachineSchedulesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/virtualMachinesMappers.ts
  packages/@azure/arm-devtestlabs/lib/models/virtualNetworksMappers.ts
  packages/@azure/arm-devtestlabs/lib/operations/notificationChannels.ts
  packages/@azure/arm-devtestlabs/package.json
  packages/@azure/arm-devtestlabs/rollup.config.js
Labels: ServicePR, in progress

#809 [AutoPR] cognitiveservices/data-plane/ComputerVision
  packages/@azure/cognitiveservices-computervision/LICENSE.txt
  packages/@azure/cognitiveservices-computervision/README.md
  packages/@azure/cognitiveservices-computervision/lib/computerVisionClient.ts
  packages/@azure/cognitiveservices-computervision/lib/computerVisionClientContext.ts
  packages/@azure/cognitiveservices-computervision/lib/models/index.ts
  packages/@azure/cognitiveservices-computervision/lib/models/mappers.ts
  packages/@azure/cognitiveservices-computervision/lib/models/parameters.ts
  packages/@azure/cognitiveservices-computervision/package.json
  packages/@azure/cognitiveservices-computervision/rollup.config.js
Labels: ServicePR, in progress

#1039 Drain pending credits in batching receiver for sessions
  packages/@azure/servicebus/data-plane/lib/core/batchingReceiver.ts
  packages/@azure/servicebus/data-plane/lib/session/messageSession.ts
Labels: in progress

#1013 [AutoPR eventgrid/data-plane] Add Helm Events to ACR Schema for Event Grid
  packages/@azure/eventgrid/README.md
  packages/@azure/eventgrid/lib/eventGridClient.ts
  packages/@azure/eventgrid/lib/eventGridClientContext.ts
  packages/@azure/eventgrid/lib/models/index.ts
  packages/@azure/eventgrid/lib/models/mappers.ts
  packages/@azure/eventgrid/lib/models/parameters.ts
  packages/@azure/eventgrid/package.json
  packages/@azure/eventgrid/rollup.config.js
  packages/@azure/eventgrid/tsconfig.json
Labels: RestPRMerged, in progress

#1034 [AutoPR resourcehealth/resource-manager] Resourcehealth events response
  packages/@azure/arm-resourcehealth/LICENSE.txt
Labels: RestPRMerged, in progress

#1005 [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription
  packages/@azure/arm-eventhub/LICENSE.txt
  packages/@azure/arm-eventhub/README.md
  packages/@azure/arm-eventhub/lib/eventHubManagementClient.ts
  packages/@azure/arm-eventhub/lib/eventHubManagementClientContext.ts
  packages/@azure/arm-eventhub/lib/models/index.ts
  packages/@azure/arm-eventhub/lib/models/mappers.ts
  packages/@azure/arm-eventhub/lib/models/parameters.ts
  packages/@azure/arm-eventhub/lib/operations/consumerGroups.ts
  packages/@azure/arm-eventhub/lib/operations/disasterRecoveryConfigs.ts
  packages/@azure/arm-eventhub/lib/operations/eventHubs.ts
  packages/@azure/arm-eventhub/lib/operations/namespaces.ts
  packages/@azure/arm-eventhub/lib/operations/operations.ts
  packages/@azure/arm-eventhub/lib/operations/regions.ts
  packages/@azure/arm-eventhub/package.json
  packages/@azure/arm-eventhub/rollup.config.js
  packages/@azure/arm-eventhub/tsconfig.json
Labels: RestPRMerged, in progress

#1061 Comment listMessageSessions which doesnt work as expected
  packages/@azure/servicebus/data-plane/lib/queueClient.ts
  packages/@azure/servicebus/data-plane/lib/subscriptionClient.ts
Labels: in progress
