Repository Azure/azure-sdk-for-js, pull requests merged in 2021-10, with the labels that each got.

#17991 Sync eng/common directory with azure-sdk-tools for PR 2060
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#17976 Remove canary test matrix node verison filter
  eng/pipelines/templates/stages/archetype-sdk-tests.yml
Labels: Central-EngSys

#17799 [Perf] Update keyvault-secrets test to match .NET
  sdk/keyvault/perf-tests/keyvault-secrets/package.json
  sdk/keyvault/perf-tests/keyvault-secrets/test/getSecret.spec.ts
  sdk/keyvault/perf-tests/keyvault-secrets/test/listSecrets.spec.ts
  sdk/keyvault/perf-tests/keyvault-secrets/test/secretTest.ts
Labels: KeyVault

#18034 Post release automated changes for keyvault releases
  sdk/keyvault/keyvault-keys/CHANGELOG.md
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/src/constants.ts
  sdk/keyvault/keyvault-keys/src/generated/keyVaultClientContext.ts
  sdk/keyvault/keyvault-keys/swagger/README.md
Labels: auto-merge

#18045 Post release automated changes for servicebus releases
  sdk/servicebus/service-bus/CHANGELOG.md
  sdk/servicebus/service-bus/package.json
  sdk/servicebus/service-bus/samples/v7/javascript/package.json
  sdk/servicebus/service-bus/samples/v7/javascript/sample.env
  sdk/servicebus/service-bus/samples/v7/typescript/package.json
  sdk/servicebus/service-bus/samples/v7/typescript/sample.env
  sdk/servicebus/service-bus/src/util/constants.ts
Labels: auto-merge

#18040 Sync eng/common directory with azure-sdk-tools for PR 2071
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#17986 Re-enable api extractor when building abort-controller
  sdk/core/abort-controller/package.json
Labels: auto-merge

#18051 Post release automated changes for schemaregistry releases
  sdk/schemaregistry/schema-registry-avro/CHANGELOG.md
  sdk/schemaregistry/schema-registry-avro/package.json
  sdk/schemaregistry/schema-registry-avro/samples/v1/javascript/package.json
  sdk/schemaregistry/schema-registry-avro/samples/v1/javascript/schemaRegistryAvroSample.js
  sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/package.json
  sdk/schemaregistry/schema-registry-avro/samples/v1/typescript/src/schemaRegistryAvroSample.ts
Labels: auto-merge

#18059 Sync eng/common directory with azure-sdk-tools for PR 2064
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#18064 [dev-tool] Use host package's TypeScript in module loader.
  common/tools/dev-tool/register.js
Labels: dev-tool

#18424 [Text Analytics] Add links to Custom Text service docs
  sdk/textanalytics/ai-text-analytics/samples-dev/customText.ts
  sdk/textanalytics/ai-text-analytics/src/textAnalyticsClient.ts
Labels: Cognitive - Text Analytics

#18403 Remove Node.js 10 from test matrix
  eng/pipelines/templates/jobs/smoke.tests.yml
  eng/pipelines/templates/stages/platform-matrix.json
  sdk/keyvault/keyvault-admin/platform-matrix.json
  sdk/keyvault/keyvault-keys/platform-matrix.json
Labels: KeyVault
