Repository Azure/azure-sdk-for-js, pull requests merged in 2022-11, with the labels that each got.

#23665 remove team for all Communication requests
  .github/CODEOWNERS
Labels: Communication, Communication - Common, Communication - Identity

#23658 [core-http] Handle special case for `x-ms-text` autorest extension
  sdk/core/core-http/src/serializer.ts
  sdk/core/core-http/test/serializationTests.ts
Labels: Azure.Core

#23663 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23662 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
  sdk/test-utils/recorder/src/recorder.ts
  sdk/test-utils/recorder/test/testProxyClient.spec.ts
Labels: EngSys, Central-EngSys

#23675 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#23671 Remove unnecessary @azure/core-http deps
  dataplane.code-workspace
  sdk/appconfiguration/perf-tests/app-configuration/package.json
  sdk/appconfiguration/perf-tests/app-configuration/test/listSettings.spec.ts
  sdk/communication/communication-email/package.json
  sdk/communication/communication-sms/samples/v1/javascript/package.json
  sdk/communication/communication-sms/samples/v1/typescript/package.json
  sdk/keyvault/keyvault-admin/package.json
  sdk/servicebus/service-bus/test/stress/app/package.json
  sdk/servicebus/service-bus/test/stress/app/src/scenarioShortLivedReceivers.ts
  sdk/template/perf-tests/template/package.json
  sdk/template/perf-tests/template/test/getConfigurationSetting.spec.ts
Labels: EngSys, App Configuration, Communication

#23657 Nikoudsi/batch release 2022 10 01
  sdk/batch/batch/CHANGELOG.md
  sdk/batch/batch/package.json
  sdk/batch/batch/src/batchServiceClientContext.ts
  sdk/batch/batch/src/models/index.ts
  sdk/batch/batch/src/models/mappers.ts
  sdk/batch/batch/test/batchClient.spec.ts
Labels: Batch

#23680 [core-http] should use options.xmlCharKey if specified
  sdk/core/core-http/src/serializer.ts
  sdk/core/core-http/test/serializationTests.ts
Labels: Azure.Core

#23681 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#23504 Kind property for deserializer
  sdk/communication/communication-common/CHANGELOG.md
  sdk/communication/communication-common/package.json
  sdk/communication/communication-common/review/communication-common.api.md
  sdk/communication/communication-common/src/identifierModelSerializer.ts
  sdk/communication/communication-common/test/identifierModelSerializer.spec.ts
Labels: Communication, Communication - Identity

#23691 Prepare @azure/communication-common 2.2.0 for release
  sdk/communication/communication-common/CHANGELOG.md
Labels: Communication

#23695 Post release automated changes for communication releases
  sdk/communication/communication-common/CHANGELOG.md
  sdk/communication/communication-common/package.json
Labels: auto-merge, Communication

#23694 Revert "add move operation"
  sdk/cosmosdb/cosmos/review/cosmos.api.md
  sdk/cosmosdb/cosmos/samples/v3/javascript/ItemManagement.js
  sdk/cosmosdb/cosmos/src/index.ts
  sdk/cosmosdb/cosmos/src/utils/patch.ts
  sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts
Labels: Cosmos

#23562 [recorder] Remove recorder dependency from packages without recorded tests
  sdk/digitaltwins/dtdl-parser/karma.conf.js
  sdk/digitaltwins/dtdl-parser/package.json
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/karma.conf.js
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
  sdk/storage/storage-internal-avro/karma.conf.js
  sdk/storage/storage-internal-avro/package.json
  sdk/web-pubsub/web-pubsub-express/karma.conf.js
  sdk/web-pubsub/web-pubsub-express/package.json
Labels: Storage, Digital Twins, WebPubSub

#23700 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#23703 Post release automated changes for core releases
  sdk/core/core-paging/CHANGELOG.md
  sdk/core/core-paging/package.json
Labels: Azure.Core, auto-merge

#23669 [core] Prepare for 2022 November release
  sdk/core/core-amqp/CHANGELOG.md
  sdk/core/core-amqp/package.json
  sdk/core/core-http/CHANGELOG.md
  sdk/core/core-rest-pipeline/CHANGELOG.md
  sdk/core/core-rest-pipeline/package.json
  sdk/core/core-rest-pipeline/src/constants.ts
Labels: Azure.Core

#23517 add multivariate anomaly detetor sample for v1.1
  common/config/rush/pnpm-lock.yaml
  eng/ignore-links.txt
  rush.json
  sdk/anomalydetector/ai-anomaly-detector-rest/.eslintrc.json
  sdk/anomalydetector/ai-anomaly-detector-rest/LICENSE
  sdk/anomalydetector/ai-anomaly-detector-rest/README.md
  sdk/anomalydetector/ai-anomaly-detector-rest/api-extractor.json
  sdk/anomalydetector/ai-anomaly-detector-rest/karma.conf.js
  sdk/anomalydetector/ai-anomaly-detector-rest/package.json
  sdk/anomalydetector/ai-anomaly-detector-rest/review/ai-anomaly-detector.api.md
  sdk/anomalydetector/ai-anomaly-detector-rest/sample.env
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/example-data/request-data.csv
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_change_point.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_entire_series_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_last_point_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_multivariate_detection.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/README.md
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/package.json
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/sample.env
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/sample_detect_change_point.js
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/sample_detect_entire_series_anomaly.js
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/sample_detect_last_point_anomaly.js
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/javascript/sample_multivariate_detection.js
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/README.md
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/package.json
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/sample.env
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_change_point.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_entire_series_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_last_point_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_multivariate_detection.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/tsconfig.json
  sdk/anomalydetector/ai-anomaly-detector-rest/src/anomalyDetectorRest.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/clientDefinitions.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/index.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/isUnexpected.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/models.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/outputModels.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/paginateHelper.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/parameters.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/pollingHelper.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/src/responses.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/swagger/README.md
  sdk/anomalydetector/ai-anomaly-detector-rest/test/public/anomalydetector.spec.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/test/public/utils/env.browser.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/test/public/utils/env.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/test/public/utils/recordedClient.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/tsconfig.json
Labels: customer-reported, auto-merge

#23711 Post release automated changes for core releases
  sdk/core/core-amqp/CHANGELOG.md
  sdk/core/core-amqp/package.json
  sdk/core/core-rest-pipeline/CHANGELOG.md
  sdk/core/core-rest-pipeline/package.json
  sdk/core/core-rest-pipeline/src/constants.ts
Labels: Azure.Core, auto-merge

#23692 datafactory release
  common/config/rush/pnpm-lock.yaml
  sdk/datafactory/arm-datafactory/CHANGELOG.md
  sdk/datafactory/arm-datafactory/_meta.json
  sdk/datafactory/arm-datafactory/package.json
  sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_create_test.json
  sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_delete_test.json
  sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_get_test.json
  sdk/datafactory/arm-datafactory/recordings/node/datafactory_test/recording_datafactory_list_test.json
  sdk/datafactory/arm-datafactory/review/arm-datafactory.api.md
  sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
  sdk/datafactory/arm-datafactory/src/index.ts
  sdk/datafactory/arm-datafactory/src/models/index.ts
  sdk/datafactory/arm-datafactory/src/models/mappers.ts
  sdk/datafactory/arm-datafactory/src/operations/dataFlowDebugSession.ts
  sdk/datafactory/arm-datafactory/src/operations/dataFlows.ts
  sdk/datafactory/arm-datafactory/src/operations/datasets.ts
  sdk/datafactory/arm-datafactory/src/operations/factories.ts
  sdk/datafactory/arm-datafactory/src/operations/globalParameters.ts
  sdk/datafactory/arm-datafactory/src/operations/integrationRuntimes.ts
  sdk/datafactory/arm-datafactory/src/operations/linkedServices.ts
  sdk/datafactory/arm-datafactory/src/operations/managedPrivateEndpoints.ts
  sdk/datafactory/arm-datafactory/src/operations/managedVirtualNetworks.ts
  sdk/datafactory/arm-datafactory/src/operations/operations.ts
  sdk/datafactory/arm-datafactory/src/operations/pipelines.ts
  sdk/datafactory/arm-datafactory/src/operations/privateEndPointConnections.ts
  sdk/datafactory/arm-datafactory/src/operations/triggers.ts
  sdk/datafactory/arm-datafactory/src/pagingHelper.ts
Labels: Mgmt

#23697 [language text] add script and auto language detection tests
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyze_languagedetection/recording_service_returns_script_with_detectlanguageinput.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_general_behavior/recording_whole_batch_input_with_auto_language_detection.json
  sdk/cognitivelanguage/ai-language-text/test/public/analyze.spec.ts
  sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
  sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts
Labels: Cognitive - Language

#23719 Post release automated changes for notificationhubs releases
  sdk/notificationhubs/notification-hubs/CHANGELOG.md
  sdk/notificationhubs/notification-hubs/package.json
  sdk/notificationhubs/notification-hubs/src/utils/constants.ts
Labels: auto-merge

#23710 Post release automated changes for entra releases
  sdk/entra/functions-authentication-events/CHANGELOG.md
  sdk/entra/functions-authentication-events/package.json
Labels: auto-merge

#23728 [@azure-rest/ai-anomaly-detector] remove unused export in sample
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_change_point.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_entire_series_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples-dev/sample_detect_last_point_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_change_point.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_entire_series_anomaly.ts
  sdk/anomalydetector/ai-anomaly-detector-rest/samples/v1-beta/typescript/src/sample_detect_last_point_anomaly.ts
Labels: Client, Cognitive - Anomaly Detector

#23704 [identity] Fix MSAL Flow additionallyAllowedTenantIds to pass through
  sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
  sdk/identity/identity/src/msal/nodeFlows/msalOpenBrowser.ts
  sdk/identity/identity/src/util/processMultiTenantRequest.browser.ts
  sdk/identity/identity/src/util/processMultiTenantRequest.ts
  sdk/identity/identity/test/httpRequests.browser.ts
  sdk/identity/identity/test/httpRequests.ts
  sdk/identity/identity/test/internal/node/clientAssertionCredential.spec.ts
  sdk/identity/identity/test/internal/node/onBehalfOfCredential.spec.ts
Labels: Azure.Identity

#23660 [core-http] mark de-serialized XML properties as handled
  sdk/core/core-http/src/serializer.ts
  sdk/core/core-http/test/serializationTests.ts
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-blob/src/ContainerClient.ts
  sdk/storage/storage-blob/src/generated/src/models/mappers.ts
  sdk/storage/storage-blob/src/utils/utils.common.ts
Labels: Azure.Core

#23670 [ServiceBus] prepare for 2022 November release
  sdk/servicebus/service-bus/CHANGELOG.md
Labels: Service Bus

#23737 [keyvault-admin] depend on keyvault-common
  sdk/keyvault/keyvault-admin/api-extractor.json
  sdk/keyvault/keyvault-admin/package.json
  sdk/keyvault/keyvault-admin/src/accessControlClient.ts
  sdk/keyvault/keyvault-admin/src/backupClient.ts
  sdk/keyvault/keyvault-admin/tsconfig.json
  sdk/keyvault/keyvault-common/package.json
Labels: KeyVault

#23734 [identity] Fix MSAL Flow additionallyAllowedTenants to pass through
  sdk/identity/identity/src/credentials/interactiveBrowserCredential.browser.ts
  sdk/identity/identity/src/msal/browserFlows/msalBrowserCommon.ts
  sdk/identity/identity/src/msal/nodeFlows/msalNodeCommon.ts
  sdk/identity/identity/test/internal/tenantIdUtils.spec.ts
Labels: Azure.Identity

#23742 Post release automated changes for core releases
  sdk/core/core-http/CHANGELOG.md
  sdk/core/core-http/package.json
  sdk/core/core-http/src/util/constants.ts
Labels: Azure.Core, auto-merge

#23721 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#23745 Post release automated changes for identity releases
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/package.json
  sdk/identity/identity/src/constants.ts
Labels: Azure.Identity, auto-merge

#23744 [identity] Merge Hotfix/identity 3.0.1 into main and 3.1.0 GA release prep
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/package.json
  sdk/identity/identity/src/constants.ts
Labels: Azure.Identity

#23727 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23757 [identity] update changelog for 3.1.0 GA release
  sdk/identity/identity/CHANGELOG.md
Labels: Azure.Identity

#23740 [EventGrid] Update Healthcare Events, Prepare for Nov Release
  .vscode/cspell.json
  sdk/eventgrid/eventgrid/CHANGELOG.md
  sdk/eventgrid/eventgrid/package.json
  sdk/eventgrid/eventgrid/review/eventgrid.api.md
  sdk/eventgrid/eventgrid/src/eventGridClient.ts
  sdk/eventgrid/eventgrid/src/generated/generatedClient.ts
  sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
  sdk/eventgrid/eventgrid/src/generated/models/index.ts
  sdk/eventgrid/eventgrid/src/generated/models/mappers.ts
  sdk/eventgrid/eventgrid/src/index.ts
  sdk/eventgrid/eventgrid/src/predicates.ts
  sdk/eventgrid/eventgrid/src/tracing.ts
  sdk/eventgrid/eventgrid/swagger/README.md
Labels: Event Grid

#23758 Post release automated changes for servicebus releases
  sdk/servicebus/service-bus/CHANGELOG.md
  sdk/servicebus/service-bus/package.json
  sdk/servicebus/service-bus/src/util/constants.ts
Labels: Service Bus, auto-merge

#23709 Update average duration time when a request fails or succeeds.
  sdk/monitor/monitor-opentelemetry-exporter/src/export/base.ts
  sdk/monitor/monitor-opentelemetry-exporter/src/export/statsbeat/statsbeatMetrics.ts
  sdk/monitor/monitor-opentelemetry-exporter/test/internal/statsbeat.test.ts
Labels: Monitor

#23705 [Azure Monitor OpenTelemetry Exporter] 1.0.0-beta.10 release
  sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/monitor-opentelemetry-exporter/package.json
  sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
  sdk/monitor/monitor-opentelemetry-exporter/swagger/README.md
Labels: Monitor

#23760 Post release automated changes for eventgrid releases
  sdk/eventgrid/eventgrid/CHANGELOG.md
  sdk/eventgrid/eventgrid/package.json
  sdk/eventgrid/eventgrid/src/generated/generatedClientContext.ts
  sdk/eventgrid/eventgrid/src/tracing.ts
  sdk/eventgrid/eventgrid/swagger/README.md
Labels: Event Grid, auto-merge

#23741 [keyvault] keyvault-common: Prepare release
  sdk/keyvault/keyvault-common/CHANGELOG.md
Labels: KeyVault

#23770 Post release automated changes for hybridcontainerservice releases
  sdk/hybridcontainerservice/arm-hybridcontainerservice/CHANGELOG.md
  sdk/hybridcontainerservice/arm-hybridcontainerservice/package.json
  sdk/hybridcontainerservice/arm-hybridcontainerservice/src/hybridContainerServiceClient.ts
Labels: auto-merge

#23775 Use deployment/approval for npm admin task pipeline
  eng/pipelines/npm-tasks.yml
Labels: auto-merge, Central-EngSys

#23761 fix: search-documents - modified mocha tests to use function keyword instead of arrow syntax
  sdk/search/search-documents/test/internal/base64.spec.ts
  sdk/search/search-documents/test/internal/browser/synonymMap.browser.spec.ts
  sdk/search/search-documents/test/internal/geographyPoint.spec.ts
  sdk/search/search-documents/test/internal/node/synonymMap.node.spec.ts
  sdk/search/search-documents/test/internal/serialization.spec.ts
  sdk/search/search-documents/test/internal/serviceUtils.spec.ts
  sdk/search/search-documents/test/public/odata.spec.ts
Labels: customer-reported, Search

#23773 [core-http] bump major version to v3
  common/config/rush/pnpm-lock.yaml
  sdk/core/core-http/CHANGELOG.md
  sdk/core/core-http/package.json
  sdk/core/core-http/src/util/constants.ts
  sdk/storage/storage-blob/package.json
Labels: Azure.Core

#23777 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#23646 [core-amqp] request response link should reject when sender error
  sdk/core/core-amqp/CHANGELOG.md
  sdk/core/core-amqp/src/requestResponseLink.ts
  sdk/core/core-amqp/test/requestResponse.spec.ts
  sdk/servicebus/service-bus/test/public/sendAndSchedule.spec.ts
Labels: Azure.Core

#23779 [ServiceBus] resolve received messages immediately when we got extra
  sdk/servicebus/service-bus/src/core/batchingReceiver.ts
Labels: Service Bus

#23652 Update Item batch operation method signature
  sdk/cosmosdb/cosmos/review/cosmos.api.md
  sdk/cosmosdb/cosmos/src/client/Item/Items.ts
  sdk/cosmosdb/cosmos/test/public/functional/item.spec.ts
Labels: Cosmos

#23688 resources regenerate
  common/config/rush/pnpm-lock.yaml
  sdk/resources/arm-resources/CHANGELOG.md
  sdk/resources/arm-resources/_meta.json
  sdk/resources/arm-resources/package.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_create_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_create_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_delete_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_delete_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_get_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_get_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_list_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_list_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_update_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_resourcegroups_update_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_create_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_create_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_delete_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_delete_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_get_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_get_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_list_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_list_test.json
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_update_test.js
  sdk/resources/arm-resources/recordings/node/resources_test/recording_tagsoperations_update_test.json
  sdk/resources/arm-resources/review/arm-resources.api.md
  sdk/resources/arm-resources/samples/v5/typescript/package.json
  sdk/resources/arm-resources/src/index.ts
  sdk/resources/arm-resources/src/models/index.ts
  sdk/resources/arm-resources/src/operations/deploymentOperations.ts
  sdk/resources/arm-resources/src/operations/deployments.ts
  sdk/resources/arm-resources/src/operations/operations.ts
  sdk/resources/arm-resources/src/operations/providers.ts
  sdk/resources/arm-resources/src/operations/resourceGroups.ts
  sdk/resources/arm-resources/src/operations/resources.ts
  sdk/resources/arm-resources/src/operations/tagsOperations.ts
  sdk/resources/arm-resources/src/pagingHelper.ts
  sdk/resources/arm-resources/src/resourceManagementClient.ts
  sdk/resources/arm-resources/test/resources_examples.ts
Labels: Mgmt

#23789 fix: attestation - remove mocha arrow functions
  sdk/attestation/attestation/test/browser/attestationTests.browser.spec.ts
  sdk/attestation/attestation/test/public/attestationTests.spec.ts
  sdk/attestation/attestation/test/public/attestationTokenTests.spec.ts
  sdk/attestation/attestation/test/public/policyGetSetTests.spec.ts
  sdk/attestation/attestation/test/public/policyManagementGetSetTests.spec.ts
  sdk/attestation/attestation/test/public/tokenCertTests.spec.ts
Labels: customer-reported, Attestation

#23791 [keyvault] Prepare beta release for keyvault-admin and keyvault-keys
  sdk/keyvault/keyvault-admin/CHANGELOG.md
  sdk/keyvault/keyvault-keys/CHANGELOG.md
  sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
Labels: KeyVault

#23795 [keyvault] keyvault-admin: fix user agent integration test
  sdk/keyvault/keyvault-admin/test/internal/userAgent.spec.ts
Labels: KeyVault

#23796 Sync eng/common directory with azure-sdk-tools for PR 4623
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#23797 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23799 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23793 Post release automated changes for devcenter releases
  sdk/devcenter/developer-devcenter-rest/CHANGELOG.md
  sdk/devcenter/developer-devcenter-rest/package.json
  sdk/devcenter/developer-devcenter-rest/swagger/README.md
Labels: auto-merge

#23801 [Identity] Fix identity InteractiveBrowserCredential app with webpack example (for browser)
  sdk/identity/identity/test/manual/interactive-browser-credential/index.html
  sdk/identity/identity/test/manual/interactive-browser-credential/package.json
  sdk/identity/identity/test/manual/interactive-browser-credential/webpack.config.js
Labels: Azure.Identity

#23784 Fix core-lro version for purview catalog version
  common/config/rush/pnpm-lock.yaml
  sdk/purview/purview-catalog-rest/package.json
Labels: Purview

#23768 refresh subscriptions
  common/config/rush/pnpm-lock.yaml
  sdk/subscription/arm-subscriptions/CHANGELOG.md
  sdk/subscription/arm-subscriptions/_meta.json
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/recordings/node/my_test/recording_sample_test.js
  sdk/subscription/arm-subscriptions/recordings/node/my_test/recording_sample_test.json
  sdk/subscription/arm-subscriptions/review/arm-subscriptions.api.md
  sdk/subscription/arm-subscriptions/samples/v5/typescript/package.json
  sdk/subscription/arm-subscriptions/src/index.ts
  sdk/subscription/arm-subscriptions/src/models/index.ts
  sdk/subscription/arm-subscriptions/src/models/mappers.ts
  sdk/subscription/arm-subscriptions/src/operations/operations.ts
  sdk/subscription/arm-subscriptions/src/operations/subscriptionPolicy.ts
  sdk/subscription/arm-subscriptions/src/operations/subscriptions.ts
  sdk/subscription/arm-subscriptions/src/operations/tenants.ts
  sdk/subscription/arm-subscriptions/src/pagingHelper.ts
  sdk/subscription/arm-subscriptions/src/subscriptionClient.ts
  sdk/subscription/arm-subscriptions/test/sampleTest.ts
Labels: Mgmt

#23817 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#23821 refresh 1
  common/config/rush/pnpm-lock.yaml
  sdk/advisor/arm-advisor/CHANGELOG.md
  sdk/advisor/arm-advisor/_meta.json
  sdk/advisor/arm-advisor/package.json
  sdk/advisor/arm-advisor/recordings/node/my_test/recording_sample_test.js
  sdk/advisor/arm-advisor/recordings/node/my_test/recording_sample_test.json
  sdk/advisor/arm-advisor/review/arm-advisor.api.md
  sdk/advisor/arm-advisor/samples/v3/typescript/package.json
  sdk/advisor/arm-advisor/src/advisorManagementClient.ts
  sdk/advisor/arm-advisor/src/index.ts
  sdk/advisor/arm-advisor/src/models/index.ts
  sdk/advisor/arm-advisor/src/operations/configurations.ts
  sdk/advisor/arm-advisor/src/operations/operations.ts
  sdk/advisor/arm-advisor/src/operations/recommendationMetadata.ts
  sdk/advisor/arm-advisor/src/operations/recommendations.ts
  sdk/advisor/arm-advisor/src/operations/suppressions.ts
  sdk/advisor/arm-advisor/src/pagingHelper.ts
  sdk/advisor/arm-advisor/test/sampleTest.ts
  sdk/agrifood/arm-agrifood/CHANGELOG.md
  sdk/agrifood/arm-agrifood/_meta.json
  sdk/agrifood/arm-agrifood/package.json
  sdk/agrifood/arm-agrifood/review/arm-agrifood.api.md
  sdk/agrifood/arm-agrifood/samples/v1-beta/typescript/package.json
  sdk/agrifood/arm-agrifood/src/agriFoodMgmtClient.ts
  sdk/agrifood/arm-agrifood/src/index.ts
  sdk/agrifood/arm-agrifood/src/operations/extensions.ts
  sdk/agrifood/arm-agrifood/src/operations/farmBeatsExtensions.ts
  sdk/agrifood/arm-agrifood/src/operations/farmBeatsModels.ts
  sdk/agrifood/arm-agrifood/src/operations/operations.ts
  sdk/agrifood/arm-agrifood/src/operations/privateEndpointConnections.ts
  sdk/agrifood/arm-agrifood/src/operations/privateLinkResources.ts
  sdk/agrifood/arm-agrifood/src/pagingHelper.ts
  sdk/analysisservices/arm-analysisservices/CHANGELOG.md
  sdk/analysisservices/arm-analysisservices/_meta.json
  sdk/analysisservices/arm-analysisservices/package.json
  sdk/analysisservices/arm-analysisservices/review/arm-analysisservices.api.md
  sdk/analysisservices/arm-analysisservices/src/azureAnalysisServices.ts
  sdk/analysisservices/arm-analysisservices/src/index.ts
  sdk/analysisservices/arm-analysisservices/src/operations/operations.ts
  sdk/analysisservices/arm-analysisservices/src/operations/servers.ts
  sdk/analysisservices/arm-analysisservices/src/pagingHelper.ts
Labels: Mgmt

#23823 Post release automated changes for subscription releases
  sdk/subscription/arm-subscriptions/CHANGELOG.md
  sdk/subscription/arm-subscriptions/package.json
  sdk/subscription/arm-subscriptions/src/subscriptionClient.ts
Labels: Mgmt, auto-merge

#23824 Post release automated changes for resources releases
  sdk/resources/arm-resources/CHANGELOG.md
  sdk/resources/arm-resources/package.json
  sdk/resources/arm-resources/src/resourceManagementClient.ts
Labels: Mgmt, auto-merge

#23828 Post release automated changes for analysisservices releases
  sdk/analysisservices/arm-analysisservices/CHANGELOG.md
  sdk/analysisservices/arm-analysisservices/package.json
  sdk/analysisservices/arm-analysisservices/src/azureAnalysisServices.ts
Labels: Mgmt, auto-merge

#23829 Post release automated changes for advisor releases
  sdk/advisor/arm-advisor/CHANGELOG.md
  sdk/advisor/arm-advisor/package.json
  sdk/advisor/arm-advisor/src/advisorManagementClient.ts
Labels: Mgmt, auto-merge

#23835 fix: batch: remove mocha arrow functions
  sdk/batch/batch/test/batchClient.spec.ts
Labels: customer-reported, Batch

#23836 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#23850 fix: ai-language-conversations: remove mocha arrow functions
  sdk/cognitivelanguage/ai-language-conversations/test/public/analyze.spec.ts
Labels: customer-reported

#23856 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#23854 [ServiceBus] move a logging line to a better place
  sdk/servicebus/service-bus/src/core/batchingReceiver.ts
  sdk/servicebus/service-bus/src/receivers/receiver.ts
Labels: Service Bus

#23844 Post release automated changes for appcomplianceautomation releases
  sdk/appcomplianceautomation/arm-appcomplianceautomation/CHANGELOG.md
  sdk/appcomplianceautomation/arm-appcomplianceautomation/package.json
  sdk/appcomplianceautomation/arm-appcomplianceautomation/src/appComplianceAutomationToolForMicrosoft365.ts
Labels: auto-merge

#23405 Integrate Asset-Sync Features
  .gitignore
  sdk/test-utils/recorder/karma.conf.js
  sdk/test-utils/recorder/src/index.ts
  sdk/test-utils/recorder/src/recorder.ts
  sdk/test-utils/recorder/src/utils/createRecordingRequest.ts
  sdk/test-utils/recorder/src/utils/relativePathCalculator.browser.ts
  sdk/test-utils/recorder/src/utils/relativePathCalculator.ts
  sdk/test-utils/recorder/src/utils/sessionFilePath.ts
  sdk/test-utils/recorder/src/utils/utils.ts
Labels: Cognitive - Text Analytics

#23845 security release
  common/config/rush/pnpm-lock.yaml
  sdk/security/arm-security/CHANGELOG.md
  sdk/security/arm-security/_meta.json
  sdk/security/arm-security/package.json
  sdk/security/arm-security/recordings/node/security_test/recording_securitycontact_create_test.json
  sdk/security/arm-security/recordings/node/security_test/recording_securitycontact_delete_test.json
  sdk/security/arm-security/recordings/node/security_test/recording_securitycontact_get_test.json
  sdk/security/arm-security/recordings/node/security_test/recording_securitycontact_list_test.json
  sdk/security/arm-security/review/arm-security.api.md
  sdk/security/arm-security/samples-dev/adaptiveApplicationControlsPutSample.ts
  sdk/security/arm-security/samples-dev/apiCollectionGetSample.ts
  sdk/security/arm-security/samples-dev/apiCollectionListSample.ts
  sdk/security/arm-security/samples-dev/apiCollectionOffboardingDeleteSample.ts
  sdk/security/arm-security/samples-dev/apiCollectionOnboardingCreateSample.ts
  sdk/security/arm-security/samples/v6-beta/javascript/README.md
  sdk/security/arm-security/samples/v6-beta/javascript/adaptiveApplicationControlsPutSample.js
  sdk/security/arm-security/samples/v6-beta/javascript/apiCollectionGetSample.js
  sdk/security/arm-security/samples/v6-beta/javascript/apiCollectionListSample.js
  sdk/security/arm-security/samples/v6-beta/javascript/apiCollectionOffboardingDeleteSample.js
  sdk/security/arm-security/samples/v6-beta/javascript/apiCollectionOnboardingCreateSample.js
  sdk/security/arm-security/samples/v6-beta/typescript/README.md
  sdk/security/arm-security/samples/v6-beta/typescript/src/adaptiveApplicationControlsPutSample.ts
  sdk/security/arm-security/samples/v6-beta/typescript/src/apiCollectionGetSample.ts
  sdk/security/arm-security/samples/v6-beta/typescript/src/apiCollectionListSample.ts
  sdk/security/arm-security/samples/v6-beta/typescript/src/apiCollectionOffboardingDeleteSample.ts
  sdk/security/arm-security/samples/v6-beta/typescript/src/apiCollectionOnboardingCreateSample.ts
  sdk/security/arm-security/src/models/index.ts
  sdk/security/arm-security/src/models/mappers.ts
  sdk/security/arm-security/src/models/parameters.ts
  sdk/security/arm-security/src/operations/aPICollection.ts
  sdk/security/arm-security/src/operations/aPICollectionOffboarding.ts
  sdk/security/arm-security/src/operations/aPICollectionOnboarding.ts
  sdk/security/arm-security/src/operations/index.ts
  sdk/security/arm-security/src/operationsInterfaces/aPICollection.ts
  sdk/security/arm-security/src/operationsInterfaces/aPICollectionOffboarding.ts
  sdk/security/arm-security/src/operationsInterfaces/aPICollectionOnboarding.ts
  sdk/security/arm-security/src/operationsInterfaces/index.ts
  sdk/security/arm-security/src/securityCenter.ts
Labels: Mgmt

#23868 Post release automated changes for applicationinsights releases
  sdk/applicationinsights/arm-appinsights/CHANGELOG.md
  sdk/applicationinsights/arm-appinsights/package.json
  sdk/applicationinsights/arm-appinsights/src/applicationInsightsManagementClient.ts
Labels: Mgmt, auto-merge

#23869 Post release automated changes for appconfiguration releases
  sdk/appconfiguration/arm-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/arm-appconfiguration/package.json
  sdk/appconfiguration/arm-appconfiguration/src/appConfigurationManagementClient.ts
Labels: Mgmt, App Configuration, auto-merge

#23870 Post release automated changes for appcontainers releases
  sdk/appcontainers/arm-appcontainers/CHANGELOG.md
  sdk/appcontainers/arm-appcontainers/package.json
  sdk/appcontainers/arm-appcontainers/src/containerAppsAPIClient.ts
Labels: auto-merge

#23880 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23883 [monitor] Update @opentelemetry libs to latest
  common/config/rush/pnpm-lock.yaml
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
  sdk/monitor/monitor-opentelemetry-exporter/package.json
  sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/javascript/package.json
  sdk/monitor/monitor-opentelemetry-exporter/samples/v1-beta/typescript/package.json
  sdk/monitor/monitor-opentelemetry-exporter/samples/v1/javascript/package.json
  sdk/monitor/monitor-opentelemetry-exporter/samples/v1/typescript/package.json
  sdk/monitor/monitor-query/package.json
Labels: Monitor

#23750 Post release automated changes for maps releases
  sdk/maps/maps-common/CHANGELOG.md
  sdk/maps/maps-common/package.json
  sdk/maps/maps-route-rest/CHANGELOG.md
  sdk/maps/maps-route-rest/package.json
  sdk/maps/maps-route-rest/swagger/README.md
  sdk/maps/maps-search/CHANGELOG.md
  sdk/maps/maps-search/package.json
  sdk/maps/maps-search/src/constants.ts
  sdk/maps/maps-search/src/generated/generatedClientContext.ts
  sdk/maps/maps-search/swagger/README.md
Labels: auto-merge

#23813 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#23891 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#23803 [Recorder] Revert the redirected URL after we get the response from test-proxy
  sdk/compute/arm-compute-rest/test/public/utils/customizedTestPolicy.ts
  sdk/compute/arm-compute-rest/test/public/utils/recordedClient.ts
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_ipgroups_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_ipgroups_create_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_ipgroups_get_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_ipgroups_list_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_subnets_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_subnets_create_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_subnets_get_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_subnets_list_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_virtualnetworks_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_virtualnetworks_create_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_virtualnetworks_get_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_virtualnetworks_list_test.json
  sdk/network/arm-network-rest/recordings/browsers/network_test/recording_virtualnetworks_updatetags_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_ipgroups_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_ipgroups_create_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_ipgroups_get_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_ipgroups_list_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_subnets_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_subnets_create_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_subnets_get_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_subnets_list_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_virtualnetworks_begindeleteandwait_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_virtualnetworks_create_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_virtualnetworks_get_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_virtualnetworks_list_test.json
  sdk/network/arm-network-rest/recordings/node/network_test/recording_virtualnetworks_updatetags_test.json
  sdk/network/arm-network-rest/test/public/network_rest_sample.spec.ts
  sdk/network/arm-network-rest/test/public/utils/customizedTestPolicy.ts
  sdk/network/arm-network-rest/test/public/utils/recordedClient.ts
  sdk/test-utils/recorder/CHANGELOG.md
  sdk/test-utils/recorder/src/recorder.ts
  sdk/test-utils/recorder/src/utils/typeGuards.ts
  sdk/test-utils/recorder/test/testProxyTests.spec.ts
Labels: Mgmt

#23859 [Language Text] Update entity recognition NER tests
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_entity_recognition_with_resolution.json
  sdk/cognitivelanguage/ai-language-text/recordings/browsers/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_entity_recognition_with_resolution.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/aad_textanalysisclient_analyzebatch_actions_prebuilt/recording_entity_recognition_with_resolution.json
  sdk/cognitivelanguage/ai-language-text/recordings/node/apikey_textanalysisclient_analyzebatch_actions_prebuilt/recording_entity_recognition_with_resolution.json
  sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
  sdk/cognitivelanguage/ai-language-text/test/public/expectations.ts
Labels: Cognitive - Language

#23776 [Azure Monitor OpenTelemetry Exporter ]Post release changes for monitor releases
  sdk/monitor/monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/monitor-opentelemetry-exporter/package.json
  sdk/monitor/monitor-opentelemetry-exporter/src/generated/applicationInsightsClient.ts
  sdk/monitor/monitor-opentelemetry-exporter/src/utils/constants/applicationinsights.ts
  sdk/monitor/monitor-opentelemetry-exporter/swagger/README.md
Labels: Monitor

#23888 recording refresh 3
  common/config/rush/pnpm-lock.yaml
  sdk/changeanalysis/arm-changeanalysis/CHANGELOG.md
  sdk/changeanalysis/arm-changeanalysis/_meta.json
  sdk/changeanalysis/arm-changeanalysis/package.json
  sdk/changeanalysis/arm-changeanalysis/recordings/node/my_test/recording_sample_test.js
  sdk/changeanalysis/arm-changeanalysis/recordings/node/my_test/recording_sample_test.json
  sdk/changeanalysis/arm-changeanalysis/review/arm-changeanalysis.api.md
  sdk/changeanalysis/arm-changeanalysis/samples/v2/typescript/package.json
  sdk/changeanalysis/arm-changeanalysis/src/azureChangeAnalysisManagementClient.ts
  sdk/changeanalysis/arm-changeanalysis/src/index.ts
  sdk/changeanalysis/arm-changeanalysis/src/models/index.ts
  sdk/changeanalysis/arm-changeanalysis/src/operations/changes.ts
  sdk/changeanalysis/arm-changeanalysis/src/operations/operations.ts
  sdk/changeanalysis/arm-changeanalysis/src/operations/resourceChanges.ts
  sdk/changeanalysis/arm-changeanalysis/src/pagingHelper.ts
  sdk/changeanalysis/arm-changeanalysis/test/sampleTest.ts
  sdk/changes/arm-changes/CHANGELOG.md
  sdk/changes/arm-changes/_meta.json
  sdk/changes/arm-changes/package.json
  sdk/changes/arm-changes/recordings/node/my_test/recording_sample_test.js
  sdk/changes/arm-changes/recordings/node/my_test/recording_sample_test.json
  sdk/changes/arm-changes/review/arm-changes.api.md
  sdk/changes/arm-changes/samples/v1/typescript/package.json
  sdk/changes/arm-changes/src/changesClient.ts
  sdk/changes/arm-changes/src/index.ts
  sdk/changes/arm-changes/src/models/index.ts
  sdk/changes/arm-changes/src/operations/changes.ts
  sdk/changes/arm-changes/src/pagingHelper.ts
  sdk/changes/arm-changes/test/sampleTest.ts
Labels: Mgmt

#23781 [app-config] Update feature flags sample with timewindow filter
  sdk/appconfiguration/app-configuration/samples-dev/featureFlag.ts
Labels: App Configuration

#23904 Sync eng/common directory with azure-sdk-tools for PR 4746
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#23922 Post release automated changes for identity releases
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/package.json
  sdk/identity/identity/src/constants.ts
Labels: Azure.Identity, auto-merge

#23920 [identity] Expires on timestamp should be in seconds not ms
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/package.json
  sdk/identity/identity/src/constants.ts
  sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
  sdk/identity/identity/test/internal/node/azureApplicationCredential.spec.ts
  sdk/identity/identity/test/internal/node/managedIdentityCredential.spec.ts
Labels: Azure.Identity

#23925 [Monitor Query] Fix link
  sdk/monitor/monitor-query/README.md
Labels: Monitor

#23935 Post release automated changes for datafactory releases
  sdk/datafactory/arm-datafactory/CHANGELOG.md
  sdk/datafactory/arm-datafactory/package.json
  sdk/datafactory/arm-datafactory/src/dataFactoryManagementClient.ts
Labels: Mgmt, auto-merge

#23934 Post release automated changes for trafficmanager releases
  sdk/trafficmanager/arm-trafficmanager/CHANGELOG.md
  sdk/trafficmanager/arm-trafficmanager/package.json
  sdk/trafficmanager/arm-trafficmanager/src/trafficManagerManagementClient.ts
Labels: Mgmt, auto-merge

#23936 Post release automated changes for containerservice releases
  sdk/containerservice/arm-containerservice/CHANGELOG.md
  sdk/containerservice/arm-containerservice/package.json
  sdk/containerservice/arm-containerservice/src/containerServiceClient.ts
Labels: Mgmt, auto-merge

#23933 Post release automated changes for batch releases
  sdk/batch/arm-batch/CHANGELOG.md
  sdk/batch/arm-batch/package.json
  sdk/batch/arm-batch/src/batchManagementClient.ts
Labels: Mgmt, Batch, auto-merge

#23940 [core-xml] Update CHANGELOG for release
  sdk/core/core-xml/CHANGELOG.md
  sdk/notificationhubs/notification-hubs/CHANGELOG.md
  sdk/notificationhubs/notification-hubs/package.json
Labels: Azure.Core

#23957 cognitiveservices refresh
  common/config/rush/pnpm-lock.yaml
  sdk/cognitiveservices/arm-cognitiveservices/CHANGELOG.md
  sdk/cognitiveservices/arm-cognitiveservices/_meta.json
  sdk/cognitiveservices/arm-cognitiveservices/package.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_create_test.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_delete_test.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_get_test.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_list_test.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_regeneratekey_test.json
  sdk/cognitiveservices/arm-cognitiveservices/recordings/node/cognitiveservices_test/recording_accounts_update_test.json
  sdk/cognitiveservices/arm-cognitiveservices/review/arm-cognitiveservices.api.md
  sdk/cognitiveservices/arm-cognitiveservices/src/cognitiveServicesManagementClient.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/index.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/accounts.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/commitmentPlans.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/commitmentTiers.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/deletedAccounts.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/deployments.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/operations.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/operations/resourceSkus.ts
  sdk/cognitiveservices/arm-cognitiveservices/src/pagingHelper.ts
Labels: Mgmt

#23583 Fix test pipeline for rooms with ppe connectionstr
  sdk/communication/communication-rooms/karma.conf.js
  sdk/communication/communication-rooms/sample.env
  sdk/communication/communication-rooms/samples-dev/participantOperations.ts
  sdk/communication/communication-rooms/samples-dev/roomOperations.ts
  sdk/communication/communication-rooms/samples/v1-beta/javascript/README.md
  sdk/communication/communication-rooms/samples/v1-beta/javascript/participantOperations.js
  sdk/communication/communication-rooms/samples/v1-beta/javascript/roomOperations.js
  sdk/communication/communication-rooms/samples/v1-beta/javascript/sample.env
  sdk/communication/communication-rooms/samples/v1-beta/typescript/README.md
  sdk/communication/communication-rooms/samples/v1-beta/typescript/package.json
  sdk/communication/communication-rooms/samples/v1-beta/typescript/sample.env
  sdk/communication/communication-rooms/samples/v1-beta/typescript/src/participantOperations.ts
  sdk/communication/communication-rooms/samples/v1-beta/typescript/src/roomOperations.ts
  sdk/communication/communication-rooms/test.env
  sdk/communication/communication-rooms/test/internal/roomsClient.mocked.spec.ts
  sdk/communication/communication-rooms/test/public/utils/recordedClient.ts
  sdk/communication/communication-rooms/tests.yml
Labels: auto-merge, Communication

#23962 Update CHANGELOG.md
  sdk/cognitiveservices/arm-cognitiveservices/CHANGELOG.md
Labels: Mgmt

#23954 recording refresh 8
  common/config/rush/pnpm-lock.yaml
  sdk/dns/arm-dns/CHANGELOG.md
  sdk/dns/arm-dns/_meta.json
  sdk/dns/arm-dns/package.json
  sdk/dns/arm-dns/recordings/node/my_test/recording_sample_test.json
  sdk/dns/arm-dns/review/arm-dns.api.md
  sdk/dns/arm-dns/samples/v5/typescript/package.json
  sdk/dns/arm-dns/src/dnsManagementClient.ts
  sdk/dns/arm-dns/src/index.ts
  sdk/dns/arm-dns/src/models/index.ts
  sdk/dns/arm-dns/src/operations/recordSets.ts
  sdk/dns/arm-dns/src/operations/zones.ts
  sdk/dns/arm-dns/src/pagingHelper.ts
  sdk/dns/arm-dns/test/sampleTest.ts
  sdk/domainservices/arm-domainservices/CHANGELOG.md
  sdk/domainservices/arm-domainservices/_meta.json
  sdk/domainservices/arm-domainservices/package.json
  sdk/domainservices/arm-domainservices/recordings/node/my_test/recording_sample_test.json
  sdk/domainservices/arm-domainservices/review/arm-domainservices.api.md
  sdk/domainservices/arm-domainservices/samples/v4/typescript/package.json
  sdk/domainservices/arm-domainservices/src/domainServicesResourceProvider.ts
  sdk/domainservices/arm-domainservices/src/index.ts
  sdk/domainservices/arm-domainservices/src/models/index.ts
  sdk/domainservices/arm-domainservices/src/operations/domainServiceOperations.ts
  sdk/domainservices/arm-domainservices/src/operations/domainServices.ts
  sdk/domainservices/arm-domainservices/src/operations/ouContainerOperationGrp.ts
  sdk/domainservices/arm-domainservices/src/operations/ouContainerOperations.ts
  sdk/domainservices/arm-domainservices/src/pagingHelper.ts
  sdk/domainservices/arm-domainservices/test/sampleTest.ts
  sdk/eventhub/arm-eventhub/CHANGELOG.md
  sdk/eventhub/arm-eventhub/_meta.json
  sdk/eventhub/arm-eventhub/package.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_create_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_create_test.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_delete_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_delete_test.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_get_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_get_test.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_listbynamespace_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_eventhubs_listbynamespace_test.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_namespaces_create_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_namespaces_create_test.json
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_namespaces_delete_test.js
  sdk/eventhub/arm-eventhub/recordings/node/eventhub_test/recording_namespaces_delete_test.json
  sdk/eventhub/arm-eventhub/recordings/node/my_test/recording_sample_test.js
  sdk/eventhub/arm-eventhub/review/arm-eventhub.api.md
  sdk/eventhub/arm-eventhub/samples/v5/typescript/package.json
  sdk/eventhub/arm-eventhub/src/eventHubManagementClient.ts
  sdk/eventhub/arm-eventhub/src/index.ts
  sdk/eventhub/arm-eventhub/src/models/index.ts
  sdk/eventhub/arm-eventhub/src/operations/clusters.ts
  sdk/eventhub/arm-eventhub/src/operations/consumerGroups.ts
  sdk/eventhub/arm-eventhub/src/operations/disasterRecoveryConfigs.ts
  sdk/eventhub/arm-eventhub/src/operations/eventHubs.ts
  sdk/eventhub/arm-eventhub/src/operations/namespaces.ts
  sdk/eventhub/arm-eventhub/src/operations/operations.ts
  sdk/eventhub/arm-eventhub/src/operations/privateEndpointConnections.ts
  sdk/eventhub/arm-eventhub/src/operations/schemaRegistry.ts
  sdk/eventhub/arm-eventhub/src/pagingHelper.ts
  sdk/eventhub/arm-eventhub/test/eventhub_examples.ts
Labels: Mgmt

#23698 Fix Short Codes tests
  common/config/rush/pnpm-lock.yaml
  sdk/communication/communication-short-codes/package.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
  sdk/communication/communication-short-codes/review/communication-short-codes.api.md
  sdk/communication/communication-short-codes/samples-dev/createAndDeleteProgramBrief.ts
  sdk/communication/communication-short-codes/samples-dev/getAndUpdateProgramBrief.ts
  sdk/communication/communication-short-codes/src/index.ts
  sdk/communication/communication-short-codes/src/mappers.ts
  sdk/communication/communication-short-codes/test/public/createGetDeleteUSProgramBrief.spec.ts
  sdk/communication/communication-short-codes/test/public/createUpdateUSProgramBrief.spec.ts
  sdk/communication/communication-short-codes/test/public/utils/recordedClient.ts
  sdk/communication/communication-short-codes/test/public/utils/testProgramBriefAttachment.ts
  sdk/communication/communication-short-codes/test/public/utils/testUSProgramBrief.ts
Labels: Communication

#23858 [core-rest-pipeline] await `prepareFormData()`
  sdk/core/core-rest-pipeline/CHANGELOG.md
  sdk/core/core-rest-pipeline/src/policies/formDataPolicy.ts
Labels: Azure.Core

#23978 Post release automated changes for devspaces releases
  sdk/devspaces/arm-devspaces/CHANGELOG.md
  sdk/devspaces/arm-devspaces/package.json
  sdk/devspaces/arm-devspaces/src/devSpacesManagementClient.ts
Labels: Mgmt, auto-merge

#23976 Post release automated changes for deploymentmanager releases
  sdk/deploymentmanager/arm-deploymentmanager/CHANGELOG.md
  sdk/deploymentmanager/arm-deploymentmanager/package.json
  sdk/deploymentmanager/arm-deploymentmanager/src/azureDeploymentManager.ts
Labels: Mgmt, auto-merge

#23977 Post release automated changes for desktopvirtualization releases
  sdk/desktopvirtualization/arm-desktopvirtualization/CHANGELOG.md
  sdk/desktopvirtualization/arm-desktopvirtualization/package.json
  sdk/desktopvirtualization/arm-desktopvirtualization/src/desktopVirtualizationAPIClient.ts
Labels: auto-merge

#23975 fix version of containerservice
  common/config/rush/pnpm-lock.yaml
  sdk/containerservice/arm-containerservice/CHANGELOG.md
  sdk/containerservice/arm-containerservice/_meta.json
  sdk/containerservice/arm-containerservice/package.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_create_test.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_delete_test.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_get_test.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_getupgradeprofile_test.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_list_test.json
  sdk/containerservice/arm-containerservice/recordings/node/containerservice_test/recording_managedclusters_update_test.json
  sdk/containerservice/arm-containerservice/src/containerServiceClient.ts
Labels: Mgmt

#23982 Post release automated changes for eventhub releases
  sdk/eventhub/arm-eventhub/CHANGELOG.md
  sdk/eventhub/arm-eventhub/package.json
  sdk/eventhub/arm-eventhub/src/eventHubManagementClient.ts
Labels: Mgmt, Event Hubs, auto-merge

#23983 Post release automated changes for domainservices releases
  sdk/domainservices/arm-domainservices/CHANGELOG.md
  sdk/domainservices/arm-domainservices/package.json
  sdk/domainservices/arm-domainservices/src/domainServicesResourceProvider.ts
Labels: Mgmt, auto-merge

#23984 Post release automated changes for dns releases
  sdk/dns/arm-dns/CHANGELOG.md
  sdk/dns/arm-dns/package.json
  sdk/dns/arm-dns/src/dnsManagementClient.ts
Labels: Mgmt, auto-merge

#23980 Post release automated changes for devtestlabs releases
  sdk/devtestlabs/arm-devtestlabs/CHANGELOG.md
  sdk/devtestlabs/arm-devtestlabs/package.json
  sdk/devtestlabs/arm-devtestlabs/src/devTestLabsClient.ts
Labels: Mgmt, auto-merge

#23965 Post release automated changes for web-pubsub releases
  sdk/web-pubsub/web-pubsub/CHANGELOG.md
  sdk/web-pubsub/web-pubsub/package.json
  sdk/web-pubsub/web-pubsub/src/generated/generatedClientContext.ts
  sdk/web-pubsub/web-pubsub/swagger/README.md
Labels: auto-merge, WebPubSub

#23948 Post release automated changes for web-pubsub releases
  sdk/web-pubsub/arm-webpubsub/CHANGELOG.md
  sdk/web-pubsub/arm-webpubsub/package.json
  sdk/web-pubsub/arm-webpubsub/src/webPubSubManagementClient.ts
Labels: auto-merge, WebPubSub

#23949 Post release automated changes for security releases
  sdk/security/arm-security/CHANGELOG.md
  sdk/security/arm-security/package.json
  sdk/security/arm-security/src/securityCenter.ts
Labels: Mgmt, auto-merge

#23946 Post release automated changes for signalr releases
  sdk/signalr/arm-signalr/CHANGELOG.md
  sdk/signalr/arm-signalr/package.json
  sdk/signalr/arm-signalr/src/signalRManagementClient.ts
Labels: Mgmt, auto-merge

#23986 Post release automated changes for containerservice releases
  sdk/containerservice/arm-containerservice/CHANGELOG.md
  sdk/containerservice/arm-containerservice/package.json
  sdk/containerservice/arm-containerservice/src/containerServiceClient.ts
Labels: Mgmt, auto-merge

#23968 Post release automated changes for containerregistry releases
  sdk/containerregistry/arm-containerregistry/CHANGELOG.md
  sdk/containerregistry/arm-containerregistry/package.json
  sdk/containerregistry/arm-containerregistry/src/containerRegistryManagementClient.ts
Labels: Mgmt, Container Registry, auto-merge

#23874 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Do Not Merge

#23991 Post release automated changes for loadtestservice releases
  sdk/loadtestservice/arm-loadtesting/CHANGELOG.md
  sdk/loadtestservice/arm-loadtesting/package.json
  sdk/loadtestservice/arm-loadtesting/src/loadTestClient.ts
Labels: auto-merge

#23930 Post release automated changes for machinelearning releases
  sdk/machinelearning/arm-machinelearning/CHANGELOG.md
  sdk/machinelearning/arm-machinelearning/package.json
  sdk/machinelearning/arm-machinelearning/src/azureMachineLearningWorkspaces.ts
Labels: auto-merge

#23943 Post release automated changes for core releases
  sdk/core/core-xml/CHANGELOG.md
  sdk/core/core-xml/package.json
Labels: Azure.Core, auto-merge

#23955 Post release automated changes for notificationhubs releases
  sdk/notificationhubs/notification-hubs/CHANGELOG.md
  sdk/notificationhubs/notification-hubs/package.json
  sdk/notificationhubs/notification-hubs/src/utils/constants.ts
Labels: auto-merge

#23972 [dev-tool] Fix build error in full rush update
  common/config/rush/pnpm-lock.yaml
  common/tools/dev-tool/package.json
  common/tools/dev-tool/src/util/testUtils.ts
Labels: dev-tool

#24021 [engsys] update rush version to latest
  common/scripts/install-run-rush.js
  common/scripts/install-run.js
  rush.json
Labels: EngSys

#24020 [engsys] Upgrade dev dependency `dotenv` version to `^16.0.0` for selected packages
  common/config/rush/pnpm-lock.yaml
  common/tools/dev-tool/package.json
  sdk/cognitivelanguage/ai-language-text/package.json
  sdk/identity/identity/package.json
  sdk/servicebus/service-bus/package.json
  sdk/storage/storage-blob/package.json
  sdk/template/template/package.json
Labels: EngSys, Service Bus, Storage, Azure.Identity, dev-tool

#24027 [engsys] upgrade dependency `fs-extra` to `^11.0.0`
  common/config/rush/pnpm-lock.yaml
  common/tools/dev-tool/package.json
Labels: dev-tool

#23929 recording refresh 6
  common/config/rush/pnpm-lock.yaml
  sdk/datacatalog/arm-datacatalog/CHANGELOG.md
  sdk/datacatalog/arm-datacatalog/_meta.json
  sdk/datacatalog/arm-datacatalog/package.json
  sdk/datacatalog/arm-datacatalog/recordings/node/my_test/recording_sample_test.js
  sdk/datacatalog/arm-datacatalog/recordings/node/my_test/recording_sample_test.json
  sdk/datacatalog/arm-datacatalog/review/arm-datacatalog.api.md
  sdk/datacatalog/arm-datacatalog/samples/v4/typescript/package.json
  sdk/datacatalog/arm-datacatalog/src/dataCatalogRestClient.ts
  sdk/datacatalog/arm-datacatalog/src/models/index.ts
  sdk/datacatalog/arm-datacatalog/test/sampleTest.ts
  sdk/datadog/arm-datadog/CHANGELOG.md
  sdk/datadog/arm-datadog/_meta.json
  sdk/datadog/arm-datadog/package.json
  sdk/datadog/arm-datadog/recordings/node/my_test/recording_sample_test.js
  sdk/datadog/arm-datadog/recordings/node/my_test/recording_sample_test.json
  sdk/datadog/arm-datadog/review/arm-datadog.api.md
  sdk/datadog/arm-datadog/samples/v3/typescript/package.json
  sdk/datadog/arm-datadog/src/index.ts
  sdk/datadog/arm-datadog/src/microsoftDatadogClient.ts
  sdk/datadog/arm-datadog/src/models/index.ts
  sdk/datadog/arm-datadog/src/operations/marketplaceAgreements.ts
  sdk/datadog/arm-datadog/src/operations/monitors.ts
  sdk/datadog/arm-datadog/src/operations/operations.ts
  sdk/datadog/arm-datadog/src/operations/singleSignOnConfigurations.ts
  sdk/datadog/arm-datadog/src/operations/tagRules.ts
  sdk/datadog/arm-datadog/src/pagingHelper.ts
  sdk/datadog/arm-datadog/test/sampleTest.ts
  sdk/datamigration/arm-datamigration/CHANGELOG.md
  sdk/datamigration/arm-datamigration/_meta.json
  sdk/datamigration/arm-datamigration/package.json
  sdk/datamigration/arm-datamigration/recordings/node/my_test/recording_sample_test.json
  sdk/datamigration/arm-datamigration/review/arm-datamigration.api.md
  sdk/datamigration/arm-datamigration/samples-dev/databaseMigrationsSqlMiCreateOrUpdateSample.ts
  sdk/datamigration/arm-datamigration/samples-dev/databaseMigrationsSqlVMCreateOrUpdateSample.ts
  sdk/datamigration/arm-datamigration/samples/v3-beta/javascript/databaseMigrationsSqlMiCreateOrUpdateSample.js
  sdk/datamigration/arm-datamigration/samples/v3-beta/javascript/databaseMigrationsSqlVMCreateOrUpdateSample.js
  sdk/datamigration/arm-datamigration/samples/v3-beta/typescript/package.json
  sdk/datamigration/arm-datamigration/samples/v3-beta/typescript/src/databaseMigrationsSqlMiCreateOrUpdateSample.ts
  sdk/datamigration/arm-datamigration/samples/v3-beta/typescript/src/databaseMigrationsSqlVMCreateOrUpdateSample.ts
  sdk/datamigration/arm-datamigration/src/dataMigrationManagementClient.ts
  sdk/datamigration/arm-datamigration/src/index.ts
  sdk/datamigration/arm-datamigration/src/models/index.ts
  sdk/datamigration/arm-datamigration/src/operations/files.ts
  sdk/datamigration/arm-datamigration/src/operations/operations.ts
  sdk/datamigration/arm-datamigration/src/operations/projects.ts
  sdk/datamigration/arm-datamigration/src/operations/resourceSkus.ts
  sdk/datamigration/arm-datamigration/src/operations/serviceTasks.ts
  sdk/datamigration/arm-datamigration/src/operations/services.ts
  sdk/datamigration/arm-datamigration/src/operations/sqlMigrationServices.ts
  sdk/datamigration/arm-datamigration/src/operations/tasks.ts
  sdk/datamigration/arm-datamigration/src/operations/usages.ts
  sdk/datamigration/arm-datamigration/src/pagingHelper.ts
  sdk/datamigration/arm-datamigration/test/sampleTest.ts
Labels: Mgmt

#23961 recording refresh 10
  common/config/rush/pnpm-lock.yaml
  sdk/frontdoor/arm-frontdoor/CHANGELOG.md
  sdk/frontdoor/arm-frontdoor/_meta.json
  sdk/frontdoor/arm-frontdoor/package.json
  sdk/frontdoor/arm-frontdoor/recordings/node/my_test/recording_sample_test.js
  sdk/frontdoor/arm-frontdoor/recordings/node/my_test/recording_sample_test.json
  sdk/frontdoor/arm-frontdoor/review/arm-frontdoor.api.md
  sdk/frontdoor/arm-frontdoor/samples/v5/typescript/package.json
  sdk/frontdoor/arm-frontdoor/src/frontDoorManagementClient.ts
  sdk/frontdoor/arm-frontdoor/src/index.ts
  sdk/frontdoor/arm-frontdoor/src/models/index.ts
  sdk/frontdoor/arm-frontdoor/src/operations/experiments.ts
  sdk/frontdoor/arm-frontdoor/src/operations/frontDoors.ts
  sdk/frontdoor/arm-frontdoor/src/operations/frontendEndpoints.ts
  sdk/frontdoor/arm-frontdoor/src/operations/managedRuleSets.ts
  sdk/frontdoor/arm-frontdoor/src/operations/networkExperimentProfiles.ts
  sdk/frontdoor/arm-frontdoor/src/operations/policies.ts
  sdk/frontdoor/arm-frontdoor/src/operations/preconfiguredEndpoints.ts
  sdk/frontdoor/arm-frontdoor/src/operations/rulesEngines.ts
  sdk/frontdoor/arm-frontdoor/src/pagingHelper.ts
  sdk/frontdoor/arm-frontdoor/test/sampleTest.ts
  sdk/hanaonazure/arm-hanaonazure/CHANGELOG.md
  sdk/hanaonazure/arm-hanaonazure/_meta.json
  sdk/hanaonazure/arm-hanaonazure/package.json
  sdk/hanaonazure/arm-hanaonazure/recordings/node/my_test/recording_sample_test.js
  sdk/hanaonazure/arm-hanaonazure/recordings/node/my_test/recording_sample_test.json
  sdk/hanaonazure/arm-hanaonazure/review/arm-hanaonazure.api.md
  sdk/hanaonazure/arm-hanaonazure/samples/v4-beta/typescript/package.json
  sdk/hanaonazure/arm-hanaonazure/src/hanaManagementClient.ts
  sdk/hanaonazure/arm-hanaonazure/src/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/models/index.ts
  sdk/hanaonazure/arm-hanaonazure/src/operations/operations.ts
  sdk/hanaonazure/arm-hanaonazure/src/operations/providerInstances.ts
  sdk/hanaonazure/arm-hanaonazure/src/operations/sapMonitors.ts
  sdk/hanaonazure/arm-hanaonazure/src/pagingHelper.ts
  sdk/hanaonazure/arm-hanaonazure/test/sampleTest.ts
Labels: Mgmt

#24023 Sync eng/common directory with azure-sdk-tools for PR 4713
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#24035 Post release automated changes for datadog releases
  sdk/datadog/arm-datadog/CHANGELOG.md
  sdk/datadog/arm-datadog/package.json
  sdk/datadog/arm-datadog/src/microsoftDatadogClient.ts
Labels: auto-merge

#24030 [core-client] Port xmlIsMsText from core-http
  sdk/core/core-client/CHANGELOG.md
  sdk/core/core-client/review/core-client.api.md
  sdk/core/core-client/src/interfaces.ts
  sdk/core/core-client/src/serializer.ts
  sdk/core/core-client/test/serializer.spec.ts
Labels: Client, Azure.Core

#24001 [monitor-ingestion] More perf test options
  sdk/monitor/perf-tests/monitor-ingestion/README.md
  sdk/monitor/perf-tests/monitor-ingestion/test/uploadLogs.spec.ts
Labels: Monitor

#24051 Post release automated changes for healthcareapis releases
  sdk/healthcareapis/arm-healthcareapis/CHANGELOG.md
  sdk/healthcareapis/arm-healthcareapis/package.json
  sdk/healthcareapis/arm-healthcareapis/src/healthcareApisManagementClient.ts
Labels: Mgmt, auto-merge

#24052 Post release automated changes for healthbot releases
  sdk/healthbot/arm-healthbot/CHANGELOG.md
  sdk/healthbot/arm-healthbot/package.json
  sdk/healthbot/arm-healthbot/src/healthbotClient.ts
Labels: Mgmt, auto-merge

#24053 Post release automated changes for hybridcompute releases
  sdk/hybridcompute/arm-hybridcompute/CHANGELOG.md
  sdk/hybridcompute/arm-hybridcompute/package.json
  sdk/hybridcompute/arm-hybridcompute/src/hybridComputeManagementClient.ts
Labels: Mgmt, auto-merge

#24054 Post release automated changes for hybridkubernetes releases
  sdk/hybridkubernetes/arm-hybridkubernetes/CHANGELOG.md
  sdk/hybridkubernetes/arm-hybridkubernetes/package.json
  sdk/hybridkubernetes/arm-hybridkubernetes/src/connectedKubernetesClient.ts
Labels: Mgmt, auto-merge

#23990 Fix apiVersion policy issue in core-client-rest
  sdk/core/core-client-rest/CHANGELOG.md
  sdk/core/core-client-rest/src/apiVersionPolicy.ts
  sdk/core/core-client-rest/test/getClient.spec.ts
Labels: Azure.Core

#23696 Bump the version of @azure/communication-common to 2.2.0 in all ACS packages
  sdk/communication/communication-alpha-ids/CHANGELOG.md
  sdk/communication/communication-alpha-ids/package.json
  sdk/communication/communication-alpha-ids/src/generated/src/tracing.ts
  sdk/communication/communication-chat/CHANGELOG.md
  sdk/communication/communication-chat/package.json
  sdk/communication/communication-chat/src/generated/src/chatApiClient.ts
  sdk/communication/communication-chat/src/generated/src/tracing.ts
  sdk/communication/communication-chat/swagger/README.md
  sdk/communication/communication-email/CHANGELOG.md
  sdk/communication/communication-email/package.json
  sdk/communication/communication-identity/CHANGELOG.md
  sdk/communication/communication-identity/package.json
  sdk/communication/communication-identity/src/generated/src/tracing.ts
  sdk/communication/communication-job-router/package.json
  sdk/communication/communication-network-traversal/CHANGELOG.md
  sdk/communication/communication-network-traversal/package.json
  sdk/communication/communication-network-traversal/src/constants.ts
  sdk/communication/communication-phone-numbers/CHANGELOG.md
  sdk/communication/communication-phone-numbers/package.json
  sdk/communication/communication-rooms/CHANGELOG.md
  sdk/communication/communication-rooms/package.json
  sdk/communication/communication-rooms/src/generated/src/roomsApiClient.ts
  sdk/communication/communication-rooms/src/generated/src/roomsApiClientContext.ts
  sdk/communication/communication-short-codes/CHANGELOG.md
  sdk/communication/communication-short-codes/package.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
  sdk/communication/communication-short-codes/src/generated/src/shortCodesClient.ts
  sdk/communication/communication-short-codes/src/generated/src/tracing.ts
  sdk/communication/communication-short-codes/src/utils/constants.ts
  sdk/communication/communication-short-codes/swagger/README.md
  sdk/communication/communication-sms/CHANGELOG.md
  sdk/communication/communication-sms/package.json
  sdk/communication/communication-sms/src/constants.ts
  sdk/communication/communication-sms/src/generated/src/smsApiClient.ts
  sdk/communication/communication-sms/src/generated/src/smsApiClientContext.ts
  sdk/communication/communication-sms/src/generated/src/tracing.ts
  sdk/communication/communication-sms/swagger/README.md
Labels: Communication

#24025 [language text] LRO partiallySucceeded status
  sdk/cognitivelanguage/ai-language-text/src/lro.ts
  sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
Labels: Azure.Core

#24049 [core-client] Allow resettable streams
  sdk/core/core-client/CHANGELOG.md
  sdk/core/core-client/src/serializer.ts
Labels: Azure.Core
