Repository Azure/azure-sdk-for-js, pull requests merged in 2022-12, with the labels that each got.

#24047 Update stress Dockerfile
  sdk/servicebus/service-bus/test/stress/Dockerfile
Labels: Service Bus

#23860 [App configuration] Import logger to app configuration
  sdk/appconfiguration/app-configuration/package.json
  sdk/appconfiguration/app-configuration/src/appConfigCredential.ts
  sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
  sdk/appconfiguration/app-configuration/src/featureFlag.ts
  sdk/appconfiguration/app-configuration/src/internal/helpers.ts
  sdk/appconfiguration/app-configuration/src/internal/synctokenpolicy.ts
  sdk/appconfiguration/app-configuration/src/logger.ts
  sdk/appconfiguration/app-configuration/src/secretReference.ts
Labels: App Configuration

#23896 [app-config] Cleanup resources after the test
  sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_get_secretreference.json
  sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_update_secretreference.json
  sdk/appconfiguration/app-configuration/recordings/browsers/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_list_and_update_multiple_secretreferences.json
  sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_get_secretreference.json
  sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_and_update_secretreference.json
  sdk/appconfiguration/app-configuration/recordings/node/appconfigurationclient__secretreference_secretreference_configuration_setting/recording_can_add_list_and_update_multiple_secretreferences.json
  sdk/appconfiguration/app-configuration/test/public/secretReference.spec.ts
  sdk/appconfiguration/app-configuration/test/public/tracing.spec.ts
Labels: App Configuration

#24079 Add *.env to .gitignore
  .gitignore
  sdk/eventhub/mock-hub/samples/typescript/sample.env
Labels: Event Hubs

#24069 [container-registry] Pass resettable streams through to generated client
  sdk/containerregistry/container-registry/package.json
  sdk/containerregistry/container-registry/recordings/node/containerregistryblobclient/recording_can_upload_blob_from_resettable_stream.json
  sdk/containerregistry/container-registry/recordings/node/containerregistryblobclient/recording_can_upload_oci_manifest_from_resettable_stream.json
  sdk/containerregistry/container-registry/src/blob/containerRegistryBlobClient.ts
  sdk/containerregistry/container-registry/test/public/containerRegistryBlobClient.spec.ts
Labels: Container Registry

#24080 [text analytics] Unskip test
  sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
Labels: Cognitive - Text Analytics

#24098 Revert "[text analytics] Unskip test"
  sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
Labels: Cognitive - Text Analytics

#24081 Sync eng/common directory with azure-sdk-tools for PR 4856
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: EngSys, Central-EngSys

#24101 [monitor-query] Update @azure/monitor-opentelemetry-exporter dependency
  common/config/rush/pnpm-lock.yaml
  sdk/monitor/monitor-query/package.json
Labels: Monitor

#23910 Post release automated changes for azurestackhci releases
  sdk/azurestackhci/arm-azurestackhci/CHANGELOG.md
  sdk/azurestackhci/arm-azurestackhci/package.json
  sdk/azurestackhci/arm-azurestackhci/src/azureStackHCIClient.ts
Labels: Mgmt, auto-merge

#23926 Post release automated changes for botservice releases
  sdk/botservice/arm-botservice/CHANGELOG.md
  sdk/botservice/arm-botservice/package.json
  sdk/botservice/arm-botservice/src/azureBotService.ts
Labels: Mgmt, auto-merge

#23966 Post release automated changes for customer-insights releases
  sdk/customer-insights/arm-customerinsights/CHANGELOG.md
  sdk/customer-insights/arm-customerinsights/package.json
  sdk/customer-insights/arm-customerinsights/src/customerInsightsManagementClient.ts
Labels: Mgmt, auto-merge

#24007 Post release automated changes for features releases
  sdk/features/arm-features/CHANGELOG.md
  sdk/features/arm-features/package.json
  sdk/features/arm-features/src/featureClient.ts
Labels: Mgmt, auto-merge

#23967 Post release automated changes for confluent releases
  sdk/confluent/arm-confluent/CHANGELOG.md
  sdk/confluent/arm-confluent/package.json
  sdk/confluent/arm-confluent/src/confluentManagementClient.ts
Labels: Mgmt, auto-merge

#23873 Post release automated changes for appplatform releases
  sdk/appplatform/arm-appplatform/CHANGELOG.md
  sdk/appplatform/arm-appplatform/package.json
  sdk/appplatform/arm-appplatform/src/appPlatformManagementClient.ts
Labels: Mgmt, auto-merge

#23908 Post release automated changes for changeanalysis releases
  sdk/changeanalysis/arm-changeanalysis/CHANGELOG.md
  sdk/changeanalysis/arm-changeanalysis/package.json
  sdk/changeanalysis/arm-changeanalysis/src/azureChangeAnalysisManagementClient.ts
Labels: Mgmt, auto-merge

#23912 Post release automated changes for attestation releases
  sdk/attestation/arm-attestation/CHANGELOG.md
  sdk/attestation/arm-attestation/package.json
  sdk/attestation/arm-attestation/src/attestationManagementClient.ts
Labels: Mgmt, Attestation, auto-merge

#23918 Post release automated changes for billing releases
  sdk/billing/arm-billing/CHANGELOG.md
  sdk/billing/arm-billing/package.json
  sdk/billing/arm-billing/src/billingManagementClient.ts
Labels: Mgmt, auto-merge

#24011 Post release automated changes for resources-subscriptions releases
  sdk/resources-subscriptions/arm-resources-subscriptions/CHANGELOG.md
  sdk/resources-subscriptions/arm-resources-subscriptions/package.json
  sdk/resources-subscriptions/arm-resources-subscriptions/src/subscriptionClient.ts
Labels: Mgmt, auto-merge

#24013 Post release automated changes for locks releases
  sdk/locks/arm-locks/CHANGELOG.md
  sdk/locks/arm-locks/package.json
  sdk/locks/arm-locks/src/managementLockClient.ts
Labels: Mgmt, auto-merge

#24014 Post release automated changes for policy releases
  sdk/policy/arm-policy/CHANGELOG.md
  sdk/policy/arm-policy/package.json
  sdk/policy/arm-policy/src/policyClient.ts
Labels: Mgmt, auto-merge

#24032 Post release automated changes for databox releases
  sdk/databox/arm-databox/CHANGELOG.md
  sdk/databox/arm-databox/package.json
  sdk/databox/arm-databox/src/dataBoxManagementClient.ts
Labels: Mgmt, auto-merge

#24015 Post release automated changes for managedapplications releases
  sdk/managedapplications/arm-managedapplications/CHANGELOG.md
  sdk/managedapplications/arm-managedapplications/package.json
  sdk/managedapplications/arm-managedapplications/src/applicationClient.ts
Labels: Mgmt, auto-merge

#24016 Post release automated changes for templatespecs releases
  sdk/templatespecs/arm-templatespecs/CHANGELOG.md
  sdk/templatespecs/arm-templatespecs/package.json
  sdk/templatespecs/arm-templatespecs/src/templateSpecsClient.ts
Labels: Mgmt, auto-merge

#24033 Post release automated changes for databoxedge releases
  sdk/databoxedge/arm-databoxedge/CHANGELOG.md
  sdk/databoxedge/arm-databoxedge/package.json
  sdk/databoxedge/arm-databoxedge/src/dataBoxEdgeManagementClient.ts
Labels: Mgmt, auto-merge

#24034 Post release automated changes for databricks releases
  sdk/databricks/arm-databricks/CHANGELOG.md
  sdk/databricks/arm-databricks/package.json
  sdk/databricks/arm-databricks/src/azureDatabricksManagementClient.ts
Labels: Mgmt, auto-merge

#24036 Post release automated changes for datacatalog releases
  sdk/datacatalog/arm-datacatalog/CHANGELOG.md
  sdk/datacatalog/arm-datacatalog/package.json
  sdk/datacatalog/arm-datacatalog/src/dataCatalogRestClient.ts
Labels: Mgmt, auto-merge

#24039 Post release automated changes for hanaonazure releases
  sdk/hanaonazure/arm-hanaonazure/CHANGELOG.md
  sdk/hanaonazure/arm-hanaonazure/package.json
  sdk/hanaonazure/arm-hanaonazure/src/hanaManagementClient.ts
Labels: Mgmt, auto-merge

#24040 Post release automated changes for frontdoor releases
  sdk/frontdoor/arm-frontdoor/CHANGELOG.md
  sdk/frontdoor/arm-frontdoor/package.json
  sdk/frontdoor/arm-frontdoor/src/frontDoorManagementClient.ts
Labels: Mgmt, auto-merge

#24037 Post release automated changes for datamigration releases
  sdk/datamigration/arm-datamigration/CHANGELOG.md
  sdk/datamigration/arm-datamigration/package.json
  sdk/datamigration/arm-datamigration/src/dataMigrationManagementClient.ts
Labels: Mgmt, auto-merge

#24058 Post release automated changes for containerservice releases
  sdk/containerservice/arm-containerservice/CHANGELOG.md
  sdk/containerservice/arm-containerservice/package.json
  sdk/containerservice/arm-containerservice/src/containerServiceClient.ts
Labels: Mgmt, auto-merge

#24092 Post release automated changes for keyvault releases
  sdk/keyvault/arm-keyvault/CHANGELOG.md
  sdk/keyvault/arm-keyvault/package.json
  sdk/keyvault/arm-keyvault/src/keyVaultManagementClient.ts
Labels: Mgmt, KeyVault, auto-merge

#24093 Post release automated changes for iotcentral releases
  sdk/iotcentral/arm-iotcentral/CHANGELOG.md
  sdk/iotcentral/arm-iotcentral/package.json
  sdk/iotcentral/arm-iotcentral/src/iotCentralClient.ts
Labels: Mgmt, auto-merge

#24094 Post release automated changes for machinelearning releases
  sdk/machinelearning/arm-machinelearning/CHANGELOG.md
  sdk/machinelearning/arm-machinelearning/package.json
  sdk/machinelearning/arm-machinelearning/src/azureMachineLearningWorkspaces.ts
  sdk/machinelearning/arm-webservices/CHANGELOG.md
  sdk/machinelearning/arm-webservices/package.json
  sdk/machinelearning/arm-webservices/src/azureMLWebServicesManagementClient.ts
  sdk/machinelearning/arm-workspaces/CHANGELOG.md
  sdk/machinelearning/arm-workspaces/package.json
  sdk/machinelearning/arm-workspaces/src/machineLearningWorkspacesManagementClient.ts
Labels: Mgmt, auto-merge

#24105 Post release automated changes for machinelearningcompute releases
  sdk/machinelearningcompute/arm-machinelearningcompute/CHANGELOG.md
  sdk/machinelearningcompute/arm-machinelearningcompute/package.json
  sdk/machinelearningcompute/arm-machinelearningcompute/src/machineLearningComputeManagementClient.ts
Labels: Mgmt, auto-merge

#24106 Post release automated changes for operationsmanagement releases
  sdk/operationsmanagement/arm-operations/CHANGELOG.md
  sdk/operationsmanagement/arm-operations/package.json
  sdk/operationsmanagement/arm-operations/src/operationsManagementClient.ts
Labels: Mgmt, auto-merge

#24107 Post release automated changes for mariadb releases
  sdk/mariadb/arm-mariadb/CHANGELOG.md
  sdk/mariadb/arm-mariadb/package.json
  sdk/mariadb/arm-mariadb/src/mariaDBManagementClient.ts
Labels: Mgmt, auto-merge

#24108 Post release automated changes for peering releases
  sdk/peering/arm-peering/CHANGELOG.md
  sdk/peering/arm-peering/package.json
  sdk/peering/arm-peering/src/peeringManagementClient.ts
Labels: Mgmt, auto-merge

#24091 Post release automated changes for kubernetesconfiguration releases
  sdk/kubernetesconfiguration/arm-kubernetesconfiguration/CHANGELOG.md
  sdk/kubernetesconfiguration/arm-kubernetesconfiguration/package.json
  sdk/kubernetesconfiguration/arm-kubernetesconfiguration/src/sourceControlConfigurationClient.ts
Labels: Mgmt, auto-merge

#24112 Post release automated changes for postgresql releases
  sdk/postgresql/arm-postgresql/CHANGELOG.md
  sdk/postgresql/arm-postgresql/package.json
  sdk/postgresql/arm-postgresql/src/postgreSQLManagementClient.ts
Labels: Mgmt, auto-merge

#24111 Post release automated changes for maps releases
  sdk/maps/arm-maps/CHANGELOG.md
  sdk/maps/arm-maps/package.json
  sdk/maps/arm-maps/src/azureMapsManagementClient.ts
Labels: Mgmt, auto-merge

#24115 update changelog
  sdk/managementgroups/arm-managementgroups/CHANGELOG.md
Labels: Mgmt

#24114 Post release automated changes for powerbiembedded releases
  sdk/powerbiembedded/arm-powerbiembedded/CHANGELOG.md
  sdk/powerbiembedded/arm-powerbiembedded/package.json
  sdk/powerbiembedded/arm-powerbiembedded/src/powerBIEmbeddedManagementClient.ts
Labels: Mgmt, auto-merge

#24117 Post release automated changes for managementgroups releases
  sdk/managementgroups/arm-managementgroups/CHANGELOG.md
  sdk/managementgroups/arm-managementgroups/package.json
  sdk/managementgroups/arm-managementgroups/src/managementGroupsAPI.ts
Labels: Mgmt, auto-merge

#24026 [ACR] Add samples for blob and manifest upload/download
  sdk/containerregistry/container-registry/samples-dev/uploadDownloadBlob.ts
  sdk/containerregistry/container-registry/samples-dev/uploadManifest.ts
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/README.md
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/anonymousListTags.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/containerRegistryClient.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/deleteImages.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/package.json
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/repositoryAndArtifact.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/sample.env
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/setImageProperties.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadDownloadBlob.js
  sdk/containerregistry/container-registry/samples/v1-beta/javascript/uploadManifest.js
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/README.md
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/package.json
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/sample.env
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/anonymousListTags.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/containerRegistryClient.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/deleteImages.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/repositoryAndArtifact.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/setImageProperties.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadDownloadBlob.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/src/uploadManifest.ts
  sdk/containerregistry/container-registry/samples/v1-beta/typescript/tsconfig.json
Labels: Container Registry

#24125 [monitor opentelemetry exporter] Fix README code snippet bugs
  sdk/monitor/monitor-opentelemetry-exporter/README.md
Labels: Monitor

#24104 [identity] Remove `UnavailableMessage` from `ChainedTokenCredential`
  sdk/identity/identity/review/identity.api.md
  sdk/identity/identity/src/credentials/azureApplicationCredential.ts
  sdk/identity/identity/src/credentials/chainedTokenCredential.ts
  sdk/identity/identity/src/credentials/defaultAzureCredential.ts
Labels: Client, Azure.Identity

#24102 identity: managedIdentityCredential expires-in/-on
  sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
Labels: customer-reported, Azure.Identity

#24129 Sync eng/common directory with azure-sdk-tools for PR 4878
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#24143 Post release automated changes for mixedreality releases
  sdk/mixedreality/arm-mixedreality/CHANGELOG.md
  sdk/mixedreality/arm-mixedreality/package.json
  sdk/mixedreality/arm-mixedreality/src/mixedRealityClient.ts
Labels: Mgmt, auto-merge, Mixed Reality

#24140 Post release automated changes for notificationhubs releases
  sdk/notificationhubs/arm-notificationhubs/CHANGELOG.md
  sdk/notificationhubs/arm-notificationhubs/package.json
  sdk/notificationhubs/arm-notificationhubs/src/notificationHubsManagementClient.ts
Labels: Mgmt, auto-merge

#24139 Post release automated changes for oep releases
  sdk/oep/arm-oep/CHANGELOG.md
  sdk/oep/arm-oep/package.json
  sdk/oep/arm-oep/src/openEnergyPlatformManagementServiceAPIs.ts
Labels: auto-merge

#24121 Post release automated changes for privatedns releases
  sdk/privatedns/arm-privatedns/CHANGELOG.md
  sdk/privatedns/arm-privatedns/package.json
  sdk/privatedns/arm-privatedns/src/privateDnsManagementClient.ts
Labels: Mgmt, auto-merge

#24144 update test in comput-rest
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_create_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_delete_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_get_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_list_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_availabilitysets_update_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_create_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_delete_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_get_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_list_test.json
  sdk/compute/arm-compute-rest/recordings/browsers/compute_test/recording_virtualmachines_update_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_create_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_delete_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_get_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_list_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_availabilitysets_update_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_create_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_delete_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_get_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_list_test.json
  sdk/compute/arm-compute-rest/recordings/node/compute_test/recording_virtualmachines_update_test.json
Labels: Mgmt

#24071 Blob Storage - container name rules link
  sdk/storage/storage-blob/src/BlobServiceClient.ts
  sdk/storage/storage-blob/src/ContainerClient.ts
Labels: Client, Storage

#24148 [dev-tool] Remove stale sample guardrails
  common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts
  common/tools/dev-tool/src/util/samples/info.ts
  common/tools/dev-tool/src/util/samples/syntax.ts
  common/tools/dev-tool/test/samples/files/expectations/cjs-forms/typescript/tsconfig.json
  common/tools/dev-tool/test/samples/files/expectations/output-customization/typescript/tsconfig.json
  common/tools/dev-tool/test/samples/files/expectations/simple/javascript/getConfigurationSetting.js
  common/tools/dev-tool/test/samples/files/expectations/simple/typescript/src/getConfigurationSetting.ts
  common/tools/dev-tool/test/samples/files/expectations/simple/typescript/tsconfig.json
  common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/javascript/getConfigurationSetting.js
  common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/src/getConfigurationSetting.ts
  common/tools/dev-tool/test/samples/files/expectations/simple@1.0.0-beta.1/typescript/tsconfig.json
  common/tools/dev-tool/test/samples/files/inputs/simple/getConfigurationSetting.ts
  common/tools/dev-tool/test/samples/files/inputs/simple@1.0.0-beta.1/getConfigurationSetting.ts
Labels: dev-tool

#23830 Post release automated changes for agrifood releases
  sdk/agrifood/arm-agrifood/CHANGELOG.md
  sdk/agrifood/arm-agrifood/package.json
  sdk/agrifood/arm-agrifood/src/agriFoodMgmtClient.ts
Labels: auto-merge, AgriFood

#24151 [engsys] clean up rollup dev dependencies
  sdk/communication/communication-job-router/package.json
  sdk/communication/communication-network-traversal/package.json
  sdk/core/core-amqp/package.json
  sdk/digitaltwins/dtdl-parser/package.json
  sdk/eventhub/event-hubs/package.json
  sdk/notificationhubs/notification-hubs/package.json
Labels: Event Hubs, Azure.Core, Digital Twins, Communication

#24133 [core-amqp] remove map entry when we are done processing its task queues
  sdk/core/core-amqp/CHANGELOG.md
  sdk/core/core-amqp/src/util/lock.ts
Labels: Azure.Core

#23409 [dev-tool] Drop NodeJS v12 and add v18
  common/tools/dev-tool/src/commands/samples/checkNodeVersions.ts
Labels: dev-tool

#24132 Hotfix/identity 3.1.2
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts
Labels: Azure.Identity

#24152 [engsys] upgrade dev dependency `puppeteer` to `^19.2.2`
  common/config/rush/pnpm-lock.yaml
  sdk/core/core-amqp/package.json
  sdk/core/core-http/package.json
  sdk/core/core-lro/test/lro.spec.ts
  sdk/core/core-lro/test/utils/utils.ts
  sdk/core/core-rest-pipeline/package.json
  sdk/core/logger/package.json
  sdk/eventhub/event-hubs/package.json
  sdk/identity/identity-cache-persistence/package.json
  sdk/identity/identity-vscode/package.json
  sdk/identity/identity/package.json
  sdk/keyvault/keyvault-certificates/package.json
  sdk/keyvault/keyvault-common/package.json
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-secrets/package.json
  sdk/servicebus/service-bus/package.json
  sdk/storage/storage-blob-changefeed/package.json
  sdk/storage/storage-blob/package.json
  sdk/storage/storage-file-datalake/package.json
  sdk/storage/storage-file-share/package.json
  sdk/storage/storage-internal-avro/package.json
  sdk/storage/storage-queue/package.json
  sdk/web-pubsub/web-pubsub-express/package.json
  sdk/web-pubsub/web-pubsub/package.json
Labels: Service Bus, Event Hubs, Storage, KeyVault, Azure.Identity, Azure.Core, WebPubSub

#24157 [Identity] Post release version bump
  sdk/identity/identity/CHANGELOG.md
  sdk/identity/identity/package.json
  sdk/identity/identity/src/constants.ts
Labels: Azure.Identity

#24076 Support PPE live tests for Identity SDK
  sdk/communication/communication-identity/tests.yml
Labels: Communication, Communication - Identity

#23666 Added documentation regarding logging.
  sdk/cosmosdb/cosmos/README.md
Labels: Cosmos

#23639 Adding VSCode launch configurations for debuging individual testcases as well as single files.
  sdk/cosmosdb/cosmos/.vscode/launch.json
  sdk/cosmosdb/cosmos/Contributing.md
Labels: Cosmos

#24167 Sync eng/common directory with azure-sdk-tools for PR 4813
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#24185 [web-pubsub-client] Add a browser sample and fix some bugs
  sdk/web-pubsub/web-pubsub-client/.eslintrc.json
  sdk/web-pubsub/web-pubsub-client/package.json
  sdk/web-pubsub/web-pubsub-client/samples-browser/package.json
  sdk/web-pubsub/web-pubsub-client/samples-browser/public/index.html
  sdk/web-pubsub/web-pubsub-client/samples-browser/sample.env
  sdk/web-pubsub/web-pubsub-client/samples-browser/server.js
  sdk/web-pubsub/web-pubsub-client/samples-browser/src/index.js
  sdk/web-pubsub/web-pubsub-client/samples-browser/webpack.config.js
  sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.browser.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.ts
  sdk/web-pubsub/web-pubsub-client/src/ws.browser.js
  sdk/web-pubsub/web-pubsub-client/tsconfig.json
Labels: auto-merge, WebPubSub

#24184 Post release automated changes for anomalydetector releases
  sdk/anomalydetector/ai-anomaly-detector-rest/CHANGELOG.md
  sdk/anomalydetector/ai-anomaly-detector-rest/package.json
  sdk/anomalydetector/ai-anomaly-detector-rest/swagger/README.md
Labels: auto-merge

#24186 Post release automated changes for commerce releases
  sdk/commerce/arm-commerce/CHANGELOG.md
  sdk/commerce/arm-commerce/package.json
  sdk/commerce/arm-commerce/src/usageManagementClient.ts
Labels: Mgmt, auto-merge

#24170 Update JS engsys team on codeowners
  .github/CODEOWNERS
Labels: Central-EngSys

#24187 [text analytics] Unskip test
  sdk/textanalytics/ai-text-analytics/test/public/textAnalyticsClient.spec.ts
Labels: Cognitive - Text Analytics

#24197 update changlog
  sdk/recoveryservicesbackup/arm-recoveryservicesbackup/CHANGELOG.md
Labels: Mgmt

#24205 Sync eng/common directory with azure-sdk-tools for PR 4930
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#23969 datalake refresh
  common/config/rush/pnpm-lock.yaml
  sdk/datalake-analytics/arm-datalake-analytics/CHANGELOG.md
  sdk/datalake-analytics/arm-datalake-analytics/_meta.json
  sdk/datalake-analytics/arm-datalake-analytics/package.json
  sdk/datalake-analytics/arm-datalake-analytics/recordings/node/datalakeanalytics_test/recording_accounts_create_test.js
  sdk/datalake-analytics/arm-datalake-analytics/recordings/node/datalakeanalytics_test/recording_accounts_create_test.json
  sdk/datalake-analytics/arm-datalake-analytics/recordings/node/datalakeanalytics_test/recording_accounts_delete_test.js
  sdk/datalake-analytics/arm-datalake-analytics/recordings/node/datalakeanalytics_test/recording_accounts_get_test.js
  sdk/datalake-analytics/arm-datalake-analytics/review/arm-datalake-analytics.api.md
  sdk/datalake-analytics/arm-datalake-analytics/samples/v2-beta/typescript/package.json
  sdk/datalake-analytics/arm-datalake-analytics/src/dataLakeAnalyticsAccountManagementClient.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/index.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/models/index.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/operations/accounts.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/operations/computePolicies.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/operations/dataLakeStoreAccounts.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/operations/firewallRules.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/operations/storageAccounts.ts
  sdk/datalake-analytics/arm-datalake-analytics/src/pagingHelper.ts
  sdk/datalake-analytics/arm-datalake-analytics/test/datalake-analytics_examples.spec.ts
  sdk/datalake-analytics/arm-datalake-analytics/test/sampleTest.ts
Labels: Mgmt

#24162 [engsys] upgrade dev dependency magic-string to ~0.27.0
  common/config/rush/pnpm-lock.yaml
  sdk/apimanagement/api-management-custom-widgets-scaffolder/package.json
  sdk/formrecognizer/ai-form-recognizer/package.json
Labels: Cognitive - Form Recognizer

#24216 [engsys] update `puppeteer` version in `web-pubsub-client`
  common/config/rush/pnpm-lock.yaml
  sdk/web-pubsub/web-pubsub-client/package.json
Labels: WebPubSub

#24218 [communication-job-router] format with prettier
  common/config/rush/pnpm-lock.yaml
  sdk/communication/communication-job-router/karma.conf.js
  sdk/communication/communication-job-router/package.json
  sdk/communication/communication-job-router/src/models/models.ts
  sdk/communication/communication-job-router/src/models/options.ts
  sdk/communication/communication-job-router/src/models/responses.ts
  sdk/communication/communication-job-router/src/routerAdministrationClient.ts
  sdk/communication/communication-job-router/src/routerClient.ts
  sdk/communication/communication-job-router/test/internal/utils/mockClient.ts
  sdk/communication/communication-job-router/test/public/exceptionPolicies.spec.ts
  sdk/communication/communication-job-router/test/public/utils/recordedClient.ts
  sdk/communication/communication-job-router/test/public/utils/testData.ts
Labels: Client, Communication

#24206 [core/many] Unpin dependencies
  common/config/rush/pnpm-lock.yaml
  common/tools/dev-tool/package.json
  sdk/anomalydetector/ai-anomaly-detector-rest/package.json
  sdk/appconfiguration/app-configuration/package.json
  sdk/appconfiguration/app-configuration/samples/v1-beta/javascript/package.json
  sdk/appconfiguration/app-configuration/samples/v1-beta/typescript/package.json
  sdk/devcenter/developer-devcenter-rest/package.json
  sdk/deviceupdate/iot-device-update-rest/package.json
  sdk/documenttranslator/ai-document-translator-rest/package.json
  sdk/identity/identity/package.json
  sdk/identity/identity/samples/v2/javascript/package.json
  sdk/identity/identity/samples/v2/typescript/package.json
  sdk/loadtestservice/load-testing-rest/package.json
  sdk/maps/maps-geolocation-rest/package.json
  sdk/maps/maps-render-rest/package.json
  sdk/maps/maps-route-rest/package.json
  sdk/maps/maps-route-rest/samples-dev/directions.ts
  sdk/maps/maps-route-rest/test/public/mapsRouteClient.spec.ts
  sdk/maps/maps-search/package.json
  sdk/maps/maps-search/samples/v1-beta/javascript/package.json
  sdk/maps/maps-search/samples/v1-beta/typescript/package.json
  sdk/monitor/monitor-ingestion/package.json
  sdk/notificationhubs/notification-hubs/package.json
  sdk/purview/purview-administration-rest/package.json
  sdk/purview/purview-catalog-rest/package.json
  sdk/purview/purview-scanning-rest/package.json
  sdk/recoveryservicessiterecovery/arm-recoveryservices-siterecovery/package.json
  sdk/service-map/arm-servicemap/package.json
  sdk/synapse/synapse-access-control-rest/package.json
  sdk/test-utils/testing-recorder-new/package.json
  sdk/web-pubsub/web-pubsub-client/package.json
Labels: Mgmt, Azure.Identity, Monitor, App Configuration, Synapse, Cognitive - Translator, dev-tool, Purview, WebPubSub

#24213 Update prepare-pipelines.yml to use the new jobs-based template
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#24209 Post release automated changes for resourcemover releases
  sdk/resourcemover/arm-resourcemover/CHANGELOG.md
  sdk/resourcemover/arm-resourcemover/package.json
  sdk/resourcemover/arm-resourcemover/src/resourceMoverServiceAPI.ts
Labels: Mgmt, auto-merge

#24211 Post release automated changes for iothub releases
  sdk/iothub/arm-iothub/CHANGELOG.md
  sdk/iothub/arm-iothub/package.json
  sdk/iothub/arm-iothub/src/iotHubClient.ts
Labels: Mgmt, auto-merge

#24230 Sync eng/common directory with azure-sdk-tools for PR 4944
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#24231 [engsys] update `nyc` version to `^15.0.0`
  common/config/rush/pnpm-lock.yaml
  sdk/anomalydetector/ai-anomaly-detector-rest/package.json
  sdk/appservice/arm-appservice-rest/package.json
  sdk/communication/communication-job-router/package.json
  sdk/compute/arm-compute-rest/package.json
  sdk/containerservice/arm-containerservice-rest/package.json
  sdk/devcenter/developer-devcenter-rest/package.json
  sdk/loadtestservice/load-testing-rest/package.json
  sdk/maps/maps-geolocation-rest/package.json
  sdk/maps/maps-render-rest/package.json
  sdk/maps/maps-route-rest/package.json
  sdk/maps/maps-search-rest/package.json
  sdk/network/arm-network-rest/package.json
  sdk/personalizer/ai-personalizer-rest/package.json
  sdk/servicefabric/arm-servicefabric-rest/package.json
Labels: Mgmt, Communication

#24226 [engsys] upgrade `@typescript-eslint/` dependencies to `~5.46.1`
  common/config/rush/pnpm-lock.yaml
  common/tools/eslint-plugin-azure-sdk/package.json
Labels: eslint plugin

#24202 [web-pubsub-client] Fix some bugs
  sdk/web-pubsub/web-pubsub-client/package.json
  sdk/web-pubsub/web-pubsub-client/samples-browser/server.js
  sdk/web-pubsub/web-pubsub-client/samples-browser/webpack.config.js
  sdk/web-pubsub/web-pubsub-client/samples-dev/helloworld.ts
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/README.md
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/helloworld.js
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/package.json
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/sample.env
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/README.md
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/package.json
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/sample.env
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/src/helloworld.ts
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/tsconfig.json
Labels: customer-reported, auto-merge, WebPubSub

#24193 [dev-tool] Add api-surface min/max TypeScript testing
  common/config/rush/pnpm-lock.yaml
  common/tools/dev-tool/package.json
  common/tools/dev-tool/src/commands/run/check-api.ts
  common/tools/dev-tool/src/commands/run/index.ts
  common/tools/dev-tool/src/util/resolveProject.ts
  common/tools/dev-tool/test/samples/files.spec.ts
Labels: dev-tool

#24235 [engsys] upgrade `rollup-plugin-sourcemaps` to ^0.6.3
  common/config/rush/pnpm-lock.yaml
  sdk/authorization/arm-authorization/package.json
  sdk/communication/communication-rooms/package.json
  sdk/service-map/arm-servicemap/package.json
  sdk/videoanalyzer/arm-videoanalyzer/package.json
Labels: Mgmt, Communication

#24229 Sync eng/common directory with azure-sdk-tools for PR 4514
  eng/common/scripts/Verify-AgentOS.ps1
Labels: EngSys, Central-EngSys

#24195 [keyvault] keyvault-certificates: depend on keyvault-common
  sdk/keyvault/keyvault-certificates/api-extractor.json
  sdk/keyvault/keyvault-certificates/package.json
  sdk/keyvault/keyvault-certificates/src/identifier.ts
  sdk/keyvault/keyvault-certificates/src/index.ts
  sdk/keyvault/keyvault-certificates/test/internal/userAgent.spec.ts
  sdk/keyvault/keyvault-certificates/tsconfig.json
Labels: KeyVault

#24222 Post release automated changes for servicebus releases
  sdk/servicebus/arm-servicebus/CHANGELOG.md
  sdk/servicebus/arm-servicebus/package.json
  sdk/servicebus/arm-servicebus/src/serviceBusManagementClient.ts
Labels: Mgmt, Service Bus, auto-merge

#24245 Post release automated changes for sql releases
  sdk/sql/arm-sql/CHANGELOG.md
  sdk/sql/arm-sql/package.json
  sdk/sql/arm-sql/src/sqlManagementClient.ts
Labels: Mgmt, auto-merge

#24247 Post release automated changes for timeseriesinsights releases
  sdk/timeseriesinsights/arm-timeseriesinsights/CHANGELOG.md
  sdk/timeseriesinsights/arm-timeseriesinsights/package.json
  sdk/timeseriesinsights/arm-timeseriesinsights/src/timeSeriesInsightsClient.ts
Labels: Mgmt, auto-merge

#24224 Post release automated changes for resourcegraph releases
  sdk/resourcegraph/arm-resourcegraph/CHANGELOG.md
  sdk/resourcegraph/arm-resourcegraph/package.json
  sdk/resourcegraph/arm-resourcegraph/src/resourceGraphClient.ts
Labels: Mgmt, auto-merge

#24223 Post release automated changes for serialconsole releases
  sdk/serialconsole/arm-serialconsole/CHANGELOG.md
  sdk/serialconsole/arm-serialconsole/package.json
  sdk/serialconsole/arm-serialconsole/src/microsoftSerialConsoleClient.ts
Labels: Mgmt, auto-merge

#24221 Post release automated changes for redisenterprise releases
  sdk/redisenterprise/arm-redisenterprisecache/CHANGELOG.md
  sdk/redisenterprise/arm-redisenterprisecache/package.json
  sdk/redisenterprise/arm-redisenterprisecache/src/redisEnterpriseManagementClient.ts
Labels: Mgmt, auto-merge

#24250 Post release automated changes for visualstudio releases
  sdk/visualstudio/arm-visualstudio/CHANGELOG.md
  sdk/visualstudio/arm-visualstudio/package.json
  sdk/visualstudio/arm-visualstudio/src/visualStudioResourceProviderClient.ts
Labels: Mgmt, auto-merge

#24249 Post release automated changes for streamanalytics releases
  sdk/streamanalytics/arm-streamanalytics/CHANGELOG.md
  sdk/streamanalytics/arm-streamanalytics/package.json
  sdk/streamanalytics/arm-streamanalytics/src/streamAnalyticsManagementClient.ts
Labels: Mgmt, auto-merge

#24207 [app-config] Add error message for 412 error
  sdk/appconfiguration/app-configuration/CHANGELOG.md
  sdk/appconfiguration/app-configuration/package.json
  sdk/appconfiguration/app-configuration/src/appConfigurationClient.ts
  sdk/appconfiguration/app-configuration/src/internal/constants.ts
  sdk/appconfiguration/app-configuration/test/public/index.spec.ts
Labels: App Configuration

#24242 [Schema Registry] Update test-resources.json
  sdk/schemaregistry/test-resources.json
Labels: Schema Registry

#24237 Sync eng/common directory with azure-sdk-tools for PR 4940
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#24261 Post release automated changes for servicelinker releases
  sdk/servicelinker/arm-servicelinker/CHANGELOG.md
  sdk/servicelinker/arm-servicelinker/package.json
  sdk/servicelinker/arm-servicelinker/src/serviceLinkerManagementClient.ts
Labels: auto-merge

#23572 Post release automated changes for instrumentation releases
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/CHANGELOG.md
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/package.json
  sdk/instrumentation/opentelemetry-instrumentation-azure-sdk/src/configuration.ts
Labels: auto-merge

#23766 Post release automated changes for keyvault releases
  sdk/keyvault/keyvault-common/CHANGELOG.md
  sdk/keyvault/keyvault-common/package.json
Labels: KeyVault, auto-merge

#23876 Post release automated changes for cosmosdb releases
  sdk/cosmosdb/cosmos/CHANGELOG.md
  sdk/cosmosdb/cosmos/package.json
  sdk/cosmosdb/cosmos/src/common/constants.ts
Labels: Cosmos, auto-merge

#23932 Post release automated changes for elastic releases
  sdk/elastic/arm-elastic/CHANGELOG.md
  sdk/elastic/arm-elastic/package.json
  sdk/elastic/arm-elastic/src/microsoftElastic.ts
Labels: auto-merge

#24120 Post release automated changes for quota releases
  sdk/quota/arm-quota/CHANGELOG.md
  sdk/quota/arm-quota/package.json
  sdk/quota/arm-quota/src/azureQuotaExtensionAPI.ts
Labels: auto-merge

#24263 Post release automated changes for storsimple8000series releases
  sdk/storsimple8000series/arm-storsimple8000series/CHANGELOG.md
  sdk/storsimple8000series/arm-storsimple8000series/package.json
  sdk/storsimple8000series/arm-storsimple8000series/src/storSimple8000SeriesManagementClient.ts
Labels: Mgmt, auto-merge

#24264 Post release automated changes for servicefabric releases
  sdk/servicefabric/arm-servicefabric/CHANGELOG.md
  sdk/servicefabric/arm-servicefabric/package.json
  sdk/servicefabric/arm-servicefabric/src/serviceFabricManagementClient.ts
Labels: Mgmt, auto-merge

#23584 Post release automated changes for elasticsans releases
  sdk/elasticsans/arm-elasticsan/CHANGELOG.md
  sdk/elasticsans/arm-elasticsan/package.json
  sdk/elasticsans/arm-elasticsan/src/elasticSanManagement.ts
Labels: auto-merge

#24260 Post release automated changes for storagesync releases
  sdk/storagesync/arm-storagesync/CHANGELOG.md
  sdk/storagesync/arm-storagesync/package.json
  sdk/storagesync/arm-storagesync/src/microsoftStorageSync.ts
Labels: Mgmt, auto-merge

#24122 Post release automated changes for purview releases
  sdk/purview/arm-purview/CHANGELOG.md
  sdk/purview/arm-purview/package.json
  sdk/purview/arm-purview/src/purviewManagementClient.ts
Labels: auto-merge, Purview

#24262 Post release automated changes for storsimple1200series releases
  sdk/storsimple1200series/arm-storsimple1200series/CHANGELOG.md
  sdk/storsimple1200series/arm-storsimple1200series/package.json
  sdk/storsimple1200series/arm-storsimple1200series/src/storSimpleManagementClient.ts
Labels: Mgmt, auto-merge

#23798 Post release automated changes for keyvault releases
  sdk/keyvault/keyvault-admin/CHANGELOG.md
  sdk/keyvault/keyvault-admin/package.json
  sdk/keyvault/keyvault-admin/src/constants.ts
  sdk/keyvault/keyvault-admin/src/generated/keyVaultClientContext.ts
  sdk/keyvault/keyvault-admin/swagger/README.md
  sdk/keyvault/keyvault-keys/CHANGELOG.md
  sdk/keyvault/keyvault-keys/package.json
  sdk/keyvault/keyvault-keys/src/constants.ts
  sdk/keyvault/keyvault-keys/src/generated/keyVaultClient.ts
  sdk/keyvault/keyvault-keys/swagger/README.md
Labels: KeyVault, auto-merge

#23638 Post release automated changes for loadtestservice releases
  sdk/loadtestservice/load-testing-rest/CHANGELOG.md
  sdk/loadtestservice/load-testing-rest/package.json
  sdk/loadtestservice/load-testing-rest/swagger/README.md
Labels: auto-merge

#24269 Sync eng/common directory with azure-sdk-tools for PR 4988
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#24259 [web-pubsub-client] Add more tests
  common/config/rush/pnpm-lock.yaml
  sdk/web-pubsub/web-pubsub-client/.vscode/launch.json
  sdk/web-pubsub/web-pubsub-client/package.json
  sdk/web-pubsub/web-pubsub-client/review/web-pubsub-client.api.md
  sdk/web-pubsub/web-pubsub-client/src/models/index.ts
  sdk/web-pubsub/web-pubsub-client/src/webPubSubClient.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.browser.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/sendData.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/websocketClient.browser.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/websocketClient.ts
  sdk/web-pubsub/web-pubsub-client/src/websocket/websocketClientLike.ts
  sdk/web-pubsub/web-pubsub-client/src/ws.browser.js
  sdk/web-pubsub/web-pubsub-client/src/ws.browser.ts
  sdk/web-pubsub/web-pubsub-client/test/client.lifetime.spec.ts
  sdk/web-pubsub/web-pubsub-client/test/client.messages.spec.ts
  sdk/web-pubsub/web-pubsub-client/test/client.spec.ts
  sdk/web-pubsub/web-pubsub-client/test/testWebSocketClient.ts
  sdk/web-pubsub/web-pubsub-client/test/utils.ts
  sdk/web-pubsub/web-pubsub-client/tsconfig.json
Labels: auto-merge, WebPubSub

#24182 search refresh
  common/config/rush/pnpm-lock.yaml
  sdk/search/arm-search/CHANGELOG.md
  sdk/search/arm-search/_meta.json
  sdk/search/arm-search/package.json
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_create_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_create_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_delete_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_delete_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_list_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_querykeys_list_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_services_create_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_services_create_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_services_delete_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_services_delete_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_services_get_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_services_get_test.json
  sdk/search/arm-search/recordings/node/search_test/recording_services_list_test.js
  sdk/search/arm-search/recordings/node/search_test/recording_services_list_test.json
  sdk/search/arm-search/review/arm-search.api.md
  sdk/search/arm-search/samples/v3/typescript/package.json
  sdk/search/arm-search/samples/v3/typescript/tsconfig.json
  sdk/search/arm-search/src/index.ts
  sdk/search/arm-search/src/models/index.ts
  sdk/search/arm-search/src/operations/operations.ts
  sdk/search/arm-search/src/operations/privateEndpointConnections.ts
  sdk/search/arm-search/src/operations/privateLinkResources.ts
  sdk/search/arm-search/src/operations/queryKeys.ts
  sdk/search/arm-search/src/operations/services.ts
  sdk/search/arm-search/src/operations/sharedPrivateLinkResources.ts
  sdk/search/arm-search/src/pagingHelper.ts
  sdk/search/arm-search/src/searchManagementClient.ts
  sdk/search/arm-search/test/search_examples.ts
Labels: Mgmt, Search

#24283 Post release automated changes for network releases
  sdk/network/arm-network/CHANGELOG.md
  sdk/network/arm-network/package.json
  sdk/network/arm-network/src/networkManagementClient.ts
Labels: Mgmt, auto-merge

#24275 Post release automated changes for digitaltwins releases
  sdk/digitaltwins/arm-digitaltwins/CHANGELOG.md
  sdk/digitaltwins/arm-digitaltwins/package.json
  sdk/digitaltwins/arm-digitaltwins/src/azureDigitalTwinsManagementClient.ts
Labels: Mgmt, Digital Twins, auto-merge

#24285 Post release automated changes for storage releases
  sdk/storage/arm-storage/CHANGELOG.md
  sdk/storage/arm-storage/package.json
  sdk/storage/arm-storage/src/storageManagementClient.ts
Labels: Mgmt, Storage, auto-merge

#24271 Post release automated changes for synapse releases
  sdk/synapse/arm-synapse/CHANGELOG.md
  sdk/synapse/arm-synapse/package.json
  sdk/synapse/arm-synapse/src/synapseManagementClient.ts
Labels: Mgmt, Synapse, auto-merge

#24279 Sync eng/common directory with azure-sdk-tools for PR 4880
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#24130 Migrate from win2019 to win2022
  eng/pipelines/aggregate-reports.yml
  eng/pipelines/npm-tasks.yml
  eng/pipelines/templates/jobs/ci.yml
  eng/pipelines/templates/jobs/smoke.tests.yml
  eng/pipelines/templates/stages/archetype-js-release.yml
  eng/pipelines/templates/stages/platform-matrix.json
  eng/pipelines/templates/steps/use-node-test-version.yml
Labels: Mgmt, Communication

#24298 Update prepare-pipelines flags
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#24300 [Language Text] Fix min/max testing
  sdk/cognitivelanguage/ai-language-text/test/public/analyzeBatch.spec.ts
Labels: Cognitive - Language

#24294 Post release automated changes for cdn releases
  sdk/cdn/arm-cdn/CHANGELOG.md
  sdk/cdn/arm-cdn/package.json
  sdk/cdn/arm-cdn/src/cdnManagementClient.ts
Labels: Mgmt, auto-merge

#24291 [web-pubsub-client] Update readme
  sdk/web-pubsub/web-pubsub-client/README.md
  sdk/web-pubsub/web-pubsub-client/samples-dev/helloworld.ts
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/javascript/helloworld.js
  sdk/web-pubsub/web-pubsub-client/samples/v1-beta/typescript/src/helloworld.ts
Labels: auto-merge, WebPubSub

#24303 delete locks-profile-2019-03-01
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/LICENSE.txt
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/README.md
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/package.json
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/rollup.config.js
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/managementLockClient.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/managementLockClientContext.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/models/authorizationOperationsMappers.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/models/index.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/models/managementLocksMappers.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/models/mappers.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/models/parameters.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/operations/authorizationOperations.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/operations/index.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/src/operations/managementLocks.ts
  sdk/locks/arm-locks-profile-hybrid-2019-03-01/tsconfig.json
Labels: Mgmt

#24312 Sync eng/common directory with azure-sdk-tools for PR 4985
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#24299 Fix Program Brief leftovers
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__creates_us_program_brief_using_upsert/recording_can_create_get_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/recordings/browsers/shortcodesclient__updates_us_program_brief_using_upsert/recording_can_create_and_update_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__creates_gets_updates_lists_and_deletes_us_program_brief/recording_can_create_get_update_list_and_delete_a_us_program_brief.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__lists_short_codes/recording_can_list_all_acquired_short_codes.json
  sdk/communication/communication-short-codes/recordings/node/shortcodesclient__manage_attachments/recording_can_manage_attachments.json
  sdk/communication/communication-short-codes/test/public/createGetDeleteUSProgramBrief.spec.ts
  sdk/communication/communication-short-codes/test/public/createUpdateUSProgramBrief.spec.ts
  sdk/communication/communication-short-codes/test/public/manageProgramBriefAttachment.spec.ts
  sdk/communication/communication-short-codes/test/public/manageUSProgramBriefs.spec.ts
  sdk/communication/communication-short-codes/test/public/utils/testUSProgramBrief.ts
Labels: Communication

#24330 Post release automated changes for policy releases
  sdk/policy/arm-policy-profile-2020-09-01-hybrid/CHANGELOG.md
  sdk/policy/arm-policy-profile-2020-09-01-hybrid/package.json
  sdk/policy/arm-policy-profile-2020-09-01-hybrid/src/policyClient.ts
Labels: Mgmt, auto-merge

#24331 Post release automated changes for network releases
  sdk/network/arm-network-profile-2020-09-01-hybrid/CHANGELOG.md
  sdk/network/arm-network-profile-2020-09-01-hybrid/package.json
  sdk/network/arm-network-profile-2020-09-01-hybrid/src/networkManagementClient.ts
Labels: Mgmt, auto-merge

#24329 Post release automated changes for postgresql releases
  sdk/postgresql/arm-postgresql-flexible/CHANGELOG.md
  sdk/postgresql/arm-postgresql-flexible/package.json
  sdk/postgresql/arm-postgresql-flexible/src/postgreSQLManagementFlexibleServerClient.ts
Labels: Mgmt, auto-merge

#24326 Post release automated changes for storage releases
  sdk/storage/arm-storage-profile-2020-09-01-hybrid/CHANGELOG.md
  sdk/storage/arm-storage-profile-2020-09-01-hybrid/package.json
  sdk/storage/arm-storage-profile-2020-09-01-hybrid/src/storageManagementClient.ts
Labels: Mgmt, Storage, auto-merge

#24327 Post release automated changes for subscription releases
  sdk/subscription/arm-subscriptions-profile-2020-09-01-hybrid/CHANGELOG.md
  sdk/subscription/arm-subscriptions-profile-2020-09-01-hybrid/package.json
  sdk/subscription/arm-subscriptions-profile-2020-09-01-hybrid/src/subscriptionClient.ts
Labels: Mgmt, auto-merge
